### ISSUE TITLE
Support reset expiration method for session store

### ISSUE THREAD

**Issue by heroandtn3** [expressjs/session#105]
I know that every time browser sends request, session middleware will call `touch` method to reset `maxAge`. But it seems to be not work with session store.

For example, I'm using `connect-redis` as a session store for my application. `connect-redis` supports `ttl` option as a session expiration and I set it to 1 hour like this:

```js
var session = require('express-session');
var RedisStore = require('connect-redis')(session);

app.use(session({
    store: new RedisStore({client: redis.createClient(), ttl: 3600}),
    secret: 'keyboard cat',
    cookie: { maxAge: 3600000 }
}));
```

I notice that every  time browser sends request, expiration of session on store does not be reset, it's still expired after 1 hour whether session middleware call `touch` before. To workaround this issue, I have to set `resave` option to `true`, should I do this or is there any other solution like a `touch` method for session store?

**Comment by dougwilson** [comment]
Crap, this is not going to be easy, since `touch()` already has a sync external interface. There really needs to be a 2.0 soon... The biggest hurdle is specifying an interface of the store, including a way for the store to declare compatibility levels.

**Comment by dougwilson** [comment]
Ok, so now a session store can implement a `touch` method that will be called if the session is not saved (i.e., for a session, either `store.save`, `store.touch` or nothing will be called when the request is over).

This means, for example, `connect-redis` can implement a `store.touch(sid, sess, callback)` method that can update the TTL, even if `resave: false` is set.

/cc @wavded

**Comment by heroandtn3** [comment]
Glad to see your commit about this issue. Thanks!

**Comment by dougwilson** [comment]
I'm just making sure I got all the kinks out and this will be in the 1.10.0 release, probably tomorrow.
