### ISSUE TITLE
extra char when buffering express output

### ISSUE THREAD

**Issue by kapouer** [expressjs/session#109]
Hi,

https://github.com/expressjs/session/commit/5c503e7552ea48342f4ce4ce1322606eb8ee217c seems really a wrong hack - it ends up adding an extra char to what's written to the response ?!?
https://github.com/kapouer/express-buffer-response/blob/master/index.js suffers from this.
As a workaround i understand i should discard "writes" after "end" was called, yet i'm worried it's going to break soon...

**Comment by dougwilson** [comment]
This is not an issue, as many, many production sites and this module's own test suite do not suffer at all. For one thing, you should never, ever be doing the res.write and res.end in the finished callback.

**Comment by dougwilson** [comment]
But anyway, I can check it out, if you post what version of node.js, what version of express, and what version of this module you are using. Then post me some example code that uses that buffer module I can copy and paste into a file and run and that demonstrates the issue (and provide instructions on how to reproduce if just running the file does not cause the issue).

**Comment by kapouer** [comment]
hmmm i understand now that response's Content-Length has authority over what's actually written to the response. I'll submit myself to that behavior as it surely won't break, ever.
