### ISSUE TITLE
Resave and saveUninitialized defaults

### ISSUE THREAD

**Issue by a00andos** [expressjs/session#111]
I'm still getting a warning if not explicitly declaring resave and saveUninitialized options. 
How long will you keep this warning and when will the defaults change?

**Comment by JoeWagner** [comment]
When version, 2.0 comes out the defaults should change and the warnings will go away.  You can set the options explicitly if you don't want to see the warnings.

**Comment by dougwilson** [comment]
The defaults will change and messages go away in 2.0. I don't know exactly when that is, as I wanted to change the engine with 2.0, but it seems like the engine change may just wait for 3.0.

**Comment by faiq** [comment]
Why don't you just shut them off in the current version, if they're deprecated?

**Comment by dougwilson** [comment]
> Why don't you just shut them off in the current version, if they're deprecated?

I'm not 100% sure what this means. We cannot remove them in the current version, as people's code will break. They are deprecated, which is why there is a warning. You can disable warnings if you set the environment `NO_DEPRECATION=express-session`, or start `node` with `--no-deprecation`.
