### ISSUE TITLE
Shared Session v2

### ISSUE THREAD

**Issue by jeremykentbgross** [expressjs/session#112]
I have been having issues that I thought were a browser fault where it appeared that multiple requests eventually got gave a different cookie and got a different session.

After sleeping on it it occurred to me that maybe this was because I was using the same user login on multiple devices, and multiple browsers on each of those devices, and maybe I am either somehow doing this wrong, or perhaps it isn't supported properly.  So I restarted my app and logged in with the (formerly most) troublesome device+browser combination.  After this restart it worked perfectly on that device which seems to confirm my suspicion.  I found this former issue: https://github.com/expressjs/session/issues/108 but it didn't seem to answer my question or solve my problem.

I am wondering: do I need to keep track of multiple sessions per user myself and somehow identify all the unique devices/browsers/(and proxy routings someday as needed) they might use at the same time separately?  If so, how should I do this?  If not, am I doing something else wrong?

My code for handling the logins as is follows:
```javascript
var LocalStrategy = require('passport-local').Strategy;

module.exports =
{
	init: function init(inPassport, inUsers)
	{
		console.log("Using Local Memory Storage");
	
		inPassport.use(
			new LocalStrategy(
				function(inUsername, inPassword, inDone)
				{
					var aUser;
					
					console.log('Trying to login user:', inUsername);
					
					aUser = inUsers[inUsername];
					if(!aUser)
					{
						console.log('No User:', inUsername);
						return inDone(null, false, { message: 'Incorrect username or password.' });
					}
					
					if(/*aUser.userName === inUsername && */aUser.password === inPassword)
					{
						console.log('User Found:', inUsername);
						return inDone(null, aUser);
					}
					
					console.log('Bad Password for:', inUsername);
					return inDone(null, false, { message: 'Incorrect username or password.' });
				}
			)
		);

		inPassport.deserializeUser(
			function(inUsername, inDone)
			{
				var aUser;
				
				aUser = inUsers[inUsername];
				if(!aUser)
				{
					inDone(null);
				}
				
				if(aUser.userName === inUsername)
				{
					inDone(null, aUser);
					return;
				}

				//failed
				inDone(null);
			}
		);
	}
};
```

**Comment by dougwilson** [comment]
Hi! Are you sure you are posting in the right repo? Your posted code is all passport, of which I have no knowledge of :(

**Comment by JoeWagner** [comment]
>I am wondering: do I need to keep track of multiple sessions per user myself and somehow identify all the unique devices/browsers/(and proxy routings someday as needed) they might use at the same time separately? If so, how should I do this? If not, am I doing something else wrong?

@jeremykentbgross you need to serialize each user into and out of the specific browser's session i.e. implement *login sessions*.  This is what the `passport` module does for for you.
This module only handles creating a, hopefully unique, session for each client/browser.  That is assuming that client honors the `set-cookie` header.

From the code you have posted above, it seems likely that you are having an issue with the correct usage of `passport`

**Comment by dougwilson** [comment]
Looks like @jeremykentbgross also opened the issue over in `passport-local`: https://github.com/jaredhanson/passport-local/issues/94 (linking mainly for people who come by here).
