### ISSUE TITLE
setting a time limit to update the session

### ISSUE THREAD

**Issue by rafaelcardoso** [expressjs/session#113]
I have an idea and maybe it could be helpful to this middleware.

Here is: I want to use the option resave: true, but I do not want to make an update on mongodb (or any other database) on every single request. Maybe could be nice if we had an option that says: I want to 'resave' the session on my database just one time in an period of five days, or one time in X hours. So, does not matter how many requests the user make on the interval of the time established, we will just update the session on the database when the current date is X hours or X days before the expires date, if it is, we do the update and the session will be avaliable for five days again. Saving the database of many consecutive written in a short period of time.

What do you think?
I'm sorry by my english, i'm trying to improve it :/

**Comment by JoeWagner** [comment]
@rafaelcardoso I'm not sure I understand what you are saying.
If you use `resave: false` the session will only be (re)saved if there are changes made to it.  Is that what you are looking for?

**Comment by rafaelcardoso** [comment]
yes but, I want to keep the user logged in even if he does not change the session. Exemple: The user log in to website, and keep returning to the website consecutives times per day (without changing the session), I want to update the session expires date on database just one time per day.

**Comment by dougwilson** [comment]
This is already possible with `resave: false` as long as the store module you're using implements the `touch` interface and you are using 1.10.0: only the expires date will get updated if there were no session changes.

**Comment by gabeio** [comment]
Or rolling: true...?

**Comment by rafaelcardoso** [comment]
@dougwilson yeah, the touch method should works for me, but the module i'm using (connect-mongo) does not implement this interface, i will look for another one. Thank you all guys!

**Comment by rafaelcardoso** [comment]
Just in case someone drop on this issue by searching on google: the maintainer of connect-mongo middleware just updated their code, now the .touch() method are available.

Issue: https://github.com/kcbanner/connect-mongo/issues/149
Implementation: https://github.com/kcbanner/connect-mongo/commit/2836e4d9c5825d11302f818df2e5d3bf371694e6
Test: https://github.com/kcbanner/connect-mongo/commit/1193e9f385838a8584030734f6976740187935a3

**Comment by dougwilson** [comment]
Nice!!!! :)

**Comment by rafaelcardoso** [comment]
Guys, i guess that I found a bug.
I'm using this configs:

`saveUninitialized: false`, `resave: false`, `rolling: false`

But the session module is touching the session on database on every single request, due this line: https://github.com/expressjs/session/blob/master/index.js#L270

I guess that it's wrong, session.touch() must be executed just when the resave option is set to true or when the method req.session.touch() is explicity called, right?

By removing this line worked for me.

**Comment by dougwilson** [comment]
This is, unfortunately, working correctly. I think there is a misunderstanding of what "touch" means in this case. A session is "touched" in this module if it is loaded and then the request ends; it is only saved if you changed something in it, or you have resave:true.

**Comment by dougwilson** [comment]
Your original request is way beyond the scope of this module, unfortunately,and has a lot of issues in how it would be implemented. It is also something that needs to be implemented by the store, not this module (this module tells the store all the information necessary; it is up to the store to decide how to act on it). Perhaps you want to write a decorator store and use it to decorate the mongo store you are using to make it do the lazy stuff you want.

**Comment by rafaelcardoso** [comment]
You said: "it is only saved if you changed something in it, or you have `resave:true`"

I do not have `resave:true` and I do not changed the session, my route just render the template, check it:

```javascript
router.get('/', function(req, res) {
  	res.render('index');
});
```

And it is calling the .touch() method..

But that's ok, no worries. I will make an decorator to do this thing, it's a very specific feature anyway.
Thanks a lot :v:

**Comment by dougwilson** [comment]
Ok :) and by save, I mean that we call set(); touch() is not a session save, though your store may still write to the database, to keep the session from expiring.
