### ISSUE TITLE
option to touch session only in certain situations

### ISSUE THREAD

**Issue by arieljake** [expressjs/session#114]
If I understand correctly, the store is being asked to touch the session on every request that passes through the session middleware, which may result in many touches per html page request if that page pulls in multiple static files, makes multiple ajax calls, etc.

Doesn't it make sense to specify some type of filter so that this is reduced, ideally to once per request?

One possibility would be to specify a regex for when touch should be executed.

**Comment by dougwilson** [comment]
Filtering is already a part of Express, so there is no reason to duplicate that here. One simple solution is to `app.use()` this module _after_ your `app.use()` your static module, then no requests for static assets will try to load sessions or touch them.

**Comment by arieljake** [comment]
> this module after your app.use() your static module

this is not possible, because the static module must be placed after all other routes.

> Filtering is already a part of Express

I get that. Then what else is possible?

**Comment by arieljake** [comment]
I mean, as a user of session(), are you not concerned about hitting your database potentially many times to touch your sessions when it is not needed?

**Comment by dougwilson** [comment]
I have the `session` middleware scoped to the URLs I actually need it for (besides the fact that I have static at the top). If your site is layout requires that static be at the bottom, then I guess you can't just put the session module after it. Can you give an example of what kind of filter you need?

**Comment by arieljake** [comment]
Oh, do you just place the session.use in the route handler chain for those routes you need it for? The way we might use ensureAuthenticated? As in:

router.get('/', session(), myRoute);

**Comment by arieljake** [comment]
Btw, I don't think you want to use the static middleware before your routes because it tries to stream every request, passing to next() on stream error which I'm not sure the cost of but anyway seems unnecessarily costly to me.

**Comment by dougwilson** [comment]
> One possibility would be to specify a regex for when touch should be executed

If this is a regexp on the path, this is the Express-based solution:
```js
var expressSession = require('express-session')

var sessionMiddleware = expressSession({ /* your config */})
app.use(function (req, res, next) {
  if (/something/.test(req.url)) {
    sessionMiddleware(req, res, next)
  } else {
   next()
  }
})
```
I'm sure there are modules on npm that does this for you already.

> Btw, I don't think you want to use the static middleware before your routes because it tries to stream every request, passing to next() on stream error 

This is not true.

**Comment by dougwilson** [comment]
Though if you have your static mounted at `/` instead of at something like `/public` or `/assets`, then yes, putting the static first will cause unnecessary file system stat calls

**Comment by arieljake** [comment]
> Though if you have your static mounted at / instead of at something like /public or /assets

You are absolutely right that adding a prefix would solve this problem. Thank you, I had not thought of that.

Per your suggestion, are these not equivalents:

app.use(function (req, res, next) {
  if (/something/.test(req.url)) {
    sessionMiddleware(req, res, next)
  } else {
   next()
  }
})

and

app.use(/something/, sessionMiddleware);

**Comment by dougwilson** [comment]
> Per your suggestion, are these not equivalents

I didn't say they were equivalent; in fact, they are not supposed to be equivalent. Your suggestion was "one possibility would be to specify a regex for when touch should be executed". I was just saying how you could invoke this middleware conditionally depending on come regular expression.

**Comment by arieljake** [comment]
I was merely asking if they were equivalent. I think my needs are addressed by your suggestions. Thanks for the help, I appreciate it.
