### ISSUE TITLE
deprecation issue?

### ISSUE THREAD

**Issue by gabeio** [expressjs/session#116]
I don't know why but I can't shake this issue and I read through any other issue pertaining to this. ie: #100 but it hasn't helped :cry:
```Javascript
var express, expressSession, app, aSecret, port, server;
express = require('express');
expressSession = require('express-session');
app = module.exports = express();
aSecret = process.env.cookie;
app.use(expressSession({
  secret: aSecret,
  resave: false,
  saveUninitialized: true,
  cookie: {
    path: '/',
    httpOnly: true
  }
}));
app.route('*').get(function(req, res){
  return res.send('ok');
});
if (!module.parent && (process.env.HTTP != null || process.env.PORT != null)) {
  port = (process.env.HTTP || process.env.PORT) || (yargs.argv.http || yargs.argv.port);
  console.log('Server started on port ' + port + ' at ' + new Date(Date.now()));
  server = app.listen(port);
}
```
what am I doing wrong? I thought this is how to pass secret to express-session?

-----
I keep getting:
```bash
express-session deprecated req.secret; provide secret option app.js:6:9
```

**Comment by dougwilson** [comment]
It's very likely that if you `console.log(aSecret)`, it's an empty string.

**Comment by gabeio** [comment]
darnit I thought I checked that already woops thanks!

**Comment by mikeleonardonline** [comment]
I'm getting "express-session deprecated req.secret; provide sec ret option at app\index.js:19:9". I was so happy to find this and now i've wasted two hours trying to get it to work.

**Comment by kmjayadeep** [comment]
@dougwilson same mistake..hehe thanks

**Comment by tnguyen14** [comment]
Ran into this error today as well. Perhaps there can be a better error message here?

**Comment by gabeio** [comment]
@tnguyen14 do you have an idea for what would make the error message better? Suggested edits are welcome!

**Comment by johnantoni** [comment]
Same here, thought it was deprecated but was actually an empty string.

Could always switch deprecation to:

`express-session warning req.secret; provide session secret`

or 

`express-session warning req.secret; session secret undefined` or blank ?

**Comment by Mutembeijoe** [comment]
> It's very likely that if you `console.dir(aSecret)`, it's an empty string.

Thanks, i was not setting the env variables on heroku

**Comment by CalebDelbridge** [comment]
It's been almost 5 years, and we still have the same error message suggesting that the method we are using is deprecated but, in actuality, is just undefined.
