### ISSUE TITLE
why secure =  true, site must be https-enabled?

### ISSUE THREAD

**Issue by i5ting** [expressjs/session#117]

**Comment by Fishrock123** [comment]
Yes. Secure will make the cookies https-only.

If you need to transfer them partially over http, as in with a reverse-proxy, you can use `proxy: true`

**Comment by Fishrock123** [comment]
See https://github.com/expressjs/session#options and https://github.com/expressjs/session#cookie-options :)

**Comment by dougwilson** [comment]
You don't even need to muck with proxy setting here if you're using Express and setup your trust there :) But yes, setting secure to true will require HTTPS.

**Comment by i5ting** [comment]
thanks for all reply
