### ISSUE TITLE
unique cookie when using multiple apps

### ISSUE THREAD

**Issue by Sjonnie2nd** [expressjs/session#124]
Just a minor suggestion for updating the documentation.

I tried to access 2 different node apps in the same browser on the same machine and I noticed the session cookies disturbed eachother. After logging in in the first app and logging in in the second app, the first cookie was invalid.

Digging through the possible options (secret, cookie.path, genid(), name), with trial & error I ended up with setting the names to fe. "connect.app1.sid" and "connect.app2.sid". After it it worked like a charm. 

Perhaps it could help others to mention at the option "name": "If you want to use multiple applications ensure your applications use unique name's"

And further.. Great work!

**Comment by dougwilson** [comment]
Done :)!
