### ISSUE TITLE
Use generated cookie from one app in another app

### ISSUE THREAD

**Issue by cthayur** [expressjs/session#125]
Hi there,

Here's my scenario:

My web app is hosted at 'web.test.com' and my API is hosted at 'api.test.com'.

I've managed to get the cookie generated at the web app over to the api with jQuery by setting the domain to '.test.com'.

How do i use this cookie at the api to authenticate the user?

**Comment by JoeWagner** [comment]
This question may be outside the scope of express-session. For login sessions, you may want to look at [passport](https://github.com/jaredhanson/passport), which potentially uses this module.

**Comment by gabeio** [comment]
This is not outside the scope of express-session. If you are using a db backend instead of in memory and they are both connected to the same db backend the session should persist between the two apps.

**Comment by JoeWagner** [comment]
>If you are using a db backend instead of in memory and they are both connected to the same db backend the session should persist between the two apps.

Yes this is possible.  I was simply pointing out that you will need some kind of layer on top of this module to handle authentication.  I believe this is what the @cthayur was asking.
Perhaps I am misunderstanding the question?

**Comment by dougwilson** [comment]
Call you store's `.get()` method with the session ID? Is that a viable option?

**Comment by dougwilson** [comment]
Closing due to lack of answering questions. If you do answer them, I'll gladly re-open the issue :)
