### ISSUE TITLE
Explain resave issues more

### ISSUE THREAD

**Issue by dantman** [expressjs/session#126]
The `resave` option says "Depending on your store this may be necessary" but doesn't explain why it may be necessary for some stores and not for others.

**Comment by dougwilson** [comment]
It is necessary if, without this option set to `true`, the store ends up prematurely expiring the session because `.set` is no longer called on every request for that session.

**Comment by dougwilson** [comment]
And as of 1.10.0 of this library, stores can implement a `.touch` method where they can keep the session alive without needing to overwrite the data itself. If you can came up with a non-confusing description of this to add to the docs, that would be much appreciated!

**Comment by dantman** [comment]
How about this?
"This may be necessary if your store implements expiration but does not implement `.touch`"

**Comment by dantman** [comment]
And thanks for the note about `.touch`. I'm trying to cleanup `connect-session-sequelize` right now because I'd like to use it but it doesn't implement expiration. I'll try to remember to implement that as well.

**Comment by dougwilson** [comment]
> This may be necessary if your store implements expiration but does not implement .touch

Unfortunately this answer doesn't apply to all the versions in which `resave` is deprecated but don't understand `.touch` yet (versions >= 1.6.0 and < 1.10.0). The message should apply to all the versions in which people will come searching from seeing deprecation messages (unfortunately npm can only show one version of a readme).

**Comment by dougwilson** [comment]
I added something to the readme. Let me know if this isn't enough/feel free to expand on it :)
