### ISSUE TITLE
Proper way of deprecating a session secret

### ISSUE THREAD

**Issue by gzurbach** [expressjs/session#127]
Hi there!

First of all, thank you for that great library. We've been using it is production for 3 months now and it works perfectly!

I'd like to change my session secret once in a while (every month?) to strengthen my security. But if I do that, I believe all my users will loose their session. It's not a huge deal but I'd rather avoid that scenario. Would you have recommendations on how to proceed in a smother way?

Also, I was thinking that maybe instead of having a single secret in the config, we could allow to set an array of secrets. This way, one could add a new secret on day 1 and remove the old secret two days later. In the meantime, the authentication will check against both secrets.

Pushing the idea further, I was also thinking it may be a good thing to always have 2 or 3 (rotating) secrets in order to increase protection against brute force attacks... what do you think?

**Comment by dougwilson** [comment]
Supporting multiple secrets and key rotation is definitely a planned feature. As for the current state of this module, I unfortunately don't think it is easily possible, but I will look into it this weekend.

**Comment by gzurbach** [comment]
Thanks for your quick answer. I'd be willing to help if you are open to PRs? In a first time I'd like to discuss the overall idea on how to support several secrets. I was thinking the options could take an array of valid secrets and maybe add an option to list deprecated secrets (only used to unsign cookies).

**Comment by dougwilson** [comment]
Typically you just provide an array and everything is signed with the 0th array element. Then to unsign, you just iterate through each secret until one works.
