### ISSUE TITLE
Allow session store for particular http methods like POST, GET etc

### ISSUE THREAD

**Issue by shahidbits** [expressjs/session#130]

**Comment by JoeWagner** [comment]
@shahidbits can you elaborate a little more on what you are trying to accomplish?

**Comment by dougwilson** [comment]
Regardless, it's not the task of a middleware; the user can simply wrap the middleware with whatever invokation logic that they need:
```js
var expressSession = require('express-session')

app.use(onlyFor(['GET', 'POST'], expressSession({ /* options */ })))

function onlyFor(methods, middleware) {
  return function (req, res, next) {
    if (methods.indexOf(req.method) === -1) return next()
    return middleware(req, res, next)
  }
}
```

**Comment by shahidbits** [comment]
Actually, I thought of such an option because I ran into Cross-origin resource sharing issue.
The browser would send an HTTP OPTIONS along with all the requests to the server. Thus, express-session is bound to store session for every request.

**Comment by dougwilson** [comment]
This is the purpose of the `saveUninitialized` option.
