### ISSUE TITLE
automatically logoff after few requests

### ISSUE THREAD

**Issue by CrackerakiUA** [expressjs/session#132]
I am using passportjs and i have simple form which check if username exists in users.
```js
app.post('/api/checkUsernameAvail', function(req, res) {
    if(req.isAuthenticated()){
        User.find(
        {username: req.body.username.toLowerCase()},
        function(err, user){
            if(user.length==0) var avail=true;
            else var avail=false;
            res.send(avail);
        });
        }else{
            res.send(false);
        }
});
```
After few requests, each time different count and different timeout, user automatically logged off. Not sure why, perhaps passport do something, but i am not sure how to fix this task. Have tried to not user `req.isAuthenticated()`, same result.

**Comment by gabeio** [comment]
why are you checking if the username is blank: `checkUsernameAvail` & `if(user.length==0) var avail=true;` if you are saying that it is checking if the user name exists...

**Comment by CrackerakiUA** [comment]
I dont have any error, just session stop exist. I have social login, and after that i have user to setup username, and in that way i am testing if username exists in database(if username given is not found, return avail=true;).

**Comment by dougwilson** [comment]
@CrackerakiUA I don't think anyone here really knows enough about PassportJS to assist here. You may want to open an issue at https://github.com/jaredhanson/passport/issues or at least explain to me how to use PassportJS/provide something I can copy and paste into a file and run to see the issue occurring.
