### ISSUE TITLE
Req Session

### ISSUE THREAD

**Issue by brunoss** [expressjs/session#140]
Why did you decided that we should define a cookie in the req instead of res?
It would make sense that when the cookie is defined to do it in res, since is the server that takes initiave to send it to the client.

**Comment by dougwilson** [comment]
Hmm, I'm not sure what the question is :/

**Comment by Fishrock123** [comment]
He's asking why cookies are on the request.

I'd say because they are a client-thing and more related to the request portion. I suppose it would make more sense to be abel to send cookies from the response.

**Comment by dougwilson** [comment]
lol, I'm still not sure what this means. We read `req.headers.cookies` (https://github.com/expressjs/session/blob/master/index.js#L457), which is because it's a Cookie HTTP header on the request; Node.js puts them there, we didn't.

Can you elaborate, @Fishrock123 ?

**Comment by Fishrock123** [comment]
Actually, you do set cookies from the request, my bad.

@dougwilson that's what he's asking about, this is node-level stuff, not directly ours.

**Comment by brunoss** [comment]
My question is why did you decided that the Session should be defined [in the request](https://github.com/expressjs/session/blob/master/index.js#L139) instead of response.

The server is the one who takes the initiative to send the session cookie to client in a header of the **response**. Only from that moment forward would make sense to retrieve that cookie from the request, since HTTP protocol states that the very same cookie that was sent before by the server must be sent again by the client.

My point is that the first time we define the session we should be doing:

``` javascript
res.session.userid = 1; //sets the cookie in the response header
//later
var userid = req.session.userid; //reads the session from the request
```
