### ISSUE TITLE
Trouble upgrading to Express 4 + standalone session middleware...

### ISSUE THREAD

**Issue by rabbitfufu** [expressjs/session#148]
Hello,

I have a question about upgrading from the old session middleware that was bundled with Express 3, and the session middleware intended for use with Express 4...

Here is the background:  

I need to support sessions on some devices that do not allow session cookies.  To do this, in Express 3 I would pass the sessionID in the querystring, then manually set the session cookie so express.session could pick it up:
```js
app.use(function getSessionByQuerystring( req, res, next ) {
    if ( req.query.session_id ) req.cookies[ "connect.sid" ] = req.query.session_id;
    next();
});

app.use( express.session({
    secret: "secret stuff",
    name: "connect.sid",
    cookie: { secure: false },
    store: store
}));
```
This worked fine. However, now that I have upgraded and am using the standalone session middle-ware, it has stopped working:
```js
var session = require( "express-session" );

app.use(function getSessionByQuerystring( req, res, next ) {
    if ( req.query.session_id ) req.cookies[ "connect.sid" ] = req.query.session_id;
    next();
});

app.use( session({
    secret: "secret stuff",
    name: "connect.sid",
    cookie: { secure: false },
    store: store
}));
```
The session middleware no longer seems able to pick up the session cookie that I am manually setting.

Can anyone tell me what has changed between the session middleware bundled with Express 3, and the new express-session middleware for use with Express 4, that would cause this to stop working? How can I manually set req.cookies[ "connect.sid" ] so that the session middleware will recognize it?  Thanks!

**Comment by dougwilson** [comment]
You need to add to req.headers.cookie instead.

**Comment by rabbitfufu** [comment]
Thank-you for the quick response!
If you don't mind me asking:  How do I write to req.headers.cookie?  I can't seem to figure that out.

**Comment by dougwilson** [comment]
Hi, sorry, was on a cell phone earlier. So the header is an array, so you may want to try `req.headers.cookie = ["connect.sid="+session_id];`

Let me know if that doesn't work (I haven't tried it myself yet). Also, what version of Express 3.x are you upgrading from (because most of Express 3.x `express.session` is literally this module :) ).

**Comment by rabbitfufu** [comment]
Hi Doug, I tried manually setting req.headers.cookie as an array above:

req.headers.cookie = ["connect.sid="+session_id];

This causes the following fatal error:

TypeError: undefined is not a function
    at Object.parse (/home/project/node_modules/express-session/node_modules/cookie/index.js:39:21)
    at getcookie (/home/project/node_modules/express-session/index.js:463:26)
    at Object.session [as handle] (/home/project/node_modules/express-session/index.js:179:36)
    at next (/home/project/node_modules/express/node_modules/connect/lib/proto.js:193:15)
    at Object.getSessionByQuerystring [as handle] (/home/project/config/env.js:47:3)
    at next (/home/project/node_modules/express/node_modules/connect/lib/proto.js:193:15)
    at next (/home/project/node_modules/express/node_modules/connect/lib/proto.js:168:78)
    at Object.cookieParser [as handle] (/home/project/node_modules/express/node_modules/connect/lib/middleware/cookieParser.js:65:5)
    at next (/home/project/node_modules/express/node_modules/connect/lib/proto.js:193:15)
    at Object.compression [as handle] (/home/project/node_modules/compression/index.js:212:5)


> Also, what version of Express 3.x are you upgrading

It's an older version:  3.4

**Comment by dougwilson** [comment]
Gotcha. Would you be willing to update to the latest 3.x prior to jumping to the latest Express 4.x just to see if there is a regression somewhere? Really, setting `req.cookies`, though deprecated, should still work.

**Comment by rabbitfufu** [comment]
Hi Doug,

> Would you be willing to update to the latest 3.x

Certainly.  I upgraded to Express 3.20.2 -- the bundled expres.session mw now exhibits exactly the same behaviour as the standalone middleware.  Setting req.cookies does not work, and manually setting req.headers.cookie throws exactly the same error.

**Comment by dougwilson** [comment]
Interesting. That is a problem, if your exact same code worked with 3.4 but didn't with 3.20. Would you be willing to make a PR to fix it or provide a complete app I can reproduce with?

**Comment by rabbitfufu** [comment]
Hi Doug.  I'd be happy to put together a sample app that you can reproduce with -- you'll have to forgive me, but I am just learning how to use GitHub -- what is simplest, should I just email it to you as a zip?

**Comment by dougwilson** [comment]
Yes, you can, though if your reproduction is more than you can just paste in this issue's comments, then be careful it can run on Windows and doesn't require things like Redis, etc.

**Comment by rabbitfufu** [comment]
Thanks Doug, I will just paste it.  Here is a simple Express app that I have confirmed is working on Express 3.4 and is broken on Express 3.20.  Please let me know if you have any questions about this.  Thanks again for your help.


var express = require('express');
var app = express();

app.use( express.cookieParser( "Secret" ));

// Get session_id from querystring and manually create session cookie
// For clients that do not allow session cookies
// eg usage: http://localhost:3000/?session_id=asdfjkasdfasdf
app.use(function getSessionByQuerystring( req, res, next ) {

	// trying to set the req.headers.cookie will result an error 
	if ( req.query.session_id ) req.headers.cookie = [ "connect.sid=" + req.query.session_id ];
	

	// setting req.cookies does not throw an error 
	// this works fine in express 3.4, express.session will correctly grab the session
	// this does not work express 3.20, express.session does not seem to recognize the cookie
	// if ( req.query.session_id ) req.cookies[ "connect.sid" ] = req.query.session_id;

	next();
});

app.use( express.session({
	secret: "Secret",
	name: "connect.sid",
	cookie: {
		secure: false
	}
}));

app.get('/', function ( req, res ) {
  res.send( 200 );
});

var server = app.listen(3000, function () {
  console.log( 'Rock and Roll' );
});

**Comment by dougwilson** [comment]
I'm having trouble getting it to work on Express 3.4, but I think it may because it's not clear what value I need to put in `session_id`. Does this look right?
```
curl -i http://127.0.0.1:3000?session_id=s%3AowkUJWGfMg4GpHDMnkmtkd4A.fknTNInCaLYw9OBGDAPOuT5zy%2BTj5l3B2Nnqt%2Ff3jlM
```

**Comment by dougwilson** [comment]
(I have the first if commented out and the second uncommented, which I believe is what you're saying the Express 3.4 configuration is)

**Comment by dougwilson** [comment]
Nevermind, that URL above does work; I must have restarted the app between when I pulled `connect.sid` and when I tried to put it in the query string, whoops! The URL is also working just fine when upgrading Express and using this library... Can you send a paste of exactly what it looks like when you use this library, now that I think I know what you're doing?

**Comment by rabbitfufu** [comment]
Yes, for testing on 3.4, here is what it should look like:

```js
var express = require('express');
var app = express();
app.use( express.cookieParser( "Secret" ));
app.use(function getSessionByQuerystring( req, res, next ) {
	if ( req.query.session_id ) req.cookies[ "connect.sid" ] = req.query.session_id;
	next();
});
app.use( express.session({
	secret: "Secret",
	name: "connect.sid",
	cookie: {
		secure: false
	}
}));
app.get('/', function ( req, res ) {
  console.log( req.sessionID );
  console.log( req.session.test );
  req.session.test = "something";
  res.send( 200 );
});
var server = app.listen(3000, function () {
  console.log( 'Rock and Roll' );
});
```

Here is how I test it.  I visit it in the browser once to generate a session:
localhost:3000/
This will spit out the sessionID in the terminal.  eg:  chKcaFaGjBQCUO2diGvGTtuV
I then use curl in a terminal to see if I can retrieve the session:
curl -i localhost:3000/?session_id=chKcaFaGjBQCUO2diGvGTtuV

You should see that on 3.4, each time I run curl, the same session is returned, and the session var req.session.test is set to "something"

On 3.20, everytime you run curl a different sessionID will be generated, and req.session.test will be undefined.

**Comment by dougwilson** [comment]
Add it to `req.signedCookies` I see now. The change in behavior was because of a security issue and so we had to change it; you cannot put unsigned values within `req.cookies`.

**Comment by rabbitfufu** [comment]
Here is example output on 3.4 each time I run curl:

Rock and Roll
chKcaFaGjBQCUO2diGvGTtuV
undefined
chKcaFaGjBQCUO2diGvGTtuV
something
chKcaFaGjBQCUO2diGvGTtuV
something
chKcaFaGjBQCUO2diGvGTtuV
something
chKcaFaGjBQCUO2diGvGTtuV
something

Here is example output on 3.20:

Rock and Roll
H3lhBiRfnzx3G8lufW2SX7WR94-wFPzu
undefined
Or9F1mQow19TdWO2bTQLUSGPasH7rYr3
undefined
rNBDoby-CHXUDfEIt4biSI9Yc0Kl3OVD
undefined
MHM4RQ29IPyIbTs3FRKxDqBqKTacVR4e
undefined

**Comment by rabbitfufu** [comment]
This works!!
Thank you sooo much for your help troubleshooting this, it is greatly appreciated.  :+1:

**Comment by dougwilson** [comment]
It's no problem! Glad we could get to the root and you have a path forward :)!

**Comment by rabbitfufu** [comment]
Hi Doug -- I'm wondering if I could ask you one more question on this topic, if you don't mind.

Using req.signedCookies works great in every situation except for one:

If I send an upload via SSL, express-session does not pick up the session.  For example, a POST of the form:
```
https://myapp.com/upload?session_id=wXmXfrMWUjHqZHQ4c7KYiHuVcRyrgJ49
```
If I send the upload via http, instead of https, everything works fine -- so I assume it has something to do with the SSL.  All other SSL requests also work fine, this only affects uploads.

Any ideas?

**Comment by dougwilson** [comment]
AFAIK there are no limitation like this with that property or this module. To be able to really say anything, I would need to be able to reproduce it so I can debug what the issue is.

**Comment by rabbitfufu** [comment]
Ok thanks again for your help the other day, I will investigate this further.

**Comment by dougwilson** [comment]
Ok, let me know if you need anything. And if you're not able to shrink something down for here, or want me to look at confidential code, please feel free to hit me up via email (on my github profile page).

**Comment by Jpunt** [comment]
I'm running into the same kind of issues here. I also need to manually set the sessionID, but setting it in `signedCookies` doesn't seem to work. 

```js
app
  .use(function(req, res, next) {
    if(req.query.sessionID) {
      req.signedCookies["connect.sid"] = req.query.sessionID;
    }
    next();
  })
  .use(session({
    httpOnly: false,
    secret: 'secret',
    resave: false,
    saveUninitialized: true
  })
  .get('/session', function(req, res) {
    console.log('sessionID:', req.sessionID);
    req.session.tmp = req.session.tmp + 1 || 0;
    req.session.save();
    res.send('session: ' + req.session.tmp);
  })
```

When I hit `http://localhost:3000/session?sessionID=42` a couple of times, the counter goes up. When I hit that exact same url in a different browser I expect it to pick up the count from the session, but it does not.

An observation: The log for `req.sessionID` is not what I gave to the query string, so I guess it's initialising its own sessionID instead. 

I've also tried a custom `genid` like so:

```js
  .use(session({
    httpOnly: false,
    secret: 'secret42',
    resave: false,
    saveUninitialized: true,
    genid: function(req) {
     return req.query.sessionID || uuid.v1();
   }
  })
```

This seemed like a cleaner solution anyway, but it also doesn't work for me. It sets the `sessionID` correctly for the first hit, but it won't update it for requests with a different `sessionID`. 

Any help on this would be great!

**Comment by dougwilson** [comment]
Please open a new issue rather than posting a new question in an old issue. You can always link to old issues if you think they may be similar / relevant. People not subscribed to this repo won't look in closed issues to help.
