### ISSUE TITLE
Add new compatible session store (Cassandra-based)

### ISSUE THREAD

**Issue by cavweb20** [expressjs/session#149]
Hi guys,

Could you add our compatible session store (Cassandra-based) to your list of session stores?

https://github.com/webcc/cassandra-store

Thanks!

**Comment by JoeWagner** [comment]
:+1:

**Comment by dougwilson** [comment]
Thank you for the suggestion! It has been added :)

**Comment by cavweb20** [comment]
You're welcome! ;)
