### ISSUE TITLE
Store sessions in javascript database

### ISSUE THREAD

**Issue by estvmachine** [expressjs/session#162]
Hi, im searching for a API to store sessions in LokiJS (http://lokijs.org/#/). With LokiJS i can use a database in  server memory BUT without install nothing more than node module (im using node.js). What i need to make **connect-lokijs**  or maybe other person know a database just based in javascript with a existing implementation for store sessions in express.

**Comment by gabeio** [comment]
mongodb uses B(/J)SON storage... alternatively there is leveldb...

**Comment by estvmachine** [comment]
Mongodb you need install it or at least have it the binary code, for me its a escalable solution and better than use server memory, but im want to make a executable version of my aplication with enclose for example (http://enclosejs.com/) and for that is better is you have only javascript code.

The leveldb looks promising :)

**Comment by gabeio** [comment]
Sorry I just got confused on what part had to be javascript... leveldb needs to build in c (automatically does this when installed with npm) but everything else is in node/javascript...

**Comment by dougwilson** [comment]
P.S. @gabeio I added you as a collaborator on this repo since you're always around here :) Feel free to decline the invite or to reach out if you have any questions.

**Comment by dougwilson** [comment]
@estvmachine as far as LokiJS goes, it does not seem like anyone has created an aadapter for this module to work with LokiJS (yet). You may want to look into the suggested LevelDB to see if it meets your requirements, as there is already a LevelDB adapter you can use: https://www.npmjs.com/package/level-session-store

**Comment by estvmachine** [comment]
I do a list of DB that really match with im searching:

LokisJS: http://lokijs.org/#/
NeDB: https://github.com/louischatriot/nedb
PouchDB: http://pouchdb.com/
nStore :https://github.com/creationix/nstore
TingoDB: http://www.tingodb.com/

If in one moment im gonna do a API for store the sessions, im gonna share it.

**Comment by gabeio** [comment]
From that list I see there is a nedb connect-session https://www.npmjs.com/package/connect-nedb-session-two it looks like it might be from the old express but I believe it should still work. Lokijs doesn't yet (unless you wanted to make one :smile:) and pouchdb also seems not to have a session store either.

**Comment by gabeio** [comment]
@dougwilson thank you :smiley:! I will shoot you an email.

**Comment by estvmachine** [comment]
Oh thanks :) , now im trying use the three to see if really useful and lightweight. Its good to know that one of the options have support to store sessions :+1:
