### ISSUE TITLE
release 1.11.3 is not on npm

### ISSUE THREAD

**Issue by episodeyang** [expressjs/session#163]
Hi, 

I tried to install the ~1.11.3 for the `unset: "destroy"` new commit, but it turned out that this version is not up on npm yet. 

Is this part of the release convention of this repo, or it is a mistake?

Cheers

**Comment by dougwilson** [comment]
Sorry, it looks like it wasn't published on accident. You do not need 1.11.3 "for the unset: "destroy" new commit" anyway; the only difference between 1.11.3 and what's published right now (1.11.2) is just some readme updates.

**Comment by dougwilson** [comment]
`unset: "destroy"` was added back in version 1.4.0.
