### ISSUE TITLE
Session cookie not stored

### ISSUE THREAD

**Issue by kbariotis** [expressjs/session#165]
It looks like when I am setting a `cookie` option like this, the session's cookie won't be stored in the browser.
```
app.use(session({
    secret: 'someWoWSecret',
    cookie: {
            "maxAge": 86400000,
            "secure": true
        }
});
```

If I remove the `cookie` everything works fine. I've also played with different values on `maxAge` and `secure` and still the same.

Any ideas?

**Comment by dougwilson** [comment]
I'm sorry, but I don't have any ideas. Without sharing your code, you're really the only one who can debug :/ I can at least say I use those settings personally in production without issues.

**Comment by gabeio** [comment]
Is your site running over https? With the "secure" option the cookie will only be returned to the website over https.

**Comment by dougwilson** [comment]
Oh, that reminds me: one thing you can try if it works when you don't specify cookie is to add it, but use exactly what the default value is and see if that works still (see documentation https://github.com/expressjs/session/blob/master/README.md#cookie). If it does work, then you can try tweaking the values and determine exactly what change is the issue. Right now you are changing a lot simply by omitting some of the default keys.

**Comment by kbariotis** [comment]
I use https only. Latest express session

```
/*
 * @module server.js 
 */
'use strict';

var express = require('express'),
    compress = require('compression'),
    bodyParser = require('body-parser'),
    logger = require('morgan'),
    winston = require('winston'),
    utils = require('./utilities/utils'),
    conf = require('./utilities/conf').conf(),
    domainMiddleware = require('./middlewares/domain'),
    cookieParser = require('cookie-parser'),
    session = require('express-session'),
    path = require('path');

    winston.info('# Environment ' + express().settings.env);

var app = express();

winston.add(winston.transports.File, {
    filename: './logs/logs.log',
    colorize: true,
    timestamp: true,
    json: false
});

/*
 * app.locals.numeral = require('jade');
 */
app.locals.moment = require('moment');

/*
 * log all requests
 */
app.use(logger('dev'));

/*
 * support json and url encoded requests
 */
app.use(compress());
app.use(bodyParser());

/*
 * setup encrypted session cookies
 *
 * Commented lines seems not to work
 *
 */
app.use(cookieParser());
app.use(session({
    secret: 'wowSecret',
    name: conf.get('session:name'),
    resave: false,
    saveUninitialized: false
    //cookie: conf.get('session:cookie')
}));

/*
 * use jade templating engine for view rendering
 */
app.set('views', __dirname + '/views');
app.set('view engine', 'jade');
app.set('jsonp callback', true);

app.use(domainMiddleware);

app.use(function (req, res, next) {
    if (express().settings.env === 'development') {
        next();
    } else {
        if (utils.getProtocol(req) === 'http://') {
            return res.redirect('https://' + req.get('Host') + req.url);
        } else {
            next();
        }
    }
});

app.use(require('./core/base'));

module.exports = app;
```

```
/**
 * @module core/base
 * @description
 */

'use strict';

var express = require('express'),
    winston = require('winston'),
    auth = require('../routes/auth'),
    dashboard = require('../routes/dashboard'),
    authMiddleware = require('../middlewares/auth'),
    authDataMiddleware = require('../middlewares/data-api-auth'),
    favicon = require('serve-favicon'),
    path = require('path'),
    router = express.Router(),
    PrettyError = new (require('pretty-error'))();

/*
 * statically serve from the 'public' folder
 */
router.use(express.static(path.join(__dirname, '../../public'), {
    maxAge: 86400000
}));

/*
 * set routes. each module exposes its won routes
 */
router.use(function (req, res, next) {
    var tmpPath = req.path.split('/').filter(Boolean);
    var retPath = '';
    retPath = (tmpPath.length > 0) ? tmpPath[0] : '';
    retPath = (tmpPath.length > 1) ? retPath + '-' + tmpPath[1] : retPath;
    res.locals.curpath = retPath;
    next();
});


router.use(favicon(__dirname + '/../../public/images/favicon.png'));

router.use('/auth', auth);

router.use(authMiddleware);
router.use(authDataMiddleware);

router.use('/', dashboard);

router.use('/*', function (req, res) {

    winston.error('Not Found at : ' + req.originalUrl + req.method);

    res.status(404);
    res.render('error', {
        title: 'Service Management Platform',
        status: 404
    });
});

router.use(function (err, req, res, next) {
    if (!err) {
        err = new Error('Unkown error');
    }

    winston.error(err);

    res.status(err.errorCode || 500);

    if(req.app.get('env') !== 'development' &&
       req.app.get('env') !== 'test') {

        res.render('error', {
            title: 'Service Management Platform',
            status: 500
        });

    } else {

        console.log(PrettyError.render(err));

        res.render('error', {
            title: 'Service Management Platform',
            status: 500,
            err: err
        });

    }

});


module.exports = router;
```

**Comment by dougwilson** [comment]
@kbariotis have you been able to debug your issue using the steps from https://github.com/expressjs/session/issues/165#issuecomment-106783973 yet?

**Comment by wmulligan** [comment]
I have the same issue.  Setting cookie secure to false works, but cookie secure true fails.  The cookie is not sent to the browser when cookie secure is true.

My server is behind a proxy, so I am not sure if they is affecting it.  The other cookies I create all work with secure mode enabled, it is just the session cookie that is broken.

Any ideas?

**Comment by gabeio** [comment]
When you run node behind a reverse proxy node has no idea it's running https in the front. So you might be getting the cookies back but express says they aren't secure because between your node and reverse proxy the connection is only http.

**Comment by gabeio** [comment]
yeah @kbariotis & @wmulligan try setting `app.set('trust proxy', 1)` if you are running express/node behind a reverse proxy like `nginx` or `haproxy` etc.

**Comment by wmulligan** [comment]
Yes I set app.set('trust proxy', 1), but that did not help.  I've looked at the session code, and it seems to be using a special header to detect if they are connected to https.  My proxy does not seem to populate that header.

I had to create a simple hack to get everything to work:

```
function secure(req, res, next) {
    req.headers['x-forwarded-proto'] = 'https';
    next();
  };
```

**Comment by wmulligan** [comment]
Perhaps it would be useful to offer a option to bypass the secure connection detection?

**Comment by gabeio** [comment]
that's excessively not recommended. it's better to let the reverse proxy set it I know nginx can do that with a one liner... haproxy should be able to do it too I haven't had as much http time with haproxy as tcp...

**Comment by wmulligan** [comment]
My particular setup is a load balancer that terminates the SSL connection.  Then a unsecure connection goes to nginx proxy that handles authentication. Finally it reaches my express server.  Unfortunately, I don't have control to modify the load balancer to have it pass extra headers.

**Comment by gabeio** [comment]
oh so like cloudflare -> nginx -> express, yeah I have the same kinda setup I got it to work with the `app.set('trust proxy', 1)` though but I add the proxy_set_header X-Forwarded-Proto at nginx still. I guess your hack will have to work!

**Comment by kbariotis** [comment]
Unfortunately either `app.set('trust proxy', 1)` either the header hack got it working. Thing is that even localy is not working. I 'll continue the investigation.

**Comment by wmulligan** [comment]
The hack only works if you call ```session({proxy: true, ..})```.

**Comment by gabeio** [comment]
@kbariotis just to double check for the locally run copy you will need to
disable the secure: true or your browser will not send the cookie back and
node will not trust it.

**Comment by dougwilson** [comment]
Hi everyone, I see there hasn't been any activity in 6 days. Is everything resolved? If not, what, specifically, is outstanding?

**Comment by kbariotis** [comment]
@dougwilson It seems like it's an issue with my code. Not with express-session. I am closing it and thank you for your help.
