### ISSUE TITLE
cannot set "httpOnly" property

### ISSUE THREAD

**Issue by alanpurple** [expressjs/session#168]
mb this is question rather than a bug
```
server.use(session({
    secret: 'do not need to know',
    resave: false,
    saveUninitialized: false,
    store: new MongoStore({ mongooseConnection: mongoose.connection }),
    cookie: { httpOnly: false }
}));
```

```
router.get('/google/callback',
    passport.authenticate('google', { failureRedirect: '/login' }),
    function (req, res) {
    console.log(req.session.cookie.httpOnly);              <-------------------   true
    res.redirect('/');
});
```

what did I do wrong?

**Comment by dougwilson** [comment]
Does it happen if you don't use MongoStore? The store as the ability to influence this, so it could be a bug with the store.

**Comment by gabeio** [comment]
@alanpurple did you previously have the setting to true at all? if so it's possible your browser has not gotten the httpOnly false update if your session hasn't changed/updated/other.

**Comment by alanpurple** [comment]
@dougwilson  I have to try
@gabeio  never

**Comment by alanpurple** [comment]
@dougwilson 
yep, works fine without MongoStore

**Comment by gabeio** [comment]
Yeah it probably is. Which MongoStore package are you using?

**Comment by alanpurple** [comment]
@gabeio 
0.8.1, which is the latest

**Comment by gabeio** [comment]
okay thanks I have a project I can test this on to see if I can reproduce the issue

**Comment by gabeio** [comment]
I just swapped in connect-mongo into a project of mine but httpOnly worked fine... I noticed you are using `passport` I haven't really played with that module much but I know it does use the session library is it possible it is overwriting the httpOnly parameter.

**Comment by alanpurple** [comment]
@gabeio
passport is supposed to be used upon express session and passport session is just embedded into express session
Actually in fact it appends new object in session not in session.cookie

**Comment by gabeio** [comment]
my only thoughts are try clearing your browser's cookies and try it again because I could not reproduce your issue :frowning:

**Comment by alanpurple** [comment]
@gabeio 
yeah..you were right
after cleaning up....works fine

thanks a lot

**Comment by gabeio** [comment]
No problem!

For whatever reason the `httpOnly` is very sticky while trying to reproduce the issue I was noticing it sometimes stayed one way or the other.
