### ISSUE TITLE
So what exactly saveUninitialized is for?

### ISSUE THREAD

**Issue by yolapop** [expressjs/session#169]
The thing that I got is that when `saveUninitialized` is false then it's not storing session in store. So then how to create session manually if it's not in `req.session`?

**Comment by gabeio** [comment]
@yolapop `saveUninitialized` means if you have not added anything to the "session" there is no session created. ie: A user goes to your blog to read something they are just there to read something and leave they don't need a session `saveUninitialized` will not make a session for them. If they login and you run `req.session.username = <their username>` their session is created and a cookie is sent to them. 
- This is great for the EU sites that need to abide by the cookie law that requires them to ask permission before sending the user a cookie.
- It also is great if you have limited space & a lot of your traffic will not need sessions.

**Comment by yolapop** [comment]
@gabeio thanks for the explanation, but when I used `saveUninitialized = false`, I couldn't set `req.session.username = <their username>` because `req.session` was undefined. I'm confused about how to create session manually

**Comment by yolapop** [comment]
Wait, sorry I just remembered, it's resolved. `req.session` was not `undefined`.
