### ISSUE TITLE
Creating User model

### ISSUE THREAD

**Issue by aHumanBeing** [expressjs/session#180]
Question here: Using this module together with connect-redis for session store and passport/passport-ldap.  Would you have an example/doc of creating a User model as I get this error:  

User is not defined
ReferenceError: User is not defined

I can get the session id to store so it seems to be a bit functional. If this question belongs elsewhere just let me know.

**Comment by JoeWagner** [comment]
@aHumanBeing Just throwing out a guess here, but if you're getting `ReferenceError: User is not defined`.  Try grepping around in your code for "User", and look for places this var is being used before its defined.
Do you have a stack trace?

**Comment by JoeWagner** [comment]
Also, I assume you looked at [this example](https://github.com/mintbridge/passport-ldap/blob/master/example.js)

**Comment by aHumanBeing** [comment]
Yes I've seen that example and thanks for getting back.  It's not defined anywhere in my code so I'm trying to figure out how to define it properly. The example you mention references 'user' but I don't see it defined.  Below is the stack trace.

User is not defined

ReferenceError: User is not defined
    at /home/Erick.Neverson/IdeaProjects/OASIS/app.js:62:3
    at pass (/home/Erick.Neverson/IdeaProjects/OASIS/node_modules/passport/lib/authenticator.js:353:9)
    at Authenticator.deserializeUser (/home/Erick.Neverson/IdeaProjects/OASIS/node_modules/passport/lib/authenticator.js:358:5)
    at SessionStrategy.authenticate (/home/Erick.Neverson/IdeaProjects/OASIS/node_modules/passport/lib/strategies/session.js:49:28)
    at attempt (/home/Erick.Neverson/IdeaProjects/OASIS/node_modules/passport/lib/middleware/authenticate.js:341:16)
    at authenticate (/home/Erick.Neverson/IdeaProjects/OASIS/node_modules/passport/lib/middleware/authenticate.js:342:7)
    at Layer.handle [as handle_request] (/home/Erick.Neverson/IdeaProjects/OASIS/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/home/Erick.Neverson/IdeaProjects/OASIS/node_modules/express/lib/router/index.js:302:13)
    at /home/Erick.Neverson/IdeaProjects/OASIS/node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (/home/Erick.Neverson/IdeaProjects/OASIS/node_modules/express/lib/router/index.js:321:12)

**Comment by JoeWagner** [comment]
Any change you have a capitalization error?  I noticed that the error is `User`, but the example is `user`
Whats on line 62 of app.js?

**Comment by aHumanBeing** [comment]
app.js here:  http://ur1.ca/mxah0

**Comment by JoeWagner** [comment]
Looks like you are not following the example.  
https://github.com/mintbridge/passport-ldap/blob/master/example.js#L40-42

line 62 is a call to `User.findById`.  `User` is not defined anywhere in this file.  What are you expecting `User.findById` to do?

**Comment by aHumanBeing** [comment]
Ahh :)  I changed that and it worked. I basically need to convert the user object the strategy returns into something that can be stored on the session (which it seems to be doing now). I'll still need to store other data within the session and I'm not sure exactly how to do that just yet.  I thought this is what the User object was for.  Is that correct?

**Comment by JoeWagner** [comment]
>I'll still need to store other data within the session and I'm not sure exactly how to do that just yet. I thought this is what the User object was for. Is that correct?

Can't really say without knowing more about what you are doing, but the two options I would suggest are

 - put it in the `req.user` by appending fields to the `user` object you return inside the deserialize function
 - add a middleware after passport but before your routes that puts it on `req.session`

**Comment by aHumanBeing** [comment]
Basically I'm loggin user in via ldap.  I need to know what permissions they have because they will be restricted from certain pages and certain buttons on those pages based on their permissions (memberof). Thanks for your suggestions!
