### ISSUE TITLE
cookie  response

### ISSUE THREAD

**Issue by cclient** [expressjs/session#181]
only the first request will response cookie

then  request the server the cookie  store in mongodb expires modified

but the cookie in Browser(responsed) never change untill it's expired

by default like jee and asp.net 

while set cookie expirses 10 minutes。
if i don't access the  serever in 10 minutes the cookies will removed at the time。
but in express-session it's different。

i edit the express-session code too solve the question

"version": "1.11.3"

express-session/index.js

find string "shouldSetCookie"

old code 

     if (!shouldSetCookie(req)) {
        return;
      }
     setcookie(res, name, req.sessionID, secrets[0], cookie.data);

just  delete "restun",the every request will get cookie with new expires

new code

     if (!shouldSetCookie(req)) {
     }
     setcookie(res, name, req.sessionID, secrets[0], cookie.data);

**Comment by dougwilson** [comment]
Hi! To me, what you are describing you want is already possible without modifying any source code, you just need to alter the appropriate settings. You'll want to set `rolling: true` in the options as well as set `cookie: { maxAge: 10 * 60 * 1000 }`
