### ISSUE TITLE
getAll() for SessionStore API requested

### ISSUE THREAD

**Issue by chk-** [expressjs/session#184]
Hi!
I was searching for a way to access all sessions, for updating some of them.
Until now I iterated over the active sockets (socket.io), where I stored the sessionId for each connection.
But in the case where a user is currently offline, but the session is still valid, I need to change the way I access the user's session.
So I recommend to extend the SessionStoreAPI with a getAll function for this use case. For now I add it to myself, but I'm wondering if other developers need this? What do you think?

Best regards!

**Comment by dougwilson** [comment]
The "session store API" is only the methods this module actually calls on the store. After that, it's up to the actual session store you are using to implement something for you.

The MemoryStore, the only thing we provide, already has this API: store.all

**Comment by chk-** [comment]
All right, thank you for pointing this out!

**Comment by dougwilson** [comment]
I just listed `store.all` in the readme to potentially put more "officialness" on it.

**Comment by chk-** [comment]
That's great! I also suggest the callback's sessions array should be in the format [{sid, session},..]
