### ISSUE TITLE
creating multiple session object with express-session

### ISSUE THREAD

**Issue by pravin-mindstix** [expressjs/session#186]
Hi, i am using connect-mongo and express-session for session handling in my app.

here is my code : 
app.use(session({
cookie: { maxAge: 1000 * 60 * 60 * 24, path : '/userprofile/user_Profile'} ,

  secret: "XXXX" ,
  store:new MongoStore({
          db: config.db.name,
          mongooseConnection:mongoose.connection, 
          collection: 'session', 
          stringify:false,
          autoReconnect:true,
          touchAfter: 24 * 3600 // time period in seconds
  }),
  saveUninitialized: true,
  resave: true
},function(err){
console.log(err || 'connect-mongodb setup ok');
}));

problem is that when app hit endpoint --> ( path : '/userprofile/user_Profile' ) then its creates session object every time. i don't want to create session every time.

in this endpoint what i did is, first I validated session object in this session collection and if object is not present then i want to create new session for user.

request.session.name="userId"

{ "_id" : "wunv7rlnMcU3fz8ocfZWZKL0IBU09TLs", "session" : { "cookie" : { "originalMaxAge" : 86399999, "expires" : ISODate("2015-07-24T09:55:12.052Z"), "secure" : null, "httpOnly" : true, "domain" : null, "path" : "/userprofile/user_Profile" }, "name" : "XX385XXX", }, "expires" : ISODate("2015-07-24T09:55:12.052Z"), "lastModified" : ISODate("2015-07-23T09:55:12.054Z") }

this is my valid object.

here is empty session object is created on every call

{ "_id" : "E5uyuBN0mwVfkbMcgSKmKwT3FLNICl1W", "session" : { "cookie" : { "originalMaxAge" : 86400000, "expires" : ISODate("2015-07-24T09:55:21.392Z"), "secure" : null, "httpOnly" : true, "domain" : null, "path" : "/userprofile/user_Profile" } }, "expires" : ISODate("2015-07-24T09:55:21.392Z"), "lastModified" : ISODate("2015-07-23T09:55:21.393Z") }

{ "id" : "vcwnba_yGUf-CuE-wj8AWTrUIfx6Rmz", "session" : { "cookie" : { "originalMaxAge" : 86400000, "expires" : ISODate("2015-07-24T10:10:30.636Z"), "secure" : null, "httpOnly" : true, "domain" : null, "path" : "/userprofile/user_Profiler" } }, "expires" : ISODate("2015-07-24T10:10:30.636Z"), "lastModified" : ISODate("2015-07-23T10:10:30.637Z") }

I don't understand what's wrong with this ? 
Thanks for any help.

**Comment by dougwilson** [comment]
Hi! In you example you have "saveUninitialized: true", which will cause empty sessions to be saved for every request. It sounds like you may want to change that to "saveUninitialized: false".

**Comment by pravin-mindstix** [comment]
I tried that too, but it still creating multiple object on each request made to this endpoint, i want to save session only if session object is not in session collection.

request.session.name="XXX";

**Comment by gabeio** [comment]
You have `resave` set to true if you look at the readme:

>Forces the session to be saved back to the session store, even if the session was never modified during the request.

essentially saving the session automatically no matter what you do. in addition the `saveUninitialized: true` means that if the user has no session they will be given a blank session which you are free to change while the request is still being handled on the server.

**Comment by pravin-mindstix** [comment]
Thank you very much gabeio , 
resave: false , works for me,

Now i need to do more testing on my production where i use Two server and mongodb replication, Hope it will works there also. :)  :+1:

**Comment by pravin-mindstix** [comment]
Hey Thanks gabeio,

saveUninitialized:false,
resave: false,  
works for me, its not creating multiple session object, now need to test it on production as well where my two server is running with mongodb replication. Hope it will works there also.

Awesome :100:
