### ISSUE TITLE
Scope session to specific endpoints

### ISSUE THREAD

**Issue by pronebird** [expressjs/session#190]
Hi,

Is it possible to scope session to be used only on specific endpoints? I need it to organize obscure Oauth2 authorization which does some nasty redirects, so I need to temporary keep redirect URL somewhere.

**Comment by gabeio** [comment]
You could run a different app for that endpoint but no sessions are not scoped.

**Comment by dougwilson** [comment]
It really depends on what the word "endpoint" means in your question. If you're talking about a URL prefix, yes, you just mount them at the appropriate path prefix in Express and set the session cookie's path to match:
```js
app.use('/oauth', session({
  secret: 'keyboard cat',
  resave: false,
  saveUninitialized: false,
  cookie: { secure: true, path: '/oauth' }
}))

app.use(session({
  secret: 'keyboard cat',
  resave: false,
  saveUninitialized: false,
  cookie: { secure: true, path: '/ }
}))
```

**Comment by pronebird** [comment]
Thanks @dougwilson! This is exactly what I am talking about. I don't need it to be globally included,o only for /admin.
