### ISSUE TITLE
Why express session is very slow?

### ISSUE THREAD

**Issue by yahao87** [expressjs/session#191]
Environment
vm - centos7(4cpu, 8Gb memory, gigabit NAT)

I tested in the Express version 3 and 4.
set as follows..

package.json
```javascript
{
  "name": "apiauth",
  "version": "1.0.0",
  "description": "", 
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },  
  "author": "", 
  "license": "ISC",
  "dependencies": {
    "express": "4.13.3",
    "body-parser": "~1.13.3",
    "connect-redis": "~2.4.1",
    "cookie-parser": "~1.3.5",
    "cookie-session": "~1.2.0",
    "express-session": "~1.11.3",
    "redis-connection-pool": "1.1.0"
  }
}
```

A. no session api.js
```javascript
var express = require('express');
var http = require('http');
var app = express();
var server = http.createServer(app);
var session = require('express-session');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');
app.use(cookieParser());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

app.get('/test.json', function (req, res) {
	data = {a:[1,2,3,4,5,67,7,8,9,0,10]};
	res.send(data);
});

server.listen(8182, function() {
	console.log('Express server listening on port ' + server.address().port);
});
```

![Image](http://upload2.inven.co.kr/upload/2015/08/07/bbs/i11455483476.png)

B. session api.js
```javascript
var express = require('express');
var http = require('http');
var app = express();
var server = http.createServer(app);
var session = require('express-session');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');
app.use(cookieParser());
app.use(session({
	key: 'sid',
	secret: "test.kr",
	resave: false,
	saveUninitialized: true,
	cookie: {secure: false, maxAge: 60000, domain: '.test.kr'}
}));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

app.get('/test.json', function (req, res) {
	data = {a:[1,2,3,4,5,67,7,8,9,0,10]};
	res.send(data);
});

server.listen(8182, function() {
	console.log('Express server listening on port ' + server.address().port);
});
```
![Image of Yaktocat](http://upload2.inven.co.kr/upload/2015/08/07/bbs/i11445803432.png)
Content download speed is extremely slow. Despite of the local environment.

How can I speed up?

Then, most of the login process is applied to a very slow download time(min 200ms).
Is called the normal operation?
download time over 200ms per login session?
additionally, not surprisingly worse when the local is not.
Is Express session originally very slow?
Should I use another language for the session?

I am already being used to redis-session and passport-google on a live server.
But it's too slow.
passport is fast.
So the test is done in the above code.
Redis session even slow, local storage as well.

![Image of redissession](http://upload2.inven.co.kr/upload/2015/08/07/bbs/i10514994900.png)

Network is Gigabit Network.
And content size is smaller than 1kbyte.

This problem occurs at any time, anywhere.
It was tested in a ssd, it is what happened in one computer.
And it appears the same on another computer.
it's nothing to do with local.
Make a test into the code listed above in your vm.
And to test the local chrome browser.(not 127.0.0.1 but VM's NAT IP)
Do you think this is another problem in this environment?
It will be able to get the same results. always.
I tested in three PC.
There is a complete code above.
You can test. In less than a minute.

Compare it to A and B.
Content download time is tcp problems.
This happened to the handshake abnormally terminated at express-session?

Original Link : https://github.com/strongloop/express/issues/2727#issuecomment-128841518

**Comment by dougwilson** [comment]
Please see the comment https://github.com/strongloop/express/issues/2727#issuecomment-128913254
