### ISSUE TITLE
Add Infinispan connect support

### ISSUE THREAD

**Issue by rustyx** [expressjs/session#193]
Please add support for a simple REST store like the one exposed by [Infinispan](https://docs.jboss.org/author/display/ISPN/Infinispan+REST+Server).
The API is extremely simple:
`GET /<cache-id>/<key>` to retrieve an object
`PUT /<cache-id>/<key>` to store an object
`DELETE /<cache-id>/<key>` to delete an object

**Comment by gabeio** [comment]
Anyone can add any store they wish, just fork one of the stores and change it to connect to your database :smiley:. But this module itself does not directly connect to any database.

**Comment by dougwilson** [comment]
Simple implementation you can add to your own app:
```js
var bodyParser = require('body-parser')
var express = require('express')
var expressSession = require('express-session')

var store = /* create your favorite store here */

var app = express()
app.use(expressSession({
  store: store,
  secret: 'keyboard cat',
  resave: false,
  saveUninitialized: true
}))

app.get('/session/:id', function (req, res, next) {
  store.get(req.params.id, function (err, sess) {
    if (err) return next(err)
    res.json(sess)
  })
})

app.put('/session/:id', bodyParser.json(), function (req, res, next) {
  store.set(req.params.id, req.body, function (err) {
    if (err) return next(err)
    res.sendStatus(200)
  })
})

app.delete('/session/:id', function (req, res, next) {
  store.destroy(req.params.id, function (err) {
    if (err) return next(err)
    res.sendStatus(200)
  })
})
```
