### ISSUE TITLE
Fingerprint

### ISSUE THREAD

**Issue by joetm** [expressjs/session#194]
Is the fingerprint option still available?
If yes: What does it do?

**Comment by dougwilson** [comment]
Hi! As far as I know, there has never been an option called "fingerprint" in this module. Perhaps you reported the issue to the wrong module?

**Comment by joetm** [comment]
A fingerprint fingerprint function was defined here:
http://stackoverflow.com/questions/13888420/expressjs-sessions-not-working-on-ie-server

**Comment by dougwilson** [comment]
Ah, I see. The call express.session is not this module, but code from a long, long time ago part of old versions on express. This is a different module.
