### ISSUE TITLE
Question: use the same database for session store

### ISSUE THREAD

**Issue by xuefengwang** [expressjs/session#198]
Hi, I'm building a multi-tenancy web app. Each tenant has his own database schema and I create the session table in each tenant's schema. For the main app's database access, I attach the database connection to the request such as "req.db = db". I would like to pass the req.db to session store, so that the session store can use the same database connection for that tenant. But I found no way to pass the req.db to session store. The interface of session store only take sessionId and session object. Anyone can shed some light on? Thanks.

**Comment by xuefengwang** [comment]
I found a way to do it. Assume the main database is setup and attached to req.db.

```
app.use((function () {
    var options = {
        store: new MySQLStore(),
        secret: 'supersecret',
        cookie: {
            maxAge: 604800000
        },
        resave: false,
        saveUninitialized: false
    };
    var func = session(options);
    return function (req, res, next) {
        // to pass main db to session store
        if (req.db) options.store.db = req.db;

        func(req, res, next);
    };
})());
```

**Comment by JoeWagner** [comment]
@xuefengwang if you are happy with your solution, can we close this issue?

**Comment by xuefengwang** [comment]
Yes. Thanks.
