### ISSUE TITLE
cookieOptions.secure = true when terminating SSL at load balancers

### ISSUE THREAD

**Issue by nodesocket** [expressjs/session#202]
We terminate SSL at our load balancers, and then send traffic to web servers where node actually runs over regular http.

So, even though the site is running https, locally to node it is http. I tried turning on:

    cookieOptions.secure = true;

But this prevents cookies from being created. Is there a solution for this?

**Comment by gabeio** [comment]
If I remember correctly express is not TRUSTING the load balancer so the https cookie is not trusted. but the cookie should be created & sent to the client. which also means if your site does not run https only then if you load the site with http the https cookies are not sent. try enabling `app.set('trust proxy', 1)` should tell express to trust one load balancer/reverse proxy

**Comment by nodesocket** [comment]
No dice :game_die:.

Still does not create the cookie using:

    app.set('trust proxy', true);

**Comment by gabeio** [comment]
does not create the cookie? (as in you are not getting them in the client?) that's very strange. I'll check on my server...

**Comment by nodesocket** [comment]
Correct, no session cookie showing up in Chrome developer tools resources.

**Comment by dougwilson** [comment]
You can read documentation on how Express works with proxies in the documentation at http://expressjs.com/guide/behind-proxies.html

Likely, you are not getting a `X-Forwarded-Proto` header from your reverse proxy terminating SSL to your Express server.

**Comment by nodesocket** [comment]
I am setting the following on the load balancer in nginx:

````
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
````

**Comment by dougwilson** [comment]
Can you add the following to your Express app and report back?
```js
app.use(function (req, res, next) {
  console.dir(req.headers)
  next()
})
```

**Comment by dougwilson** [comment]
We are also assuming you are using Express 4.13.x, so let us know if you're using a different version of Express.

**Comment by shaunwarman** [comment]
Just throwing this out there. But your application doesnt live in an iframe
does it?

**Comment by nodesocket** [comment]
Got it working, it was an nginx misconfiguration. However, one more follow up question.

If I want to do some logic based on the request, can I change the setup to something like:

````javascript
        app.use(function (req, res, next) {
            var cookieOptions = { expires: false };
            if(isAdmin || req.get('x-forwarded-proto').toLowerCase() === 'https') {
                cookieOptions.secure = true;
                cookieOptions.proxy = true;
            }

            session({
                store: new RedisStore({
                    client: this.sessionStore.client
                }),
                secret: require('bc-settings').session.secret,
                name: 'brandcast.ssid',
                resave: false,
                saveUninitialized: false,
                cookie: cookieOptions
            });
        });
````

**Comment by dougwilson** [comment]
That example, as-is, won't work. I''m trying to write up one that does for you, but I'm not sure about `this.sessionStore` in there. Does that actually refer to `app.sessionStore`? Basically what is the `this` referring to in the example?

**Comment by nodesocket** [comment]
Sorry, ignore that, just assume there is a variable that stores the redis client called `sessionStore`.

**Comment by dougwilson** [comment]
Cool:)
```js
// create middleware
var store = new RedisStore({ client: sessionStore.client });
var insecureSession = createSessionMiddleware(store, {
  expires: false
});
var secureSession = createSessionMiddleware(store, {
  expires: false,
  secure: true,
  proxy: true
});

// attach middleware
app.use(function (req, res, next) {
  if (isAdmin || req.protocol === 'https') return secureSession(req, res, next);
  return insecureSession(req, res, next);
});

function createSessionMiddleware(store, cookieOptions) {
  return session({
    store: store,
    secret: require('bc-settings').session.secret,
    name: 'brandcast.ssid',
    resave: false,
    saveUninitialized: false,
    cookie: cookieOptions
  });
}
```

**Comment by nodesocket** [comment]
Perfect, thanks so much!

**Comment by nodesocket** [comment]
@dougwilson just tried running the code you gave to dynamically switch the secure flag on and off, and found that instantiating two createSessionMiddleware just uses the last one that was created. I.E. always uses secureSession. Any ideas?

````
ar insecureSession = createSessionMiddleware(store, {
            expires: false,
            secure: false
        });

        var secureSession = createSessionMiddleware(store, {
            expires: false,
            secure: true,
            proxy: true
        });
````

**Comment by dougwilson** [comment]
Hi @nodesocket , it seems to work just fine for me. Are you sure the `req.protocol === 'https'` condition is not just returning `false` for every single request?

**Comment by nodesocket** [comment]
I just confirmed, that `req.protocol === http` yet using secureSession.

See:

````
//// Thanks @dougwilson - https://github.com/expressjs/session/issues/202
        var store = new RedisStore({ client: this.sessionStore.client });

        var insecureSession = createSessionMiddleware(store, {
            expires: false
        });

        var secureSession = createSessionMiddleware(store, {
            expires: false,
            secure: true,
            proxy: true
        });

        app.use(function (req, res, next) {
            if (req.protocol === 'https') {
                return secureSession(req, res, next);
            }

            return insecureSession(req, res, next);
        });

        function createSessionMiddleware(store, cookieOptions) {
            return session({
                store: store,
                secret: require('bc-settings').session.secret,
                name: 'brandcast.ssid',
                resave: false,
                saveUninitialized: false,
                cookie: cookieOptions
            });
        }
````

Are you able to reproduce?

**Comment by dougwilson** [comment]
Well, that's the thing: I'm not able to reproduce, including using the exact code you are pasting...

**Comment by nodesocket** [comment]
@dougwilson are you testing with or without ssl or both? I am seeing it using `secureSession` when `req.protocol === 'http'`.

Thanks for the all help by the way, really appreciate it.

**Comment by dougwilson** [comment]
I'm testing with both and when I use http I get insecureSession and with https I am getting secureSession. If you keep seeing "http" as the protocol, even if you are using https, then you have some missing header or other miscondiguration.

**Comment by nodesocket** [comment]
@dougwilson 

So I have to refactor the code you provided to get it working for both secure and insecure. Notice, that the fix is to reassign the variable `sessionMiddleware` if we are using https, instead of instantiating both outside of the middleware. Does that make sense, why this is required yet?

````
//// Thanks @dougwilson - https://github.com/expressjs/session/issues/202
        var store = new RedisStore({ client: this.sessionStore.client });

        var sessionMiddleware = createSessionMiddleware(store, {
            expires: false
        });

        app.use(function (req, res, next) {
            if (req.protocol === 'https') {
                sessionMiddleware = createSessionMiddleware(store, {
                    expires: false,
                    secure: true,
                    proxy: true
                });

                return sessionMiddleware(req, res, next);
            }

            return sessionMiddleware(req, res, next);
        });

        function createSessionMiddleware(store, cookieOptions) {
            return session({
                store: store,
                secret: require('bc-settings').session.secret,
                name: 'brandcast.ssid',
                resave: false,
                saveUninitialized: false,
                cookie: cookieOptions
            });
        }
```

**Comment by dougwilson** [comment]
Hi @nodesocket , the example I provided works just fine for me, which is why I'm so confused what is going on on your side. The example you just provided actually does not work for me, as it provide the following broken behavior:

1. A request comes in over HTTP and has a non-secure cookie (correct behavior).
2. A request comes in over HTTPS and has a secure cookie (correct behavior).
3. A request comes in over HTTP and has a secure cookie (_incorrect behavior_). Because your code above is overwriting the `sessionMiddleware` in the HTTPS branch and then there is no where where it gets set back to HTTP when an HTTP request comes in, once one HTTPS request arrives, all future requests get a secure cookie, which does not work for HTTP.

**Comment by dougwilson** [comment]
Can I presume the reason you keep pasting indented code here is that the code you pasted above is inside something? The other thing is, if you are not provided the full, absolute complete file and are instead just pasting to me a small part of it, there isn't a way I can understand why my example is not working out for you.

**Comment by nodesocket** [comment]
I think the difference is that we use the same "setup" code from two sites (front-end) and backend (editor). The front-end is over http and the backend is over https. Both code paths call this init code to setup the cookies.

**Comment by nodesocket** [comment]
This was the only way I got both cases working. By default we setup `secure: true`, and if `req.protocol == 'http' we override to `secure: false`.

````
//// Thanks @dougwilson - https://github.com/expressjs/session/issues/202
        var store = new RedisStore({ client: this.sessionStore.client });

        var sessionMiddleware = createSessionMiddleware(store, {
            expires: false,
            secure: true,
            proxy: true
        });

        app.use(function (req, res, next) {
            if (req.protocol == 'http') {
                sessionMiddleware = createSessionMiddleware(store, {
                    expires: false,
                    secure: false,
                    proxy: false
                });
            }

            return sessionMiddleware(req, res, next);
        });

        function createSessionMiddleware(store, cookieOptions) {
            return session({
                store: store,
                secret: require('bc-settings').session.secret,
                name: 'brandcast.ssid',
                resave: false,
                saveUninitialized: false,
                cookie: cookieOptions
            });
        }
```

**Comment by dougwilson** [comment]
Gotcha. I mean what you just posted has the issues outlined in https://github.com/expressjs/session/issues/202#issuecomment-140983970 . It's hard to understand why what I pasted does not work for you if you are not providing the full, absolute complete file and are instead just pasting to me a small part of it.

**Comment by azotova** [comment]
@nodesocket  I know this is an old thread but I am experiencing a very similar issue.  What was the nginx configuration that worked for you?  Thanks!

**Comment by spencer-rig** [comment]
@nodesocket I may also have the same issue, what was the nginx configuration you ended up with?
