### ISSUE TITLE
Callback for cookie expiration

### ISSUE THREAD

**Issue by Zambonilli** [expressjs/session#204]
Add a field to allow the client to set a callback function whenever a session has expired.  This would be really helpful for scenarios like issue #177 where we need to maintain an xref of users to sessions to update/invalidate the value of the cookie stored in the store.

**Comment by dougwilson** [comment]
We may be able to provide this. PRs are welcome, but since this data is in the `store` modules, you may have to add this feature in the store you are using.

**Comment by Zambonilli** [comment]
Thanks for the quick response.  I'll take a look at what it would require.  However, I might just setup a redis subscriber and listen on the pubsub for expires events since I'm using the connect-redis store.

**Comment by Zambonilli** [comment]
I'd like to double check my analysis to add this feature before starting on a PR.  We'll need to add to the store interface an optional setExpires function with one argument a function to call when the store expires a session.  expressjs-session will expose a similar method to the clients via options that is expired.  At this point, we'll simply wire up the two if the store supports it.  The actual signature of the function to call would just have the sid of the session expired.

So, using the connect-redis store the flow would be when connect-redis is constructed it will need to create or receive two redis connections one for listening to published expires and another to execute the other commands.  It will also need to implement the setExpires method and store the function that needs to be called when an expires event is published from redis.  Finally, the method in connect-redis that listens for expires to be published will simply look at if there's a function set and run that whenever it receives an expires.  It will not wait for a callback.

Let me know if this sounds right.  There's a lot of wiring here that will take some coordination between expressjs-session and connect-redis and I want to make sure we don't hardcode us into only having one store that supports this feature.  I need this feature relatively soon so I'll probably just implement with a direct connection to redis and get the PR going at the same time and swap over once it's solid and ready for master.

**Comment by dougwilson** [comment]
Hi @Zambonilli , so before we get too far, ideally any interface added to this module can be implement by all stores (or, at least most of them). Can you evaluate the feasibility to add this feature to at least 5 other stores listed on our page? If they are all feasible, then we can move forward with adding the interface to this abstraction.

**Comment by Zambonilli** [comment]
Sure no problem.  That makes sense.

**Comment by Zambonilli** [comment]
I don't think there's going to be enough stores that can support this.  I'm going to brainstorm other ways to raise an expires event without using the stores or ramping the RAM.

**Comment by hat27533** [comment]
Hi,

Could the cookie object not fire an event?

Neil Hathaway

On Wednesday, 16 September 2015, Mike Lohmeier <notifications@github.com>
wrote:

> I don't think there's going to be enough stores that can support this. I'm
> going to brainstorm other ways to raise an expires event without using the
> stores or ramping the RAM.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/expressjs/session/issues/204#issuecomment-140893342>.
>


-- 
Neil Hathaway
PushBack Software Limited

**Comment by hat27533** [comment]
What about using a scheduler like https://www.npmjs.com/package/node-schedule, you know the cookie expiry time ? Simply schedule something for when the cookie expires ?

I am using express-socket.io-session in this snippet

io.on('connection', function (socket) {
    console.log("==> Socket Connection Established");
    console.log(socket.id, socket.handshake.sessionID);
    
    var d = socket.handshake.session.cookie._expires;
    var job = schedule.scheduleJob(d, function () {
        console.log('The cookie has expired');
        socket.emit('logout', true);
    });
...

**Comment by Zambonilli** [comment]
I was thinking something similar but the problem with this is that you'd have to have sticky sessions.  If you didn't have sticky sessions another node could get a request for the cookie and you wouldn't know that you need to update the expiration time.

**Comment by gabeio** [comment]
all the nodes would have to all be in sync and all know that the expire time was bumped and remember network lag that means when they try to sync the exp time might be different depending on the server that was hit with the exp time.

-----

what I do is set redis's expire time and the cookie's expire time to the same thing which means if they are bumped they are both reset.

This could be achieved by saving a variable like _exp: <timestamp when session expires> when session goes to read the value and sees it's past the _exp the session is destroyed and then tells the browser to delete the session cookie also.
