### ISSUE TITLE
Session regenerates itself new session ID and sets new sid  cookie after expiry.

### ISSUE THREAD

**Issue by ashishkataria** [expressjs/session#205]
```coffeescript
  session= require('express-session')  
  MemStore=session.MemoryStore
  RedisStore = require('connect-redis')(session)  
  @app.use \/edit @express.static __dirname
  @app.use \/view @express.static __dirname   

  @use \json, @express.static(__dirname),session: { secret: 'secret', unset:'destroy',resave: false,  saveUninitialized: false, store: new RedisStore, httpOnly: true,  cookie: {maxAge: 30000 } } ,'bodyParser',@app.router

My post login action is as, here i am printing the @request.session on console:

    @post '/_login': ->
    console.log @request.session

If i refreshes my post login page after 10 seconds of session expiry or click on any other link inside my application, it itself generates and assigns a new sid to the client.
After 10 seconds of expiry, it itself generates and assigns/resets  a new sid cookie to the client.
 If session expires I don't want it to regenerate and pass  new sid automatically  to the browser.

What's wrong here, Please help.
Thanks.

**Comment by JoeWagner** [comment]
@ashishkataria I would try removing the expires and maxAge options one at a time and see if/when things start working

**Comment by dougwilson** [comment]
Hi @ashishkataria , you need to set the `saveUninitialized` option to `false` (https://github.com/expressjs/session#saveuninitialized).

**Comment by ashishkataria** [comment]
@JoeWagner  Thanks for replying.
I tried removing expires, still it regenerates the new session Id itself.
Actually Session gets expire after defined maxAge, but it again regenerates  the new session Id by itself.

**Comment by ashishkataria** [comment]
@dougwilson  Thanks for replying.

I added the saveUninitialized: false, still after session expiry,  it regenerates the new session Id by itself.
Please check my updated code above if you find anything wrong in that.
Thanks.

**Comment by Mo33n** [comment]
+1 for this same issue.

**Comment by dougwilson** [comment]
Hi @ashishkataria , what you are explaining is actually just how this module works and is not a bug.

You see, when a cookie expires in the web browser, the web browser sends no session ID; there is no way to understand that the cookie expired. This means that we cannot tell the difference between a browser with no cookie and a browser that had one and it didn't expire.

This module generates a new session with a new ID whenever there is no session in the request. You would have to implement you own logic on top of this to determine what you need to do.
