### ISSUE TITLE
Cookie names are capitalized and it breaks things

### ISSUE THREAD

**Issue by scaryguy** [expressjs/session#206]
As stated here: http://stackoverflow.com/questions/11311893/is-the-name-of-a-cookie-case-sensitive
Cookie names are case-sensitive. Express-session is capitalizing the name attribute and it shouldn't happen, I think.

Here is my config:

```js
app.use(session({
    store: new RedisStore({
        host: config.redis_instance_local_ip,
        port: config.redis_instance_local_port
    }),
    cookie: {
        'domain': '.mydomain.com'
    },
    secret: config.application_session_secret,
    resave: false,
    saveUninitialized: true
}));
```

This results following:
```
connect.sid=s%3ApGErf0IUZpXGqWNwaAy4Y1Gv5u1tKGDq.7ZFKgyQboP9XPM7I%2FAhdNNnq6YtMiRoFu4CeVlxdz9c; Domain=.my_domain.com; Path=/; HttpOnly
```

I tried to do it like `'domain': '.mydomain.com'` but it still capitalizes the name.

I have another header file created by nginx loadbalancer and it has 'domain' option lowercased. On Safari, -I guess- because of that, cookies doesn't merge. There might be some other consequence in different circumstances for other people, too.

Is there a way to force it to be as it's given? If there is not, don't you think that this is an issue?

**Comment by dougwilson** [comment]
Hi! I think you are a little confused with that SO post; yes, the _name of the cookie_ is case-sensitive, but the word "Domain" in the `Set-Cookie` header is not the name of the cookie, rather a name of an attribute. These are not case-sensitive.

You can find lots of information on the exact specification of the `Set-Cookie` header in RFC 6265 (https://tools.ietf.org/html/rfc6265).

Specifically, as noted in section 5.2.3 (https://tools.ietf.org/html/rfc6265#section-5.2.3), the word "Domain" is not case-sensitive:

> If the attribute-name case-insensitively matches the string "Domain", the user agent MUST process the cookie-av as follows.

This means that whatever the issue you are having is, it is unlikely related to the casing of the "domain" attribute, or there is a much bigger problem.

**Comment by scaryguy** [comment]
I didn't know that 'domain' attribute is a special attribute and an exception of case-sensitivity of attribute-names :)

Thanks.

**Comment by dougwilson** [comment]
Yep, because it's an attribute (all attribute names are not case-sensitive) :)

```
connect.sid=s%3ApGErf0IUZpXGqWNwaAy4Y1Gv5u1tKGDq.7ZFKgyQboP9XPM7I%2FAhdNNnq6YtMiRoFu4CeVlxdz9c; Domain=.my_domain.com; Path=/; HttpOnly
\_________/ \________________________________________________________________________________/  \___________________/  \____/  \______/
     |                                               |                                           \___/ \___________/    \/\/    \____/
   cookie                                          cookie                                          |         |           | |       |
    name                                            value                                        attr       attr      attr attr   attr
                                                                                                 name       value     name value  name
```

**Comment by scaryguy** [comment]
Thanks for detailed explanation :)
