### ISSUE TITLE
Prevent Session Extension for Certain Requests

### ISSUE THREAD

**Issue by diginfo** [expressjs/session#210]
There are certain requests that I do not want express to extend the session expiry date for, like background ajax pings that are sent from the client browser to see whether the server is alive and if the session is still open.

    app.use(express.session({
      rolling: false,
      store: app.conf.sessionStore,
      secret: 'mysecret', 
      cookie:{
        maxAge: 60000 * 30
      }
    }));

    if(req.query.ping == 'y'){
     // Don't extend session max-age
    }

Is this possible ? - I have looked through the documentation  and I cannot seem to find anything useful, I have also googled this and don't get any useful hits ?

**Comment by dougwilson** [comment]
When you are running your ping route, do you even need access to `req.session` at all?

**Comment by diginfo** [comment]
Yes, I need to test whether the session is alive, if the session is not alive then the client browser will call the login page.

**Comment by diginfo** [comment]
How can I achieve this ?

**Comment by dougwilson** [comment]
You'll want to add the option `resave: false` to your configuration, so the session doesn't keep getting resaved to your store on every access.
