### ISSUE TITLE
req.session is undefined

### ISSUE THREAD

**Issue by oodzchen** [expressjs/session#216]
Here is the config:
```javascript
var flash = require('connect-flash');

...

var session = require('express-session');
var MongoStore = require('connect-mongo')(session);

...

// save session to database
app.use(session({
  secret: settings.cookieSecret,
  key: settings.db, // cookie name
  resave: true,
  saveUninitialized: true,
  cookie: {maxAge: 1000*60*60*24*30}, //30 days
  store: new MongoStore({
    db: settings.db,
    host: settings.host,
    port: settings.port
  })
}));

app.use(flash());
```

I use `console.log(req.session)` in the callback function of `app.post()`, it returns `undefined` every time, which will cause an error in the `connect-flash`.

**Comment by gabeio** [comment]
so your app looks like:
```
app.post(function(req, res, next){
  console.log(req.session);
})
```
?
because I don't see anything right off the bat as issues with your code there...(besides that if you have a lot of throughput your mongodb might have a writing issue but that's a different issue you only might face) in anywise you may want to try with `resave:false`

**Comment by dougwilson** [comment]
When `req.session` is undefined, it means that your MongoDB session store is offline.

Looking at the `connect-mongo` source code (https://github.com/kcbanner/connect-mongo/blob/master/src/connect-mongo.js) this will happen if it could not connect to the MongoDB. If you start you app with the environment variable `DEBUG` set to `connect-mongo` you should see some helpful information (e.x. `DEBUG=connect-mongo npm start`).
