### ISSUE TITLE
Can't store value in 'id' in express session. 

### ISSUE THREAD

**Issue by gauravjns** [expressjs/session#217]
I mean when i store something in req.session.id=100 and display somewhere it shows some random string. I am thinking it must be a id of session that middleware is uses to identify session. 

I wasted 1 hour by setting the session varaible req.session.id 

As setting id in session is very common, we should change to _id or something internally as mongo does. If that not possible mention in docs clearly

 Thank you

**Comment by dougwilson** [comment]
Thanks, we'll document that you cannot change it. We provide this so you can get the ID of the session; changing to `_id` will signify that you're no longer allowed to know the ID of your session.
