### ISSUE TITLE
Delete an attribute from session after a timeout

### ISSUE THREAD

**Issue by khalilTN** [expressjs/session#226]
Hello,
Actually, i have a big object that is saved to session and waits for user to treat it, then the object is deleted from session. (I'm using `MemoryStore`)
My issue is, when the user doesn't choose to treat this object, it will remain in the session.
As you know, `session.destroy` will destroy the whole session, so it's not a solution in my case.
I tried to use `setTimeout` and set `req.session.myObject = null` after a timeout, but it seems that every modification applied on the session after sending http response will not be conserved.
How can i handle this ?
Thanks a lot.

**Comment by dougwilson** [comment]
> but it seems that every modification applicated on the session after sending http response will not be conserved.

You just need to call `req.session.save()` after the modification to actually save that change.

**Comment by khalilTN** [comment]
Thanks a lot, it worked !

**Comment by dougwilson** [comment]
No problem! And after thinking even more, you may want to use a `reload` in your `setTimeout` before the save, as to not overwrite something added afterwards:
```js
setTimeout(function () {
  req.session.reload(function (err) {
    if (err) return
    req.session.myObject = null
    req.session.save()
  })
}, 60000)
```
