### ISSUE TITLE
Should cookie.maxAge and store.ttl (e.g. redis) always be the same?

### ISSUE THREAD

**Issue by rightaway** [expressjs/session#227]
Should `cookie.maxAge` and `store.ttl` (when using `connect-redis` as a store) always be identical? Of course they're in different formats, milliseconds vs seconds, but I mean should the times ever represent different moments, like where one expires before the other?

If not, then I'd like to suggest adding an `expiry` option to session that when set would provide a default value for `cookie.maxAge` and `store.ttl` to be applied in case those options aren't set.

**Comment by dougwilson** [comment]
The `maxAge` option is provided to the store on every operation, so if the store wants to use it instead of a separate setting, it could certainly be modified to do so. Have you brought the issue up to the store module?
