### ISSUE TITLE
Cookie domain option ignored

### ISSUE THREAD

**Issue by mmerkes** [expressjs/session#228]
If you set the domain option on the cookie, it gets promptly ignored. I put in some logs at various points around cookie creation and such, and it never seems to make it into the constructor. I haven't been able to fully understand where the issue is occurring, but I see two functions that generate sessions (and cookies):

```javascript
// index.js line 138
  // generates the new session
  store.generate = function(req){
    req.sessionID = generateId(req);
    req.session = new Session(req);
    req.session.cookie = new Cookie(cookieOptions);

    if (cookieOptions.secure === 'auto') {
      req.session.cookie.secure = issecure(req, trustProxy);
    }
  };
```

```javascript
// session/store.js line 76
Store.prototype.createSession = function(req, sess){
  var expires = sess.cookie.expires
    , orig = sess.cookie.originalMaxAge;
  sess.cookie = new Cookie(sess.cookie);
  if ('string' == typeof expires) sess.cookie.expires = new Date(expires);
  sess.cookie.originalMaxAge = orig;
  req.session = new Session(req, sess);
  return req.session;
};
```

`store.generate` has the correct cookie options, but `createSession` only passes in options from `sess` and seems to be the only one actually called. `store.generate` doesn't ever seem to get called when I've played around with it. It appears `store.generate` should be user for new sessions, and `createSession` should used to create objects for existing sessions, but it doesn't work that way.

I'm plan to investigate further tonight (or when I have the chance), and I will update my post as I discover more.

UPDATE 1

After further research, if I delete the cookie in the browser manually, it's fine. However, if you are running the server and hit the app with your browser before you set the domain, `createSession` will be run and it won't add the domain until the cookie gets deleted by your browser.

**Comment by dougwilson** [comment]
> However, if you are running the server and hit the app with your browser before you set the domain,  createSession  will be run and it won't add the domain until the cookie gets deleted by your browser.

Yes, this is how cookies and web browsers function.

**Comment by dougwilson** [comment]
In addition, most of the stores listed here will remember cookie settings in the session, so if you change the settings and load a session that was made with previous settings, you'll still see the previous settings.

**Comment by mmerkes** [comment]
Ok. Thanks for the response. However, I would expect that if I logout, I would have to create a new session, and I would get the default cookie options, not the settings that I had with my previous session.

**Comment by dougwilson** [comment]
Hm. Unless you can provide specific instructions on exactly how I reproduce, including all necessary code, I cannot really answer for your specific case.

**Comment by mmerkes** [comment]
Ok. I'll try to trim an example down where I can share it.

Essentially, here is the repro:

1. I have an app with express-session and passport, with `cookie.maxAge` set.
2. I create an account and the cookie has `maxAge` set
3. I add the `domain` option, restart the server
4. I log out, create a new account, and my cookie has the options of my previous session cookie
5. I delete the cookie via Chrome dev tools, and when I log back in, the domain is set on the cookie

**Comment by dougwilson** [comment]
For example, this module provides no such concept of "logout", so I would have to see your code to know how you implemented logout.

I won't really be able to assist unless you can remove passport from your app, so there are as minimal dependencies as possible, otherwise it will take a long time, ad I will have to learn passport, debug it, etc.

**Comment by dougwilson** [comment]
If the "log out" operation you implemented does not actually delete the cookie, then your domain change won't be picked up, as per web browser specs.

**Comment by mmerkes** [comment]
Ok, it appears that we're getting down the heart of the issue, and I'll try to take the next steps:

1. Confirm that passport is actually deleting the cookie, and report the bug there if it's not
2. If passport looks okay, I'll put together a repro with express-session with minimum dependencies and post in this thread.

**Comment by dougwilson** [comment]
Another thing to look into is what you provided the `saveUninitialized` option to this module to be; if you set it to `saveUninitialized: true` (or didn't specify an option, so the default is to true), the logout operation may be deleting the cookie and immediately re-creating it. Setting `saveUninitialized: false` may very well fix your issue, though you need to read about the option to make sure it works correctly for your other use-cases.
