### ISSUE TITLE
Stopping new session creation for preflight (OPTIONS) requests?

### ISSUE THREAD

**Issue by bgSosh** [expressjs/session#229]
Browsers don't send cookies with CORS preflight (OPTIONS) requests, but it seems that the session module treats these as normal requests, so a new (redundant) session is generated each time. 

Is there some best practice way of stopping this with express-session?

(A similar issue was posted a long time ago on the connect repo: https://github.com/senchalabs/connect/issues/323)

**Comment by dougwilson** [comment]
> Is there some best practice way of stopping this with express-session?

Why not set `saveUninitialized: false` in your confirmation?

**Comment by bgSosh** [comment]
Thanks.  Just read the docs for that, but am unclear on the implications.  Does `saveUninitialized: false` mean that sessions from new clients must be created manually in some way?

**Comment by dougwilson** [comment]
>  Does saveUninitialized: false mean that sessions from new clients must be created manually in some way?

It means that the session won't get saved unless you actually add something to the session _or_ you call `req.session.save()`.

**Comment by bgSosh** [comment]
Wouldn't it be better for the module deal with OPTIONS requests automatically?  CORS and preflight requests are standard parts of the web after all.

**Comment by bgSosh** [comment]
I'm also using passport, so I don't think `saveUninitialized: false` is going to solve this for me.

**Comment by dougwilson** [comment]
You can certainly send a PR here and fix Passport (we make the note because it's kind of buggy Passport behavior and has not been fixed and people run into it all the time). Please note that CORS request does not equal OPTIONS requests, as OPTIONS requests are perfectly valid and can include cookies for non-CORS-preflight-related activity, so simply a PR to make this module ignore OPTIONS wouldn't be an acceptable solution.

**Comment by dougwilson** [comment]
Also, a (probably more sane) solution is to not even let CORS requests invoke this middleware by using a module to handle your CORS and preflight requests correctly, like the https://github.com/agrueneberg/Corser module. For example:
```js
app.use(corser.create({ ... }))
// ... later
app.use(expressSession({ ... }))
```
The corser module will not invoke later middleware for preflight requests, as would make sense, and since your session would be after that, you would never invoke the session mechanism for no reason.

**Comment by bgSosh** [comment]
> You can certainly send a PR here and fix Passport (we make the note because it's kind of buggy Passport behavior and has not been fixed and people run into it all the time)

Ok, if I come up with something tidy and generally applicable I'll send a PR.

> Please note that CORS request does not equal OPTIONS requests, as OPTIONS requests are perfectly valid and can include cookies for non-CORS-preflight-related activity, so simply a PR to make this module ignore OPTIONS wouldn't be an acceptable solution.

Yeah IMO it's a pity that OPTIONS was used for the preflight when it has more general uses - makes it difficult to deal with in a generic way (in cases like this).  Seems like it should have had it's own verb.  I've never seen anyone using OPTIONS for anything other than CORS though.   Would you consider a config option like `ignoreOptionsRequests : true`  to be an acceptable solution with regards to the PR?

> Also, a (probably more sane) solution is to not even let CORS requests invoke this middleware by using a module to handle your CORS and preflight requests correctly

Right. Thanks.

**Comment by dougwilson** [comment]
>  Would you consider a config option like ignoreOptionsRequests : true to be an acceptable solution with regards to the PR?

No, because you can already accomplish this with the given solution in the `connect` issue. That just adds bloat for something that can easily be implemented as a npm module like `app.use(exceptForMethods(['OPTIONS']], expressSession({ ... })))`. The entire foundation of Express middlewares is to encourage you to wrap them and not reuire them to get bloated with unnecessary features and work-arounds.

**Comment by bgSosh** [comment]
> You can certainly send a PR here

So what did you mean here?

**Comment by dougwilson** [comment]
> > You can certainly send a PR here

> So what did you mean here?

I meant you can send a PR that will ignore CORS pre-flight requests, not simply any OPTIONS request, as outlined in the last sentence of https://github.com/expressjs/session/issues/229#issuecomment-158149824

**Comment by bgSosh** [comment]
Well I think the only way to do it without a config switch would be to catch OPTIONS requests that have `Access-Control-Request-Method` set, and ignore those.

**Comment by george-kar** [comment]
Any progress on this? I still have the same problem here and OPTIONS set a new cookie. I am using Passport

**Comment by joewagner** [comment]
hey @george-kar,
Have you tried using the `corser` module or not giving OPTIONS requests to this middleware as described above?

**Comment by george-kar** [comment]
@joewagner I found solution with this middleware (I had to change it a bit to check origin)

https://gist.github.com/cuppster/2344435

but I still cant understand why I have to use a middleware, it has to be fixed by expressjs/session.

**Comment by robertsLando** [comment]
I have used express official [cors](https://github.com/expressjs/cors) module by following this part in docs [enabling-cors-pre-flight](https://github.com/expressjs/cors#enabling-cors-pre-flight) and by setting cors like: 

```javascript
// must be included before session and other routes using cors:
// Certain CORS requests are considered 'complex' and require an initial
// OPTIONS request (called the "pre-flight request")
app.options('*', cors({ credentials: true, origin: true }))

app.use(session({ ---- your session config here ---- }))

....

//Api using cors
  app.delete('/myApi', cors({ credentials: true, origin: true }), middlewares.isAuthenticated, function(req, res){});

```

Cors works but I'm still not able to preserve `req.session` between calls and I can't authorize users

**Comment by bbroniewski** [comment]
It can be solved by:
```javascript
request.session.destroy();
```

... in the options handler.

Example:
```javascript
server.options('/path', function(request, response) {
    request.session.destroy();
});
```
