### ISSUE TITLE
Express 4, inconsistent view count in sample code

### ISSUE THREAD

**Issue by kenpeter** [expressjs/session#231]
The following code is copied from req.session in https://github.com/expressjs/session

Using express 4, the problem is

The views count is working in firefox. Every time, the views increase once after a page refresh.

The views count increases twice, in chrome and opera. That is not right?

```js
var express = require('express');
var session = require('express-session');
var app = express();

app.use(session({
  secret: 'keyboard cat',
  resave: true,
  saveUninitialized: true, 
  cookie: { maxAge: 60000 }
}));

app.use(function(req, res, next) {
  var sess = req.session;
  if (sess.views) {
    //test
    debugger;

    sess.views = sess.views + 1;
    res.setHeader('Content-Type', 'text/html');
    res.write('<p>views: ' + sess.views + '</p>');
    res.write('<p>expires in: ' + (sess.cookie.maxAge / 1000) + 's</p>');
    res.end();
  } else {
    sess.views = 1;
    res.end('welcome to the session demo. refresh!');
  }
});

app.listen(process.env.PORT || 4000);
```

**Comment by gabeio** [comment]
try logging all the requests from the client.
firefox follows a more private methodology. So it might try to get favicon.ico once and give up for a long time.
chrome and opera I believe continuously tries for the favicon nearly every request. as this example applies to all routes including /favicon.ico... the number can increase multiple times which may be very strange.

**Comment by dougwilson** [comment]
Hi! I'm closing this issue because it is stale. Pretty much 100% of the time, it's because of an implied request your web browser is making. I recommend you trying the example we have in our readme vs your example above, as the readme example won't count un-related requests.

**Comment by dougwilson** [comment]
Sorry, I misunderstood. I'll update the example in the readme.
