### ISSUE TITLE
Don't create session id for whom don't support Cookies

### ISSUE THREAD

**Issue by scaryguy** [expressjs/session#232]
Currently, even though a client doesn't support Cookies, with every request a unique session id is created in Redis (of course if it's the store that was set).  Here is an example key and value: 

Key: 
```
"sess:jhZoaPMzPRneoIk4Ya82ETZ_bcZ3YpND"
```
Value: 
```
"{\"cookie\":{\"originalMaxAge\":86400,\"expires\":\"2015-11-23T10:55:55.110Z\",\"httpOnly\":true,\"domain\":\".eee.com\",\"path\":\"/\"}}"
```

If the client doesn't support Cookies, these data are completely useless and it just occupies space in the memory for no good.

What do you think?

**Comment by gabeio** [comment]
there is a way to not send them cookies unless they need a session using `saveUninitialized: false` setting. In essence you don't send them a session unless you add something to the session. In addition when you do send them a cookie you can bounce them off a session check page which will direct them to a "you aren't accepting cookies" page if they don't have a session...

**Comment by dougwilson** [comment]
Hi @scaryguy , you have two options, in general:

1. As @gabeio said, you need to provide `saveUninitialized: false` in your options to this module, and ensure that for the requests you want to have a session, you set some value in the session object and don't set a value in sessions you don't want to get stored.
2. You'll have to detect somehow if the client supports cookies or not, and then simply conditionally invoke this middleware based on that detection.
