### ISSUE TITLE
Cannot write cookie

### ISSUE THREAD

**Issue by Tiendq** [expressjs/session#234]
I removed cookie-parser and tried to set a cookie with below code but no cookie sent to client:

```javascript
app.get("/", function(request, response) {
   response.render("home");
   request.session.cookie.username = "Tien";
});
```
I re-added cookie-parser and add a line to above function to write cookie as usual, it worked:

`response.cookie("rememberme", "1", { maxAge: 10000, httpOnly: true });`

What's issue with my code? Thanks,

**Comment by dougwilson** [comment]
Hi @Tiendq ! I'm not really sure what you are trying to do; this module does not provide any kind of API to let you set arbitrary properties on `request.session.cookie`, and `response.cookie` method is not part of this module, either. Perhaps you filed this issue on the wrong repository? If you think you're in the right place, can you provide full code to reproduce the issue, full instructions on how to reproduce and what you expect to happen for each of the examples?
