### ISSUE TITLE
same cookie set twice

### ISSUE THREAD

**Issue by ovaris** [expressjs/session#236]
I have following problem, session-middleware is overriding cookie params, response headers:
```
set-cookie:csrf_token=yswk3DEY-0P4b7OzM91HlUrA_K3tTrXlh-ag; Path=/
set-cookie:csrf_token=yswk3DEY-0P4b7OzM91HlUrA_K3tTrXlh-ag; Path=/,hubchat:sess=s%3Ax5yv4-tfStj4YsZifTzFSrJ9Xz8GGhfO.52ZEVGdQRjDApzE%2F5Wefgw3os7OEMd%2FI5W4uxxjzSiQ; Path=/; Expires=Tue, 01 Dec 2015 13:12:56 GMT; HttpOnly
```
I have set custom cookie `csrf_token` like this:
`res.cookie("csrf_token", req.csrfToken(), { httpOnly: false });`

And it is set correctly before logging in the user, but right when session middleware kicks in, it goes wrong.

Session config is:
````
let sessionConfig = {
            secret: config.session.secret,
            name: "hubchat:sess",
            cookie: {
                httpOnly: true,
                secure: config.cookie.secure,
                maxAge: (config.cookie.maxAge * 1000)
            },
            resave: false,
            saveUninitialized: false,
            unset: "destroy"
        };
```

Versions used:
- Node 4.2.1 
- expressjs 4.13.3
- express-session 1.12.1

**Comment by ovaris** [comment]
It seems that using `connect-mongodb` as session store was causing this weird behaviour. After switching to `connect-mongo`(https://github.com/kcbanner/connect-mongo) it works like expected!

**Comment by JamesMGreene** [comment]
@ovaris: It sounds like you should close this issue, then, right?
