### ISSUE TITLE
Please add connect-memcached as the compatible session module

### ISSUE THREAD

**Issue by chojrak11** [expressjs/session#247]
https://www.npmjs.com/package/connect-memcached
It can be next to Redis, because those are both in-memory databases.
Thanks!

**Comment by gabeio** [comment]
If you would like to make a pr where you want it to be listed along with the stars that would be greatly appreciated :+1: .

**Comment by chojrak11** [comment]
Ahh okay I'm new here, I was confused with PR and I understood it as problem report instead of pull request :-) You can close it, and I'll make PR.

**Comment by gabeio** [comment]
See pr #249.
