### ISSUE TITLE
some error code in readme

### ISSUE THREAD

**Issue by ManfredHu** [expressjs/session#252]
i try to write in this:
```javascript
app.use(session({
        secret: 'manfredHu', 
        resave: false,
        saveUninitialized: true
    }));
```

but it's error,so i find in stackOverflow, like this can use Session:
```javascript
app.use(expressSession({
        secret: 'manfredHu', //加密
        resave: false,
        saveUninitialized: true
    }));
```

**Comment by dougwilson** [comment]
Hi! Can you show which part of the readme? At the very top, it says that you require the module as `var session = require('express-session')`, so `session()` will work. No where in the readme do we show a variable called `expressSession`.
