### ISSUE TITLE
Add user information to session object - like PassportJS' serializeUser functionality

### ISSUE THREAD

**Issue by parky128** [expressjs/session#255]
I have been over this [article](https://www.airpair.com/express/posts/expressjs-and-passportjs-sessions-deep-dive#optimize-passportjs) which is an excellent explanation of how PassportJS uses the session object for storing user information once they have been authenticated using the serialize and deserialize functions.

But I'm now wondering, if you dont need to use any of the strategies that Passport offers and just want to persist some user information in the session, this could just be done by setting properties directly on the req.session object, so isn't PassportJS just overkill in this use case?

**Comment by gabeio** [comment]
> this could just be done by setting properties directly on the req.session object, so isn't PassportJS just overkill in this use case?

Yes it can be. Passport is really if you are looking to use multiple different authentications... eg: Google & Facebook or many more... It also might be if you aren't really interesting in building that part yourself and just want to get the app done and don't want to worry too much about the details. Though it also has a nice built in way to implement 2-step-auth if you are looking to do that for your app.
