### ISSUE TITLE
Session cookie gets too large

### ISSUE THREAD

**Issue by BorisKozo** [expressjs/session#257]
Hi
I think I am using session wrong. I have a problem with the cookie size being sent to the client. It seems that the entire content of the session is being put in the cookie instead of just some token which can be used on the server to get the actual data.

Is there a way to avoid sending the entire content of the session to the client for each request and instead just send some token (such as sessionId)?

I am using redis-connect store for the session store.
I am on express 3

Thanks.

**Comment by gabeio** [comment]
> It seems that the entire content of the session is being put in the cookie instead of just some token which can be used on the server to get the actual data.

Yes, something is absolutely setup incorrectly. Could I see the parts of your app that setup sessions (please don't include secret strings,keys,etc. but most of the setup will be helpful.

for example my setup it's pretty simple (note that this is express4/5 but if I remember correctly 3 it's really different in this case...):
```js
var express = require("express")
  ,redisClient
  ,connectRedis = require("connect-redis")
  ,app = module.exports = express()
  ,RedisStore = connectRedis(expressSession)
// ...
app.use(expressSession({
        secret: (process.env.secret), // pass secret as `export secret=somethinghere`
        resave: false,
        rolling: true,
        saveUninitialized: false,
        name: (process.env.session),
        cookie: {
            maxAge: (process.env.ttl || 86400) // ttl or 24 hours
        },
        store: new RedisStore({
            ttl: (process.env.ttl || 86400), // set this to the same this as the cookie so they expire together... (less bloat in the database)
            prefix: (process.env.namespace||"sess"), // optional
            client: (redisClient || process.env.redis || "localhost:6379") // try a variable try env then try localhost
        })
    }))
// ...
```

**Comment by BorisKozo** [comment]
This is what I have (part of a much larger file so maybe something is missing)
````
var session = require('express-session');
var RedisStore = require('connect-redis')(session);
var redis_store = new RedisStore({host: apconfig.redis_host, port: apconfig.redis_port});
app.use(express.cookieParser('secret')); //this is not the actual secret 
app.use(session({
    key: 'app.sess',
    secret: 'secret',
    maxAge: (1000 * 60 * 15)),
    secure: true,
    saveUninitialized: true,
    resave: true,
    store: redis_store
}));
````

**Comment by gabeio** [comment]
The docs say you no longer need the cookieParser...

> Note Since version 1.5.0, the cookie-parser middleware no longer needs to be used for this module to work. This module now directly reads and writes cookies on req/res. Using cookie-parser may result in issues if the secret is not the same between this module and cookie-parser.

that MAY be your issue...

the rest looks correct, I don't see anything straight off the bat that looks set incorrectly...

-----

sidenote: when you are saving stuff to the session make sure you are saving like so:
```js
req.session.<variable> = <value>
```
because if you happen to be saving it into the:
```js
req.session.cookie
//or
req.cookie
```
that's probably your issue.

**Comment by BorisKozo** [comment]
That I be dammed... I just found this in some unrelated module deep in the code:

````
res.cookie('sso', req.session, {});
````

Thanks @gabeio for helping. Your sidenote sent me finding all the places where ````req.session```` is used and I found this line!

**Comment by gabeio** [comment]
oh gosh yes there's the issue :smile: :+1: glad to be of assistance!
