### ISSUE TITLE
I am facing an issue where session regenerated in but document is nil in express, connect-redis, ioredis

### ISSUE THREAD

**Issue by echorohit** [expressjs/session#258]
I have added my question here in stackoverflow. Please have a look and suggest me what I can do to fix this problem.

http://stackoverflow.com/questions/34671655/redic-doc-is-nil-after-session-regeneration-in-express

**Comment by gabeio** [comment]
just a little side-note you absolutely will need to change your current sessions secret as the edit you made is still visible... a suggestion would actually be to use something like process.env.secret for passing your secret to your app... eg:
```js
app.use(session({
    store: new RedisStore({client: ioRedis, disableTTl:true, prefix:'prefix:'}),
    genid:function(req){
        return sessionManager.getSessionId(req);
    },
    name:"name",
    rolling: true,
    saveUninitialized: false,
    unset: 'keep',
    resave: true,
    secret: (process.env.secret) // set this using export secret='something' in your terminal before running your app
}));
```

**Comment by gabeio** [comment]
`req.sessionID` is not the session's id... `req.session.id` is the sessions id so try:

```js
console.log('previous session id', req.sessionID);
        if(req.session.newSessionToken) {
            let tempSession = req.session;
            req.session.regenerate(function(err){
                if(err){
                    throw(err);
                }
                //req.sessionID = tempSession.newSessionToken;
                req.session.id = tempSession.newSessionToken;
                req.session = tempSession;
                req.session.newSessionToken = null;
                delete req.session.newSessionToken;
                console.log('new session id', req.session.id);
                res.header('x-jabong-sessionid', req.session.id);
                req.session.save(function(err){
                   if(err){
                       throw err;
                   }
                    return res.json(data);
                });

            })
        } else {
            res.header('x-jabong-sessionid', req.session.id);
            return res.json(data);
        }
```

**Comment by dougwilson** [comment]
Hi @echorohit I looked at your code, but I can't really tell what is going on and what could be going wrong. Would it be possible to provide a complete application we can copy into a file & actually run ourselves? Then provide the steps we need to take on that application to see the same issue? Then we can debug it a bit to figure out what is going on.

**Comment by echorohit** [comment]
Hi @dougwilson , How I can send you the code? Would you prefer zip? As I can not send the complete code publicly?

**Comment by echorohit** [comment]
Let me explain the scenario, When client hit my api I create a session id for him and pass back for further  communications.The session doc should be be persist and document should not expires as per the need.  Now is login call has been asked then I need to change the previous session id into  a new session id and copies document of previous session id to new session id doc. This is the basic requirement. So I set a flag in session that session updation needed and I do change the session id and copy previous doc into a new doc.

**Comment by echorohit** [comment]
@gabeio Getting error while setting req.session.id too.
```sh
  uncaughtException===TypeError: Cannot assign to read only property 'id' of #<Session>
        TypeError: Cannot assign to read only property 'id' of #<Session>
        at /home/bll/bll-jb/server/lib/bll-router/lib/router.js:34:36
```

**Comment by echorohit** [comment]
Any findings here??

**Comment by JoeWagner** [comment]
@echorohit I'm not sure I understand what is going on in your code, but you shouldn't be setting `session.id` or `sessionID` in this way.  Maybe instead try using the request object to pass your `tempSession` along to the `genid` function.
e.g.
```
app.use(session({
    genid:function(req){
        //  use req.tempSession if available, otherwise do whatever you have been doing
        return (req.tempSession && req.tempSession.id) || sessionManager.getSessionId(req);
    },
    // the rest of your options, etc...
```

Then later...
```
if(req.session.newSessionToken) {
            req.tempSession = req.session;
            // `regenerate` will call your `genid` function
            req.session.regenerate(function(err){
                if(err){
                    throw(err);
                }
                // your session ID should be correct here, and you
                // can set the session to whatever you like ...

                // finally, cleanup tempSession if you want
                req.tempSession = void 0;
```

If this doesn't give you a solution, please do as @dougwilson requests above and provide some code that we can run here or in a gist.

**Comment by dougwilson** [comment]
Closing since we haven't gotten a copy of the code as requested, so it's not possible to determine anything more.
