### ISSUE TITLE
Why is the connect.sid cookie sent when a session is modified? 

### ISSUE THREAD

**Issue by ctorda-sp** [expressjs/session#264]
In our application, we're modifying the session on every request (to set the last accessed time) This causes the connect.sid cookie to be sent with the response to every request. 

Shouldn't the cookie only be sent when the session ID changes? 

The logic in question is in shouldSetCookie in index.js 
```
return cookieId != req.sessionID
        ? saveUninitializedSession || isModified(req.session)
        : rollingSessions || req.session.cookie.expires != null && isModified(req.session);
```

**Comment by JoeWagner** [comment]
Are you using the [`rolling`](https://github.com/expressjs/session#rolling) option?

**Comment by ctorda-sp** [comment]
We weren't using it before, but the default was false. I set it to false and it's still behaving the same way.

app.use(session({
        store: sessionStore,
        secret: 'oursecret',
        cookie: {expires: false},
        resave: true,
        saveUninitialized: false,
        rolling: false}));

**Comment by JoeWagner** [comment]
I believe the line: `cookie: {expires: false}` is not valid.  You can't set cookies that never expire.  If you're trying to make the cookie expire when the browser is closed (browser-session cookie) you should use `maxAge: null`

**Comment by gabeio** [comment]
Yes `cookie: {expires: false}` is not valid.

> expires: a Date object indicating the cookie's expiration date (expires at the end of session by default).
> maxAge: a number representing the milliseconds from Date.now() for expiry

**Comment by ctorda-sp** [comment]
Thanks guys, that fixed it. Should I modify the issue title or leave it as is?

**Comment by JoeWagner** [comment]
The title is fine as is.  Glad we could help!

**Comment by itisRamzan** [comment]
> Thanks guys, that fixed it. Should I modify the issue title or leave it as is?

Hey can you give me what is the final session options?
