### ISSUE TITLE
Cookie Session is not interchangeable with express-session

### ISSUE THREAD

**Issue by scurker** [expressjs/session#269]
This has been an issue I've been investigating over the past couple of weeks, and wanted to start a discussion about the future of express/session and potentially cookie-session. Currently, given that MemoryStore is not recommended beyond debugging and its issues even with debugging when the process restarts, there's no quick alternative. The closest is cookie-session, but unfortunately it does not match the same expected method signature that session expects for its stores.
#5 addresses setting the default session to be cookie session, but it's currently locked. However, with the way that session implements requests it would be difficult to make cookie-session compatible without some significant changes to session since you never have immediate access to the request object.

I started to write my own module that would allow cookie sessions to be use with express/session, but the plugin method would have to be slightly different given that request isn't available immediately within express/session.

**Comment by dougwilson** [comment]
Hi @scurker, thanks for the feedback! I re-read your paragraphs a few times, but I'm not certain what the proposal is.
