### ISSUE TITLE
POST requests doesn't save session

### ISSUE THREAD

**Issue by chiefGui** [expressjs/session#271]
**Problem:** when `app.post('/user')`, I am able to `req.session.isLoggedIn = true` but `req.session.isLoggedIn` is `undefined` in every place I call for it.

**Expected:** to save `isLoggedIn` to be able to use wherever I want.

**Attempts:**

- I already tried to `req.session.save()` after defining the session's variable and didn't work as well.

**Code:**

```js
import express from 'express'
import session from 'express-session'
import cookieParser from 'cookie-parser'

const app = express()
const PORT = 3000

app.use(cookieParser())
app.use(session({secret: 'atomicbomb'}))

app.get('/', (req, res) => {
  res.send('home ' + req.session.isLoggedIn) // always undefined
})

app.post('/user/authenticate', (req, res) => {
  req.session.isLoggedIn = true
  res.sendStatus(200)
})

app.listen(PORT, () => {
  console.log(`Listening at :${PORT}`)
})
```

*There are a plenty of topics out there with different solutions, but none of them worked for me and that's why I am creating this one.*

**Comment by JoeWagner** [comment]
@chiefGui I took the above code and rewrote it without any ES6 stuff and it works as expected.
What is your node version, and the flags you're running with?  What module versions are you using?

A thought for a quick fix:  The issue potentially stems from the `cookie-parser` module not having a secret.  This is mentioned in the [README](https://github.com/expressjs/session#cookie-options).

**Comment by kelthenoble** [comment]
True @JoeWagner  and @chiefGui It's recommended if you're running https  -> 

![screen shot 2016-02-09 at 11 58 06 am](https://cloud.githubusercontent.com/assets/1773260/12928789/5c4735d8-cf24-11e5-97d3-6746151e4a24.png)

**Comment by chiefGui** [comment]
Well guys, the thing is that I am doing the `POST` request through a different domain and somehow it isn't recogninzing the session as it should to do. I didn't figure out so far a solution, but the problem is diagnosed, since I've tested the same through different domains and with or without es6.

Also, @JoeWagner, I've already tested the `cookie-parser` with and without the secret—no success.

**Comment by JoeWagner** [comment]
@chiefGui I'm not sure I understand your issue, but if you are using different domains then the cookie will not be sent.  Cookies follow the same origin policy, you can read about this [here](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy)

As I said above, The code you provided works perfectly well for me.  If you want to provide code that demonstrates the issue, please include all versions and how you are running and testing.  If you can do this someone here will definitely help you out.

**Comment by chiefGui** [comment]
Yo, @JoeWagner! It was my bad, actually. I'm so sorry for this.

Basically, what I was missing is: `.withCredentials()` to go with my request to the server. I'm using the fantastic [superagent](https://github.com/visionmedia/superagent) and it has an option built-in to deal with that.

So, problem solved—a mistake of mine.

Thanks!
