### ISSUE TITLE
is genid unique when express is used on multiple node servers?

### ISSUE THREAD

**Issue by jayku4u** [expressjs/session#272]
Hi,

I am running 2 or more express instances behind a load balancer and use a redis store in the backend.  I don't have any custom genid function defined to create a session. 

is there any chance that the sessionID generated by the 2 different express node instances be same? 

For example,
User 1 visits my site. Gets Session ID "session:1" from the first instance and this is saved in Redis.
User 2 visits and same gets SessionID "session:1" from the second instance.

Is this possible?

How does "instance 2" know that the "session:1" was already issued by the "instance 1" and in use?

JK

**Comment by gabeio** [comment]
From my understanding of the system it doesn't know that another session with the same id is already in use it assumes it's not. What session does is it generates a very long random key which is the session id. With the session id at a large enough value (even by default) the idea is that they will almost never collide, as what you are suggesting. So in essence they also don't need to know.

**Comment by dougwilson** [comment]
Yea, the current `genid` function produces a random value, using the `uid-safe` module (https://github.com/expressjs/session#genid). The random value that is generated uses 24 bytes from your system's cryptographic random pool. 24 bytes wide means this is a 192 bit random number.

There is virtually no possible way you'd end up with colliding session IDs by default unless there is a problem with the cryptographic operations on your servers.

**Comment by waghanza** [comment]
@dougwilson what do you recommend to create session id, the **default** behavior https://www.npmjs.com/package/uid-safe or https://www.npmjs.com/package/uuid

it seems that https://www.npmjs.com/package/uuid is more maintained (and thus we could avoid collision)

**Comment by dougwilson** [comment]
The module uid-safe is perfectly maintained and has the same collision resistance as uuid. If you have specific issues with the uid-safe package, please open an issue there with specifics and I can address them :+1:
