### ISSUE TITLE
Cloudant connect store

### ISSUE THREAD

**Issue by komalda** [expressjs/session#278]
Hi,

Looking for cloudant session store. Please let me know if it can be releasable near future.
Br. Giri

**Comment by dougwilson** [comment]
Hi @komalda! We actually don't make any of the stores, rater they are independent modules created by the community. We list them here to make it easy to find. If there is no Cloudant store listed, then either no one has created one, or we just don't know it exists yet.

If you find one, please submit a PR for us to get it listed! If you cannot find one, creating it may be a fun project to do!
