### ISSUE TITLE
Generate different session after request

### ISSUE THREAD

**Issue by WenXuanYuan** [expressjs/session#283]
I use post method to upload a file and write the file path into session, but when every time I post, a new session was generated, Here are the config of my project
```js
//cookie parse
	app.use(cookieParser('keybord cat'));
/** session */
	app.use(session({
		store: new RedisStore(redisConf.options),
		resave: false,
		secret: 'keybord cat',
	}));
```
I use this code to print the sessionID
```js
console.log('==============================================');
			console.log(req.sessionID);
			console.log('++++++++++++++++++++++++++++++++++++++++++++++');
```
Here are the result I got
```
OPTIONS /upload 200 11.218 ms - 2
-==============================================
iXtcahEgYi_KzMRF3EG8WEPeT0O-N62g
++++++++++++++++++++++++++++++++++++++++++++++
{ '/upload': 
   [ { name: 'a 2.jpg',
       path: 'public/uploads/tmp/upload_ddf4e79a62f659c2568b29312eb69e4b' } ] }
POST /upload 200 48.547 ms - -
OPTIONS /upload 200 1.545 ms - 2
-==============================================
t2LwScYp6XaiU_QCaoZUgZKhnCZonQrg
++++++++++++++++++++++++++++++++++++++++++++++
{ '/upload': 
   [ { name: 'a.jpg',
       path: 'public/uploads/tmp/upload_0ce89f425bc4552b7e0b37ddf97c9310' } ] }
```
I need your help, Thank you very much.

**Comment by dougwilson** [comment]
Hi! The `OPTIONS` requests you are seeing is likely because you are doing some kind of JavaScript request to make your POSTs. The sessions are being generated because those `OPTIONS` calls are pre-flight requests for the cross origin resource sharing specification, most likely.

You can stop those from generating new sessions if you add a CORS handler to your application, before you use this module. For example, you can use https://github.com/expressjs/cors:

```js
// you need to setup your CORS options, or "{origin: false}" to disable CORS
app.use(cors( ... options ... ));
```

**Comment by WenXuanYuan** [comment]
@dougwilson Let me have a look, Thank you very much!

**Comment by WenXuanYuan** [comment]
@dougwilson I tried to use cors ,but still can`t solve my problem and I find there are no cookies information in my resources , what should I do?

**Comment by dougwilson** [comment]
Hi @WenXuanYuan, I'm not sure, sorry, there just isn't enough information provided here to understand what is happening. I would suggest dropping by http://gitter.im/expressjs/express to ask around for help to see what you can find.

**Comment by WenXuanYuan** [comment]
@dougwilson I have solved my problem , because of cookie is not sent in cross domain request.
