### ISSUE TITLE
【waiting for answer】A question about leaking memory

### ISSUE THREAD

**Issue by yalishizhude** [expressjs/session#284]
I'm really doubt why don't we check the session store's size and release the memory to prevent leak memory for production environment?
Is there any other problem?
thx~

**Comment by JoeWagner** [comment]
The memory store included here is not intended for use in production.  You should choose a production ready store from the list of [compatible stores](https://github.com/expressjs/session#compatible-session-stores)
If you're interested in the thinking around this, #128 has some discussion on the topic.  Basically, this module is not responsible for handling stores.  The included memory store is there for testing purposes.
