### ISSUE TITLE
Can I store a Class(Object) in express-session and then retrieve the Object?

### ISSUE THREAD

**Issue by augcampos** [expressjs/session#286]
Hi there,
I have a class Class SessionUser {...}

The on user login I set the request.session.user = new SessionUser( ... );
request.session.save()

and to get the Session user  var current_user =  Object.create(SessionUser, request.session.user ); // this fails to cast the info in request.session.user  to a new Object.

Thanks in advance.

**Comment by dougwilson** [comment]
Hi @augcampos, whatever you put into `req.session` is serialized by the store library you are using. Most, if not all will just use `JSON.stringify`/`JSON.parse`, but you should consult the sore that you are using.
