### ISSUE TITLE
"trust proxy" setting doesn't appear to be used as a default.

### ISSUE THREAD

**Issue by justincy** [expressjs/session#288]
The documentation for the `proxy` setting says

> * `undefined` Uses the "trust proxy" setting from express

That doesn't appear to be happening. Are the docs incorrect or would this be a bug?

**Comment by dougwilson** [comment]
We have tests for this in https://github.com/expressjs/session/blob/30a3f498203e0cd3b8815713f29e1f8f10f8c34a/test/session.js and it seems to work for me. Can you provide a reproduction case?
