### ISSUE TITLE
Please publish 1.13.1

### ISSUE THREAD

**Issue by siboulet** [expressjs/session#289]
Latest version on npmjs is 1.13.0.

Thanks

**Comment by dougwilson** [comment]
omg, oops!

**Comment by gabeio** [comment]
@dougwilson just wondering if you are holding 1.13.1 behind for anything?

**Comment by dougwilson** [comment]
In the end, 1.13.1 was accidentally not published, and it didn't really contain anything of substance. 1.13.1 is effectively canceled and the next version will just be 1.14.0.
