### ISSUE TITLE
Passing new session value from server to user browser??

### ISSUE THREAD

**Issue by 1nfinite** [expressjs/session#292]
Assuming that the user has an existing cookie in his/her browser.

And the user do a request to the server.
Suppose that I have explicitly change the expiry date time in session as follow if the user request success, how could I push this newly set expiry datetime back to the targeted user browser who did this request?
```
var hour = 3600000
req.session.cookie.expires = new Date(Date.now() + hour)
req.session.cookie.maxAge = hour
```

**Comment by 1nfinite** [comment]
To put it simple, after i update expires and maxAge in server session, how could i reflect the new expiry datetime to user browser cookie?

**Comment by gabeio** [comment]
This does depend a little based on your configuration but you seem to have the answer right there when you set something to the `req.session.cookie.expires` and or `req.session.cookie.maxAge` it should update the client with the new cookie age.

**Comment by 1nfinite** [comment]
@gabeio  Hi i think the question mention about req.session.cookie.expires is not set accordance to req.session.cookie.maxAge. However, my concern is browser cookie does not update the expiry date time as accordance to the server session new maxAge/expiry datetime

**Comment by gabeio** [comment]
Do you have rolling set to true? if so rolling currently has an issue which I appended a link to the open pull request. the issue is that rolling overrides the maxAge/expires which will therefore not end up the same as the server session's expire datetime

**Comment by 1nfinite** [comment]
@gabeio i didn't initialize rolling so it supposed to be false by default.

**Comment by 1nfinite** [comment]
@gabeio I have explicity set rolling=false and saveUninitialized=true. Also, I set `req.session.cookie.maxAge = 864000` but the expiry datetime in client browser cookie is still the same as previous value.

Would like you to clarify something:
1) Is the client and server session expiry will be in sync by default?? 

I am using v1.9.1 of express session btw.

**Comment by gabeio** [comment]
There is no default for rolling you may or may not need it depending on your application as per the documentation. Setting `rolling` to `true` automatically syncs the client and server expiration time to the default.

**Comment by 1nfinite** [comment]
Thanks. Setting rolling to true resolve the issue. case close.
