### ISSUE TITLE
How to get list of all logged in users in express-session

### ISSUE THREAD

**Issue by abhaygarg** [expressjs/session#294]
In Admin page we need to show list of all users who are logged in . In mongo-db it save data in this form

```
{
    "_id" : "rpojHNHHzmT-mzlaLfA1nl2fBcAqLAFW",
    "session" : "{\"cookie\":{\"originalMaxAge\":null,\"expires\":null,\"httpOnly\":true,\"path\":\"/\"},\"_csrfSecret\":\"8N3x6krQOaaayQ==\"}",
    "expires" : ISODate("2016-04-11T14:03:43.595Z")
}
```

So I am very confused how express-session work , How it check which user if logged in. Right now our requirement to get list of all logged in users . We also need to show last login of User

Will express-session help us. or we need to write our own login ?

**Comment by gabeio** [comment]
I'm going to go ahead and assume you also use the mongodb for the rest of your database also (though honestly this is applicable to any database especially SQLs). Using express-sessions to keep track of a users sessions, make a separate user collection which ends up being a sort of "intermediary table" where the user's id is the lookup and then just the latest session id from `req.session.id`. This also does not have to be one entry you can have multiple sessions using this method. This allows building of functionality like "kill all other sessions" and loop over the hopefully small amount of session that the user has open and delete all that are not currently the `req.sessiond.id`.

**Comment by abhaygarg** [comment]
Ok thanks , Actually In our previous Project we implement our own logic for session handling , And that also helps like Admin wants to login into any different account . So Now I remove express-session and implement that same Logic . Thanks for your answer
