### ISSUE TITLE
401 responses - distinguish between no session found and session expired

### ISSUE THREAD

**Issue by parky128** [expressjs/session#299]
Hi,

I am using express-session and have configured a session expiry, I understand express will return 401 responses back to the client, but I wondered if there was a way to tell the client the specific reason for the 401.

Right now I can see a 401 is served back whenever a non logged in user first visits my application, or are logged in, but their session has expired. The 401 response looks identical in both cases.

Basically, I want to display a user to the message that their session has expired.

Right now I'm setting a variable in my client side application that tracks whether they are logged in or not. When their session expires, I redirect them to my login page and because my login var is still set to true I can assume they arrived back at login due to a session expiry, so I have some logic in place to show a session expiry message.

I just wondered if there was a smarter way to do this through the express generated 401's?

I hope I have made sense with this question!

Thanks

**Comment by dougwilson** [comment]
Hi @parky128, this module does not send any responses back to the client, including 401 responses. I'm sure you can code up a 401 response in your own code, but in order for us to help, we would need to understand the code you implemented.

Can you provide a complete script we can copy and paste into a file to run to reproduce your issue? Then explain how to reproduce the 401 with your code and we can understand what is going on with your code.

**Comment by parky128** [comment]
Hi @dougwilson - OK I have has a face palm moment and just realised I have overlooked a helper function my route middleware are all calling, which actually does a check for a property on the `req.session` object and sends a 401 back if it's not present.

So I have this right now:

```javascript
module.exports.hasAccessToken = function(req, res, next) {
  if(req.session.accessToken){
    next();
  } else {
    res.status(401).send();
  }
};
```

I am using `connect-mongo` as my store and on login I am adding an `accessToken` property to `req.session` using a value returned from an OAuth provider.

If I console log out what `req.session` is after login in I see

```
Session {
  cookie:
   { path: '/',
     _expires: Tue Apr 05 2016 08:58:10 GMT+0100 (GMT Daylight Time),
     originalMaxAge: 3000,
     httpOnly: true },
  accessToken: '<token_value_here>' }
```

When the session has expired and the 401 is being sent by my function further above I see

```
Session {
  cookie:
   { path: '/',
     _expires: null,
     originalMaxAge: null,
     httpOnly: true } }
```

`req.session` also evaluates to the above when a non logged in user visits the application. So there is no way for me tell if the user was previously logged in and their session cookie has since expired. I cant user the browser cookies collection since httpOnly is being used.

So what I would ultimately like to do is add some extra information to the response body in `res.status(401).send();` with some sort of reason code to say why the 401 is being sent, such as 'SESSION_EXPIRED'

Is this achievable?

Thanks

**Comment by parky128** [comment]
Hi @dougwilson - OK I have has a face palm moment and just realised I have overlooked a helper function my route middleware are all calling, which actually does a check for a property on the `req.session` object and sends a 401 back if it's not present.

So I have this right now:

```javascript
module.exports.hasAccessToken = function(req, res, next) {
  if(req.session.accessToken){
    next();
  } else {
    res.status(401).send();
  }
};
```

I am using `connect-mongo` as my store and on login I am adding an `accessToken` property to `req.session` using a value returned from an OAuth provider.

If I console log out what `req.session` is after login in I see

```
Session {
  cookie:
   { path: '/',
     _expires: Tue Apr 05 2016 08:58:10 GMT+0100 (GMT Daylight Time),
     originalMaxAge: 3000,
     httpOnly: true },
  accessToken: '<token_value_here>' }
```

When the session has expired and the 401 is being sent by my function further above I see

```
Session {
  cookie:
   { path: '/',
     _expires: null,
     originalMaxAge: null,
     httpOnly: true } }
```

`req.session` also evaluates to the above when a non logged in user visits the application. So there is no way for me tell if the user was previously logged in and their session cookie has since expired. I cant user the browser cookies collection since httpOnly is being used.

So what I would ultimately like to do is add some extra information to the response body in `res.status(401).send();` with some sort of reason code to say why the 401 is being sent, such as 'SESSION_EXPIRED'

Is this achievable?

Thanks

**Comment by dougwilson** [comment]
Hi @parky128, it really depends on why the session is gone. If it is because the cookie in the web browser expired, well, it is literally impossible to tell the difference between a browser without the cookie and a browser that used to have a cookie, since no cookie is sent from the browser in both cases. If the session just expired on the server side, but the cookie is still in the browser, you can always use the `cookie-parser` middleware and test to see if the cookie was sent.
