### ISSUE TITLE
How do I set additional cookies without using cookie-parser? Docs state do not use Session and Cookie Parser Together

### ISSUE THREAD

**Issue by dman777** [expressjs/session#300]
From reading documentation:

It states:

> the cookie-parser middleware no longer needs to be used for this
> module to work. This module now directly reads and writes cookies on
> req/res. Using cookie-parser may result in issues if the secret is not
> the same between this module and cookie-parser.

Aside from the default cookie that express-session creates, how do I set additional cookies with express-session?

 Since session doesn't have the `cookie()` api to set cookies. I don't want to use `cookie-parser` to follow the best practice the documentation states on not using those together.

**Comment by dougwilson** [comment]
Hi! The documentation does in no way say you cannot use the two together. It just state that using `cookie-parser` is not actually _required_ to use this module now (it used to be required in older 1.x versions) and that just keep in mind you have to use the same secret for this module and `cookie-parser` if you use the `cookie-parser` module.

**Comment by dman777** [comment]
:+1: Thank you so much!
