### ISSUE TITLE
Session not working on edge.

### ISSUE THREAD

**Issue by jaoxico** [expressjs/session#301]
Does anyone here have accessed any express with express-session project on edge browser?
The browser simply does not send the cookie on requests.

Does anyone know how to solve this?
Thanks in advance.

**Comment by jaoxico** [comment]
I've just found the reason it's not working on edge.
On my app ajax requests are done to get info depending on session situation.
But, edge does not repeat the requests when it is in cache.

God bless Microsoft.

**Comment by ManfredHu** [comment]
app.use(expressSession({
  secret: 'keyboard cat',
  resave: false,
  saveUninitialized: true,
  cookie: { secure: true }
}))

you can try this one

**Comment by gabeio** [comment]
You might need to server a `no-programa: cache` header

**Comment by armadill-odyssey** [comment]
Did you guys ever figure out the solution to this?

**Comment by dougwilson** [comment]
Hi @armadill-odyssey the OP determined the issue & solution for their own issue but did not share the details beyond what they posted above.

**Comment by davidchaiken** [comment]
Almost 5 years after this thread, Bing and Google still put it near the top of the results for the query "express-session microsoft edge," so it seems like it's worth documenting an answer to the original question.

I put this line of code in the <head> of my HTML document to make express-session (1.17.2) work with Microsoft Edge (94.0.992.50):
`<meta http-equiv="pragma" content="no-cache">`.
