### ISSUE TITLE
es2015 Map object looks problem 

### ISSUE THREAD

**Issue by petersunquest** [expressjs/session#302]
When use a type of Map object that will be a normal Object.

session = req.session;
session.testMap = new Map()
typeof session.testMap  ==> 'map'
res.end()

... Then in other request
session = req.session;
typeof session.testMap  ==> 'Object'

Thanks

**Comment by dougwilson** [comment]
Hi! This module does not perform the inflation/deflation of your session. You will need to file this issue against whatever store module you are using asking them to support Map.

**Comment by petersunquest** [comment]
Hi Dougwilson,

Thank you for your reply.
I use nodejs and express, so the 'express-session' jest a middle module.
Is express don't support Map type.

Peter

**Comment by tunniclm** [comment]
I think Doug is referring to the session store that is being used with `express-session` which can be configured with this option: https://github.com/expressjs/session#store
