### ISSUE TITLE
Cookie.domain property included in Cookie.data without default and is not mentioned in documentation

### ISSUE THREAD

**Issue by fvgs** [expressjs/session#303]
The [`Cookie.domain` property is included in `Cookie.data`](https://github.com/expressjs/session/blob/master/session/cookie.js#L103) but is not assigned a default value. Furthermore, `Cookie.domain` can be [set via the options](https://github.com/expressjs/session/blob/master/session/cookie.js#L103), but is not mentioned in the documentation.

Thus, I see the following two issues:

1. `Cookie.domain` is accessed without a default assignment and without being required from the user.
2. `Cookie.domain` is not mentioned as an option in the documentation despite being user-configurable and a standard property.

**Comment by dougwilson** [comment]
All cookie options are not fully documented in the README :)
