### ISSUE TITLE
how can i create sessions with different options?

### ISSUE THREAD

**Issue by linejine** [expressjs/session#305]
i want to create sessions with different options.
for example, i create login session with cookie.maxAge 30 minutes and bookmark session with no cookie.maxAge-persistent session without deleting session.
how can i do?

**Comment by gabeio** [comment]
You probably want 1 of 2 things... probably either use a cookie separately or if you really want two sessions you can mount two different sessions in different places or both(though that might not be the best idea)...

eg:
```javascript
var loginSession = session({
  secret: 'keyboard cat',
  resave: false,
  saveUninitialized: false,
  maxAge: 1800,
})

var bookmarkSession = session({
  secret: 'something else',
  resave: false,
  saveUninitialized: false,
})

// and then mount it like so to different routes:
app.get('/bar', loginSession, function (req, res, next) {
  res.send('you viewed this page ' + req.session.views['/bar'] + ' times')
})

app.get('/foo', bookmarkSession, function (req, res, next) {
  res.send('you viewed this page ' + req.session.views['/foo'] + ' times')
})

// or mount both
app.get('/both', loginSession, bookmarkSession, function (req, res, next) {
  res.send('you viewed this page ' + req.session.views['/bar'] + ' times')
})
```

there's even more you can do like mount the login globally & the bookmarks locally depending on where you want it or vise versa ...
