### ISSUE TITLE
How to make some addresses do not use session?

### ISSUE THREAD

**Issue by a348730140** [expressjs/session#306]
```javascript
//index.js
var express = require('express');
var router = express.Router();

//use session
router.get('/',function(req, res, next) {})

//not use session
router.get('/test',function(req, res, next) {})
```

How to address `/test` does not use session

**Comment by gabeio** [comment]
You can use something like this: https://github.com/expressjs/csurf#ignoring-routes (yes csurf is not sessions but that example should give you the answer you are looking for)

Options:
 1. do not have sessions mounted globally, have routers which do not have sessions mounted and routers which do have sessions mounted
 2. do not mount sessions globally; mount them on each individual route. (issues: more specific but more time consuming and easy to forget to mount it on a route)

**Comment by a348730140** [comment]
@gabeio thx :D 
i see
