### ISSUE TITLE
I want to do some tings after the session is  destoried. what should I do?

### ISSUE THREAD

**Issue by hlerenow** [expressjs/session#308]
I want to do some tings after the session is  destoried. what should I do?

**Comment by gabeio** [comment]
after the session is destroyed is actually generic...
do you mean:
 - after you destroy a session with `req.session.destroy()`?
 - when the client's session is expired?
 - when the database's session is expired?

**Comment by hlerenow** [comment]
"By default cookie.maxAge is null, meaning no "expires" parameter is set so the cookie becomes a browser-session cookie. When the user closes the browser the cookie (and session) will be removed."

I do this.And I want to to some things after  the cookie (and session) will be removed. instead of after  destroy a session with req.session.destroy().

**Comment by dougwilson** [comment]
That is impossible, as the browser makes no request to the web site when it closes, so there is no generic way to know when the user closed their web browser and thus deleted the cookie, sorry! If you know of a way, you're always welcome to make a PR!

**Comment by hlerenow** [comment]
but I think it's possible,because the session is saved in servicer,and session will be destoried at a certain time instead of keep living ,this can be control by program,so we can expose a interface or a event to do something after session is destoried,Maybe it will has some delayed.the session of j2e has a listener to do this ,(eg for j2e : public void sessionDestroyed(HttpSessionEvent se)  ),so I think we can also do this.

**Comment by dougwilson** [comment]
Hi @hlerenow, I understand your ask now. No, we will not add that to this module. You are supposed to use your store module to do this, and if the store module wants to provide an interface that emits an event, it is 100% free to do so.

For example, say your store module provides this as an event, called "destroy", then you would perhaps do the following (it all depends on what your store module provide you):
```js
var store = new YourFavoriteStore()

store.on('destroy', function (sess) {
  // react to your store destroying a session
})

app.use(expressSession({ store: store }))
```

You are required to access this through your store module, not this module.

**Comment by hlerenow** [comment]
Thank your answer and hope you have a  nice day.  : -)
