### ISSUE TITLE
Issue encountered when updating my own req.session properties

### ISSUE THREAD

**Issue by parky128** [expressjs/session#312]
This is probably more of a 'how to' question more suited for StackOverflow, which I have actually posted on there but am not attracting any comments, so my apologies but I thought I'd try here in case this is an issue with this library or at least my usage of it.

I'm using `express-session` to save an OAuth 2 access token users are provided with when they login. This token then gets used for subsequent requests as a bearer token Authorization header to a separate API server. I'm just setting a custom property so `req.session.accessToken` and then using in a further outgoing request from my Express middleware.

This token has a short life and when expires, needs to be refreshed and the new token that gets generated needs to be saved back into the session object using `express-session`.

I have this token refresh flow working fairly well in some middleware I have written, but I have encountered a situation where after updating my `req.session.accessToken` property, a subsequent request that follows soon after end's up using the previously set value for this property and I am unsure why.

Here's my code in Express

**routes.controller.js**

```
//Currently handling GET API requests from client
module.exports.fetch = function(req, res) {
  var options = helpers.buildAPIRequestOptions(req);
  helpers.performOutgoingRequest(req, res, options);
};
```

**helpers.js**

```
module.exports.buildAPIRequestOptions = function(req, url) {
  var options = {};
  options.method = req.method;
  options.uri = 'http://someurl.com' + req.path;
  options.qs = req.query;
  options.headers = {
    'Authorization': 'Bearer ' + req.session.accessToken
  };
  return options;
};

module.exports.performOutgoingRequest = function(req, res, options) {
  request(options, function(err, response, body){
    if(response.statusCode === 401){
      console.log(chalk.red('\n--- 401 RESPONSE RECEIVED TRY REFRESHING TOKENS ---'));
      //Note the third param to call below is a callback and is invoked when calling next() in the refreshToken middleware
      authController.refreshToken(req, res, function(){
        console.log(chalk.green('\n--- RETRYING ORIGINAL REQUEST WITH UPDATED ACCESS TOKEN ---'));
        //Re-use original request options, but making sure we update the Authorization header beforehand
        options.headers.Authorization = 'Bearer ' + req.session.accessToken;
        retryOutgoingRequest(res, options);
      });
    } else {
      res.status(response.statusCode).send(body);
    }
  }); 
};


function retryOutgoingRequest(res, options) {
  request(options, function(err, response, body){
    if(err) {
      console.log(err);
    }
    res.status(response.statusCode).send(body);
  });
};
```

**auth.controller.js**

```
module.exports.refreshToken = function(req, res, next) {
  var formData = {
      grant_type: 'refresh_token',
      refresh_token: req.session.refreshToken
    },
    headers = {
      'Authorization' : 'Basic ' + consts.CLIENT_KEY_SECRET_BASE64
    };
  request.post({url:consts.ACCESS_TOKEN_REQUEST_URL, form:formData, headers: headers, rejectUnauthorized: false}, function(err, response, body){
    var responseBody = JSON.parse(body);
    if (response.statusCode === 200) {
      req.session.accessToken = responseBody.access_token;
      req.session.refreshToken = responseBody.refresh_token;
      next();
    } else {
      console.log(chalk.yellow('A problem occurred refreshing tokens, sending 401 HTTP response back to client...'));
      res.status(401).send();
    }
  });
};
```

For the most part the above is working just fine

When a user first log's in, some additional user profile info is fetched from the API server before they are taken to the main page of the application.

Some of the pages in the application also fetch data on page load, and so are subject to the access token checks.

During normal usage, so when a user logs in, and starts clicking around the pages, I can see the tokens are getting swapped out and saved in the session store via express-session as and when they expire. The new access token is correctly being used for subsequent requests as per the middleware I have written.

I now have a scenario where this does not work.

So say I'm on a page that loads data on page load, lets say its an orders page. If I wait until the configured token expiry time on the API server has passed and then refresh the browser, the client side app will first make a request for the user info, and on success will then request the orders data required for the page (using AngularJS promises)

In my Express app the user info request gets a 403 from API server and so the tokens get refreshed via my middleware above, and the req.session.accessToken gets updated which I can see through console logging in my server application. But the next fetch of data for the orders ends up using the previously set access token and this causes a further unauthorised error from the API server since a request is being made with an invalid token.

If I refresh the browser again, both the user info and orders are fetched using the correct updated token from the previous middleware flow.

So I'm unsure what's going on here, I'm wondering if it's a timing issue with the req.session object not being persisted back to the session store in time for the next request to pick up?

Anyone got any ideas what may be going on here?

**Comment by mike-goodwin** [comment]
What session store are you using?

**Comment by parky128** [comment]
Hi, I'm using connect-mongo and I also have my set rolling to true on my express-session config

**Comment by dougwilson** [comment]
The only thing I can think of is the "issue" that Node.js is highly parallel. This means that your requests from the client is just not in series, but in parallel, such that a request can come in even before a "previous request" completely persisted the access token to the store.

You an confirm if this is the case by adding the following middleware at least above your session middleware and seeing if it resolves the issue (do not actually use this as a solution, because it will kill all parallelism and performance). You also need to be 100% sure that you are only running a single instance of your app for this test:
```js
app.use((function () {
  var process = []
  var onFinished = require('on-finished') // npm i on-finished@2
  return function (req, res, next) {
    onFinished(res, function () {
      process.shift()

      if (process.length !== 0) {
        process[0]()
      }
    })

    if (process.push(next) === 1) {
      next()
    }
  }
}()))
```

**Comment by dougwilson** [comment]
Oops, I never came back to this issue since there was never any other comments. I'm going to close this from inactivity, if that is OK :)
