### ISSUE TITLE
how can i build another data when the session was created

### ISSUE THREAD

**Issue by xxholly32** [expressjs/session#313]
my express setting

```
app.use(session({
    store: new RedisStore({
        host: settings.redisUrl,
        port: settings.redisPort,
        pass : settings.redisAuth,
        db : settings.redisDbindex
    }),
    rolling: true,//配合maxAge使用，同步更新最大超时时间
    cookie:{ maxAge : settings.redisSessionLostTime },
    secret: settings.cookieSecret
}));
```

when i login, my redis create 
sess:wL33D9ltSAzwCfYV_aJ-k9txGhaVZiBq : ............

now i need create another data (key is my userId) into the redis
how?
and i want it destory when the session is out.

ty

**Comment by gabeio** [comment]
sessions doesn't do what you are asking to do.

What you probably want to do is to set the data inside the session object `req.session`.

How sessions works:

user's cookie: `somekey:<random token>`
database: `<random token>:{user data}`

the `{user data}` can be as simple as a username which you can then look up the rest of the user data within a database.

**Comment by xxholly32** [comment]
@gabeio 
i dont want inside the session object 

actually i want set a new data into the redis
key is my userid ,value is sessionid

**Comment by gabeio** [comment]
you'll have to do that manually. sessions does not do anything but lookup the session object and dump the contents to `req.session`
