### ISSUE TITLE
Handle writing to session after response has finished.

### ISSUE THREAD

**Issue by jmacmahon** [expressjs/session#315]
Example code:
```
app.get('/set_session_deferred', function (req, res) {
  res.on('finish', function () {
    req.session.test = 'bla';
  });
  res.end('ok');
});
```

This data is not actually kept in the session.  I haven't looked at the code so I don't know why, but I imagine it's because session store synchronisation happens before the 'finish' event is emitted?

**Comment by dougwilson** [comment]
The session is auto-saved on the response, so after it has finished, the auto-save has already occurred. You can always save it again at any time, even after the response has completed, though, just use `req.session.save` (https://github.com/expressjs/session#sessionsave):

```js
app.get('/set_session_deferred', function (req, res) {
  res.on('finish', function () {
    req.session.test = 'bla';
    req.session.save(function (err) {
      // do whatever
    });
  });
  res.end('ok');
});
```
