### ISSUE TITLE
Creating a session for multiple different domains

### ISSUE THREAD

**Issue by karlkurzer** [expressjs/session#323]
My app can be accessed from various different domains: _x.com_, _x.org_, _abc.x.com_ or _blog.x.com_. While I understand how to include sub domains I am wondering, if there is a straight forward way to use a session for more than one domain, so that users can log in on _x**.com**_ and will be logged in to _x**.org**_ as well once they visit that page.

I am looking forward to some ideas :-)

**Comment by dougwilson** [comment]
It's not possible to do that with cookies. You would have to use some sort of SSO system.

**Comment by karlkurzer** [comment]
@dougwilson thanks for the clarification :-)
