### ISSUE TITLE
sharing a session between multiple node(express) processes

### ISSUE THREAD

**Issue by afrozl** [expressjs/session#334]
I have an app that authenticates users and serves the views/UI. I also have a separate API server that I want should share the session info from the first app. How would I go about accomplishing this?

**Comment by shaunwarman** [comment]
It's very common to have an external session store for this exact purpose. Check out the [session store] (https://github.com/expressjs/session#session-store-implementation) section and one of the (popular choices) [https://github.com/tj/connect-redis] using (redis) [http://redis.io/] as your database for fast session read/writes. This way all node processes have a shared session available via RPC.

**Comment by afrozl** [comment]
I'm already using connect-mongo as a session store. I guess the part I am missing is how to make the other node processes recognize the same session. In other words, only the UI process sets the session/session id and the other processes just piggy back off that session?

**Comment by shaunwarman** [comment]
So usually the session ID is available in the UI from the cookie. So if you are passing this information down to your API and it interacts with the same session store then you should be able to query based on session ID and get the same session information.

I am not sure of your setup, but I imagine to middleware should parse the cookie for the session ID and that's what you want. Most if it is abstracted from you.. so you only look at `req.session` and everything else should be handled.

**Comment by gabeio** [comment]
some notes about using multiple node processes. the secret especially, but pretty much all of the options, must be identical for every process.

**Comment by afrozl** [comment]
Thanks guys, I have it working now. The trick was as you said, all options, specifically the secret and key had to be the same.
