### ISSUE TITLE
Support new Database

### ISSUE THREAD

**Issue by HemangSoft** [expressjs/session#338]
Hi, 

I see the list of supported database. Could it possible to save the session in Orientdb database or any plan for future support ?

Thanks

**Comment by gabeio** [comment]
All database support has been contributed by the community.

Your in luck a quick npm search turned up https://github.com/ffissore/connect-orientdb though it looks dated & under tested (low star count).

**Comment by HemangSoft** [comment]
Thanks

**Comment by HemangSoft** [comment]
Hello,

var OrientDBStore = require('connect-orientdb')(express);

It gives below error
Error: Most middleware (like session) is no longer bundled with Express and must be installed separately.

Could you please guide me how to use it in express ?
Thanks

**Comment by gabeio** [comment]
try:
```
var express = require('express')
var session = require('express-session') // add this
var SQLiteStore = require('connect-orientdb')(session) // change express to session
```

the example on connect-orientdb readme is from express v3.x

**Comment by HemangSoft** [comment]
Hi
I tried below
require("coffee-script");
require("coffee-script/register");
var express = require('express');
var session = require('express-session');
var orientDBStore = require('connect-orientdb')(session);

Getting below error:
/node_modules/connect-orientdb/lib/connect-orientdb.coffee:191
    })(connect.session.Store);
TypeError: Cannot read property 'Store' of undefined

I am using following versions:
 "express": "^4.14.0",
 "express-session": "^1.14.0",
"coffee-script": "^1.10.0"
"connect-orientdb": "^1.3.2"
"connect-assets": "^5.3.2"
"request": "^2.74.0"

Let me know if any version has issue.
