### ISSUE TITLE
Session cookies break when Unicode Emojii Values are entered

### ISSUE THREAD

**Issue by ammuench** [expressjs/session#342]
Okay, so I know this sounds a bit crazy, but I'm currently running a site that uses Steam for OpenID, and part of that is that it passes back their steam username, which is serialized in the session.

We had a user who's cookie JSON was continually stored as unfinished--it simply cut-off halfway through.  Turns out he had Unicode Emojii in his steam name that caused the cookie to just give up and stop there--causing a failure later when the website tried to read the session since it couldn't parse an invalid JSON file  (see attached images).  

I'm not sure where it's failing in the process, but it appears that when a unicode emojii gets passed through, the cookie stops being written completely and is sent incomplete

<img width="660" alt="screen shot 2016-08-19 at 12 47 12 pm" src="https://cloud.githubusercontent.com/assets/2099658/17818991/91e2e6fa-660b-11e6-84fb-b737f405574a.png">
<img width="939" alt="screen shot 2016-08-19 at 12 43 20 pm" src="https://cloud.githubusercontent.com/assets/2099658/17818990/91e167e4-660b-11e6-9871-0e20f77f6bf8.png">

**Comment by dougwilson** [comment]
This is most likely an issue with the store module you are using, not this module. Which store are you using? Have you reported the issue there?

**Comment by ammuench** [comment]
Ah, yeah, that'd be the mySQLsession store plugin.  Sorry for the mixup, thanks for the redirect!
