### ISSUE TITLE
typings error

### ISSUE THREAD

**Issue by taoqf** [expressjs/session#350]
error:
```bash
error TS2305: Module 'createApplication' has no exported member 'CookieOptions'.
```
code:
```ts
  namespace session {
    export interface SessionOptions {
      secret: string;
      name?: string;
      store?: Store | MemoryStore;
      cookie?: express.CookieOptions; // ln43
      genid?: (req: express.Request) => string;
      rolling?: boolean;
      resave?: boolean;
      proxy?: boolean;
      saveUninitialized?: boolean;
      unset?: string;
    }
```

**Comment by gabeio** [comment]
I'm sorry but I believe this is not an issue that should be reported to this repository. `createApplication` is not part of this library and express does not have a property named `CookieOptions`.

Unless you have more information or more ways to reproduce this issue there is not much for us to do.

**Comment by dougwilson** [comment]
Yea, this module does not provide any typings.
