### ISSUE TITLE
Safari browser: New sessions when privacy option turned on

### ISSUE THREAD

**Issue by heldertb** [expressjs/session#355]
FYI: This is not actually an issue with session, it is however something that can put a lot of developers using Safari with their heads down.
Description:
When using the native macOS browser Safari you have the option of enabling a privacy feature called 'Ask sites to not follow me'
If this is turned on and you use req.session in your backend, a new session will be created every time a user would do a call to the backend, which causes lost data in your session data.

I don't know if this feature is only available in the latest beta of macOS Sierra or it is already available in older version too.
I just spent a few hours looking for why my session data stopped working.
Hope this helps other people.
On the other hand, this may be something that can be addressed if it is possible?

**Comment by dougwilson** [comment]
What are you using for your saveUninitialized setting? True or false? This should not be an issue if you use false, right?

**Comment by heldertb** [comment]
Haven't tried putting it on false. I'll try it later and let you know

**Comment by dougwilson** [comment]
No problem! I was assuming that whatever that Safari setting was was ignoring the `Set-Cookie` or something, causing every request to not have the session ID so a new session was generated and saved. The next major release the default behavior of this module will switch to `saveUninitialized: false` which is a better behavior, I think, but the module was built with the opposite behavior before the current maintainers

**Comment by heldertb** [comment]
Apparently that seems to be a good idea (:

**Comment by hareshstilyoapps** [comment]
Hello @dougwilson I am facing this same issue even though I have set `saveUninitialized: false`.

**Comment by dougwilson** [comment]
I'm sorry I don't have Safari browser, so no idea. Please submit a PR with a fix, thank you 🙏
