### ISSUE TITLE
Cookie name attribute is set at the wrong level

### ISSUE THREAD

**Issue by jordanrastrick** [expressjs/session#356]
Running 1.14.1. The [docs](https://www.npmjs.com/package/express-session) indicate that to set an alternative cookie name to `'session.id'`, you include an attribute `name` in the `cookie` object:

`app.use(session({
  cookie: {
    name: 'newName'
    ...
  }
  ...
}));`

However, this doesn't work. On inspection of the source, it is evident that - contrary to the docs (and I think intuition) - you have to set name at the outer level:

`app.use(session({
  name: 'newName'
  cookie: {
    ...
  }
  ...
}));`

**Comment by dougwilson** [comment]
Thanks for the feedback! I looked at the docs and I don't see where it says the `name` option goes in the `cookie` object. Can you elaborate on what we can do?

**Comment by jordanrastrick** [comment]
Under `cookie` it states that 

> The following are options that can be set in this object.

Attributes are then listed which can be set in the cookie object - `domain`, `expires`, `httpOnly` etc. `name` appears to be in this list, although actually now that I read the rest of the doc more closely it seems to be simply unclear where the the list of `cookie` attributes ends, unless I'm missing something.

I would expect the cookie name to be part of the `cookie` object - so personally I would suggest supporting passing name in either way (for backwards compatibility.) If not, make the docs clearer on when the list of `cookie` attributes ends, maybe by moving it to the end of the allowed `session` attributes. Indeed, this should probably happen anyway.

Cheers.

**Comment by dougwilson** [comment]
Please feel free to submit some PRs :)

**Comment by dougwilson** [comment]
Sorry, clicked on the comment + close instead of just the comment button :)
