### ISSUE TITLE
Session expiration does not auto refresh in each request

### ISSUE THREAD

**Issue by gordomium** [expressjs/session#357]
version: v1.14.1
store: redis

======

To auto refresh session in each request
- **A** should update redis TTL
- **B** should update cookie.expires in redis store
- **C** should set cookie.expires as `set-cookie` in headers

#### End a request without other middles
- **A** `fail`
- **B** `fail`
- **C** `fail`

#### Call `req.session.touch()`
- **A** `clear`
- **B** `clear`
- **C** `fail`

#### Modify `req.session` in each request
- **A** `fail`
- **B** `fail`
- **C** `clear`

Isn't `Session.save()` or `Session.touch()` no need to call?

======

This is the base middleware

```js
const session = require('express-session')
const RedisStore = require('connect-redis')(session)

const RedisClient = require('ioredis')

app.use(
  session({
    name,
    secret,
    cookie: {
       domain,
       maxAge: 7 * 24 * 60 * 60 * 1000
    },
    store: new RedisStore({ client: new RedisClient(config.redis) })
  })
)
```

**Comment by gabeio** [comment]
I believe you are looking for the option `rolling: true`.

**Comment by gordomium** [comment]
Thx, i missed this

**Comment by gabeio** [comment]
No problem! If you have any other issues don't be afraid to ask.
