### ISSUE TITLE
Set Cache-Control: private when session is active

### ISSUE THREAD

**Issue by YousefED** [expressjs/session#362]
When using express-session for user sessions, and returning different responses to different users (e.g. the example in the README), by default there is no Cache-Control header set.

This means there's a risk that caches / proxies in between return the wrong (cached) response to the wrong user. I think nearly all use-cases for express-session would need Cache-Control: private.

**Comment by dougwilson** [comment]
Hi @YousefED, perhaps you can outline a proposal for how this module would accomplish this, or even offer up a PR? We probably don't want to clobber anything someone else is setting in that header, and I'm sure there are people who want to add other directives like no-transform that may be in addition to private and is probably route-specific, so I suppose the implementation would need to gracefully handle all that, if you are up to it.

**Comment by YousefED** [comment]
My quick thoughts would be the following:
- On the requests where Express sends a set-cookie header, also set cache-control: private. I can't think of any reason why you wouldn't need this header on requests where you set the session cookie. I think not enforcing this would even open up security issues on many sites.
- For other pages, I agree the impact of setting the cache-control can be beyond what we want to achieve; we'd also affect pages that don't do anything with session information (not serving private content). Ideally, we'd still set the header on these pages, and recommend people to only use the session-middleware on pages where session information is actually used. Realistically, I understand this is not how most people set up express-session (they just do so for all routes), so it might not be the best approach at this moment. If we take this trade-off; I think we should at least stress the importance of cache-control headers in the documentation and examples.

**Comment by dougwilson** [comment]
Cool. What about how we should handle other directives and clobbering? Would you be willing to take a stab at implementing this in a pull request?

**Comment by YousefED** [comment]
I think setting my first point as an option defaulting to true (set cache-control, if not set already), should be enough. Middleware loaded after can still override the header of course.

Unfortunately, at the moment my time is very limited to implement this in a PR myself. When we have more development resources at the company I'm busy setting up we might be able to look into this.

**Comment by dougwilson** [comment]
That's ok, as I also don't have the time to :) so if you think there is enough information in here that someone can come and implement to your satisfaction, awesome! Otherwise feel free to add any other details in. I have a few more questions to help clarify for whoever comes by:

> set cache-control, if not set already

And if the cache control is set to public, should the module leave that as public?

**Comment by dougwilson** [comment]
Hi @YousefED I'm going to close this, as I haven't seen any interest in generating a PR, and I didn't really get any response to my previous question, so the issue seems stalled at a point I don't think anyone but you has enough information to really put together a PR. Please feel free to make one :)
