### ISSUE TITLE
Q: Different ports

### ISSUE THREAD

**Issue by trzyrazyzero** [expressjs/session#364]
Hi, i building app and i have my api on xx.xx.xx.xx:4444 and my site on xx.xx.xx.xx:4445.
On two ports there are same cookies, but only on my api port its display properly session id.
How to make it to work with two ports?

**Comment by dougwilson** [comment]
Hi @trzyrazyzero, yea, by the way cookies work, they will appear on both ports, as it pretty much only keys off the hostname and path (and sometimes scheme if you set it to only work over https). It's possible that each server has a different secret value, which would cause them not to trust the cookies set from each other. Can you provide the details on how you are currently setup?

**Comment by staminna** [comment]
I have two node instances of node-express running on my project  on difference express ports but when I login at the second, I am logged out of the previous logged in server. 
Can anyone help a but with a small snippet or link?

**Comment by joewagner** [comment]
@staminna Try using custom `name` options for your each of your projects 
https://github.com/expressjs/session#name

**Comment by staminna** [comment]
I set different names for each app but I can get from 127.0.0.1:8444 to 127.0.0.1:8443 but not the other way arround.

**Comment by joewagner** [comment]
@staminna when you say name, you mean you gave each app a different cookie name, i.e. not `connect.sid`

**Comment by staminna** [comment]
Affirmative Joewagner.

**Comment by joewagner** [comment]
@staminna not sure what the problem is then.  Can you provide a "sample app" that demonstrates the issue?

**Comment by staminna** [comment]
I am using MEAN.JS stack and [node-calendar-sync](https://github.com/jasonjoh/node-calendar-sync). I set different names for the cookies. It may be I need to set cookie.samesite or could it be both apps use slightly different Oauth methods for authentication?

**Comment by joewagner** [comment]
@staminna This module doesn't handle logging in or logging out, so its very difficult to say anything without an example.  If you want to create a small application with minimal dependancies that can be run to reproduce the issue, that would be ideal.
