### ISSUE TITLE
originalMaxAge might get in negative number when set both maxAge and expires

### ISSUE THREAD

**Issue by jackycute** [expressjs/session#365]
Hi guys!
We've encounter an issue that cause session expired immediately after creation.
And we found the cause is the `originalMaxAge` is a negative number in the DB.

I set both `maxAge` and `expries` in the config like below:
```
app.use(session({
    name: config.sessionname,
    secret: config.sessionsecret,
    resave: false, //don't save session if unmodified
    saveUninitialized: true, //always create session to ensure the origin
    rolling: true, // reset maxAge on every response
    cookie: {
        maxAge: config.sessionlife,
        expires: new Date(Date.now() + config.sessionlife)
    },
    store: sessionStore
}));
```
the `config.sessionlife` is `14 * 24 * 60 * 60 * 1000`
and I'm not sure if we setup correctly.

Thanks for helping us!

**Comment by jackycute** [comment]
confirmed that remove `expires` in the config would solve this issue.

**Comment by gabeio** [comment]
From the [docs](https://github.com/expressjs/session#expires) it's suggested to use maxAge.

> Note The expires option should not be set directly; instead only use the maxAge option.

And probably best to only use maxAge.

> Note If both expires and maxAge are set in the options, then the last one defined in the object is what is used.

**Comment by jackycute** [comment]
Oh I missed the first mention there.
Anyway I've changed to use maxAge now, everything works fine though.
Probably more specifically to say not set both them in docs?

**Comment by dougwilson** [comment]
> Probably more specifically to say not set both them in docs?

Yes, the docs say don't even set `expires`.

**Comment by jackycute** [comment]
True!
Well, I'm ok to close this issue.
