### ISSUE TITLE
overriding cookie maxAge

### ISSUE THREAD

**Issue by siacomuzzi** [expressjs/session#367]
Hi,

What's the proper way to override the cookie's maxAge? is the following code ok?

```
app.use(session({
  secret: 'keyboard cat',
  store: myStore,
  cookie: { path: '/', httpOnly: true, secure: true, maxAge: 60000 }
}));

app.use(function(req, res, next) {
  if (req.internals.customMaxAge) {
    // override cookie max age
    req.session.cookie.maxAge = req.internals.customMaxAge;
  }

  next();
});
```

is `store.touch` implementation mandatory in this case?

Thanks

**Comment by gabeio** [comment]
I really haven't ever needed to manually set it, from the docs it says `req.session.touch()` is the way you should be resetting the maxAge and also (depending on the store) extending the expire. But usually if you need to keep the session's maxAge at the configured maxAge constantly (every request) you can use `rolling: true` which is specifically for re-saving the session & resetting the maxAge.

**Comment by siacomuzzi** [comment]
Thanks. I'll try.

More context: I have a multitenant scenario where each tenant has the ability to specify his own maxAge

**Comment by dougwilson** [comment]
I'm going to close this issue since there hasn't been anything since, so I assume @gabeio suggestion worked :)!
