### ISSUE TITLE
No difference between resave: true/false and saveUninitialized: true/false?

### ISSUE THREAD

**Issue by hojas** [expressjs/session#372]
It seems that there is no difference `resave` is true or false and `saveUninitialized` is true or false ?

**Comment by JoeWagner** [comment]
@hojas the difference can sort of be boiled down to _Create_ vs _Update_

`resave` specifies whether you want to save a session on every request, even if it wasn't modified.  This is useful if you don't want to update your session store with objects that have not changed. 

`saveUninitalized` specifies whether you want to save a _new session_ for requests that don't already have a session, even if the session wasn't modified.  This is useful if you want to limit session creation to requests that actually add something to the session object.

hopefully that helps

**Comment by hojas** [comment]
@joewagner  `resave` is false, and the session wasn't modified, but the expires of session in MongooDB also updated every time. Even though the session not resaved repeatedly.

**Comment by joewagner** [comment]
@hojas your store may be updating the expire.  Is that a problem?
