### ISSUE TITLE
Hard to distinguish from <h4>, <h5> and <h6> on www.npmjs.com

### ISSUE THREAD

**Issue by kidlj** [expressjs/session#378]
It's better not to use h4, h5, h6 in `README.md` file, which serves as docs at this module's page on www.npmjs.com. See the screenshot:

![npmjs](https://cloud.githubusercontent.com/assets/300616/19775624/9986f116-9ca3-11e6-9c85-8ac3ebf8abe2.png)

**Comment by dougwilson** [comment]
Yea, sorry, meant to fix that from when #356 was filed :)
