### ISSUE TITLE
DeprecationWarning in node.js v7.0.0

### ISSUE THREAD

**Issue by c941010623** [expressjs/session#380]
when i use nodejs v7.0.0 and use this package and i use session store
i get the error:

DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.

how fix ??

**Comment by dougwilson** [comment]
Hi @c941010623 this module hasn't been updated yet to really support Node.js 7.x (since it just arrived a few days ago), so thanks for making us aware of this new deprecation! You can add `--no-deprecation` to your Node.js command line arguments to suppress the warning until we release an update.

**Comment by dougwilson** [comment]
Hi @c941010623 the only place in the code we are using the `Buffer` constructor is here: https://github.com/expressjs/session/blob/8e57b21bef0d53010c4d37f4beee3f0341f3eaa6/index.js#L284

That line is using `new`, so I'm not sure what you are seeing. Can you tell me from which line that deprecation warning is coming from for where we need to fix?

**Comment by dougwilson** [comment]
Ah, found it: it comes from our dependency `crc`. Someone will need to file an issue at https://github.com/alexgorbatchev/node-crc and we can upgrade it when a new version is published.

**Comment by dougwilson** [comment]
haha, nevermind! The PR https://github.com/alexgorbatchev/node-crc/pull/44 was submitted to that module and merged not too long ago. Now we wait for a npm release :)

**Comment by c941010623** [comment]
thank you very much ^^
