### ISSUE TITLE
Need update to crc 3.4.1 to quench node v7 DeprecationWarning

### ISSUE THREAD

**Issue by killroy42** [expressjs/session#382]
The current dependency of CRC v3.4.0 cause a DeprecationWarning in node v7 for the "New Buffer()" syntax. CRC have fixed this in 3.4.1, It seems just updating the dependency removed the warning.

**Comment by dougwilson** [comment]
Thanks for the heads up! I have already updated the crc dependency in master, so looks like this is already pending a release :)
