### ISSUE TITLE
express-session or cookie-session: security

### ISSUE THREAD

**Issue by tomek121** [expressjs/session#389]
Which method is much more safer when it comes to the security of data? Can anyone open/steal the cookie and get the session data? 

In my project I am using redirect instruction which reloads the page and thus deletes the input provided by user. In order to transfer the data between the pages and then render it again (for user convenience) I need to use either cookies (e.g. req.cookie.userStreet) or session (e.g. req.session.userStreet). As I know flash is using cookies - is it safe?

**Comment by gabeio** [comment]
This module does *not* store the session data in the cookie, it's stored in either memory or a [compatible database](https://github.com/expressjs/session#compatible-session-stores), and thus the security is solely dependent on how much info you pass to the user else where. where as the cookie-session is actually sending the session data back to the user inside the cookie and also is then limited to the [cookie's size limit](https://github.com/expressjs/cookie-session#max-cookie-size).

**Comment by dougwilson** [comment]
Yea, if you are asking about security of your data, this is the module you wait--in `cookie-session`, all the data is stored in the user's web browser, accessible to them, while this module stores all the data on the server, never being sent to the client.
