### ISSUE TITLE
Is it possible to limit the amount of simultaneous logins per user?

### ISSUE THREAD

**Issue by hbarcelos-revmob** [expressjs/session#394]
Currently we're willing to allow only one simultaneous login per user.

Is it possible to do it right now? If not, are you willing to accept a PR with this feature?

Thanks.

**Comment by dougwilson** [comment]
Since this module is just generic to session storage, regardless of even having a logical user, this module does not D this and it wouldn't belong in this layer.

**Comment by hbarcelos-revmob** [comment]
Yes, I understand that, but giving the possibility of customizing the cookie payload would make this possible. Without this, I cannot think a way of making this work.

**Comment by dougwilson** [comment]
I have never had an issue implementing one-session-per-user with this module as-is.

**Comment by hbarcelos-revmob** [comment]
Would you mind sharing an overall idea? Thank's.

Em ter, 6 de dez de 2016 22:00, Douglas Wilson <notifications@github.com>
escreveu:

**Comment by dougwilson** [comment]
When your user logs in, query your data store for all the sessions associated with that user. If there are any, either (1) invalidate them and continue log in or (2) deny the log in.
