### ISSUE TITLE
express-session slices end of json chunk buffer

### ISSUE THREAD

**Issue by nshahpazov** [expressjs/session#395]
In the index.js of express-session lines 290 and 291

```javascript
ret = _write.call(res, chunk.slice(0, chunk.length - 1));
chunk = chunk.slice(chunk.length - 1, chunk.length);
```

causes my tests to fail since it's returning a json with missing last character which is the closing bracket. I get an `Unexpected end of JSON input` because it's trying to parse a json without a closing bracket.

When I remove the `- 1` my json response is completely fine and has a closing bracket.

Is this a bug in express-session, where should I address this?

**Comment by dougwilson** [comment]
If this were a bug, this module would be unusable. Yes, it dies slice off the last char, but if you read more of the code, it will still write that char at a later time, completing the response.

Can you share all the following details:

1. Version of this module you're using.
2. Version of Node.js
3. Complete source code that reproduces the issue. It should be as minimal as you can get it to rule out other libraries causing issues.
4. Instructions on how to run your code to see the issue.

**Comment by nshahpazov** [comment]
I have dealt with the problem. Please feel free to close the issue :)

**Comment by Mactaivsh** [comment]
@dougwilson Hi, I was reading the source code. I am confused about this: 
``` js
ret = _write.call(res, chunk.slice(0, chunk.length - 1));
chunk = chunk.slice(chunk.length - 1, chunk.length);
```
Why is it necessary to split the chunk?

for example, if the chunk is `{ “msg”: "some-message"}` it will be slice into `{ “msg”: "some-message"` and `}` and send to the client by two times (which call the `_write` function twice)

why don't just send it to the client at once for good？

**Comment by dannyharding10** [comment]
> I have dealt with the problem. Please feel free to close the issue :)

@nshahpazov how did you fix this problem?
