### ISSUE TITLE
store.destory([sids], callback) would be nice

### ISSUE THREAD

**Issue by barisusakli** [expressjs/session#397]
So we don't have to write code like 

```
async.each(sids, function (sid, next) {
    db.sessionStore.destroy(sid, next);
}, next);
```

and hit the database multiple times.

If store.destroy accepts an array connect-redis can use `multi.del()` and connect-mongo can use `$in: sids`.

**Comment by dougwilson** [comment]
Session stores are free to define whatever extensions they want; this module just defines the methods it will call on the store.
