### ISSUE TITLE
Usage of properties named 'cookie' inside req.session

### ISSUE THREAD

**Issue by gustavohenke** [expressjs/session#398]
Hi!
I have a micro service architecture in my app, and I store the cookie ID of my auth server in `req.session.auth.cookie`. 
Therefore, it did not conflict with `req.session.cookie`, set by express-session.

I experienced a problem of a session not being updated, even though it did change.
However, what changed was that property `req.session.auth.cookie`.

I debugged thru the code of express-session, and found [this function](https://github.com/expressjs/session/blob/588d099/index.js#L579-L585) (I used the permalink in order to folks always hit the same lines of code):

```js
function hash(sess) {
  return crc(JSON.stringify(sess, function (key, val) {
    if (key !== 'cookie') {
      return val;
    }
  }));
}
```

This `hash` function is used to determine whether a session changed after the request finishes.  

By reading this code, one could think that it would ignore *only* `req.session.cookie` when calculating
the hash, right?

Well, think again.
Actually, the [replacer function of `JSON.stringify`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#The_replacer_parameter) is applied recursively.
This means that my `req.session.auth.cookie` is ignored, and my session is not updated.

I know that this is probably an edge case, but I think that documenting this behavior could save someone's else time (I spent ~4 hours on this myself).

What are your thoughts?
Thanks in advance!

**Comment by dougwilson** [comment]
Rather than document, it sounds like a legitimate bug. Would you be willing to make a PR to fix it to only ignore the top level cookie property?

**Comment by gustavohenke** [comment]
Sure.
I'll be sending the PR soon.
