### ISSUE TITLE
Save multiple session objects in MongoDB

### ISSUE THREAD

**Issue by bradware** [expressjs/session#402]
Right now I am building an API to support multiple users signing in, and creating session management for that with connect-mongo. 

What logic do I need to add to store a new document in the session collection when more than one user has created a session? None of the examples online show this logic piece, and right now if I login/register with multiple users, only 1 session document is created and it is just constantly overwritten in the sessions collection. Thanks!

Repo: https://github.com/bradware/moola-backend

**Comment by dougwilson** [comment]
I'm not sure I understand.  This is a session module, and it doesn't understand user sessions, just web browser sessions. Are you saying that in your repo, if you open a browser on computer A and log in with user 1, if you opened a browser on computer B, and logged in as user 2, it would override the user 1 session on computer A?

**Comment by bradware** [comment]
Oh wow, I thought the session would be based on user data, not the browser. I totally missed that.

So if I was testing my API through Postman, and creating different users, would it make sense for the session document in Mongo to be overridden by the second user logged in through Postman?

**Comment by bradware** [comment]
"Are you saying that in your repo, if you open a browser on computer A and log in with user 1, if you opened a browser on computer B, and logged in as user 2, it would override the user 1 session on computer A?"

No I was simply logging in and registering with different user credentials through Postman for testing. So that may be why it was being overriden in Mongo storage.

**Comment by dougwilson** [comment]
I may also be confused because I don't understand what documents / collections are or how mongo works.

**Comment by dougwilson** [comment]
Ok, if you are using the same browser, you are in the same session, since this module has no idea what a use login is, it just thinks you're trying to update a property in an existing session.

You can use the regenerate method to force a new session creation, of course.

**Comment by bradware** [comment]
Is there a way to simulate requests from different browsers with an application running locally?

**Comment by dougwilson** [comment]
> So if I was testing my API through Postman, and creating different users, would it make sense for the session document in Mongo to be overridden by the second user logged in through Postman?

Yes, since the session is associated with the browser, all those requests are the same browser. It is similar to how virtually every site works, where you cannot be logged in as two users at the same time for the same site in the same browser. For example, if you go to GitHub.com and log in, if you were to log in to another account with the same browser, the original login would in essence be replaced with the new user.

> Is there a way to simulate requests from different browsers with an application running locally?

You would have to manage the session cookies yourself in order to do that, instead of letting the browser manage them for you.

**Comment by bradware** [comment]
awesome, thanks for answering all of my questions!
