### ISSUE TITLE
Using for cors api server

### ISSUE THREAD

**Issue by EasonWang01** [expressjs/session#403]
Is it possible to using it for an express api server,that not render page?
Because res.cookie and req.session not working for api server.

**Comment by chrisHchen** [comment]
I think api server don't usually keep session, if you are looking for a way to keep session on a pure api server without implement any Store, maybe you can keep session information at an open store by calling its apis

**Comment by EasonWang01** [comment]
ok,but I was still wonder about that is express be able to use res.cookie to set cookie for client,even if the page is not rendered by that server.

**Comment by gabeio** [comment]
express session will set cookies even if no page is rendered BUT something has to be sent back. so even `res.send("ok")` is enough. That is not just express that has to do with http.

**Comment by EasonWang01** [comment]
```
Set-Cookie:rememberme=yes; Max-Age=900; Path=/; Expires=Wed, 28 Dec 2016 03:00:48 GMT
```
the response header has cookie but still not set cookie for the client side,so I guess express-session wil not work. 

Is `res.cookie` not working for api server?Or something get wrong

**Comment by gabeio** [comment]
> the response header has cookie but still not set cookie for the client side, I guess express-session will not work.

Yes expressjs/session requires the ability of the client to be able to handle cookies.

> And browser doesn't support read cookie from XHR.

You may need to add `xhr.withCredentials = true;` see https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials

**Comment by EasonWang01** [comment]
thanks!
