### ISSUE TITLE
Using session with ExpressJS client and server

### ISSUE THREAD

**Issue by porta8080** [expressjs/session#404]
Guys I created this question in StackOverflow because I wonder if it is possible to use the session feature if my client application is also a NodeJS Express.

http://stackoverflow.com/questions/41351242/cookies-handling-when-client-side-is-also-an-expressjs-app

Suppose client and server are two NodeJS apps, can I keep the session data between requests? How will server know about the session id?

**Comment by dougwilson** [comment]
Shat module are you using to make requests to the server? Typically just enable that module's cookie jar and you're done.

**Comment by joewagner** [comment]
@porta8080 Is this issue resolved?

**Comment by porta8080** [comment]
Yes. As explained in StackOverflow. Thanks for the support!
