### ISSUE TITLE
I guess what session is shared in browser.

### ISSUE THREAD

**Issue by greenfrog82** [expressjs/session#409]
I've developed two web apps. These two web apps are developed by Express which use exrepss-session and passport.js for authentication. And These two web apps have log-in page. 

Let's call these web apps each Parent and Child for this question.

I log in Parent in chrome. And I try to log in Child in chrome which is same web browser logged in Parent. Then I access Parent, I logged out. This situation is occured vise versa.

Why has this situation occured? I guess what session is shared in browser. 
How can I solve this problem?

**Comment by joewagner** [comment]
Can you elaborate on your setup?  Are both applications running under the same domain name?  Any chance of a working example?

**Comment by greenfrog82** [comment]
Above all, Thank u for your attention. 
This code is owned my company. So I can't open this code. But you wanna see this code, I will write sample code up to tomorrow. 
Before I write sample code, Please consider the follow information. 
I am running these web apps in same domain which is more exactly my development PC. If these web apps running on another web browser, Parent is running on chrome and Child is running on IE, This problem is not occurred.

**Comment by joewagner** [comment]
My pleasure helping out.
Some sort of example would probably help shed light on the issue, but I'll take a guess that you are sending a cookie set by App1 to App2 and vice versa.

**Comment by greenfrog82** [comment]
I will write sample code as soon as possible and I will see you sample code. 
Thank u for your help again!!
