### ISSUE TITLE
how can i get connect.sid value

### ISSUE THREAD

**Issue by xshua06** [expressjs/session#410]
because the client don\t support cookie, i want send connect.sid by res.json({'connect.sid': 'value'}) to client.

**Comment by gabeio** [comment]
currently expressjs/session only supports cookies. see #159.

**Comment by dougwilson** [comment]
The raw value is available in `req.sessionID` (https://github.com/expressjs/session#reqsessionid-1), though that is not the signed cookie value, though you can always calculate that yourself using your secret and the `cookie-signature` module.
