### ISSUE TITLE
Disabling the automatic session.save()

### ISSUE THREAD

**Issue by aayushijain23** [expressjs/session#411]
The scenario that I'm working on is as follows:
I have some session data along with a sessionID stored in dynamoDB. I do a get for fetching the session data and override request.session contents with that data, along with the sessionID as well. I store session related data along with the sessionID(the one that overwrites the generated sessionID) in dynamoDB explicitly. But I was unaware of the fact that session.save() gets called once the response is send from the server, which stores the modified contents with generated sessionID. Now I have duplicate records in dynamoDB. According to my need, I want to store the updated session contents with the sessionID I had used previously to store them and not with the newly generated sessionID that gets created with every session usage. Is there a way of disabling session.save() that gets called automatically at the end of a response? 

I might be going against the way a session is used. But this is my need. Can this feature be incorporated in the future? Or is there any other alternative?

Just an addition to the above mentioned issue: As per my need, I want express.session to work per session and not per call as it is behaving at the moment. Till the time the user's session is alive, I want all the modifications done to the session to be stored using the same session instance's id and not a separate one.

**Comment by joewagner** [comment]
Hi @aayushijain23 

What this module is designed to do is: 

1.  set and parse the cookie for the client
2.  create/read/update/delete the data for that client
3.  add an object to `req.session` that is mapped to your data store in part 2 above

it sounds like you have "home rolled" everything but handling the cookie.  Can you either drop the module all together, or let it handle the CRUD for your data store?

Alternatively, can you explore the [genid](https://github.com/expressjs/session#genid) option and find a solution?

**Comment by aayushijain23** [comment]
Hi @joewagner 
I used the module to set the cookie expiry.  I even performed CRUD operations on the data in addition to adding obejcts to request.session. I even used the genid option to generate a sessionID in the uuid4 format. All I wanted to do was update the contents of the already stored session and store the session with the same ID say '123' it was earlier stored with. But the updated session data gets saved using an ID say 'ABC' that gets generated when session is in use, courtesy of session.save().

**Comment by joewagner** [comment]
hmm, I'm not sure I understand your issue.  
Can you provide some code to explain?

**Comment by dougwilson** [comment]
I'm going to close this issue since there hasn't been a response.
