### ISSUE TITLE
Session not being saved on certain devices

### ISSUE THREAD

**Issue by DanielLuu** [expressjs/session#412]
Does not seem to be related to OS (iOS, android, windows) or device type (Mac, PC, etc.)   It seems to be on random devices the session isn't being stored into my database.  Using connect-pg-simple.

**Comment by dougwilson** [comment]
Hi @DanielLuu that's really weird. Any additional insight you can provide so we have a place to start to figure out a resolution? Any kind of code & instructions I can use to reproduce the issue?

**Comment by DanielLuu** [comment]
You can check out this specific commit.  I moved my session handling over to cookie-session for the time being since that seems to not have an issue.  I suspect it's something to do with the way heroku handles client calls.  Let me know if you see anything funky. https://github.com/UNAVSA/dotorg/blob/5a39a9a98ef63beaa4ad5fe790e8987ac6f64042/server/app.js

**Comment by dougwilson** [comment]
Nothing sticks out, unfortunately :(
