### ISSUE TITLE
session timeout vs cookie timeout

### ISSUE THREAD

**Issue by siacomuzzi** [expressjs/session#415]
Looks like the session and the cookie always expire together. We can't have a cookie last longer than the session?

This is the scenario I want to achieve:

> If the user remains active, the session will last no more than X days, but if not, the session will terminate after Y days.

Thanks.

**Comment by joewagner** [comment]
@siacomuzzi The store you are using will determine how long the session exists.  This module will handle the `set-cookie` header, which will determine how long until the cookie exists.

So if I understand your use case, you can set the `cookie.expires` option to "X" and set the TTL in your store to "Y".  Assuming your store implements `touch` the "Y" value will be moved forward if the user is active.  This also assumes you are using the default `rolling: false` option.

Will that work for you?

**Comment by siacomuzzi** [comment]
Thanks for the details. This is my configuration (I'm using [connect-mongo](https://github.com/jdesboeufs/connect-mongo/) as store):
```
app.use(session({
  secret:      'shhh',
  store:       new MongoStore({ db: dbInstance }),
  name:        'foo',
  resave:      true,
  saveUninitialized: false,
  cookie:      {
    path:       '/',
    httpOnly:   true,
    maxAge:     SEVEN_DAYS,
    secure:     true
  }
}));
```

[connect-mongo](https://github.com/jdesboeufs/connect-mongo/) has `options.ttl` but this is ignored if `session.cookie.expires` exists: https://github.com/jdesboeufs/connect-mongo/blob/master/src/index.js#L230-L231 (that's why both timeouts are always the same)

**Comment by joewagner** [comment]
I can't say for sure, as I haven't used `connect-mongo`, but I think you want to [disable session cleaning](https://github.com/jdesboeufs/connect-mongo#disable-expired-sessions-cleaning).  Then create your own TTL index based on your needs

**Comment by siacomuzzi** [comment]
I'll forward the question to `connect-mongo`, thanks!
