### ISSUE TITLE
Sessions not saved in iFrame

### ISSUE THREAD

**Issue by edeuxk** [expressjs/session#417]
Hello,

I'm running a website which is accessible by an iFrames and/or directly through the website.
And I have a problem with the iFrame because some of my clients are automatically logged out after login.
-> In fact they are not logged out, they automatically have a new session each time they access a new website page THROUGH the iFrame.

So I am guessing 2 things : 
- My middleware configuration is not right? (express-session, please check bellow) 
- Or is it in the browser client that I need to specify something?

Personally, I don't have this problem, because I am using the latest google chrome version, so sessions are correctly saved in my browser and in the server.

But some of my clients, probably using an older web browser with a tablet or PC, they have this problem.

So here is my configuration :

My session use in server.js using express-session middleware : 
```
 // Session use
 app.use(session({
 	secret: process.env.SESSION_SECRET,
 	resave: true,
 	secure: true,
 	saveUninitialized: true,
 	store: sessionStore
 }));
```
Personally I don't have this issue with my browser, it correctly store my session with the iFrame and the server recognize my session each time! Even if I'm in the iFrame or directly through the website.

By the way if you want my logic code : 

My logic in controller auth.js: 
```
/*
 * Methode POST pour la connexion d'un compte utilisateur
 */
 exports.postLogin = (req, res, next) => {
  req.assert('email', 'E-mail non valide.').isEmail();
  req.assert('password', 'Le mot de passe ne peut pas être vide.').notEmpty();
  req.sanitize('email').normalizeEmail({ remove_dots: false });

  const errors = req.validationErrors();

  if (errors) {
    req.flash('error', 'Entrez vos informations');
    return res.redirect('/connexion');
  }

  passport.authenticate('local', (err, user, info) => {
    if (err) {
    	return next(err);
    }

    if (!user) {
      req.flash('error', 'Mauvais mot de passe ou e-mail.');
      return res.redirect('/connexion');
    }
    req.logIn(user, (err) => {
      if (err) { return next(err); }
      req.flash('success', 'Vous êtes maintenant connecté(e).');
      res.redirect(req.session.returnTo || '/');
    });
  })(req, res, next);
};
```

My logic in passport.js : 
```
**
 * Sign in using Email and Password.
 */
 passport.use(new LocalStrategy({
  usernameField: 'email',
  passReqToCallback: true
}, function (req, email, password, done){

  var User = req.app.locals.models['Users'];

  User.findOne({where: {email: email.toLowerCase() || null}}, function(err, user){
    if (!user) {
      return done(null, false, { msg: 'E-mail introuvable' });
    }
    var CryptoJS = require("crypto-js");

    if (CryptoJS.enc.Base64.stringify(CryptoJS.HmacSHA256(password, user.salt)) === user.password){
      return done(null, user);
    } else {
      return done(null, false, { msg: 'Mot de passe invalide.' });
    }
  });
}));
```

**Comment by dougwilson** [comment]
This is a known issue especially if your iframe is a different domain name that the site that hosts the iframe. Various browsers will block cookies set by the iframe which of course means no session cookie can get set by the module, as the browser will silently drop it. Is that what you're seeing?

**Comment by edeuxk** [comment]
Yes the domain is different from the site that host the iFrame.
But is it possible to trick this?

I mean I am pretty sure that when you embed a youtube video with the iFrame, youtube recognize the user if he's connected or not even if the website URL is not the main URL youtube.com.

I changed my configuration for : 
` // Session use
 app.use(session({
 	secret: process.env.SESSION_SECRET,
 	resave: false,
    // cookie: {maxAge: (24 * 60 * 60 * 1000)},
 	saveUninitialized: true,
 	store: sessionStore
 }));
`

What do you think?

**Comment by dougwilson** [comment]
It may be possible, but I am not familiar enough to say. There is only so much you can do to what comes back from the cookie and I remember back when I worked at a help desk we had this issue with a web site and Safari and we had to help the users unblock third party cookies for it to work, but that was like 10 years ago.

**Comment by dougwilson** [comment]
Looking at http://www.google.com/search?q=cookie+iframe most suggestions seem to be that you can get old IE versions to accept the cookie by setting a P3P header that properly describes how you will handle user privacy and if it matches what a user accepts, IE will accept the cookie.

**Comment by edeuxk** [comment]
Hey thanks, I am guessing one thing, do I have to put this into the iframe header?

Or in the website including the iframe?
Thank you

**Comment by dougwilson** [comment]
I think http://labs.fundbox.com/third-party-cookies-with-ie-at-2am/ has the best write up from the sites in the prior link, because it explains that the solution for IE and Safari are different. I hope this helps!

**Comment by edeuxk** [comment]
I used p3p middleware to fix it.
