### ISSUE TITLE
Why `Max-Age` cookie attribute is not used instead of a hairy `Expires` attribute

### ISSUE THREAD

**Issue by Pavek** [expressjs/session#421]
To my surprise, I failed to find existing issue on that, so I keep wondering why `Max-Age` cookie attribute is not used instead of `Expires` as defined by [RFC6265](https://tools.ietf.org/html/rfc6265)?

I use a recommended `cookie.maxAge` option in my project, but still the cookie I see in unit tests has `Expires: <date>`.

I believe `Max-Age` was invented to solve an obvious issue with (historically older) `Expires` attribute: that is, dates on server and client generally don't match due to time zones. So, it is impossible to control on server how exactly client will interpret the date sent.

Also *please expire asap* command from server seems easier to do with `Max-Age=-1` (or any value, <=0, per [spec](https://tools.ietf.org/html/rfc6265#section-5.2.2)) than with `Expires: Thu 02 Feb 1970 12:34:3` (can you say that latter is correct at all?).

The only drawback I found is that [IE 6/7/8 do not support it](http://mrcoles.com/blog/cookies-max-age-vs-expires/). But most of us don't care anymore, right? For those who cares `Expires` can be send, additionally (unlocked by a settings flag?).

**Comment by dougwilson** [comment]
I mean, you found the reason: browser compatibility. There are even browsers that choke if you include both, so we only include expires. The expires includes the time zone, so being on different time zones is a non-issue.

**Comment by Pavek** [comment]
@dougwilson, thanks! I see timezones is not really an issue, but in general the clocks are not in sync (which might be an issue). Are you aware of any tests that prove that browsers incompatibility still remains nowadays? (just wondering)

More practical question: what is the recommended way to implement `logout` API call in terms of session closing and, especially, a *test* for it?

Perfectionist in me says implementation should be: destroy session (+ DB record) and cookie in browser. The cookie destroy part should probably looks like this (response): `Set-Cookie: _sid:deleted;Max-Age:-1`. I could test this cookie with `supertest` easily (with `Expires: <date-in-the-past>` it is not so easy, but ok too. That's why original question was born, actually.).

Unfortunately, I cannot find how to implement+test  *both* session and cookie destroy (in above terms):

1. if I do `req.session = null` (a documented way to destroy), in response I don't have `Set-Cookie`,  even with `rolling: true` option.
2. so, in order to test expired `Set-Cookie`, I opt to `req.session.cookie.maxAge = 0;`. But can this guaranty the session is really destroyed (and DB record too)?

**Comment by dougwilson** [comment]
Hi @Pavek you already listed the web browsers that have the issue. In fact the article you linked to even says:

> Unfortunately, none of the current versions of Internet Explorer support max-age, so if you want proper cookie persistence cross-browser, then stick to expires.

Which is exactly why we have stuck with Expires, not Max-Age.

Testing should be pretty straight forward using Webdriver or some similar technology that you are already using to test your UI. It is certainly beyond the scope of this module, and using Max-Age vs Expires would have no effect on any proper testing that is utilizing a proper cookie jar to validate cookies.

**Comment by Pavek** [comment]
@dougwilson, thanks for reply.

To contribute to this discussion, I found this pretty decent cookie compat table: https://inikulin.github.io/cookie-compat/
The situation in general is pretty bad  -- who knew Cookie is such a nut.. :)

One particular test case confirms that **no recent IE/Edge versions** support `"foo=bar; max-age=-1"` for cookie expiry.

**Comment by Pavek** [comment]
Here is presumably Edge's public 'feature request' page with votes: https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/7718688-support-for-cookie-max-age

I tried to vote but got `Exceeded API Limit` error :(

**Comment by dougwilson** [comment]
Thanks for that information, @Pavek , very helpful :)
