### ISSUE TITLE
Error: EPERM: operation not permitted

### ISSUE THREAD

**Issue by luckyqiao** [expressjs/session#424]
Hi! I use this module in my app. Sometimes it throws Error `"Error: EPERM: operation not permitted, rename '6iU7HYN8jOSY-Biqpv5uRZT_I-AAgTkA.json.1374059317' -> '6iU7HYN8jOSY-Biqpv5uRZT_I-AAgTkA.json'
    at Error (native)"`. Then my app will stop running, even I ran app as Administrator.
This is my environment:
- OS: Windows 7
- node version: 6.9.5
- express: 4.x

Thanks!

**Comment by dougwilson** [comment]
Hi @luckyqiao that error seems most likely to be coming from whatever store module you are using. Please report to the store module's issue tracker :)
