### ISSUE TITLE
TypeError: store.set is not a function at InternalFieldObject.ondone

### ISSUE THREAD

**Issue by pfjare** [expressjs/session#429]
Getting this error  when I try to use store functions

```
store.set(req.sessionID, req.session, function(err) {
      ^

TypeError: store.set is not a function
       at InternalFieldObject.ondone
```

This is my setup

```
var store = new session.MemoryStore();

var serveSession = session({
  genid: function(req) {
    return uuid.v4();
  },
  secret: 'CLx2wWpEJ94KV8Fw4ewVhRzU',
  resave: false,
  saveUninitialized: false,
  store: store
});

```

**Comment by dougwilson** [comment]
Hi @pfjare I see you closed the issue, so I assume you were able to work out the solution. Please feel free to documentation the solution here in case someone else stumbles into the same issue :)

**Comment by pfjare** [comment]
Yep all good. It was just a misunderstanding on my part on how the session store worked.
