### ISSUE TITLE
How to update the session data querying by a specific field-value pair?

### ISSUE THREAD

**Issue by IonicaBizau** [expressjs/session#430]
http://stackoverflow.com/q/42230240/1420197

Thanks!

**Comment by dougwilson** [comment]
Hi! The way in which you would do this ultimately depends on the underlying store module you are using, as there is no interface to do that in here. Feel free to ask on the issue tracker for the store you are using 😊

**Comment by IonicaBizau** [comment]
Oh, thanks!

I opened a new issue here: https://github.com/jdesboeufs/connect-mongo/issues/256
