### ISSUE TITLE
override TTL for a given document

### ISSUE THREAD

**Issue by bwyss** [expressjs/session#431]
I would love to see the ability to update the ttl expiration on a per document basis.

**Comment by dougwilson** [comment]
Hi @bwyss can you give an example of what you mean or even a PR? We don't have anything in this module called "TTL" so I'm just trying to understand what the request means :)

**Comment by bwyss** [comment]
I am setting my sessions to have a maxAge of 15 minuets. After 15' of inactivity the user is logged out - as their session expires (expected behavior).  However, if the user shows activity, I would like to change the Time-To-Live (TTL) of the session expires index (per document).

**Comment by dougwilson** [comment]
Hi @bwyss I gotcha. So what do you want to update it to? In your example, this module will automatically extend the session with activity based on your settings. Is it possible this module can already do the feature you're requesting? I'm still not 100% sure what you're asking for, so not sure. Is it possible you can make a PR?

**Comment by dougwilson** [comment]
I guess in other words, does the `rolling` option (https://github.com/expressjs/session#rolling) implement what you're looking for? If not, in what way is it different / what would need to be added to fit your use-case?

**Comment by bwyss** [comment]
@dougwilson ooooooh, I missed that option, yes, that is exactly what I need Thank you!!
I says "Force a session identifier cookie to be set on every response."
A 'response' in this case is every time the client passes the JWT token to the server and it is validated? - which would occurs on every endpoint call.

**Comment by dougwilson** [comment]
I'm not sure; this module doesn't support JWTs or tokens, so I'm not sure if you're using something on top of this module and how the option would come into play with what you're doing without more information.

**Comment by bwyss** [comment]
Oh, sorry, I'm getting my modules crossed. Short answer, this is exactly what I was looking for, thanks!

**Comment by dougwilson** [comment]
Awesome, no problem!
