### ISSUE TITLE
TypeError: option expires is invalid

### ISSUE THREAD

**Issue by spencer-rig** [expressjs/session#432]
#Hi,
I noticed a slight problem in trying to get my cookies to have the proper expiry.

Here's the config I'm starting with:
```js
server.use(session({
  store: new pgSession({
    pg: pg,
    conString: Config.connectionString,
    tableName: 'session'
  }),
  secret: Config.session.secret,
  resave: false,
  saveUninitialized: false,
  cookie: { httpOnly: true, secure: Config.session.secure}
}));
```

- When I set `cookie.maxAge` to an integer, the cookie ends up with that integer in `cookie.originalMaxAge` **and** in `cookie.expires` (this triggers the `option is invalid` error--`cookie.expires` should contain a Date).
- When I set `cookie.expires` to a Date, the cookie never even reaches the store.

Am I missing something? Some other way to set a cookie's max age or expiration date?

**Comment by dougwilson** [comment]
Hi @spencer-rig that's weird, because almost every single test in our test suite sets the `cookie.maxAge` option, so I don't think any tests would pass if it caused an error. Perhaps there is something going wrong in your setup? Can you provide all the following?

1. The full stack trace for the error message you put in the title.
2. The version of this module you're using
3. The version of Node.js you're using

Thanks!

**Comment by spencer-rig** [comment]
I just now realize that perhaps I'm setting `maxAge` to a string...

My node version is v6.9.0. Dependencies in my package.json:

```
"bluebird": "^3.4.7",
"connect-pg-simple": "^3.1.2",
"dotenv": "^4.0.0",
"express": "^4.14.1",
"express-flash": "0.0.2",
"express-session": "^1.15.0",
"github": "^8.1.1",
"lodash": "^4.17.4",
"passport": "^0.3.2",
"passport-github2": "^0.1.10",
"pg": "^6.1.2",
"pg-query": "^0.11.0",
"pug": "^2.0.0-beta11"
```
The record in my pg store:
```
OuLpY4VWT4vCF4Yto41dRHFQdIPK1LNo | {"cookie":{"originalMaxAge":"1209600000","expires":"1209600000","secure":false,"httpOnly":true,"path":"/"},"passport":{"user":{"username":"spencer-rig"}}} | 2017-02-22 15:23:13
```

And the stack trace: 
```
TypeError: option expires is invalid
    at Object.serialize (/Users/spencer/Sites/devops/mamoswine/node_modules/cookie/index.js:145:13)
    at setcookie (/Users/spencer/Sites/devops/mamoswine/node_modules/express-session/index.js:636:21)
    at ServerResponse.<anonymous> (/Users/spencer/Sites/devops/mamoswine/node_modules/express-session/index.js:242:7)
    at ServerResponse.writeHead (/Users/spencer/Sites/devops/mamoswine/node_modules/on-headers/index.js:46:16)
    at ServerResponse._implicitHeader (_http_server.js:157:8)
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:446:10)
    at writetop (/Users/spencer/Sites/devops/mamoswine/node_modules/express-session/index.js:290:26)
    at ServerResponse.end (/Users/spencer/Sites/devops/mamoswine/node_modules/express-session/index.js:338:16)
    at ServerResponse.redirect (/Users/spencer/Sites/devops/mamoswine/node_modules/express/lib/response.js:899:10)
    at complete (/Users/spencer/Sites/devops/mamoswine/node_modules/passport/lib/middleware/authenticate.js:248:26)

```

**Comment by spencer-rig** [comment]
Ok yes. It was a string. If I make sure it's an integer then everything works as expected. Sorry for the alarm!

**Comment by dillondoyle** [comment]
I'd like to add a similar not about problem I had. When I set both maxAge and expires with ints, it errors and doesn't create cookie. I'm using version 0.3.1

Here is code:
```
res.setHeader('Set-Cookie', cookie.serialize('f_jwt', String(res.locals.built_jwt.token), {					
   httpOnly: true,		
   path: '/',		
   expires: 31536000,				
   maxAge: 31536000,		
   sameSite:'strict',		
   secure:true,			
   domain: 'domainhere.com'	
}));
```

`TypeError: option expires is invalid at Object.serialize (/srv/node_modules/cookie/index.js:145:13) at write_res (/srv/action.js:2223:41) at Layer.handle [as handle_request] (/srv/node_modules/express/lib/router/layer.js:95:5) at next (/srv/node_modules/express/lib/router/route.js:137:13) at write_user_row_to_bq (/srv/action.js:2007:2) at Layer.handle [as handle_request] (/srv/node_modules/express/lib/router/layer.js:95:5) at next (/srv/node_modules/express/lib/router/route.js:137:13) at write_event_work (/srv/action.js:1977:2) at Layer.handle [as handle_request] (/srv/node_modules/express/lib/router/layer.js:95:5) at next (/srv/node_modules/express/lib/router/route.js:137:13)`

I was able to get the cookie to write by removing expires from options and only using maxAge
