### ISSUE TITLE
Unable to write to the stream using the reference stored in express-session

### ISSUE THREAD

**Issue by rahul-desai3** [expressjs/session#433]
In my project, I am uploading a huge file of few GBs to the server, in chunks - 10MB chunk at a time, using the [blueimp jQuery-File-Upload plugin](https://github.com/blueimp/jQuery-File-Upload). 

I have a `writeStream` at the Node.js backend attached to a [express-session][1], just so the file uploads from 2 different users do not get messed up. I create a `writeStream` for every upload and attach it to the session.

*The problem is that*, when the first data chunk is received at the backend, the `writeStream.write` is not found in the session.

**Relevant part of my Node.js / Express.js code:**

    // session config:
    expressApp.use(session({
        genid: function(req) {
            return uuidV1();
        },
        secret: '***',
        resave: true,
        saveUninitialized: true,
        cookie: { secure: false }
    }));

    // create writeStream
    expressApp.post('/createStream', function(request, response) {
    
        request.session.wstream = fileSystem.createWriteStream(uploadsDirectoryLocation + '/' + request.body.fileName);
    
        request.session.wstream.on('finish', function() {
            console.log('*********************************** file has been written ***********************************');
        });
    
        response.send({ response: 'success' });
    
    });

    // on every chunk received, write to the stream
    expressApp.post('/uploadFile', function(request, response) {
    
        var size = 0;
    
        console.log(request.session.wstream);  // the attached 'wstream' does show up

        request.on('data', function(data) {
            size += data.length;
    
            request.session.wstream.write(data);  // app crashes here
    
            console.log('Got chunk: ' + data.length + ' total: ' + size);
            console.log('data', data);
        });
    
        request.on('end', function() {
            console.log("total size = " + size);
            response.send("response");
        });
    
        request.on('error', function(e) {
            console.log("ERROR: " + e.message);
            response.send("response");
        });
    
    });
    
    // close the stream
    expressApp.post('/closeStream', function(request, response) {
    
        request.session.wstream.end();
    
        response.send({ response: 'success' });
    
    });

The exact error is:

            streamObj.wstream.write(data);
                             ^
    
    TypeError: Cannot read property 'write' of undefined

***However***, If am not attaching the `writeStream` to the session and keeping it global, it does work. But, breaks for different sessions, obviously.

What am I doing wrong here?  How do I fix this?

  [1]: https://github.com/expressjs/session

[Same question posted on StackOverflow.](http://stackoverflow.com/questions/42447175/unable-to-write-to-the-stream-using-the-reference-stored-in-express-session)

**Comment by dougwilson** [comment]
The reason is that the data in `req.session` is saved to the database using `JSON.stringify`, and functions cannot be represented in there. You can only store simple values like numbers and strings in `req.session`, not complex functions, unfortunately.

**Comment by dougwilson** [comment]
I don't think this is really stated in the docs, so should get it in there :)
