### ISSUE TITLE
Can not read session cookies

### ISSUE THREAD

**Issue by kimvex** [expressjs/session#437]
Hello I have a problem when I save a session and then I want to use that cookie in a path, the session object is empty.

my code
```js
    this.app.use(session({
      secret: process.env.SEC,
      resave: false,
      saveUninitialized: false,
    }));
```

I add the data

`sol.session.name = correo;`

  `sol.session.cookie.expires = moment().add(14, 'days').unix();`

If I make a console.log after adding the data shows me the information as well

```
Session {
  cookie:
   { path: '/',
     _expires: 1490340284,
     originalMaxAge: 1490340284,
     httpOnly: false,
     secure: false },
  name: 'chomi@kimvex.com' }
```

But if I try to enter a route and require the session data, I get an empty object

```
Session {
  cookie:
   { path: '/',
     _expires: null,
     originalMaxAge: null,
     httpOnly: false,
     secure: false } }
```

Make a search and I found that I am not the only one with that problem but in places where other people with the same problem asked did not give them an answer that would work

[http://stackoverflow.com/questions/42604372/express-session-undefined](url)
[http://stackoverflow.com/questions/42663278/unable-to-read-session-cookies-due-to-express-session](url)

**Comment by dougwilson** [comment]
Hi @kimvex it's possible there is an issue with your code, especially your assignment to the `.expires` property; that needs to be a `Date` object, not a number (documentation https://github.com/expressjs/session#cookieexpires).

**Comment by kimvex** [comment]
@dougwilson Make the change for Date and continue with the same problem, the session disappears when I upload the page or try to access another.

**Comment by dougwilson** [comment]
Hm, weird. I would love to take a look. Can you provide the following?

1. The version of Node.js you are using
2. The version of this module you are using
3. Complete code of a server I can run to reproduce the issue. Try not to use any other modules, but if you need to, please state the versions you're using.
4. Complete instructions for how to reproduce the issue using the code you provided. Please Note anything you think may be relevant like the browser you're using.

Thank you!

**Comment by kimvex** [comment]
Node v6.9.1
express-session v1.15.1

`'use strict';

/*
  Modulo para iniciar sesion
*/

const schema  = require('../models/db/schema');
const session = require('express-session');
const moment  = require('moment');

class Login {
  constructor(config = {}){

    let {correo, pass, res, sol, next} = config;
    let hour = 3600000;

   schema.users.findOne({correo: correo})
      .then(data => {
        if(pass == data.pass){
                  sol.session.name = correo;
                  sol.session.cookie.expires = new Date(Date.now() + hour);
                 return res.status(200);
                 console.log(sol.session);
        }else{
           return res.status(201);
        }
      })
      .catch(err => {
        if(err) throw err;
      });

  }
}

module.exports = Login;`

In the express configuration

`    this.app.use(session({
      secret: SECRET,
      resave: false,
      saveUninitialized: false,
      cookie: {
          httpOnly: false,
          secure: false
      }
    }));`

The problem occurs when reloading the page, the session is lost. Something curious is that after I store the cookies I make a console.log () and it shows me the cookie with the data that I gave, but when reloading the page that data is lost.

`   schema.users.findOne({correo: correo})
      .then(data => {
        if(pass == data.pass){
                  sol.session.name = correo;
                  sol.session.cookie.expires = new Date(Date.now() + hour);
                 return res.status(200);
                 console.log(sol.session);
        }else{
           return res.status(201);
        }
      })
      .catch(err => {
        if(err) throw err;
      })`

**Comment by dougwilson** [comment]
Thanks, @kimvex ! I would love to take a look and what is happening. Can you provide the following?

1. Complete code of a server I can run to reproduce the issue. Try not to use any other modules, but if you need to, please state the versions you're using.
2. Complete instructions for how to reproduce the issue using the code you provided. Please Note anything you think may be relevant like the browser you're using.

Thank you!

**Comment by kimvex** [comment]
Here is the code in my repository, do not use many external modules to make testing easier, the server information is displayed in the terminal.

Use mongodb and create a db called login, inside create a collection called users to which you will be passed two data email and pass (as well as email and pass)

Example: db.users.save ({email: 'kimvex@kimvex.com', pass: '1234'});

mongo version 3.4.0

Browser: Opera 43.0.2442.1165 

Used modules:

    "body-parser": "^1.17.1",
    "cors": "^2.8.1",
    "express": "^4.15.2",
    "express-session": "^1.15.1",
    "helmet": "^3.5.0",
    "mongoose": "^4.8.7",
    "nunjucks": "^3.0.0"

Respository: [https://github.com/kimvex/express-session-test](url)

**Comment by dougwilson** [comment]
Thanks, @kimvex ! It would be awesome if it didn't need mongo to run, since I have to spend some time setting that up and have never used it, so if it's not possible to remove that requirement, please give me a lot of time to look at it. Also, I still need you to provide:

> Complete instructions for how to reproduce the issue using the code you provided.

**Comment by kimvex** [comment]
@dougwilson Of course, update the code where you do not use mongo and simulate the event and also pass the replica instructions.

**Comment by kimvex** [comment]
repository updated https://github.com/kimvex/express-session-test

step 1:

run project and ingrees to http://localhost:3000 o http://localhost:3000/login

step 2:

Ingress email and password and watch the terminal for response of server.

step 3: 

click into "Into profile if add correct email and password" and watch the terminal for response of server.

In this step you should pass to http: // localhost: 3000 / profile because the session is started and the cookies are set.

The problem is that as cookies are not saved we are redirected to the home and cookies do not exist

**Comment by dougwilson** [comment]
Hi @kimvex I'm working through your instructions now.

**Comment by dougwilson** [comment]
Hi @kimvex the issue here is that your app is actually just broken; the login request never actually sends and response to the web browser, and just hangs. This means that no cookie is ever set in the browser. The fix is change the line https://github.com/kimvex/express-session-test/blob/master/app/website/controllers/login.js#L58 to `res.sendStatus(200)` to actually send the response instead of letting it hang.

I hope this helps! It turned out to not be an issue related to this module at all :)

**Comment by kimvex** [comment]
@dougwilson Hello thank you very much for the support shown. A few days ago I found the solution and forget to answer that I had already achieved it. The problem was not in express-session but in the headers of fetch that lacked some specifications.

**Comment by aliabbasjaffri** [comment]
@kimvex can you provide here what the problem was and how did you solve it? Because i am running into something similar.

**Comment by kimvex** [comment]
Hello, sorry I do not remember very well how the problem was going, but because of what I read and when seeing a project of the same dates, it seems that when I sent the data from frontend I was not sending certain parameters, as in the case of credentials. And it seems that it only happened to me with the use of the `Fetch` method.

I think this was the way to solve it, there was a little bad code but it is an example:

```javascript
let myHeaders = new Headers({
      'Accept': 'application/json',
      'X-API-Key': 'foobar',
      'Content-Type': 'application/json'
    });

    fetch('http://localhost:3000/profile', {
      method: 'GET',
      credentials: 'same-origin',
      headers: myHeaders
    })
```
