### ISSUE TITLE
node session quit 

### ISSUE THREAD

**Issue by janithapm** [expressjs/session#440]
I'm using express-session and cookie-parser in my node application when user login, req.session is added the userid  . when i refresh the browser, loss the  added user information in session .what is the mistake i have done?
[router.js.docx](https://github.com/expressjs/session/files/835632/router.js.docx)
[app.js.docx](https://github.com/expressjs/session/files/835633/app.js.docx)

**Comment by dougwilson** [comment]
Hi @janithapm can you provide what the information is in those fires directly here? With those formats a common attack vector + your account being brand new, I'm not comfortable opening them.

**Comment by dougwilson** [comment]
Hi @janithapm I'm going to close this since I haven't heard anything back.
