### ISSUE TITLE
session.touch() doesn't seem to do store.touch()

### ISSUE THREAD

**Issue by ile** [expressjs/session#442]
Hi,

Why is it that this function: https://github.com/expressjs/session/blob/master/session/session.js#L47-L49

... doesn't look more like this:

```js
Session.prototype.touch = function(){
  this.resetMaxAge();

  if (typeof this.req.sessionStore.touch === 'function') {
    this.req.sessionStore.touch(this.id, this);
  }

  return this;
};
```

i.e. touch also the session in store?

**Comment by dougwilson** [comment]
Hi @ile good question, I'm not sure. It may have been overlooked when session touch support was added. I'm not sure if it's possible to add that in now in a backwards-compatible way, though. Thoughts?

**Comment by ile** [comment]
Hey.

I don't know either. Maybe someone else (@tj?) has some ideas? Or maybe the change could be put in the next major version, not sure. 

I guess I will have to fork and use that fork, for now.

**Comment by dougwilson** [comment]
Closing because no follow up and I'm not clear on what exactly is supposed to be done here. Perhaps an outline of the ask or even a PR 👍
