### ISSUE TITLE
app.use() requires middleware functions

### ISSUE THREAD

**Issue by felixfong227** [expressjs/session#446]
![image](https://cloud.githubusercontent.com/assets/13918481/24197517/e5cd93d4-0f3c-11e7-81bf-4561746b12da.png)

```javascript
const cookieParser = require('cookie-parser');
const bodyParser = require('body-parser');
const session = require('express-sessions');
// Never trust your user input ;)
const escapeHtml = require('escape-html');

// For the AJAX call
app.use(cors());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({
    extended: false
}));
app.use(cookieParser());
app.use(session({
    secret: 'password'
    ,saveUninitalized: true
    ,resave: true
}));
```

**Comment by dougwilson** [comment]
Hi @felixfong227 sorry to hear you're having issues. In the code you posted above, the reason you're having trouble is probably because you made a typo in the module's name. This module is `express-session`, but your require statement is loading `express-sessions`.

**Comment by felixfong227** [comment]
I have one more question, and for now my session(SQL) is work fine with the `app` keyword, but I'm having a new problem if I'm trying to use `req.session` at my router, and the hole `req.sessino.userInfo`  will return `undefined`  thanks

**Comment by namannjain** [comment]
Im having a similar issue like @felixfong227 . Hey, @dougwilson actually I did ' npm install express-sessions' and not 'npm install express-session' and it worked fine. But, at the time of app.use() , it says app.use() requires a middleware function. My code is similar to the one above.
