### ISSUE TITLE
"set-cookie" can't work in  line 643  of  "index.js"  otherwise you modify  "set-cookie" to "Set-Cookie"

### ISSUE THREAD

**Issue by fruit5566** [expressjs/session#449]
index.js ->line 643 ：  res.setHeader('set-cookie', header)  can't work in Chinese version of UC browser
在UC浏览器的兼容模式下，“set-cookie”会失效，如果改成”Set-Cookie”就好了，Set-Cookie(首字母大写)是node的标准写法。

Click the lightning icon   on the right of the address bar  to change it to a 'e' icon
点击地址栏右边的闪电图标 可以切换浏览器的极速模式和兼容模式

 the browser download-link http://pdds.ucweb.com/download/newest/UCBrowser/zh-cn/101/999/www

**Comment by dougwilson** [comment]
Hi @fruit5566 I'm not sure I understand your issue, mainly because a lot of it is not in English. HTTP header names are case-insensitive.

**Comment by dougwilson** [comment]
We'll set it as `Set-Cookie`, so if your Node.js version picks up the casing then it should work.
