### ISSUE TITLE
why session lost some parameter when I get req.session again

### ISSUE THREAD

**Issue by jyunhan** [expressjs/session#450]
Hi, I use express-session into my project in login module, which is testing now.
We integrated this project in 4 different computer.
it's good working in 3 of them.
but the other has a problem:
**the session lost some info when I try to detect session from request again**

this server can regenerate session as well as got all session parameters in first request,
but when this server try to detect session by new request, it lost some parameter

**scenario is:**
1. User login the platform via /login2platform
The router will check the req.query, regenerate session, and redirect to homepage (/)
This time, we can get session completely.
2. Then, we refresh this page or go to another page(/productManagement), we found server lost req.session.accesstoken.

how can I fix this problem?

[here is the console](https://lh3.googleusercontent.com/-FAR7nwCFGaU/WOw_23s9flI/AAAAAAAAATc/OW_jqT62u843fXO7vR1hQk2XWZ0P_oZHgCL0B/h492/print%2Bscreen.png)

and the follow is my code:

= =[app.js]= =
```js
app.use(session(
        {
            name: 'om.connect.sid',
            secret: 'omsystem power by LIOU"s team',
            saveUninitialized: false,
            resave: false
        }
    ));
```
= =[pagecontroller.js]= =
```js
var express = require('express'),
    router = express.Router(),
    restAuth = require('./restAPI/auth.js'),
    restUser = require('./restAPI/user.js');

router.get('/login2platform', restAuth.loginValidation, function(req, res, next) {
    return res.redirect('/');
});

router.get('/', restUser.userValidation, function(req, res, next) {
	res.render('reportManage', { title: 'SJM System' });
});

router.get('/productManagement', restUser.userValidation, function(req, res, next) {
	res.render('productManagement', { title: 'SJM System' });
});
```
= =[auth.js] = =
```js
loginValidation = function(req, res, next){
    var wrongURL = properties.get('wrong.url');
    if(!(req.query.hasOwnProperty('clientID') && req.query.hasOwnProperty('accesstoken') && req.query.hasOwnProperty('expiry'))){ 
        return res.redirect(wrongURL);
    }

    req.session.regenerate(function(err) {
        if(err){
            console.warn(colors.red(err));
            return res.redirect(wrongURL);
        }
        
        req.session.userID = req.query.clientID;
        req.session.accesstoken = req.query.accesstoken;
        req.session.cookie.expires = new Date(Date.now() + Number(req.query.expiry));
        res.locals.isLegal = true;
        return next();
    });
};
```
= =user.js= =
```js
userValidation = function(req, res, next){
    var wrongURL = properties.get('wrong.url');
    if(req.session.hasOwnProperty('userID') && req.session.hasOwnProperty('accesstoken')){ return next(); }

    return res.redirect(pentaURL); 
};
```

**Comment by kirankashalkar** [comment]
I see the same issue.
I have tried session.save and session.reload to ensure that the properties saved on the session are correct, but it seems there is some issue.
I see the values different in req.sessionStore.sessions vs. req.session.

e.g.
`
JSON.parse(sessionStore['sessionId']).projectId => "someproj"
`
vs.
`
req.session.projectId => "default"
`

**Comment by dougwilson** [comment]
I tried to piece together the snippets but wasn't able to reproduce. Can you provide all the following?

1. The version of this module
2. The version of Node.js
3. Complete code I can run and reproduce the issue with
4. Instructions for how to run the code and the steps to cause the issue

**Comment by kirankashalkar** [comment]
Here's how my code is arranged:

Module 1:
```
function saver(req, projectId) {
    return new Promise(function(resolve, reject) {
        req.session.projectId = projectId;
        req.session.save(function(err) {
            if (err) {
                console.log('Error saving session to store', err);
                return reject({}); // some error object
            }
            return resolve ({}); // some success object
        });
}
```

Module 2:
```
function reloader(req) {
    return new Promise(function(resolve, reject) {
        req.session.reload(function(err) {
            if (err) {
                return reject({}); // some error object
            }
            console.log(req.session.projecId); // sometimes differs that what is saved in saver
            console.log(JSON.parse(req.sessionStore.sessions[req.session.id]).projectId); // is always correctly reflected as per set by the saver
            return resolve({}); // some success object
        });
    });
}
```

Main module:
```
// Load Module 1.saver as an express POST route handler to update projectId
// Load Module 2.reloader as an express GET route handler to get projectId
```

Finally, call APIs from POSTMAN or any other tool that does REST/HTTP.

**Comment by jyunhan** [comment]
Our, and .

I has made this project lightly, just reserve view control and session related function.
and built at "that special computer".
We found the situation has been resolve, all session info are collected.

so weird...

We are using npm and express, and using command line "npm start" to launch.

OS: windows7 64bit
express-session: 1.15.2
Node.js v6.9.4

I can't reproduce this situation either.... 
In the lightly version, session in all server are working well.
but when I switch to production version, the situation happened again... 
I'm stuck ...  lol

**Comment by jyunhan** [comment]
@kirankashalkar @dougwilson 

thanks for your suggestion.
I adjust the login flow to avoid this problem

here is what I do:
To change /login2platform to a page url from a rest API
and call login API while page render via front-end.
then, change redirect comment into location.hreft.

Although, I resolve the login flow,
I still no idea why session lost info after res.redirect.
It seems a legacy problem, not only appear in [nodejs](http://stackoverflow.com/questions/33340996/session-lost-after-redirect), but [php](http://stackoverflow.com/questions/35237488/php-session-variables-lost-after-redirect), [ASP.net](http://stackoverflow.com/questions/33275913/session-lost-after-response-redirect)... (maybe?)

I also found some related article that suggest **DO NOT REDIRECT AFTER SESSION SETTING**,
so here is the reason why I change the design way.

**Comment by dougwilson** [comment]
Thanks for the follow up !
