### ISSUE TITLE
return nothing when I read the sessions

### ISSUE THREAD

**Issue by Thinkdiff** [expressjs/session#451]
I'm using mongo-connect for storing my session data.
## This is my session config:
```
app.use(session({
     secret: config.secureHasherKey ,
     resave: false,
     saveUninitialized: false ,
     store: new MongoStore({ mongooseConnection: connection }) ,
     cookie:{
        secure: false ,
        httpOnly: false
     }
}));
```
It stored session perfectly but can not read it.
##  This is my store database value:
```
{ 
    "_id" : "ceF8BERpvE6O-M7l_rp_lL7D0tfMP8Mi", 
    "session" : "{\"cookie\":{\"originalMaxAge\":null,\"expires\":null,\"secure\":false,\"httpOnly\":false,\"path\":\"/\"},\"auth\":\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dlZEluIjp0cnVlLCJ1c2VybmFtZSI6InJlc2VsbGVyIiwiZW1haWwiOiJhc3AuMjA3M0BnbWFpbC5jb20iLCJfaWQiOiI1OGU2MmYxODY1YWZlNjQ1MzAxOTgzYjUiLCJpcCI6IjE4NS4xMi40NC4yNDgiLCJsYXN0bG9naW4iOiIxNDkyNjkyMDYzMDE3IiwiY3JlZGl0IjoxOTk5ODkxMjAsIm93bmVyX2lkIjoiNThlNjJmMTg2NWFmZTY0NTMwMTk4M2I1Iiwic3RhdHVzIjozLCJyb2xlIjo0LCJkbnMiOiJpcHR2LmlwdHZzdGFjay5jb20iLCJwcm92aWRlcl9pZCI6Imh0dHA6Ly8xMjcuMC4wLjE6MzcwMCIsInByb3ZpZGVyX2RvbWFpbiI6IjY0MDk2ODQ4NjQ5NDgwNDk0MDk0IiwiYnJhbmQiOlsiSVBUViBTdGFjayIsIkFsbCBDaGFubmVscyBFdmVyeSBXaGVyZSIsIjExMzItNXN0YXIucG5nIl0sImFjY2VzcyI6WzEsMiwzLDUsNywxMSwxMiwxMywxNywxOCwxOSwyMCwyMiw0MSw0Miw2Miw2Myw4MSw4MiwxMDEsMTAyLDEyMSwxMzEsMTMyLDEzNCwxNTEsMTUyLDE1MywxODEsMTgyLDE5MiwxOTMsMTk0LDE5NSwxOTYsMjkyLDMwMV0sImlhdCI6MTQ5MjY5MjA3MywiZXhwIjoxNDkyNzc4NDczfQ.qT65nZehOINNv_vzHtTawmUDCSEm2z-CcOrU75eq-7Q\"}", 
    "expires" : ISODate("2017-05-04T12:40:56.621+0000")
}
```

As you can see I have "auth" session in database but when I console.log it, It show me nothing like picture:

![srdfgh](https://cloud.githubusercontent.com/assets/7890134/25231337/c2cf528e-25ec-11e7-98e4-de07b4ef1c45.PNG)

How can I fix it?

**Comment by Thinkdiff** [comment]
I found something new about my problem. When I set a session using background request, I can`t read that and when I set a session using a browser like a user workflow, I can read that.

How can I set a readable session by background request "request package in npm"?

**Comment by gabeio** [comment]
I'm not exactly sure what you mean by a "background request". Can you give me an example?

**Comment by reke592** [comment]
...  I think my implementation is wrong.
I have the same problem,
I use vue-cli in my front-end, dev-server port 8080,
the express server is running on port 8000,
express-session + connect-mongo, CORS enabled in development environment.

![1](https://user-images.githubusercontent.com/17094894/26980934-29f2b64a-4d66-11e7-90b3-b7bf8876e8ce.png)
every time I regenerate a session when I logged into my app,
it will only saved into mongodb, the req.session is not populated when I navigate the routes with requresAuth middleware.

**Comment by reke592** [comment]
Sorry it has nothing to do with the express-session,
something weird happening in axios when handling request cookie in CORS enabled transaction.
I create a gulp task to pipe my static assets in front-end to my back-end, then I disabled CORS, and use the back-end to serve the assets.
