### ISSUE TITLE
 exports session storeReady status，so that we can use others instead

### ISSUE THREAD

**Issue by zhoushaofeng** [expressjs/session#453]
exports session storeReady status，so that we can use others instead, for example we can use cookie when memcached connect fail.

**Comment by dougwilson** [comment]
```js
var store = new MyStore()
var storeReady = true
var middleware = expressSession({ store })
store.on('disconnect', () => storeReady = false)
store.on('connect', () => storeReady = true)
```

Some stores may even have a better way to query their state directly instead of tracking events.
