### ISSUE TITLE
issecure function is not checking for x-arr-ssl

### ISSUE THREAD

**Issue by munir131** [expressjs/session#469]
In Windows Azure there is header `x-arr-ssl` for check whether it is https or not.
https://github.com/expressjs/session/blob/master/index.js#L599-L626 In `issecure` function we need to check for that header too.

Reference: https://tomasz.janczuk.org/2013/12/secure-by-default-with-ssl-in-windows.html

**Comment by gabeio** [comment]
That is a platform specific header, I'm not sure if we should be supporting that.

@dougwilson can you weight in on this?

**Comment by dougwilson** [comment]
This module only looks at the header for backwards compatibility. The ideal method is to key off the req.secure boolean instead, so people can use whatever logic they desire. Adding that header in this module will cause issues, namely that almost no one will be blocking that header so users can forge the value.

**Comment by munir131** [comment]
@dougwilson I agree with you that idal method is `req.secure` but in azure `express-session` can't detect `https` protocol properly.

**Comment by dougwilson** [comment]
Hi @munir131 I'm not sure I understand what you're saying. The detection in this module is _only for backwards compatibility_, so it's not going to change. You need to change your code or some configuration such that the `req.secure` value on your `req` objects are keyed off the header `x-arr-ssl`.

For example, here is a middleware that would set this up for you:
```js
app.use((req, res, next) => {
  Object.definePropety(req, 'secure', {
    value: Boolean(req.headers['x-arr-ssl']) // NOTE: I'm not clear what the content of x-arr-ssl is, so you may need to change this exact logic
  })
  next()
})
```

**Comment by munir131** [comment]
@dougwilson Sorry for late reply. I made changes somewhat like you suggested. Thanks for detailed reply. I think we can close this issue. Thanks again.
