### ISSUE TITLE
Use with replicaSet

### ISSUE THREAD

**Issue by FrontMage** [expressjs/session#471]
I'm using `express-session` with `mongo replicaSet`.

I'm aware that replications in MongoDB are asynchronous, so I wonder if I insert a session record in the `primary`, can someone else read from `secondary` before they are synced?

Thanks for answering.

**Comment by dougwilson** [comment]
Hi @FrontMage I'm not familiar with MongoDB, though this module doesn't interact with it at all. Instead, this module asks that you use community-provided store modules to provide a method for this module to store the data. The interface between this module and the store is very simple: this module either asks for a session by an ID string or provides an ID string and a blob to store. Your questions sound like something you'll need to ask in the store module you are using.
