### ISSUE TITLE
express.js dont send response with credentials

### ISSUE THREAD

**Issue by JuliaAlaeva** [expressjs/session#472]
**I have a auth with passport:**
```
router.get('/google/callback', passport.authenticate('google'), function authenticateCallback(req, res, next) {
  console.log(req.session);
  req.session.save(function(err) {
    res.redirect(req.session.redirect);
  });
});
```

_My app.js_
```
var express = require('express');
var path = require('path');
var logger = require('morgan');
var passport = require('passport');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');
var session = require('express-session');
var dotenv = require('dotenv');
var db = require('./db');
var cors = require('cors');

var app = express();

dotenv.load();

app.use(express.static(path.join(__dirname, 'public')));
app.use(logger('dev'));
app.use(cors());
// const allowCrossDomain = function(req, res, next) {
// res.header('Access-Control-Allow-Origin', '*');
// res.header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE');
// res.header('Access-Control-Allow-Headers', 'Content-Type, Authorization');
// next();
// };
// app.use(allowCrossDomain);
app.use(cookieParser());
app.use(function(req, res, next) {
console.log(req.cookies);
next();
});
app.use(session({
name: 'myUniqueAppName',
secret: 'keyboard cat',
cookie: {
secure: false,
httpOnly: false
},
resave: false,
saveUninitialized: true
}));
app.use(passport.initialize());
app.use(passport.session());
app.set('views', __dirname + '/views');
app.use(bodyParser.urlencoded({
extended: true
}));
app.use(bodyParser.json());
require('./config/passport')(passport);

// Connect db
db.connect();

// Routes
var routesDB = require('./routes/routesDb');
app.use('/db', routesDB);
var routesAuth = require('./routes/routesAuth');
app.use('/auth', cors(), routesAuth);

// catch 404 and forward to error handler
app.use(function(req, res, next) {
var err = new Error('Not Found');
err.status = 404;
next(err);
});

// error handler
app.use(function(err, req, res, next) {
// set locals, only providing error in development
res.locals.message = err.message;
res.locals.error = req.app.get('env') === 'development' ? err : {};

// render the error page
res.status(err.status || 500);
res.render('error');
});

module.exports = app;
````

_My package.json:_
```
`{ "name": "my-server",
"version": "0.0.0",
"private": true,
"scripts": {
"start": "node ./bin/www" },
"dependencies": {
"body-parser": "~1.17.1",
"connect-flash": "^0.1.1",
"connect-mongo": "^1.3.2",
"connect-mongo-session-store": "0.0.3",
"connect-redis": "^3.3.0",
"cookie-parser": "~1.4.3",
"cookie-session": "^2.0.0-beta.2",
"cors": "^2.8.3",
"debug": "~2.6.3",
"dotenv": "^4.0.0",
"express": "~4.15.2",
"express-session": "^1.15.3",
"formidable": "^1.1.1",
"mongodb": "^2.2.28",
"mongoose": "^4.10.6",
"morgan": "~1.8.1",
"nodemon": "^1.11.0",
"passport": "^0.3.2",
"passport-facebook": "^2.1.1",
"passport-google-oauth": "^1.0.0",
"passport-session": "^1.0.2",
"passport-twitter": "^1.0.4",
"pug": "~2.0.0-beta11",
"serve-favicon": "~2.4.2",
"uuid": "^3.1.0" }
}`
```

**Steps:**

1. I send request for login with social using passport.
2.  Social site redirect me to my server callback fn.
    Callback function:
    `router.get('/facebook/callback', passport.authenticate('facebook'), function authenticateCallback(req, res, next) {
    console.log(req.session);
    req.session.save(function(err) {
    res.redirect(req.session.redirect);
    });
    });`
    Where: req.session.redirect = 'localhost:4200'.
3. I redirect to this page and send new query to my server:
    `router.get('/status', function(req, res) {
    if (!req.user) {
    res.status(200);
    res.end(JSON.stringify({
      status: false
    }));
  } else {
    res.status(200);
    res.end(JSON.stringify({
      status: true,
      user: req.user
    }));
  }
    });`

**DON'T SEND RES.END()**
In browser res is empty
**I use:** 

- My OS: Ubuntu 16.04.1 LTS;
- Node 8.0.0;
- Check in Chrome Version 58.0.3029.81 and Firefox 53.0;
- Front - Angular4.

**Thanks for your answer.**

**Comment by lfan06** [comment]
We experienced a similar issue with Chrome version 59.0.3071.109.

**Comment by dougwilson** [comment]
Can either of you provide a complete app.js file, along with the exact versions of the dependencies you are using and the complete instructions of the steps to reproduce the issue? I used the little bit of code provided with latest versions, and I have to craft almost 80% of the code just so it could run and I couldn't reproduce, so mot sure what is different.

**Comment by JuliaAlaeva** [comment]
My app.js: 
var express = require('express');
var path = require('path');
var logger = require('morgan');
var passport = require('passport');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');
var session = require('express-session');
var dotenv = require('dotenv');
var db = require('./db');
var cors = require('cors');

var app = express();

dotenv.load();

app.use(express.static(path.join(__dirname, 'public')));
app.use(logger('dev'));
// const allowCrossDomain = function(req, res, next) {
//   res.header('Access-Control-Allow-Origin', '*');
//   res.header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE');
//   res.header('Access-Control-Allow-Headers', 'Content-Type, Authorization');
//   next();
// };
// app.use(allowCrossDomain);
app.use(cookieParser());
app.use(function(req, res, next) {
  console.log(req.cookies);
  next();
});
app.use(session({
  name: 'myUniqueAppName',
  secret: 'keyboard cat',
  cookie: {
    secure: false,
    httpOnly: false
  },
  resave: false,
  saveUninitialized: true
}));
app.use(passport.initialize());
app.use(passport.session());
app.set('views', __dirname + '/views');
app.use(bodyParser.urlencoded({
  extended: true
}));
app.use(bodyParser.json());
require('./config/passport')(passport);

// Connect db
db.connect();

// Routes
var routesDB = require('./routes/routesDb');
app.use('/db', routesDB);
var routesAuth = require('./routes/routesAuth');
app.use('/auth', cors(), routesAuth);

// catch 404 and forward to error handler
app.use(function(req, res, next) {
  var err = new Error('Not Found');
  err.status = 404;
  next(err);
});

// error handler
app.use(function(err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};

  // render the error page
  res.status(err.status || 500);
  res.render('error');
});

module.exports = app;

My package.json:
{
  "name": "my-server",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node ./bin/www"
  },
  "dependencies": {
    "body-parser": "~1.17.1",
    "connect-flash": "^0.1.1",
    "connect-mongo": "^1.3.2",
    "connect-mongo-session-store": "0.0.3",
    "connect-redis": "^3.3.0",
    "cookie-parser": "~1.4.3",
    "cookie-session": "^2.0.0-beta.2",
    "cors": "^2.8.3",
    "debug": "~2.6.3",
    "dotenv": "^4.0.0",
    "express": "~4.15.2",
    "express-session": "^1.15.3",
    "formidable": "^1.1.1",
    "mongodb": "^2.2.28",
    "mongoose": "^4.10.6",
    "morgan": "~1.8.1",
    "nodemon": "^1.11.0",
    "passport": "^0.3.2",
    "passport-facebook": "^2.1.1",
    "passport-google-oauth": "^1.0.0",
    "passport-session": "^1.0.2",
    "passport-twitter": "^1.0.4",
    "pug": "~2.0.0-beta11",
    "serve-favicon": "~2.4.2",
    "uuid": "^3.1.0"
  }
}

**Comment by dougwilson** [comment]
Hi @JuliaAlaeva thanks for providing that information. I'm a little unsure how to perform the first step "I send request for login with social using passport.". Can you explain how to do that? When I start the app, what URL do I go to?

I'm also having a lot of trouble actually running the code you provided, because it is referencing a bunch of files you didn't provide. Can you provide all those files as well or provide some app code that doesn't use anything you haven't provided?

I tried making major alterations to your code above just to get it to run and I don't think I'm able to reproduce your issue, so it's probably something different between our code, but if you don't provide runnable code, I'm not sure what else I can do.

**Comment by philhubergmail** [comment]
we have just in the last few days been experiencing problems when using localhost and passport (could be from chrome 58 - not sure).  We are using azure ad b2c with passport.  I believe it's some change in chrome recently.  Works fine on safari and firefox, but safari/firefox complains when routing back to localhost that you're going from a secure to insecure connection.   Chrome seems to not warn, just start a new session, which causes the problems.  Since we're using azure ad b2c and @JuliaAlaeva  is using google I suspect the problem is with Chrome's new handling of the transition from https to http.   We've been thinking of doing self-signed certs for localhost - not sure if chrome will still do what it's doing or not.

**Comment by JuliaAlaeva** [comment]
Get reason - CORS.
Browser block request.
I get 
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at ‘http://localhost:3000/auth/status’. (Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’).`

**Comment by dougwilson** [comment]
Thanks for the follow up @JuliaAlaeva .
