### ISSUE TITLE
Express session with express-mysql-session not working at all

### ISSUE THREAD

**Issue by vikaskumar2299** [expressjs/session#474]
I learnt PHP sessions within minutes but can't use this express session even after trying for two days. I'm really stuck and it's wasting my time :(

The problem is that it saves session only first time with any request. On page reload from browser, the session ID changes, hence the old value that I stored in the session becomes undefined. Even in DB the session id keeps changing (i.e., new entries on every page reload). I've tried many many solutions gives on github and here but none of them worked for me. Tried `resave` `rolling` `maxAge` etc. but none worked.

Here's my code:

    var express = require('express');
    var mysql = require('mysql');
    var session = require('express-session');
    var MySQLStore = require('express-mysql-session')(session);
    var app = express();
    var bodyParser = require('body-parser');
    app.use(bodyParser.json({type: '*/*'}));
    var http = require('http');
    
    
    app.use(function (req, res, next) {
        res.setHeader('Access-Control-Allow-Origin', '*');
        res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS, PUT, PATCH, DELETE');
        res.setHeader('Access-Control-Allow-Headers', 'X-Requested-With,content-type');
        next();
    });
    
    var connectionPool = mysql.createPool({
            host: '127.0.0.1',
            user: 'root',
            password: '123456',
            database: 'cs_chat',
            connectionLimit: 2,
        });
    
    var options = {
        host: '127.0.0.1',
        user: 'root',
        password: '123456',
        database: 'cs_chat',
        schema: {
            tableName: 'my_session',
            columnNames: {
                session_id: 'session_id',
                expires: 'expires_column_name',
                data: 'data_column_name'
            }
        }
    };
     
    var sessionStore = new MySQLStore(options);
    
    var server=http.createServer(app);
    
    app.use(session({
      secret: 'some secret',
      resave: false,
      saveUninitialized: true,
      store: sessionStore,
      cookie: {
        secure: false,
        maxAge: 36000000,
        httpOnly: false,
      },
    }));
    
    
    app.get("/test", function(req, res, next){
         console.log(req.session);
      console.log(req.sessionID, req.session.name);
        if(!req.session.name){
            console.log("Not set.");
            req.session.name = "vikas kumar";
        } else {
            console.log("Already set");
            console.log(req.session.name);
        }
        res.end();
    });
    
    server.listen(3000, '0.0.0.0', function(){
        var host = server.address().address;
        var port = server.address().port;
        console.log("testApp socket server is listening at http://%s:%s", host, port+"\n\n");
    });

In the console, I see **Not set** every time I make request to http:/192.168.43.200:3000/test using Jquery Ajax.

**Comment by dougwilson** [comment]
Hi @vikaskumar2299 thanks for the code. I'm not sure, but I think it's an issue with your client-side AJAX requests. Are the requests sending the session cookie with them? If not, it would result in the exact behavior you're describing, because if there is no cookie, the library doesn't have the session ID to load so automatically creates a new cookie.

Also, it looks like around the same time, another user posted pretty much identical code to what you just posted. Are you following some tutorial somewhere online? Perhaps there is an issue with that tutorial? Not sure.

**Comment by vikaskumar2299** [comment]
Yeah we work in same startup and facing this issue so posted at 2-3 places together. I enabled the xhr with credentials key in Ajax request and it worked. So the issue was the cookies, that were never sent. Thank you.

**Comment by vikaskumar2299** [comment]
I will close the issues once the queries get answered.

**Comment by dougwilson** [comment]
Hi @vikaskumar2299 what still needs to be answered? Your previous comment seemed to say that it's working now. Can you clarify?

**Comment by vikaskumar2299** [comment]
Well now I've uploaded my app to /var/www/html directory on amazon EC2. Everything is working but again their is session problem. The session is saved properly when I tested using Postman but it's not saving when using Angular JS's $http service. Any views?

**Comment by vikaskumar2299** [comment]
All doubts are clarified now. The only problem was different origins. When I used same origin and port that were used at server, everything worked fine.

**Comment by duffman** [comment]
dougwilson: The best thing for this entire discussion (all threads) would have been if you´d kept quiet, you are just messing things up with your clueless posts, you clearly don´t understand how these things work, you don´t even understand the basics here, instead of messing up this discussion you should have spent some time reading up on the subject, start with HTTP basics, man you are wasting peoples time here...
