### ISSUE TITLE
conflict in session for users

### ISSUE THREAD

**Issue by Thinkdiff** [expressjs/session#478]
I have a Nodejs application and I`m using **express-session** and **redis-store** by redislabs.com.
The problem is I logged in my panel and after some minutes, when I refreshed the page, I saw myself in another account!! It was like I logged in another person's account!! this is a huge security bug. Why did this happen?

This is my config:
```
app.use(session({
     secret: config.secureKey ,
     resave: false, 
     saveUninitialized: false ,
     store: new RedisStore({host: '************************.redislabs.com', port: **** , ttl:600000000}),
     cookie:{
        httpOnly : true ,
        path     : '/' ,
        maxAge   : 600000000, /* active session for 1 week */
        expires  : new Date().getTime() + (7 * 86400000)   /* active session for 1 week */
     }
}));
```

**Comment by dougwilson** [comment]
There isn't enough information to determine that. We've had this report several times and every time it has turned out to be an issue somewhere else in the app and not this module, sometimes even the store itself was the issue.

Regardless, please provide us with the complete code to reproduce and the steps so we have something to debug, or if you cannot share code and cannot shrink the code into something reproducible, you can always debug the code and provide the technical details of where the issue is happening and we can use that to guess the issue (you could even suggest a fix).

**Comment by Thinkdiff** [comment]
this is my to section codes:

    var cluster = require('cluster');
    var PORT = +process.env.PORT || 1337;
    var server = ''; /* global for accessing server */
    var numCPUs = require('os').cpus().length;
    var underMaintenance = false;
    numCPUs = numCPUs / 2;

    if (cluster.isMaster) {

        for (var i = 0; i < numCPUs; i++) {
            cluster.fork();
        }

     cluster.on('disconnect', function(worker){
        cluster.fork();
      });

      cluster.on('exit', function(worker) {
        cluster.fork();
      });
    console.log("master " + process.pid);
    } else {

    if (underMaintenance == true) {
      var express = require('express')
    , bodyParser = require('body-parser')
    , config = require('./config.js');

    var app = express();

    app.use(express.static(__dirname + '/statics'));
    app.all("*" , function(req,resp,next){
        resp.send('<!DOCTYPE html><html><head><title>Under Maintenance</title><style         type="text/css">body{background: url("/images/under_maintenance.jpg") no-repeat fixed;background-            size: 100% auto;}</style></head><body></body></html>');
    });

    }else{

    console.log("slave " + process.pid);
    // 'use strict';
    /* Import all nedeed packages and exported modules */
    var express = require('express')
    , bodyParser = require('body-parser')
    , session = require('express-session')
    , jsonwebtoken = require('jsonwebtoken')
    , helmet = require('helmet')
    , SHA256 = require("crypto-js/sha256")
    , path = require('path')
    , os = require('os')
    , requestSender = require('request')
    , cookieParser = require('cookie-parser')
    , compression = require('compression')
    , config = require('./config.js')
    , fs = require('fs');

    const domain = require('domain');
    const theDomain = domain.create();
    theDomain.bind();

    var app = express();

    app.use(helmet());
    app.disable('x-powered-by');

    var hsts = require('hsts');
    var ienoopen = require('ienoopen');
    app.use(ienoopen());

    var NodeCache = require( "node-cache" );
    var clientCach = new NodeCache( { stdTTL: 0, checkperiod: 0 , errorOnMissing : true } );

    var nosniff = require('dont-sniff-mimetype');
    app.use(nosniff());

    var xssFilter = require('x-xss-protection');
    app.use(xssFilter());
    app.use(xssFilter({ setOnOldIE: true }));

    app.use(hsts({
     maxAge: 10886400,        // Must be at least 18 weeks to be approved by Google
      includeSubDomains: true, // Must be enabled to be approved by Google
      preload: true
    }));

    var RedisStore = require('connect-redis')(session);

    app.use(cookieParser());

    /* Session config */
    app.use(session({
         secret: config.secureHasherKey ,
         resave: false, 
         saveUninitialized: false ,
         name: "ucomapny",
         store: new RedisStore({host: 'localhost', port: 6379 , ttl:86400}),
         cookie:{
            // secure   : true ,
            httpOnly : true ,
            // domain   :'my.iptvstack.com' ,
            path     : '/' ,
            maxAge   : 86400000, /* active session for 1 week */
            // name: "dashboard",
            expires  : new Date().getTime() + (86400000)   /* active session for 1 week */
         }
    }));   

    /* Body Parser Configuration */
    app.use(bodyParser.urlencoded({extended: true}));
    app.use(bodyParser.json());

    /* Internal Gzip Configuration */
    app.use(compression()); 

    // app.use(cors());

    app.use(function(req, res, next) {
        res.header('Access-Control-Allow-Credentials', true);
        res.header('Access-Control-Allow-Origin', "*");
        res.header('Access-Control-Allow-Methods', '*');
        res.header('Access-Control-Allow-Headers', '*');
        // res.header('Access-Control-Expose-Headers', 'Authorization, Cache-Control, Content-Length,     Date, Expires, Server, Transfer-Encoding, x-goog-meta-foo1');
        next();
    });

**Comment by Thinkdiff** [comment]
@dougwilson I`m waiting for your help

**Comment by dougwilson** [comment]
Thanks for providing the code! Please let me know what the steps to reproduce are, and I will run though them to see what I can see happening in the debugger.

**Comment by Thinkdiff** [comment]
Thank a lot. What do you need for debugging?

**Comment by dougwilson** [comment]
Just need to know what the steps to reproduce are.

**Comment by Thinkdiff** [comment]
sorry I did not get your point! Reproduce of what?

**Comment by dougwilson** [comment]
The issue you stated at the top:

> The problem is I logged in my panel and after some minutes, when I refreshed the page, I saw myself in another account!! It was like I logged in another person's account!! this is a huge security bug. Why did this happen?

Now that I have the code, how do I log into the panel, for example?

**Comment by Thinkdiff** [comment]
It does not launch in public mode, unfortunately!! We launched it in our private network for testing and we found this problem.
Can you guess how a problem like this can happen?

**Comment by dougwilson** [comment]
There isn't enough information to determine that. We've had this report several times and every time it has turned out to be an issue somewhere else in the app and not this module, sometimes even the store itself was the issue.

If you can provide us with the complete code to reproduce and the steps, we can help determine the cause.

**Comment by Thinkdiff** [comment]
sorry, my manager does not allow me to give your access to codes.
Anyway, could you tell the other times that you saw and fix this problem? some example that I can think about them in our application.

**Comment by dougwilson** [comment]
Hi @Thinkdiff the few times this was reported, the users never gave code (just like you) and then eventually closed the issue saying they solved it without any further information. I don't have any information since no one provided any followup on what their issue was.

**Comment by dougwilson** [comment]
I'm going to close this since there is no clear path to resolution; without a way to reproduce the issue on my end, I'm not sure what the issue is. If you can either (a) provide code & instructions such that I can reproduce or (b) provide a fix, that would be the best path forward, unless you have another idea.
