### ISSUE TITLE
Getting a new session after redirect

### ISSUE THREAD

**Issue by Bartozzz** [expressjs/session#482]
I am trying to make an authorization system using `passport.js` (OpenID). Basically, I have a web app (on `localhost:3000`) and a REST Api (on `localhost:3001`).

First, the user makes a call to the API with an unique token I have to save. Then, I am trying to save this token on the server side though sessions:

```javascript
app.get( "/api/auth/steam", ( req, res, next ) => {
    req.session.connectionID = req.query.connectionID;
    req.session.save( next );

    console.log( "------------------------------------------" );
    console.log( req.session.id );
    console.log( req.session.connectionID );
    console.log( "------------------------------------------" );
}, passport.authenticate( "steam" ) );
```

After the magic of `passport.js` and some redirects to the `Steam` website, it finally redirects the user to my API, but the old session is then unavaible (the session id has changed after those redirects):

```javascript
app.get( "/api/auth/steam/callback", ( req, res, next ) => {
    return passport.authenticate( "steam", ( error, user ) => {
        console.log( "------------------------------------------" );
        console.log( req.session.id );
        console.log( req.session.connectionID );
        console.log( "------------------------------------------" );

        res.send( "Processing…" );
    } )( req, res, next );
} );
```

I've tried to regenerate session, but then it outputs `Error: failed to load session`. Any ideas of why the sessionID is changing after those redirects and how can I communicate data between `/api/auth/steam` and `/api/auth/steam/callback`?

### Console output:
```
------------------------------------------
1FR9LZOWnhWlvE7grIUuXQmbzUSvw08V
57wGg0AW_-EG0-EyAAAB
------------------------------------------
Executing (default): SELECT `sid`, `expires`, `data`, `createdAt`, `updatedAt` FROM `Sessions` AS `Session` WHERE `Session`.`sid` = '1FR9LZOWnhWlvE7grIUuXQmbzUSvw08V';
Executing (default): UPDATE `Sessions` SET `expires`='2017-07-12 22:38:20',`data`='{\"cookie\":{\"originalMaxAge\":null,\"expires\":null,\"httpOnly\":true,\"path\":\"/\"},\"connectionID\":\"57wGg0AW_-EG0-EyAAAB\"}',`updatedAt`='2017-07-11 22:38:20' WHERE `sid` = '1FR9LZOWnhWlvE7grIUuXQmbzUSvw08V'
Executing (default): UPDATE `Sessions` SET `expires`='2017-07-12 22:38:20',`updatedAt`='2017-07-11 22:38:20' WHERE `sid` = '1FR9LZOWnhWlvE7grIUuXQmbzUSvw08V'
Executing (ae92c1b8-1068-496a-ad75-eddc45c71ed2): START TRANSACTION;
Executing (ae92c1b8-1068-496a-ad75-eddc45c71ed2): SELECT `id`, `name`, `token`, `provider`, `avatar`, `createdAt`, `updatedAt` FROM `users` AS `users` WHERE `users`.`token` = '76561198396997708' AND `users`.`provider` = 'steam' LIMIT 1;
Executing (ae92c1b8-1068-496a-ad75-eddc45c71ed2): COMMIT;
------------------------------------------
ezIHVpwFHHipc8fQeGrSbRVhFmedtczF
undefined
------------------------------------------
```

**Comment by dougwilson** [comment]
There are a lot of possibilities and nothing specific jumps out from the description. Is it possible you can provide all the following so we can take a look?

1. Version of this module you're using.
2. Version of Node.js
3. Complete source code that reproduces the issue. A git repo of a simple example app works well.
4. Complete instructions for how to setup the app and reproduce the issue.

**Comment by Bartozzz** [comment]
I've found the bug. It's quite embarrassing. I thought that `127.0.0.1:8000` and `localhost:8000` are the same, but apparently those are handled differently by `Express.js`. So the client was requesting `127.0.0.1:8000` and Steam was returning data to `localhost:8000` - and thus the session ID was different for each "domain".

I am pretty much it is just my mistake, but if you want to investigate further I can you provide a complete source code that reproduces the "issue".
