### ISSUE TITLE
Automatically check session data on controller

### ISSUE THREAD

**Issue by rokity** [expressjs/session#483]
When the controller is called , I want that expressjs check automatically that req.session.key is present on memory . There is ??

**Comment by dougwilson** [comment]
I @rokity I'm sorry, I don't understand your question. Can you elaborate a bit more?

**Comment by rokity** [comment]
This is the standard syntax for check if session is present or not  
`
router.get('/home', function(req, res, next) {
if(req.session.test)
  res.render('home', { title: 'Test Page', 
        token : req.session.test);
  else
    res.redirect('/login?url=/home');
});
`
I want to remove the if statmant and add something of more intuitive on the router definition .
Do you like it?

**Comment by dougwilson** [comment]
Gotcha. That may be doable. What do you think it should look like instead?

**Comment by rokity** [comment]
something like this 
```javascript
router.get('/home',req.session.test, function(req, res, next) {
  res.render('home', { title: 'Test Page', 
        token : req.session.test);
});
```
this feature give the possibility to abbreviate the syntax of the route , I don't want to remove 
the possibility to check attributes and other things inside the session , only abbreviate syntax if you need this session attribute .

**Comment by dougwilson** [comment]
Gotcha. I'm not sure if it's possible for this module to implement something like that, but if you have any ideas, please feel free to try and put together a pull request with a possible solution for that, or even maybe an outline for how someone could implement that :)

**Comment by dougwilson** [comment]
I'm going close since I haven't heard back on any possible way to implement something like that in this module.
