### ISSUE TITLE
controlling session lifetime using expiration date from cookie

### ISSUE THREAD

**Issue by whatasec** [expressjs/session#490]
Hi, I have an issue. Authentication session cookies need to be session cookies but they also need to expire on the server side after a certain time. The current implementation does not allow me to do that.  I either have a persistent cookie that expires or a session cookie that lives for ever. I need a way to choose how long the server will maintain the session without forcing the cookie to set expiration date, and hence becoming a persistent cookie.

**Comment by dougwilson** [comment]
I'm not sure I understand. Most of the store modules allow you to do this. What store module are you using? May need to request that store module adds the ability to have a separate lifetime than the cookie.

**Comment by whatasec** [comment]
Hi Doug, the issue appears to be in MemoryStore

var expires = typeof sess.cookie.expires === 'string'
    ? new Date(sess.cookie.expires)
    : sess.cookie.expires

// destroy expired session
  if (expires && expires <= Date.now()) {
    delete this.sessions[sessionId]
    return
  }

expires comes from the cookie  and it should have a separated attribute to control session lifecycle. cookie.expire can be based on this new attribute but you can't use

However I just realized that the MemoryStore is not to be used so I guess the other recommendations for store might take care of this issue.

**Comment by dougwilson** [comment]
Yea, the built-in memory store is just to use for quick setup. There is a memory store in the README that is must more feature-filled and production ready if you really want a memory based store :) 👍
