### ISSUE TITLE
Looking & NOT finding debug/node.js on import

### ISSUE THREAD

**Issue by jgrauel** [expressjs/session#491]
Greetings, I am attempting to leverage sessions in my express run API. As soon as I attempt to import i get the following error..
```
ENOENT: no such file or directory... 
.../node_modules/express-session/node_modules/debug/node.js
```
I confirmed that the nested node modules is totally missing, but I did the standard npm install. Is there a step I am missing here? Thanks

**Comment by dougwilson** [comment]
Hi @jgrauel there is nothing special you need to do; I would say there is some kind of bug in your npm install. Perhaps try to clear your npm cache, remove all your node_modules folder and try again?

```
$ npm cache clean && rm -rf node_modules
$ npm install express-session
```

**Comment by dougwilson** [comment]
Closing the issue since there hasn't been a response.
