### ISSUE TITLE
Can't get req.session from ws.on('connection')

### ISSUE THREAD

**Issue by ejwaibel** [expressjs/session#493]
Trying to use the `express-session` to setup a sessionID that is shared between my API and Websocket (ws). However, it seems that my API gets the correct `req.session.id`, but the websocket request only contains `req.headers.cookie` and when it's parsed and attempting to retrieve the session from my store, I just get `undefined`. I've been pulling my hair out for hours and can't seem to find any consistent examples of how this should work.

app-server.js
```js
var config = require('./config/config'),
	express = require('express'),
	bodyParser = require('body-parser'),
	cookieParser = require('cookie-parser'),
	sessionParser = require('express-session'),
	mongodbSession = require('connect-mongodb-session')(sessionParser),
	path = require('path'),
	favicon = require('serve-favicon'),
	logger = require('loggy');

let app = express(),
	secret = '$eCuRiTy',
	sessionStore = new mongodbSession({
		uri: `mongodb://${config.server}/squarrels_sessions`,
		collection: 'sessions'
	});

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'jade');

app.use(bodyParser.json({ limit: '50mb' }));
app.use(bodyParser.urlencoded({ limit: '50mb', extended: true }));
// app.use(cookieParser(secret));

//----------
// SESSION
//----------
app.use(sessionParser({
	secret,
	store: sessionStore,
	resave: false,
	saveUninitialized: true
}));

// Additional code
```

websocket.js
```js
var	_ = require('lodash'),
		cookie = require('cookie'),
		cookieParser = require('cookie-parser'),
		WebSocket = require('ws');

const logger = require('loggy');

let wss = new WebSocket.Server({
		verifyClient: function(info, done) {
			logger.log('verifyClient() -> ', info.req.headers);
			done(info.req.headers);
		},
		server
	});

wss.on('connection', function connection(ws, req) {
		let sid = cookieParser.signedCookie(cookie.parse(req.headers.cookie)['connect.sid'], '$eCuRiTy');
		logger.info('Connection accepted:', req.headers, req.session);
		logger.info(`Clients Connected: ${wss.clients.size}`);

		logger.info('sid -> ', sid);
		store.get(sid, function(err, ss) {
			logger.log('err -> ', err);
			logger.log('ss -> ', ss);
			logger.log(req.sessionID);
		});
});
```

**Comment by dougwilson** [comment]
Since websockets don't even invoke Express.js code at all, this middleware is not even executed.

**Comment by ejwaibel** [comment]
@dougwilson I might have left out some additional code that would be invoking Express.js, please let me know what I might be missing and I can paste additional code, just didn't want to overwhelm the Issue.

**Comment by dougwilson** [comment]
Ah, gotcha, @ejwaibel ideally, the following is what we ask for when trying to troubleshoot an issue:

1. Version of Node.js you are using
2. Version of this module you are using
3. Complete code we can run to reproduce the issue. Ideally remove as many other dependencies from here as possible (which would also help you know if one of them was causing the issue). Then include the exact versions of all other needed modules you're using.
4. Complete instructions on how to setup, run, and finally call the code to see the issue. This way we can attach a debugger and walk through the issue to see what's going wrong.

**Comment by ejwaibel** [comment]
Okay, it seems that the ghosts in the machine have finally started to behave 👻 and it's working as expected 👎 , sorry for the confusion!

**Comment by dougwilson** [comment]
Hi @ejwaibel well, glad your issue was resolved. Please feel free to post again if you run into anything!

**Comment by frederikhors** [comment]
@ejwaibel how did you fixed this?
