### ISSUE TITLE
Cookie not set

### ISSUE THREAD

**Issue by booradleys** [expressjs/session#496]
Hi,
When calling in BROWSER http://localhost:3000/membre/identification/setcookie, cookie is set correctly.
But when this api url is called by http request from my angular application (http://localhost:4200/home), cookie is not set.
I don't undersand why.

IdentificationController.ts:
````
...
@Get("/setcookie")
    setcookie(@Session() session, @Req() request: Request, @Res() response: Response)
    {
        session.membre = {}
        session.membre.id = 'OK';		
        session['membre'] = 'AZERTY';
        return session;
    }
// return  {"cookie":{"path":"/","_expires":null,"originalMaxAge":null,"httpOnly":true,"domain":"localhost","sameSite"
:false,"secure":false},"membre":"AZERTY"}

    
    @Get("/getcookie")
    getcookie(@Session() session, @Req() request: Request, @Res() response: Response)
    {		
        return {'session': session};
    }
// return {"session":{"cookie":{"path":"/","_expires":null,"originalMaxAge":null,"httpOnly":true,"domain":"localhost"
,"sameSite":false,"secure":false}}}
...
````

app.
````
expressApp.use(session({
        secret: 'cookie_secret',        
        resave: true,
        saveUninitialized: true,
        cookie: {
            //domain: 'localhost',
            sameSite: false,
            path: '/', 
            httpOnly: true, 
            secure: false, 
            maxAge: null
        }
    })); // use session middleware
````

**Comment by gabeio** [comment]
If I remember correctly ports are a different domain to browsers. So you are basically attempting to access a cookie from `google.com` on `facebook.com`.

**Comment by booradleys** [comment]
So what is the correct express-session configuration when myangularapplication.com want to access to myexpressapplication.com ?

**Comment by gabeio** [comment]
I would suggest having the cookie written to both domains. I'm not sure if express-sessions will/can do that.

@dougwilson Ideas?

**Comment by dougwilson** [comment]
Web browsers do not allow that to happen for security reasons. For example, if you try to set a cookie on google.com from your site,  when you then go to google.com that cookie is not set, because the web browser just ignored it for security reasons. We can only work within the limitations web browsers impose on cookies.

**Comment by booradleys** [comment]
That means that if my angular application is localhost:4200 , my express application have to be something like api.localhost::4200 ?

**Comment by gabeio** [comment]
That sounds about right. You need them to be within the same domain (and port).

**Comment by booradleys** [comment]
I suppose i should use proxy servers.
