### ISSUE TITLE
Sessions only for some routes in your API

### ISSUE THREAD

**Issue by jgato** [expressjs/session#497]
Hi there,

some time ago I read about that I didnt find a solution. Is there any way of avoiding creating sessions for some routes of your API? We are implementing a service for publish/subscribe. Most part of the API is protected by an user/password with a cookie control. But publishing is just a POST over an url, and this is unprotected by design. So, we dont need sessions in these urls. Actually, having hundred of clients publishing (POST) hundred of events makes our DDBB increase toooooo much. How could we control this correctly? We have millions of useless sessions in a DDBB,

**Comment by gabeio** [comment]
https://github.com/expressjs/csurf#ignoring-routes

This method will work for sessions also.
