### ISSUE TITLE
1.3.2 was supposed to fix 'Cannot read property 'upserted' of undefined' issue

### ISSUE THREAD

**Issue by tanishqjain1002** [expressjs/session#498]
As the title says, when I run something as basic as the code given below i get that error.
```
var express = require('express');
var app = express();
var mongojs = require("mongojs"); 
var session = require("express-session");
var MongoStore = require('connect-mongo')(session);
var db = mongojs("MyMongoURL"); 

app.use(session({
    secret: 'secret',
    resave: true,
    saveUninitialized: true,
    store: new MongoStore({
    	db: db,
    	collection: "sessions"
    })
}));

app.get("/", function(req, res) {
	res.send(req.session)
});

app.listen(3000, function() {
	console.log("server running");
});
```

As you can see in the photo, the error still persists
![capture](https://user-images.githubusercontent.com/2004372/28995779-bcbffb06-7a0f-11e7-9990-f927b91fa537.JPG)

**Comment by dougwilson** [comment]
Hi! I'm not really sure what you mean; there has never been a version 1.3.2 of this module. The stack trace looks to be within your store module, perhaps filed this on the wrong issue tracker?
