### ISSUE TITLE
Can't set headers after they are sent

### ISSUE THREAD

**Issue by ykxkknd2** [expressjs/session#499]
```js
//eg.js
       req.session.user = {
            name : req.body.username
        };
        res.json({status:'success'})  //already sent
```
```js
//express-session/index.js
        req.session.save(function onsave(err) {
          if (err) {
            defer(next, err);
          }
            writeend();
         });
```
If an error was thrown. Express error middleware will catch the error.But usually,the middleware will render the error like "res.render('error')". So this error will be thrown :"Can't set headers after they are sent"

**Comment by dougwilson** [comment]
Hi @ykxkknd2 I'm sorry, but I'm not clear on what you're reporting. Perhaps can you condense this into a test case that demonstrates what is happening and outline what you think should happen instead? Or maybe even make a pull request?

**Comment by dougwilson** [comment]
Closing the issue since there hasn't been a response.
