### ISSUE TITLE
docs hint at advising bad security practice

### ISSUE THREAD

**Issue by mmmurf** [expressjs/session#500]
the docs mention this sort of phrasing for some of the client side cookie-related settings: 

_Note be careful when setting this to true_

This implies, contrary to the default setting and good security practice, that one might as well prefer to turn off the secure behavior in favor of one that makes accessing the cookie easier via client code.

If one wants to use cookies, the best approach is to use a different cookie for client side data sharing than the one used for server side authentication.

**Comment by dougwilson** [comment]
Hi @mmmurf please feel free to make a pull request to change the language to something you feel is better :)

**Comment by gabeio** [comment]
I actually see 2 locations of this phrase both probably needing to be improved.

**Comment by mmmurf** [comment]
I will make some improvements and submit a pull request.

**Comment by gabeio** [comment]
@mmmurf thanks! If you would also like to change the same lines in [cookie](https://github.com/jshttp/cookie) it was where the readme originated. If not I can copy your pr over to it for you.

**Comment by dougwilson** [comment]
Closing issue since no follow up for several months.
