### ISSUE TITLE
sessionid lose in the process of redirect

### ISSUE THREAD

**Issue by PowerDos** [expressjs/session#502]
Sessionid is lost in very few cases.  session is stored in redis

app.use(session({
    name: "sid",
    store: new RedisStore({
        client: Redis(251),  // 251 is redis db 
        ttl: 3600
    }),
    resave: false,
    rolling: true,
    saveUninitialized: true,
    cookie: {maxAge: 60000},                                       
    secret: '123456',

}));

**Comment by dougwilson** [comment]
If you are doing a redirect,  some browsers it works, some you need to manually save before the redirect. You can use https://github.com/expressjs/session/blob/master/README.md#sessionsavecallback to save then redirect.

I hope that helps!
