### ISSUE TITLE
How to destroy the session for a specific user id?

### ISSUE THREAD

**Issue by IonicaBizau** [expressjs/session#504]
What is the right way to destroy all the sessions except the current one for a user id?

Use case: when they change the password, it's a good thing to destroy all the sessions.

**Comment by dougwilson** [comment]
Hi @IonicaBizau this would need to be something implemented in the session store module you are using; this module only provides the mechanism to hook up a session object with a request, providing the cookie tracking. This module basically will get the session ID from a request, and ask the session store to lookup the session by that ID. If your session store serializes the data you are putting in it in some way in which you can lookup the session in the underlying data storage, then you can delete them by another key (like the user id).

The https://www.npmjs.com/package/connect-session-sequelize store is an example of a store that allows you to setup any of your data keys as a separate column in the underlying database to query on.

There are any session stores that work with this module listed at https://github.com/expressjs/session#compatible-session-stores . Find one that fits your needs, request changes to the module, or even make your own :) !
