### ISSUE TITLE
Session does not save when accessed via AJAX call

### ISSUE THREAD

**Issue by AskYous** [expressjs/session#506]
Hello,

I have a route which executes code to change a session variable. When I call that route using the fetch API (or perhaps any AJAX call), it refuses to save the modified session. However, when I access the route directly in my browser, it saves the modified session successfully. Please see [this video](https://youtu.be/FNW87qIYL-8) I made going over the problem. The repository used in the video is [here](https://github.com/islaam-database/islaam-database/tree/bug-in-express-session).

**Comment by dougwilson** [comment]
It's probably an issue with your fetch call. Is it sending the session cookie?

**Comment by dougwilson** [comment]
If the "fetch API" is the one that comes with the browser, it doesn't send cookies by default. Here is the first search results I found which may have the answer for you: https://stackoverflow.com/questions/34558264/fetch-api-with-cookie

It looks like you need to set the `credentials` option to whatever value is appropriate for your app.

**Comment by AskYous** [comment]
Thanks, @dougwilson! It worked! I never knew about the credentials thing.
