### ISSUE TITLE
New visitors getting existing sessions

### ISSUE THREAD

**Issue by wmertens** [expressjs/session#508]
I don't have a reproduction for you (yet), but I'd like to describe my environment and maybe something is obvious to you:

* Entry point is nginx doing reverse proxy and SSL offload
* Next is socketcluster.io
* This passes the http connections to Express
* Pretty textbook express setup, the cookie is only sent on session change; `trust proxy` is `loopback` (single server).

When I log in in one browser and then just visit the page in another browser, I end up in my session. However, I do not get a cookie in that other browser. The server just thinks the other browser has the same session.

I can't seem to reproduce it locally, so it might be due to Nginx.

**Comment by wmertens** [comment]
Well, I'm using graphql and I'm logging the context I'm giving graphql, and it's exactly what I expect it to be, but somehow it's using old context. I'll close this, since it obviously nothing to do with `session`.

**Comment by wmertens** [comment]
The prerender cache I wrote, which was supposed to not cache for logged-in users, was looking at the wrong place for the user, so it cached logged in pages 🙈 💩

**Comment by gabeio** [comment]
ouch, yeah be careful it's pretty easy to cache logged in user pages!
