### ISSUE TITLE
New session is saved 2x?

### ISSUE THREAD

**Issue by subversivo58** [expressjs/session#509]
I use `express 4.15.4` , `express-session 1.15.5` and each time you save a new session it is stored twice.

Only one (of these two) represents the id stored in the session cookie, why is it saving twice?

Regardless of saving to a database or a file (or even in memory), each new session is being saved twice.

**Comment by dougwilson** [comment]
Weird, it shouldn't be, and our tests indicate this is not the case or it's a bug not surfaced by our tests. Can you provide a complete app that has this issue and provide instructions on how to replicate? We can debug this.

**Comment by subversivo58** [comment]
Sorry it was my mistake, I noticed it was a `fetch` request on the client-side for a route on startup `script`. This `fetch` had no "credentials".

It was resolved with:

    fetc('./pubkey', {
        credentials: 'include',
        cache: 'reload'
    }).then((response)=>{
        return response.text();
    }).then((key)=>{
        //...
    })catch((e)=>{/*...*/})

Thank you for your attention.
