### ISSUE TITLE
Database filling up with empty sessions out of the box

### ISSUE THREAD

**Issue by darknoon** [expressjs/session#511]
When an unauthorized user hits our app, a session gets created in the database. We're not really on the internet, but found 300k sessions in our postgresql db.

I am using session with `passport` & `passport-google-oauth2` and saving via `connect-pg-simple`. It seems like this configuration should work better out of the box.

When I read the docs [here](https://github.com/expressjs/session#saveuninitialized), I assumed that the overall issue had been fixed with Passport 0.3.0, but on careful reading it says that the combination of `saveUninitialized` _and_ 0.3.0 is necessary. I wish this had been clearer when I was skimming the docs and getting started.

Initially, I assumed this was an issue with `connect-pg-simple`, so I eventually stepped through the code with the node chrome devtools and found the backtrace was checking whether to save the session via the `saveUninitialized` option, which has stemmed the tide.

**Comment by dougwilson** [comment]
Glad you got ut cleared up :+1:

**Comment by darknoon** [comment]
@dougwilson I know you probably get a lot of issues opened here that are more like questions, so I was trying to raise an issue to prevent others from getting bitten by the same thing via improvements to the docs or changing the default to `true` (which it says will be in the future?). Closing the issue makes me feel like my time was wasted writing this up.

Is there another issue that tracks that change?

**Comment by dougwilson** [comment]
Sorry, you didn't ask for any changes and there was no call to action I read in your paragraphs, so figured you just wanted to share. What are you looking to happen, perhaps if you can iutlin what you're looking for, I can help :)

**Comment by dougwilson** [comment]
> Is there another issue that tracks that change?

Not that I know of, because no one has asked for that to change. I added the deorecation because I think it should be changed, and wanted to see what would happen if people had to read the docs in order to choose a value to get rid of the warning and show all examples with it set to true so copy pasters would end up in what I think is the correct behavior.

**Comment by darknoon** [comment]
@dougwilson there is a warning? I didn't see it in my logs, not that it didn't get logged.

**Comment by dougwilson** [comment]
Yea, if you don't specify a value for  saveUninitialized it prints a warning to STDERR. Did you leave that value out when you tried? If you run the example at the bottom of the readme and comment out saveUninitialized you'll see the warning.

**Comment by dougwilson** [comment]
The warning seems to generate issues here (https://github.com/expressjs/session/issues?utf8=✓&q=saveUninitialized%20%20deprecated) and Stackoverflow asking questions, so I think there are people who see it. I don't have enough information on why you didn't see it, but can look into it if you want to put together a reproduxtion case I can try out.

**Comment by darknoon** [comment]
The error definitely doesn't show up in my logs and I have a guess as to why. It looks like session is using `depd` to output errors, and I'm using `babel-node` in a dev environment to transpile features not yet available in node.

According to the docs of `depd`, it says they are [not output when it is bundled](https://www.npmjs.com/package/depd#install) with webpack—would that apply to `babel-node` as well?

**Comment by dougwilson** [comment]
I'm not sure. How does node-babel work? It only doesn't output when a bundler loads the representation meant for a web browser; bundlers rinning for Node.js targets should not be loading web browser implementations, right? I can definitely take a look though if if you want to put together a reproduction case I can try out.

**Comment by darknoon** [comment]
Hmm, very weird. I made a test project and everything seemed to work fine with `babel-node`, `depd` directly, making a bad `session()`, even using it behind `nodemon` as I do.

Not sure why this happened but you definitely seem to be warning people.

**Comment by abcd-ca** [comment]
I have `saveUninitialized: false` but I also noticed tons of sessions quickly piling up in my database. I am not using Passport, and I don't know what's causing all of these except maybe bots crawling my endpoints. I don't see any suspicious activity like lots of login attempts. @dougwilson am I missing another setting? Thank you!
