### ISSUE TITLE
How to Ignore GET requests to /robots.txt file?

### ISSUE THREAD

**Issue by Zx-EvM** [expressjs/session#513]
I have a Node.js project. This project use local-auth with `passport.js`, `express-session` and `connect-mongo` package to store sessions in MongoDB `sessions` collection.

Each time when I update page or moving to another page, to `sessions` collection inserted 6 new items. Thus, across some time `sessions` collection becomes very large.

Code snippet for use `express-session` and `connect-mongo`:

```
var session = require('express-session')
var MongoStore = require('connect-mongo')(session)
app.use(session({
	resave: true,
	saveUninitialized: true,
	secret: secret.secretKey,
	store: new MongoStore({
		url: secret.database,
		autoReconnect: true
	})
}))
```

Morgan output in console (this happens for each page and page update):

```
C:\Users\User\Desktop\Project>node server.js
Node.js listening on port 3000
GET / 200 37.946 ms - 2670
GET /robots.txt 400 23.490 ms - 2328
GET /robots.txt 400 185.459 ms - 2328
GET /robots.txt 400 4.794 ms - 2328
GET /robots.txt 400 6.684 ms - 2328
GET /robots.txt 400 3.966 ms - 2328
GET /favicon.ico 400 7.314 ms - 2328
GET /robots.txt 400 3.713 ms - 2328
```

So, I think this happens by reason of many requests to non-existent `robots.txt` URL.

How can I make this file ignored in `express-session`?

Also I found this; http://codingteam.net/project/tapage/browse/node_modules/express/node_modules/connect/lib/middleware/session.js (lines 84 - 91):

```
 * Ignore Paths:
 *
 *  By default `/favicon.ico` is the only ignored path, all others
 *  will utilize sessions, to manipulate the paths ignored, use
 * `connect.session.ignore.push('/my/path')`. This works for _full_
 *  pathnames only, not segments nor substrings.
 *
 *     connect.session.ignore.push('/robots.txt');
```

But that's does not work in new versions of `express` and `express-session`.

**Comment by dougwilson** [comment]
There are two things you can do to keep down sessions:

1. Don't add anything to the session unless you actually want to persist something. This is the only sustaintable option that doesn't mean you have to keep an ever growing blacklist.
2. Add a middleware that will either (a) respond to the route before this middleware or (b) create a wrapper that doesn't invoke this middleware when some condition you determine is met (like the URL is a particular value).

**Comment by dougwilson** [comment]
Why do you have saveUninitialized: true in your config? That will cause the exact behavior you don't want.

**Comment by Zx-EvM** [comment]
@dougwilson if I set `saveUninitialized` to `false` that does not solve problem and new sessions still created.

btw, why `ignore` array deleted from express-sessions project?

**Comment by dougwilson** [comment]
Idk, that was never in this project.

**Comment by dougwilson** [comment]
Looking how that link implements ignore, it's identical to https://www.npmjs.com/package/ignore-paths so if that's ehat you need, wrap this middleware with that module to ignore the paths you need.
