### ISSUE TITLE
Session is different via routes

### ISSUE THREAD

**Issue by rico345100** [expressjs/session#515]
This is my session configurations:

```javascript
app.use(session({
	secret: '...',
	resave: false,
	saveUninitialized: false,
	maxAge: 1000 * 60 * 60		// 1 hour
}));
```

And this is my route codes:

```javascript
const express = require('express');
const router = express.Router();

router.use('/accounts', require('./accounts'));
router.use('/keys', require('./keys'));
router.use('/transactions', require('./transactions'));

module.exports = router;
```

Session is created when user success to login:

```javascript
router.post('/', (req, res, next) => {
	co(function*() {
		try {
			const { email, password } = req.body;
			yield auth.check(email, password);

			const getUsers = yield users.get({ email: email });
			const user = getUsers[0];
			
			const userInfo = {
				id: user.id,
				email: email,
				status: user.status,
				createdAt: user.createdAt,
				updatedAt: user.updatedAt
			};

			yield new Promise((resolve, reject) => {
				req.session.regenerate((err) => {
					if(err) {
						return reject(err);
					}

					req.session.userInfo = userInfo;

					req.session.save((err) => {
						if(err) {
							return reject(err);
						}

						resolve();
					});
				});
			});

			res.json(userInfo);
		}
		catch(err) {
			...
		}
	});
});
```

So after login, I got this sessions:
```javascript
Session {
  cookie: 
   { path: '/',
     _expires: null,
     originalMaxAge: null,
     httpOnly: true },
  userInfo: 
   { id: 1,
     email: 'test',
     status: 'inactive',
     createdAt: '2016-12-05T11:21:59.000Z',
     updatedAt: '2016-12-05T11:21:59.000Z'}
```

In **/account** route, I can see right session, but in **/keys** and **/transaction** routes, session is different, userInfo is just gone!

```javascript
Session {
  cookie: 
   { path: '/',
     _expires: null,
     originalMaxAge: null,
     httpOnly: true } }
```

Why I can only access correct session in **/account** route? What causes this?

**Comment by rico345100** [comment]
Well, I found when it's correct when it's not.

In each route uses middleware to check user have "userInfo" in session.

```javascript
function checkUserAuth(req, res, next) {
	if(req.session.userInfo) {
		return next();
	}

	next({
		status: 401,
		message: 'Unauthorized Request',
		stack: {}
	});
}
```

And /account was used the middleware inside of router.get:

```javascript
// GET /account
router.get('/', checkUserAuth, (req, res, next) => {
    ...
});
```

But /keys and /transaction used different way:

```javascript
router.use(checkUserAuth);

// GET /keys
router.get('/', (req, res, next) => {
    ...
});
```

As I know, both are same way to using middleware, or am I misunderstood?

Also I called checkUserAuth after printing the session(this is most weird part):

```javascript
// keys.js
router.use(function(req, res, next) {
	console.log('Session from keys');
	console.log(req.session);
	next();
});

router.use(checkUserAuth);

/**
 * Get keys
 */
router.get('/', checkUserAuth, (req, res, next) => {
    ...
});
```

If checkUserAuth middleware changes session, why printing session before checkUserAuth already changed even it wans't called?

**Comment by dougwilson** [comment]
Hi @rico345100 that's definitely weird and haven't seen this before. I really have no idea why that would be. I would love to attach a debugger and walk through the code to see what is happening, if you can provide all the following information:

1. Version of Node.js you're using
2. Version of this module you're using
3. Full, complete source code that reproduces the issue I can run on my machine. Above is only bits and pieces, and 99% of the time the issue is in a piece that was not originally included. I need all the code required to reproduce the issue to figure out what is happening.
4. Instructions for how to setup the code from (3) and specific instructions for how to interact with the server to see the issue (i.e. open browser to URL x, click on link Y, type in text Z, etc.).

Thank you!

**Comment by mittal01091997** [comment]
I myself having this issue, I am getting a cookie back for each session created.
Its working fine when I'm testing in postman, the session created is persisting.
But when i do the same in angular, and i send another response via different routes, it says that i'm not authenticated. (I cannot access the old session)
If someone has solution to this problem, please help me as well.

And also I saw that lot of other users are having this confusion, so I was wondering If the common problems and their solutions, along-with a step b step guide on how to do it could be added in Documentation for this Package.
Thank you.

**Comment by mittal01091997** [comment]
@dougwilson I made a test project for you to show you the exact problem i was facing with express-session.
When i was in development, i had the problem of server recognizing each request from different client.
But when i compiled the project and made it for production, the problem disappeared.

On further analysis, i think that i was using [cors](https://www.npmjs.com/package/cors), was not allowing, or i can say, causing the problem that i couldn't synchronize the front-end with back-end.

You can read [this](https://stackoverflow.com/questions/35945738/node-js-session-not-persisting) Stackoverflow question for more information on the topic.

Also [this](https://github.com/mittal01091997/Seed-Mean-Project/commit/30fca2349f2fed4912fba63e321ca064c66a82ad) is my production ready project that i made.
and [this](https://github.com/mittal01091997/Seed-Mean-Project/commit/e5c3c38eeda1eb5bbb3ef6ac5928dabee9af530f) is my project in development mode.

If you finally figure out the problem, please do add it in your documentation; I was pulling hairs on this problem from days as no sufficient info was available.

**Comment by gabeio** [comment]
@mittal01091997 please open a different issue ticket since your issue doesn't sound similar to this issue.

**Comment by mittal01091997** [comment]
@gabeio My issue was similar, and my issue, and this issue as well could be solved from what I've specified in my last reply.

**Comment by rico345100** [comment]
This issue actually blows up my mind, I was solved by just using checkUserAuth middleware inside of router.get/router.post, not router.use, but now this happens again! (And still don't get it why)

Look at this:

	function checkUserAuth(req:any, res:any, next:any) {
		return next();                    // JUST RETURN NEXT IMMEDIATELY
		if(req.session.userInfo) {
			return next();
		}

		next(new ExpiredResourceError('Session could not found1'));
	}

I just pass the middleware immediately without checking req.session but it still returns "Session could not found". This is part where using checkUserAuth:

	const { checkUserAuth } = require('../../../libs/middlewares');

	router.get('/', checkUserAuth, (req, res, next) => {
		co(function*() {
			try {
				const accountList = yield accounts.get({});
				res.json(accountList);
			}
			catch(err) {
				return next(err);
			}
		});
	});

What am I really going crazy is the middleware part. You can see the message of ExpiredResourceError has "1" at the end of the characters, and this is not typo, it's was intentional. 
So it must return "1" end of the error message but it still always returns without 1, and this means that it was came from something else but there is no more place using ExpiredResourceError!

This is ridiculous because some of router that uses exactly same middleware still works, and others not.

I have not much time to finish my project and this thing keep disturbing me. Using Node@6.9.2, and tested Express@4.16.2 and @4.14.0.

I can't give you full source code but I will make something else with same issue with this soon, maybe tomorrow, can't sure. I'm really close to deadline and this issue makes me crazy. When after I made that, please fix this quick.

**Comment by sindbad75** [comment]
Hi everyone, 
I have exactly the same problem: when I define a req.session.ANYTHINGYoutWant  (I choose here ".api") inside a Route (in server root), it is available in it's all Router. 
However, when I make a consol.log(req.session) in an other Route, test is not present.
It is here problematic to me because I want to conserve a parameter I get during the loading to use it in all my routes/requets.

Config: 
Node@8.8.1,
Express@4.16.2,
Express-session@1.15.6 with default session storage (MemoryStore).

My server root index.js:
```
import express from 'express';
import session from 'express-session';

// imports Routers
import dataBaseRoutes from './routes/dataBaseRoutes';
import homeRoutes from './routes/homeRoutes';
...

// Server
const app = express();

app.use(session({
  secret: 'keyboard cat',
  resave: true,
  saveUninitialized: true,
}));

app.use('/dataBase', dataBaseRoutes);
app.use('/home', homeRoutes);

...
```
My login Router (app.use('/dataBase', dataBaseRoutes);):
```
import express from 'express';

import { getLogin } from '...';

const router = express.Router();

router
  .route('/')
  .post((req, res, next) => {
    let sess = req.session;
    sess.api = 'token';
    console.log(sess);
    next();
  })
  .post(getLogin);

export default router;
```
My getLogin controller:

```
export const getLogin = (req, res) => {
  let sess = req.session;
  console.log(sess);
}
```
Results in the terminal:
```
Session {
  cookie: 
   { path: '/',
     _expires: null,
     originalMaxAge: null,
     httpOnly: true },
  api: 'token' }
Session {
  cookie: 
   { path: '/',
     _expires: null,
     originalMaxAge: null,
     httpOnly: true },
  api: 'token' }

```
As we can see here, the req.session.api is conserved/transmitted

On an other Router (app.use('/home', homeRoutes);), requested from the page where I am redirected after login:
```
import express from 'express';
import { getAllData } from '../controllers/homeController

const router = express.Router();

  .route('/api')
  .post(getAllData);

export default router;
```
The Controller:
```
export const getAllData = (req, res) => {
  let sess = req.session;
  console.log(sess);
}
```
Results in the terminal:
```
Session {
  cookie: 
   { path: '/',
     _expires: null,
     originalMaxAge: null,
     httpOnly: true } }

```
As we can see here, the req.session.api is  absent.

It seems here that the req.session.ANYTHINGYoutWant is available only in the Route where it is defined.
If you have any idea to solve my problem... thanks in advance!!!

**Comment by sindbad75** [comment]
I also try regrpouping all the routes in one:

```
import express from 'express';

const router = express.Router();

router
  .route('/')
  .post((req, res, next) => {
    let sess = req.session;
    sess.api = 'token';
    console.log(sess);
    next();
  })
  .post((req, res) => {
    let sess = req.session;
    console.log(sess);
  });

.route('/home')
  .post((req, res) => {
    let sess = req.session;
    console.log(sess);
  });

export default router;
```

but req.session. does not seem to be conserved/transmitted:
```
Session {
  cookie: 
   { path: '/',
     _expires: null,
     originalMaxAge: null,
     httpOnly: true },
  api: 'token' }
Session {
  cookie: 
   { path: '/',
     _expires: null,
     originalMaxAge: null,
     httpOnly: true },
  api: 'token' }
[...]
Session {
  cookie: 
   { path: '/',
     _expires: null,
     originalMaxAge: null,
     httpOnly: true } }

```

**Comment by sindbad75** [comment]
I notice that no cookie is created in my browser (FF or Chrome).
I read some issue about cookie creation and Localhost port.
I am working on Localhost:3000 (server)/3333(front in React.js) with Apache.

I also notice (probably a consequence of the cookie absence) that for each request done (passing trought different expresse Routes, the req.session.id is different.

Do you think the problem could be solved modifying Apache settings or by using an other session storage than the default MemoryStore?

**Comment by joewagner** [comment]
@sindbad75 The issue you are having is almost certainly coming from the way you have React or Apache setup.  If the cookie does not exist then this module has no way of serializing the session into the request.  Regardless, your issue sounds different than the OP.  Maybe you could write up a stackoverflow question, or open a separate issue if you think a problem exists in the `express-session` module.

**Comment by sindbad75** [comment]
Thanks,
I agree, it should come from my Apache setting.

**Comment by nebiros** [comment]
@sindbad75 did you fix that?, cause it's happening to me.

```
app.use(session({
  genid: (req) => {
    return uuid()
  },
  store: new FileStore({
    path: require('path').join(require('os').tmpdir(), 'sessions')
  }),
  secret: process.env.COOKIE_SESSION_KEY,
  resave: true,
  saveUninitialized: true,
  cookie: { maxAge: 1000 * 60 * 60 }
}))

const routes = require('./routes/routes')
const api = require('./routes/api')

app.use('/', routes)
app.use('/api', api)
```

Can't get anything from `req.session` at `api` module

**Comment by fatcat1970** [comment]
tnt
