### ISSUE TITLE
cannot retrieve session variable in different route

### ISSUE THREAD

**Issue by westdabestdb** [expressjs/session#519]
Hello, I am trying to set req.session.username on my sign in route and retrieve it in my profile route, but it says undefined on profile route. any help ?

**Comment by gabeio** [comment]
A few extra details will really help:
- Node Version
- Express Version
- Session Version
- Session-Store
- A fully working example (this does not have to be your actual app) that demonstrates the issue (this is important!)

**Comment by dougwilson** [comment]
Closing since there was no response.
