### ISSUE TITLE
generating new sessions with an asynchronous store

### ISSUE THREAD

**Issue by japherwocky** [expressjs/session#52]
Hi -

Since new sessions are [generated synchronously](https://github.com/expressjs/session/blob/master/index.js#L271), it can cause funny race conditions if other middleware layers (eg, authentication/authorization) are expecting the session to exist in the datastore.

This is kind of feature/flaw territory..  if cookies are encrypted, I guess it's safe for other middleware layers to trust what's in req.session, so maybe it's not something to be changed in the codebase.  And I guess calling `next()` without waiting around to see if the store did it's business helps benchmarks.

But maybe worth a note in the docs somewhere; this was causing our tests to fail in pretty random and mysterious ways and was kind of a PITA to track down.

**Comment by gireeshpunathil** [comment]
@japherwocky - is this still an issue for you? are you good with @dougwilson 's explanation to your concerns?

**Comment by japherwocky** [comment]
Sorry, this was so long ago, I have no idea if it's an issue for that project anymore.  Feel free to close the issue!
