### ISSUE TITLE
New cookie is not generated once 'connect.sid' is deleted

### ISSUE THREAD

**Issue by tanishqjain1002** [expressjs/session#527]
Like the title says, i was working with a Vue project and deleted 'connect.sid' by mistake(wanted to deleted other cookie). Now after refreshing and restarting also, the cookie isn't being set by express-session for some reason. I tried to imitate it again below:

1) I made a new Vue test project and made some dist files to be served
2) server.js
```js
const express = require("express");
const session = require("express-session");
const app = express();
const port = 3000;
const path = require("path");

app.use(express.static(path.join(__dirname, "dist")));
app.use(session({
	resave: true,
	saveUnitialized: true,
	secret: "kappa123"
}));



app.listen(port, () => console.log(`Server running on ${port}`));
```

Server is running!

![smooth 1](https://user-images.githubusercontent.com/2004372/33230433-477c7d18-d209-11e7-8c0d-c7b26cf35122.png)

Express is serving my index.html from '/dist' 

![smooth2](https://user-images.githubusercontent.com/2004372/33230424-19118e3c-d209-11e7-994c-3b8c38df6f8c.png)

Its all good!!!!

3) Delete 'connect.sid'

![smooth3](https://user-images.githubusercontent.com/2004372/33230458-b4114774-d209-11e7-9d8e-7426366af520.png)

4) Refresh 

![smooth4](https://user-images.githubusercontent.com/2004372/33230483-312e1ba6-d20a-11e7-8b42-eb9357b5716e.png)

The cookie is never generated again even after server restart

**Comment by tanishqjain1002** [comment]
**Workaround**: make a call to any route (regardless of its existence) and the cookie comes back but it creates a mess when writing middlewares

**Comment by dougwilson** [comment]
There must be something I'm missing, because I'm running the exact code you provided above and not getting the issue. I also don't see any of the page that you're seeing, so not sure if that's the difference or not.

Can you provide the following?

1. Version of Node.js
2. Version of this module.
3. Full app code that would show the same page you're showing above in your steps.

Thanks!

**Comment by tanishqjain1002** [comment]
@dougwilson This is the vue-cli app in production mode. Ill give you the code regardless.

**Comment by dougwilson** [comment]
Hi @tanishqjain1002 I'm not familiar with what Vue is or what vue-cli is, I apologize. If you can help me understand / learn it so I can figure out how to reproduce, that would be amazing !

**Comment by dougwilson** [comment]
Closing from no response.
