### ISSUE TITLE
No cookie generated

### ISSUE THREAD

**Issue by doliawu** [expressjs/session#529]
Express version: 4.15.5
Express-session version: 1.15.6

How to reproduce:
1. install express generator
`npm  i -g express-generator`
2. generate a project with the gererator
`express --view=pug express-test`
3. install express-session
`npm i --save express-session`
4. setup express-session middleware
modify `app.js` to following:
``` js
var express = require('express');
var path = require('path');
var favicon = require('serve-favicon');
var logger = require('morgan');
// var cookieParser = require('cookie-parser');
var session = require('express-session');
var bodyParser = require('body-parser');

var index = require('./routes/index');
var users = require('./routes/users');

var app = express();

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'pug');

// uncomment after placing your favicon in /public
//app.use(favicon(path.join(__dirname, 'public', 'favicon.ico')));
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
// app.use(cookieParser());
app.use(session({
  secret: 'session secret',
  resave: false,
  saveUninitialized: true,
  cookie: {secure: true}
}));
app.use(express.static(path.join(__dirname, 'public')));

app.use('/', index);
app.use('/users', users);

// catch 404 and forward to error handler
app.use(function(req, res, next) {
  var err = new Error('Not Found');
  err.status = 404;
  next(err);
});

// error handler
app.use(function(err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};

  // render the error page
  res.status(err.status || 500);
  res.render('error');
});

module.exports = app;

```
5. install other dependencies
`npm i`

6. start the app
`npm start`

7. Check on client if the cookie exists

**Comment by dougwilson** [comment]
Hi @doliawu thanks for the details reproduction steps! The reason is because of the setting in your app: `cookie: {secure: true}`. This setting will only use secure cookies, and since you didn't show that you made any modifications to actually setup a HTTPS server, the connection to your app wouldn't be secure and thus no cookie would be set. Removing that option will set the cookie over your HTTP connection.

I hope this helps!

**Comment by doliawu** [comment]
Exactly, thanks. @dougwilson
