### ISSUE TITLE
Reissue updated cookie when cookie domain setting changes

### ISSUE THREAD

**Issue by bruun** [expressjs/session#533]
I have an application that has been issuing session cookies without the `domain` option set. Now I would like to add a `domain` option (for subdomain support), and then tell clients to remove  their old cookie and set a new cookie that contains the domain. 

The only way I've been able to get around this is doing the following:
1. Setting the `rolling` option to `true`
2. Manually setting `request.session.cookie.domain` on every request.
3. In my case: Manually set `Set-Cookie` with a `Expires` value in the past, in order for the old cookie to expire. Some browsers, such as Chrome, will keep both cookies as they are valid for several domains. This will make sure the old cookie is removed, and a new one is set with the new domain.

This approach feels like a hack, especially as I don't want to send a `Set-Cookie` header on every request. What I'd like to achieve is that the old cookie is unset _once_, and that the new cookie is set _once_ when the `domain` option has changed.

Is there a better way to achieve what I want?

**Comment by bruun** [comment]
Using the technique described in #425 I have come up with a slightly better solution that doesn't require the `rolling` option to be enabled. Still, this feels like abusing the APIs and I don't feel confident that the behaviour won't break in the future.

```
if (req.session.cookie.domain === expectedCookieDomain) {
    next();
    return;
}

const prevSession = req.session;
req.session.regenerate((err) => {
    if (err) {
        return next(err);
    }
    Object.assign(req.session, prevSession);
    req.session.cookie.domain = expectedCookieDomain;
    res.set("Set-Cookie", `${sessionConfig.name}=deleted; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT; HttpOnly`);
    next();
});
```

**Comment by dougwilson** [comment]
Hi @bruun I don't see any kind of "API abuse" in your code example above. Is there anything in particular you are concerned about in it?

**Comment by bruun** [comment]
I guess it feels like abuse because I try to do something the documentation for **[req.session.cookie](https://github.com/expressjs/session#reqsessioncookie)** doesn't mention. If I only change the value of `req.session.cookie.domain` the cookie in the session store is updated with the domain, but the client does not get a `set-cookie` header response.

**Comment by dougwilson** [comment]
Hi @bruun we can always improve the documentation 👍 not 100% sure I understand your comment though; you're free to alter the contents of `req.session.cookie` as much as you want, which is pretty much what that documentation link says.

But yes, simply altering that I don't think causes a `set-cookie` to be generated by itself; if you have another setting that would trigger the `set-cookie` to appear (like `rolling: true`) then it should set with the alterations you made in that object, otherwise it will get set the next time a condition appears that will cause a `set-cookie` based on your settings.

**Comment by bruun** [comment]
My problem was that I assumed that any changes to a user's session cookie would trigger a `set-cookie` in the response, which I understand was a wrong assumption. Thanks for taking the time to answer @dougwilson , I'll close this issue now as I feel confident that the solution I ended up with is more than good enough.
