### ISSUE TITLE
will sync get/set works accurately when using db's session store?

### ISSUE THREAD

**Issue by ritesh-nitw** [expressjs/session#537]
I am using [mssql-session-store](https://github.com/jwathen/mssql-session-store) for my node.js app that runs in cluster mode.
 
Will sync session set and get calls: 
var currView= req.session['views'];
//do some work with currView
and 
 req.session['views']++
//do some work with req.session['views']

works accurately when used db's session store that takes sometime for updating and retrieving?

**Comment by dougwilson** [comment]
Hi @ritesh-nitw every time you alter the session object, at the response, this module hands the entire object back to your store. It's up to your store's logic on if it will replace all the field values (and thus the `++` operations end of overwriting each other) or does something smarter and only updates the changed fields.
