### ISSUE TITLE
Rancher Healthcheck session overload

### ISSUE THREAD

**Issue by Syno0** [expressjs/session#541]
Hello,

I have an application stored in a docker and managed by Rancher, this Rancher has an Healthcheck service that ping my application each second on the url "/".

And every time it happens (so each second) a new session is created in the sessions table in database.
By the way, this behavior doesn't occurred on local environment when I spam "/", but on Rancher the sessions table rapidly store hundred of thousands rows.

Any ideas ?
Thank you

**Comment by dougwilson** [comment]
Hi @Syno0 I've never heard of Rancher before so not sure off hand. Would it be possible to share the code and the request that is creating the new sessions?

**Comment by Syno0** [comment]
After reflexion I don't think that Rancher and his Healthchecker is the real problem here. Do you think that create a new session every time someone new go on "/" is a standard and acceptable behavior ? Should I create session only after logging ?

**Comment by dougwilson** [comment]
Creating a new session in your database doesn't always happen, it really depends on what your code is doing, so ideally I'd be able to see it. You really shouldn't create a new session if you know it's a health check, and yo can of course go further by not saving a session that you haven't put any data in as well, though this depends on if you want to correlate sessions across your site, etc.

**Comment by Syno0** [comment]
I use session like this in my server.js, so this code shouldn't create a new session every time someone new go on / ?

![image](https://user-images.githubusercontent.com/14804727/35057687-0291625a-fbb6-11e7-8de1-ce6c4ed575fb.png)

**Comment by gabeio** [comment]
You may want to change `saveUninitialized` to `false` as for every hit including health checks gets a session. Depending on how many and how fast your health checks are you might have a hell of a lot of open sessions.

**Comment by Syno0** [comment]
Well I count 444000 rows one hour ago so ... ^^
I'll try to set saveUninitialized to false and more globally to avoid session creation just by getting "/" url !
The weird part was that this health checker has a different uid (so considered as a new session) every time it get "/" but I don't think I can do anything on this side.

Thanks for the help!

**Comment by gabeio** [comment]
> The weird part was that this health checker has a different uid (so considered as a new session) every time it get "/" but I don't think I can do anything on this side.

exactly so by disabling the `saveUninitialized` the health checker should get no uid/session.
