### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by ryuhangyeong** [expressjs/session#545]
I am using express-session and connect-mongo.
And I found an unexpected error while creating the logout function. I have used this code well so far, but I have a problem I do not know.

```javascript
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));

app.use(session({
    secret: 'weqweqweqwe',
    resave: false,
    saveUninitialized: true,
    cookie: {
        maxAge: 14 * 24 * 60 * 60 * 1000
    },
    store: new MongoStore({
        mongooseConnection: mongoose.connection,
        ttl: 14 * 24 * 60 * 60
    })
}));
```

```javascript
// logout
exports.logout = (req, res) => {
    req.session.destroy((err) => {
        if(err) console.error(err);
        res.json("hello")
    });
    return;
        res.status(401).json({
        message: 'not logined!'
    });
}
```

error message
```bash
TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at executeOperation (C:\Users\USER\Desktop\project\daily-health-originer\backend\node_modules\mongoose\node_modules\mongodb\lib\utils.js:386:14)
    at Collection.remove (C:\Users\USER\Desktop\project\daily-health-originer\backend\node_modules\mongoose\node_modules\mongodb\lib\collection.js:1232:10)
    at withCallback.collectionReady.then.collection (C:\Users\USER\Desktop\project\daily-health-originer\backend\node_modules\connect-mongo\src\index.js:293:48)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

I am confused where I should report the issue. However, req.session.destroy () err printed the error.
It also fails to delete session data in connect-mongo at the same time as the error.

How can I get help? Thank you for your hard work.
If you want to see the full source code, please see below.

[Link](https://github.com/ryuhangyeong/daily-health-originer/tree/master)

**Comment by dougwilson** [comment]
It looks like the issue is that mongoose does not like something your app is storing in req.session object and so cannot convert it when trying to write to the database.

**Comment by ryuhangyeong** [comment]
I solve the issue, lowered the version of express-session and mongoose and connect-mongo.

maybe, the issue, to occur mongoose.

**Comment by ryuhangyeong** [comment]
@stuartkuentzel thank you, you answer.
