### ISSUE TITLE
Session not storing any value when using ajax

### ISSUE THREAD

**Issue by Prabhat-Emorphis** [expressjs/session#546]
I have a bizarre problem when I hit my node web API  from postman it store the value in session variable but from ajax it not working, every time I am getting 'undefined 'when I try to print or use session variable value.

This is my ajax calling.(I am storing session value in proper way, because from postman I am able to maintain session, let me know is I am doing anything wrong in ajax request).

// JS Code
var dt = {};
            dt['login_username'] = "example@mail.com";
            dt['login_password'] = "123456";
       $.ajax(
              {
                type: "POST",
                url:'http://172.16.1.69:3000/login',
                contentType: "application/x-www-form-urlencoded",              
                dataType: 'json', // type of response data
                timeout: 500,     // timeout milliseconds
                data:dt, 
                success: function (data) {   // success callback function
                    console.log(data);
                  },
                  error: function (errorMessage) { // error callback 
                    console.log(errorMessage);
                  }
              });

**Comment by joewagner** [comment]
@Prabhat-Emorphis Have you tried 
`contentType: application/json` 
?

Otherwise, Maybe try using your debugger to inspect the request/response for the Ajax call and see what is different from the Postman request/response
Failing that, if you could provide the following someone here will be able to help you:

1. Version of Node.js
2. Version of this module
3. Complete server and client code that reproduces the issue
4. Instructions on how to get the server running if it is more than copy and paste your provided code
5. Instructions on how to reproduce the issue.

**Comment by gabeio** [comment]
I don't know if this is ajax or xhr but a lot of issues about this have been solved with:
`credentials: 'same-origin'`

**Comment by Prabhat-Emorphis** [comment]
I am new in the backend so don't know the exact reason, but when I use IP(http://172.16.1.69:3000/login) instead of localhost(http://localhost:3000/login') it works.

**Comment by arihantdaga** [comment]
I am facing the same. 
From postman i am able to store session. 
Although when doing an api call using axios its not setting any session. 

I am running my dev server on localhost:8080 and 
This is the response header from my api server - 
`set-cookie: connect.sid=s%3ARkWOEHBm9w8UZtwPBpHjpbdiZNyzdMCi.D26552ngjuV4iFGNQY4mAZokzoMZCMgz41Bx9akMAzw; Domain=staging.mydomain.com; Path=/; HttpOnly`

But in subsequent requests to the api server browser is not appending any cookie and hence i am not getting any session value in backend(Api Server). 

This is what i used to initialize session 

```
let sess = {
  secret: 'MySecret',
  resave: false,
  saveUninitialized: true,
  cookie: { domain: "staging.theopendiaries.com", sameSite:false}
};
app.use(session(sess));
```
