### ISSUE TITLE
Feature Request: Promisification

### ISSUE THREAD

**Issue by govindrai** [expressjs/session#547]
Hi Doug,

Besides just not being able to get to it (which is totally fine), is what is the reason for the library not being promisified?

Thanks!

**Comment by gabeio** [comment]
Two things:

- I had to actually look up the word promisified to realize you mean promises.

- Are you asking why have haven't used them in the library or why we don't offer them in the api? (which I guess in turn means use them to an extent)

**Comment by dougwilson** [comment]
I'm not sure what this means.

**Comment by govindrai** [comment]
Hi guys, sorry for the confusion. Yes, I am wondering why promises are not offered in the api? Thanks!

**Comment by dougwilson** [comment]
I'm not really familiar with them. If someone wants to PR adding promises, then we can take a look 👍

**Comment by govindrai** [comment]
Gotcha. @dougwilson I'm not really confident in my abilities to promisify the library, but I'll definitely give it a shot if/when I get some time. You can close this ticket if you wish.

**Comment by gabeio** [comment]
I think the tests should be a good way to know if you are going in the right direction :+1:.

**Comment by dougwilson** [comment]
Since it's been over a month, I'm going to close the ticket for now. If you do have some code proposals or guidance on what it would mean to support Promises here, I can definitely re-open 👍 Basically something we can take some action on.
