### ISSUE TITLE
Troubleshooting for micro-service application + if I remove cookie-parser => no session

### ISSUE THREAD

**Issue by Inateno** [expressjs/session#553]
Hi,

I'm using both npm for a long time now when I came across different articles and threads about securing cookie over https, people were talking about "not using both" (and I cannot find anything related in the doc).

So today I'm using cookie-parser + express-session (stored in Redis).
IF I remove cookie-parser, no session is created (and server explodes in errors about "undefined property" everywhere).

Here is my config (and order):
I precise that I'm using a client actually hosted on "mydomain.com" and 6 servers hosted on "a.mydomain.com", "b.mydomain.com" etc...

```javascript
  var expressSessionOptions = {
    secret            : process.env.SECRET_SALT_SESSION || "secret"
    ,resave           : false
    ,saveUninitialized: true
    ,store            : new RedisStore( redisOptions ) // XXX redis server config
    ,cookie: {
      // httpOnly: false, // not sure
      // secure  : false, // not sure
      // path    : "/hexa", // do nothing
      maxAge  : 2*60*60*1000 // ok
      // domain  : "mydomain.com" // not working
    }
  };
  var cookieParserOptions = {
    domain: "mydomain.com"
  };
  
  app.use( function( req, res, next )
  {
    var origin = req.headers.origin;
    res.header( "Access-Control-Allow-Origin", origin || "localhost" );
    res.header( "Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept, authorization" );
    res.header( 'Access-Control-Allow-Credentials', true );
    res.header( 'Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE' );
    
    next();
  } );
  
  app.use( cookieParser( process.env.SECRET_SALT_COOKIE || "secretother", cookieParserOption ) );
  
  app.use( sessionMiddleware );
  
  app.use( bodyParser.json() );
  app.use( bodyParser.urlencoded( { extended: false } ) );

  // rest of the declaration, routes etc....
```

As you can see I tried a lot of different stuff and when I set "domain" or "path" in express-session the cookie seems broken (and I don't see it in the chrome dev tool cookie tab).

I precise also that I need this option "domain" to work because I made a micro-services architecture (but actually it's completely broken and the session isn't recovered between all my servers because the cookie is different).

I also saw another option to manually recover the session from Redis (ok easy) and put it in express-session (I don't have any idea about how to do this one).

Any help would be glad, I'm struggling on this for more than 20 hours and I'm upset about this lol.

Edit:
I forget to mention my npm packages versions:
```json
    "connect-redis": "^3.3.3",
    "cookie-parser": "^1.4.3",
    "express": "^4.16.2",
    "express-session": "^1.15.6",
```

**Comment by Inateno** [comment]
After hours of trying different configurations I finally got something working.

Here is my new config (I changed order`of some calls).
```javascript
  var expressSessionOptions = {
    secret            : process.env.SECRET_SALT_SESSION || "secret"
    ,resave           : false
    ,saveUninitialized: false
    ,store            : new RedisStore( redisOptions ) // XXX redis server config
    ,cookie: {
      httpOnly: false,
      // secure  : false, //nop
      // path    : "/hexa", // seems not working
      maxAge  : 10*60*60*1000 // 10 hour
    }
  };
  var cookieParserOptions = {
    httpOnly: false
  };
  
  if ( process.env.NODE_ENV === "prod" )  {
    expressSessionOptions.cookie.domain = ".mydomain.com";
    expressSessionOptions.domain = ".mydomain.com";
    cookieParserOptions.domain = ".mydomain.com";
  }

  const sessionMiddleware = session( expressSessionOptions );

  app.use( cookieParser( process.env.SECRET_SALT_SESSION || "secret", cookieParserOptions ) );
  // I was setting 2 different secret, but now I set the same and it seems to work
  // app.use( cookieParser( process.env.SECRET_SALT_COOKIE || "secret", cookieParserOptions ) );
  
  app.use( sessionMiddleware );
  app.use( bodyParser.json() );
  app.use( bodyParser.urlencoded( { extended: false } ) );

  // the rest of the declarative stuff
``

Still, I don't understand why without cookie-parser it's not working.

**Comment by dougwilson** [comment]
When it is not working, what is your value of `process.env.SECRET_SALT_SESSION`? I see that one difference between your old and new code is that you changed the default secret when that variable is not defined -- the first example they were different from each other (which thus would be broken) and the second example the default secret is now the same.

**Comment by Inateno** [comment]
Yes in my first code SALT between session and cookie were different.

But as I said I don't understand why it is not working without cookie-parser since the doc says the opposite.

Would be nice to have this documented, cauz' I tried all the things possible lol.

I also set the domain to cookie and session.

**Comment by dougwilson** [comment]
I don't know why it is not working without cookie-parser either, because I never use cookie parser in any of my apps with this module. I would like to figure it out. Maybe can you provide all the following so I can debug through what is going on?

1. Version of Node.js
2. Exact version of all the modules you are using
3. Complete source code I can copy and paste and run without modification to see the issue

Thanks! I want to get to the bottom of this, because cookie-parser is not required to use this module.

**Comment by dougwilson** [comment]
I'm going to close this since I never heard back to understand why this is happening. If you can provide the information above, I can always re-open 👍

**Comment by Inateno** [comment]
Yeah sorry for time. I have to create a sample to reproduce the exact environment, but can't do it right now.
Will do.
