### ISSUE TITLE
Warning: connect.session() MemoryStore is not designed for a production environment

### ISSUE THREAD

**Issue by dennisat** [expressjs/session#556]
Hi ExpressJs

I have a NodeJs app, where on production I am getting this message.

> Warning: connect.session() MemoryStore is not designed for a production environment, as it will leak memory, and will not scale past a single process.

After some debugging, I found out that this is coming from you. 
In precise, [from here](https://github.com/expressjs/session/blob/c720066af13d1719609096f7a24d850de9b39550/index.js#L54)

How can we fix this? What should we do to do not have any _memory leaks_?

Thank you in advance.

**Comment by dougwilson** [comment]
Just choose a store from the list https://github.com/expressjs/session/blob/master/README.md#compatible-session-stores that fits your needs best and provide it as the store option https://github.com/expressjs/session/blob/master/README.md#store :+1:

**Comment by dennisat** [comment]
Awesome! Thanks!
