### ISSUE TITLE
Option to read header other than 'cookie'

### ISSUE THREAD

**Issue by george-of-croton** [expressjs/session#559]
Currently the code reads the cookie from the header like so:

```javascript 
  var header = req.headers.cookie;
```
Is there any reasons why adding an option to define a cookie key, or set of keys would be bad?

I'm using both axios and request(i like the streaming api) in my application and request always removes the header 'cookie' because its a reserved word in the library.

I'm happy to make a PR but wanted to make sure it's something people wanted.

**Comment by dougwilson** [comment]
Right now, this module doesn't have a way to get the key other than a cookie, so it's also coded to only read from the cookie again. How are you getting the value from the module currently?

**Comment by dougwilson** [comment]
P.S. I've never had a problem using Cookies (including the cookie header) with axios, so not sure what you're doing that is preventing you from using the cookie header through axios. Maybe if you wanted to provide a reproduction case here why you cannot use the Cookie header, we may be able to help solve your axios issue.

**Comment by george-of-croton** [comment]
Issue more to do with the request than express session. Thanks for your help regardless, @dougwilson.
