### ISSUE TITLE
Request: method for updating all matching sessions

### ISSUE THREAD

**Issue by wmertens** [expressjs/session#561]
I'm pondering the problem of storing user data in the session db. This avoids another db lookup, but if the user's authorization level changes (user is banned or becomes admin etc), then the copies in the store will no longer be accurate.

The only store method that could be used to update the sessions is `.all`, but that doesn't scale.

So, perhaps there could be a store function `.updateMatching(filterDef, callback)` which takes a store-specific filter definition and calls the callback on all matching sessions?

It could fall back to a small wrapper with `.all` for sessions that don't support `.updateMatching`.

**Comment by dougwilson** [comment]
Each store technology has different abilities to search, retrieve, etc. You need to request this method from the store module you're using, assuming that has the ability to search through the sessions.

**Comment by edwardaa** [comment]
Here is my approach, `MemoryStore` and `MongoDBStore` are taken into account, you may add more store implementations like `RedisStore`.

*Note: User sessions are saved into the `user_data` field in code below.*
```js
/**
 * Update session.
 *
 * @param {Object} store Session store
 * @param {number} userId User ID
 * @param {object} update
 *
 * For example
 * <pre>
 *   updateSession(req.sessionStore, 1, { user_type: 'person' });
 * </pre>
 */
module.exports.updateSession = function (store, userId, update) {
  const storeType = store.constructor.name;
  if (storeType === 'MemoryStore') {
    // https://github.com/expressjs/session/blob/master/session/memory.js#L58
    store.all((err, sessions) => {
      for (const sessionId in sessions) {
        const session = sessions[sessionId];
        if (session.user_data.user_id == userId) {
          Object.assign(session.user_data, update);
          store.set(sessionId, session);
        }
      }
    });
  } else if (store.client && store.client.constructor.name === 'MongoClient') {
    // https://github.com/mongodb-js/connect-mongodb-session/blob/master/index.js#L83
    const collection = store.db.collection('sessions');
    const setValue = {};
    for (const key in update) {
        setValue[`session.user_data.${key}`] = update[key];
    }
    collection.updateMany({ "session.user_data.user_id": +userId }, { $set: setValue });
  } else {
    throw new Error('Unrecognized session store: ' + storeType);
  }
}
```
