### ISSUE TITLE
uid-safe doesn't seem appropriate (collisions)

### ISSUE THREAD

**Issue by greghawk** [expressjs/session#563]
We have an environment that has two servers using clustering (node instance per processor) and a shared redis store (two node/nix machines with 8 procs each).  In this enviro with enough traffic we are seeing users getting same cookie id thereby exposing private data to random users that get this shared id.  I think the source is the pseudo random bytes of uid-safe used on mutli-processes on same host.  I am going to try to use genid to set a guid for now and see if that works. We had to shut off all traffic due to this.

**Comment by dougwilson** [comment]
Very interesting. I use this module as-is to serve about 200,000 unique session across many server per day without collision. I definately would like it to work out of the box with as much as possible for sure. What aspect specifically do we need to change to work with your traffic distribution. Would simply switching to ceypto.randomBytes for sure solve the issue?

**Comment by wesleytodd** [comment]
I am not a crypto expert, but I can certainly say that I would trust node core's random bytes over a custom method.  If you are actually getting collisions (unlikely for 24 random bytes) you could use the `genid` option to check and regenerate the session id if one already exists in your session store.

**Comment by dougwilson** [comment]
Closing because we never heard back.

**Comment by greghawk** [comment]
@dougwilson  I apologize. got sidetracked.  It ended up being a shallow copy with a deeper property that was by ref that was augmenting the data. Our original threaded testing looked like dups were being made.
