### ISSUE TITLE
Values set on session cookie not persisting across session

### ISSUE THREAD

**Issue by kurokoda** [expressjs/session#569]
I am using fetch to GET a test value from a server which is deployed on a different origin. On login, I am setting a ```user_id``` value on the session and then performing this GET call using fetch:

```getData() {
    const url = `${config.API_BASE_URL}/test`;
    fetch(url, {
      method     : 'GET',
      mode       : 'cors',
      credentials: 'include',
    })
    .then(function (response) {
      console.log(response.json());
    })
    .catch(function (err) {
      console.log(err);
    });
  }
```

When this call is received on the server, the session has no ```user_id``` property set.

If I console log the session, the output is as follows:

```login success Session {
  cookie: 
   { path: '/',
     _expires: null,
     originalMaxAge: null,
     httpOnly: false,
     secure: false },
  userId: 5ab07417768692bcde934bbf }
POST /api/user/login 200 135.444 ms - 184
Session {
  cookie: 
   { path: '/',
     _expires: null,
     originalMaxAge: null,
     httpOnly: false,
     secure: false } }
GET /test 304 0.833 ms - -
```
What am I doing wrong?

**Comment by dougwilson** [comment]
Hi @kurokoda very strange indeed. I'm really not sure what could be going on here. Is there a way you can provide code that I can run to reproduce the issue? I can then try to dig in to diagnose what is happening here. I would ideally need the following:

1. Version of Node.js
2. Version of this module and all other modules used in the example.
3. Complete example code that I can run (ideally just from a copy + paste + run). The less I have to modify the code to make it run the better, so we're running the same thing.
4. Instructions for how to get the code running and instructions for how to reproduce the issue.

Thanks!

**Comment by kurokoda** [comment]
Hi @dougwilson !

I can actually give you the entirety of the code at this point. I just created public github repos for them in order to share with you. 

To run the app locally:

`mkdir test  
cd test
git clone git@github.com:kurokoda/stepping-up-frontend.git
cd stepping-up-frontend
node run start
`
Open a second terminal window

`cd test
git clone git@github.com:kurokoda/stepping-up-backend.git
cd stepping-up-frontend
node run start
`

1. Open your browser to localhost:3000, navigate to login. 
2. Login and using the credentials provided. 

You will be redirected to the user dashboard. In your terminal console, you should see the error above. In your browser console, you should see `foo {data: "test"}`, which is the output of a fetch on the user dashboard page.

**Comment by kurokoda** [comment]
@dougwilson I've also confirmed that the session.id is different on each call.

**Comment by dougwilson** [comment]
Hi @kurokoda how come in your code you shared none of the fetch calls have `credentials: 'include'` like the one you posted at the top of this thread? Cookies won't be included in the request with out that and would definitely cause the issue you're seeing, though your initial post made it seem like you did have `credentials: 'include'` in you code. Is this the correct code I'm looking at?

**Comment by dougwilson** [comment]
Your `superagent` calls would also need `.withCredentials()` method in the chain as well to enable credentials on those calls too.

**Comment by kurokoda** [comment]
@dougwilson I realized that due to your previous comment. Proving the axiom 'the weirder the bug, the more likely it is your fault', that fixes it.

**Comment by knoxcard** [comment]
Close Ticket?
