### ISSUE TITLE
Unable to clear cookie with rolling option set to true

### ISSUE THREAD

**Issue by thesynthetic** [expressjs/session#573]
I can easily set and clear cookies with session rolling set to false but can't seem to clear a cookie after rolling is set to true.  Any ideas here or is this a bug?

```
app.use(session({ key: 'user_sid',
                        secret: 'secret',
                        resave: false,
                        saveUninitialized: false,
                        cookie: {
                          maxAge: 90*24*60*60*1000
                        }, 
                        rolling: true,
                        store: new MongoStore({url: 'mongodb://localhost/session'}),
}));

app.use((req, res, next) => {
         // req.session.test = 1; //for setting cookie
         // res.clearCookie('user_sid').end(); // for clearing cookie
         next();
});
```

**Comment by dougwilson** [comment]
Because when `rolling: true` is set, this

> Force a session identifier cookie to be set on every response.

This means that your clear cookie ends up getting overwritten. If you call `req.session.destory()` to destroy the session, the cookie will not be forced set on the response. Does this work for you?

**Comment by thesynthetic** [comment]
Works perfectly, thank you. 

Would you be able to elaborate on why this works?  Is it because `res.clearCookie() `basically just overwrites the `expires` parameter which later on gets overwritten again to "now + maxage" because `rolling` is true?

**Comment by dougwilson** [comment]
Both cookies are in the response. The browser had to choose with one to honor. If you only include one, the browser will definitely choose the one you want.
