### ISSUE TITLE
Options name has been changed from "name" to "key".

### ISSUE THREAD

**Issue by abernov** [expressjs/session#575]
Options name has been changed from "name" to "key".

Please correct the main page!

**Comment by dougwilson** [comment]
I'm not sure what you're referring to and what you want changed. Can you be more specific? Or feel free to even submit a pull request with the change.

**Comment by abernov** [comment]
**name**
The name of the session ID cookie to set in the response (and read from in the request).

The default value is 'connect.sid'.

Note if you have multiple apps running on the same hostname (this is just the name, i.e. localhost or 127.0.0.1; different schemes and ports do not name a different hostname), then you need to separate the session cookies from each other. The simplest method is to simply set different names per app.
----

No option **name** at current release. Please change to **key**

**Comment by dougwilson** [comment]
What version of this module are you using? The property is called "name" in the current version.

**Comment by dougwilson** [comment]
In very old versions of this module (prior to 1.1.0) the option name was "key". In 1.1.0 we added the new option "name" and deprecated using "key". You can see this in our changelog: https://github.com/expressjs/session/blob/master/HISTORY.md#110--2014-05-12

**Comment by abernov** [comment]
I'm sorry, there was version 1.0.4
