### ISSUE TITLE
Prevent the session from expiring

### ISSUE THREAD

**Issue by mrhaxic** [expressjs/session#576]
Hello..

I would like to prevent the session from expiring where I use the node application as a backend for a mobile application, so I want the user to log in once time then the session will not expire unless the user didn't log out from the application, as a social app.

I tried the following options, but sometimes when mobile application have updated the session from the user is being lost and I have to log out and log in again.

`app.use(
  session({
    secret: "ssssxx",
    resave: true,
    saveUninitialized: false,
    store: new MongoStore({ mongooseConnection: mongoose.connection }),
    cookie: {
      httpOnly: false,
      expires: new Date(253402300000000)
    }
  })
);`

Any support would be appreciated :)

**Comment by dougwilson** [comment]
I'm not sure there is anything this module can do. It sounds like the app itself is deleting the cookie when it updates, right? If you can put together something I can run and replicate the issue I can help debug it.

**Comment by mrhaxic** [comment]
@dougwilson Actually, I am using Alamofire library. In addition, I didn't handle the cookie from the app [client] side. Is there any advise?

**Comment by dougwilson** [comment]
I've never used that off hand or made an app, so don't have any context to provide. I assume the app is automatically storing the cookie somewhere and sometimes deletes it? If you can put together something I can run and replicate the issue I can help debug it :+1:

**Comment by mrhaxic** [comment]
This class enables the app to send a request for the express server I paste especially the login API.

`import UIKit
import Alamofire
import SwiftyJSON

class API: NSObject {
    
    static var sessionManager  = SessionManager(configuration: .default)

    public static func login(username: String, password: String, completion: @escaping ((_ success:Bool, _ statusCode: Int?, _ username: String?) -> Void)) {
        var success = false
        let url = Helper.URL + "users/login"
        var params = Parameters()
        params["username"] = username
        params["password"] = password
        sessionManager.request(url, method: .post, parameters: params).validate().responseJSON { response in
            switch response.result {
            case .success(let value):
                let json = JSON(value)
                success = true
                completion(success,200,json["username"].stringValue)
            case .failure(let error):
                print(error)
                success = false
                if let httpStatusCode = response.response?.statusCode {
                    completion(success, httpStatusCode,nil)
                    if httpStatusCode == 401 {
                        Helper.sharedInstance.showError(message: "Your password was incorrect")
                    }
                    else if httpStatusCode == 402 {
                        Helper.sharedInstance.showError(message: "The username doesn't belong to an account, Sign up!")
                    }
                    else {
                        Helper.sharedInstance.showError(message: "Something goes wrong, try again!")
                    }
                } else {
                    completion(success, nil,nil)
                    Helper.sharedInstance.showError(message: "Something goes wrong, try again!")
                }
            }
        }
    }

    static let sharedInstance : API = {
        let instance = API()
        return instance
    }()

}`

**Comment by dougwilson** [comment]
I don't see anything explicit about cookie, so it must be implicit. Is there documentation for how that library manages cookies I can read?

**Comment by mrhaxic** [comment]
What is about https://github.com/Alamofire/Alamofire/blob/master/Documentation/AdvancedUsage.md#session-manager

Honestly, I have read deeply but I didn't get the best solution for that.

**Comment by dougwilson** [comment]
Hm, I still don't see any mention of how it is managing cookies. Any other docs I can read that talk about how cookies are managed?

**Comment by mrhaxic** [comment]
@dougwilson Unfourtantly, I am not sure. I am thinking to revamp the server-side to use JWT but I believe there is a resolution for that sessions because I prefer it.

**Comment by dougwilson** [comment]
Yea, not sure what to tell ya. Maybe if you can put together something I can run and replicate the issue I can help debug it 👍?

**Comment by mrhaxic** [comment]
@dougwilson I really appreciate your kind support, let's me reproduce that more and I will lets you know the soonest. Maybe there are another hint from developers also.

**Comment by dougwilson** [comment]
Closing since I haven't heard back.
