### ISSUE TITLE
Dynamic options

### ISSUE THREAD

**Issue by gfpacheco** [expressjs/session#578]
My white-label application serves several customers, and for each one I would like to set different options based on headers I receive on each request (cookie name for example).

I already forked and made the name option to accept both string and function types. If it's a function it sends the req to that function that will return the actual cookie name that should be used.

I'm just opening this for discussion, if you think it's a good fit for the lib I could open a PR implementing it, it could be done for other options as well, not only name.

What do you think?

**Comment by dougwilson** [comment]
It's been discussed several times already and it's basically been a no, in that you should make a new instance of this middleware for each matrix of option you want. This will scale to _any_ middleware you can possibly use and doesn't require every middleware out there to accept dynamic options as well as complicate the internals of evey one to account for options being dynamic with every invocation.

**Comment by gfpacheco** [comment]
The idea seems good, except I'll have to create the middlewares in start time and knowing how many customers in advance.

But that's fine, I understand that isn't a general use case and I'll keep using my fork, I really just wanted to know if it would be a good fit for the lib.

Thank you very much!

**Comment by dougwilson** [comment]
No problem. And you don't have to create them at start time or know how many ahead of time. Just create a middleware and call into a factory that creates this middleware with the parameters you want. Add memoization around your factory and that's it.
