### ISSUE TITLE
how a page automatically redirect to login page after session expire

### ISSUE THREAD

**Issue by SangramBadiHPE** [expressjs/session#580]
when a user found as ideal then i need to count expiry time. After session expire it'll automatically redirect to login page. below is my code. can anyone tell me how to handle this ?

```
var session = require('express-session');
app.use(session({
	secret: 'Test Service',
	name: "test",
	saveUninitialized: true,
	resave:false,
       //here is code for max age. i want to redirect from here. so is it possible ?
	cookie: {
		path: '/',
		maxAge: 1 * 10 * 60 * 1000,	
		overwrite: false	
	}
}));
```

**Comment by AshishkrGoyal** [comment]
@SangramBadiHPE maxage which u have set is in milisec according to the official docs.
so i must say that it is the 600 sec i.e. 10 minutes...

i think you can handle redirecting by this way !

**Comment by SangramBadiHPE** [comment]
@AshishkrGoyal yes i can change it to milisec. but is there any attribute or any json key present by which i can redirect to onther page after time out

**Comment by dougwilson** [comment]
> but is there any attribute or any json key present by which i can redirect to onther page after time out

No, that is something you'll need to implement yourself in your app.
