### ISSUE TITLE
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option

### ISSUE THREAD

**Issue by AshishkrGoyal** [expressjs/session#581]
warning message in command line is like it :
![image](https://user-images.githubusercontent.com/25322851/39418137-339824fe-4c76-11e8-9f40-41a693207e37.png)

I want to know why this warning message exist here !

Anykind of help is appreciated !

Thanks !

**Comment by dougwilson** [comment]
The error message says the issue is on line 56 in your srrver.js. please scroll down to that line.

**Comment by AshishkrGoyal** [comment]
This is at line number 56:9 
![image](https://user-images.githubusercontent.com/25322851/39439292-c37a2a42-4cc4-11e8-8332-d61ee650ee97.png)

@dougwilson Thanks for your help !

**Comment by dougwilson** [comment]
Looks like the option is misspelled. The capital I should be lowercase i.

**Comment by Dallyla** [comment]
You've just misspelled. The correct is **saveUninitialized**.

**Comment by guidomiranda** [comment]
Provide saveUninitialized option:  add saveUninitialized: true on line 62.
