### ISSUE TITLE
session does not save to store unless manually done

### ISSUE THREAD

**Issue by quiltykim** [expressjs/session#585]
Hello. While I'm able to run `req.session.save(() => res.send())` just fine in my route handler for `/` GET requests, doing that adds a session to my store per visit.  However, I'd like for the session to only persist upon changes and removing the call to `req.session.save()` makes me not persist any sessions at all, which I'd check by running `select * from session_test`.  The code is as follows:
```
var express = require('express');
var app = module.exports = express();
var session = require('express-session');
var MySQLStore = require('express-mysql-session')(session);

var options = {
    host: 'localhost',
    port: 3306,
    user: 'session_test',
    password: 'password',
    database: 'session_test'
};

var sessionStore = new MySQLStore(options);

app.use(session({
    key: 'session_cookie_name',
    secret: 'session_cookie_secret',
    store: sessionStore,
    resave: false,
    saveUninitialized: false
}));
app.get("/", (req, res) => {
  console.log("session here>>", req.session);
  res.send("foo");
});

app.listen(8080, () => console.log("listening on 8080"));
```

**Comment by dougwilson** [comment]
Your code does not save any session because you have saveUninitialized: false in the options and you never set anything in the session to save.

**Comment by quiltykim** [comment]
thanks! *slaps self*
