### ISSUE TITLE
Q: Rolling session with a touch

### ISSUE THREAD

**Issue by Martii** [expressjs/session#590]
Is there an event emitted somewhere that isn't documented *(or not yet created)* to maintain a restful state that triggers when a rolling session is ready to expire.

E.g. We would like to [touch](https://github.com/expressjs/session/blob/0c605637ef051ec4d77f0a4fa4fac4cae9483c06/README.md#sessiontouch) a [rolling session](https://github.com/expressjs/session/blob/0c605637ef051ec4d77f0a4fa4fac4cae9483c06/README.md#rolling) if the account has a flag on it to keep the session alive.

Thank you for any insight and thank you for your contributions to the *node* and *express* community. :)

**Comment by dougwilson** [comment]
Since the expiration of sessions is tracked by the store you are using, the store would need to implement the, as I understand your question, "preExprie" event.

**Comment by Martii** [comment]
We use mongodb as the store... and yes a preexpire event would be nice to have in order to remember that they want to stay logged in but only as a choice. 

I've been looking for it casually for about a year and no luck in finding such a thing... a bit frustrated that I can't find the right terminology to search for it successfully.

**Comment by dougwilson** [comment]
Yea, I've never used Mongo so have no idea on that front. For Redis, for example, it has the concept of keyspace events (https://redis.io/topics/notifications) you can subscribe to know when a key (i.e. a session that is stored in Redis) is about to expire.

**Comment by Martii** [comment]
Seems it's over at https://github.com/jdesboeufs/connect-mongo/issues/217 ... this will take a bit of time to absorb and translate to how it's done with our current system. 

Appreciate your response and the right terminology to search for. :)
