### ISSUE TITLE
Changing secret?

### ISSUE THREAD

**Issue by loomne** [expressjs/session#591]
Hi, i want to ask if is possible to change secret every 10 minutes.
I just use https://www.npmjs.com/package/node-cron, but there is nothing like session.option.secret, so i cannot change it..

**Comment by dougwilson** [comment]
If you want to change it, just reconstruct the middleware and new requests will use the new settings. A standard thing you can do with every Express.js middleware. Here is an example:

```js
var sessionMiddleware = session(options)

app.use((req, res, next) => sessionMiddleware(req, res, next))

cron(() => {
  options.secret = gensecret()
  sessionMiddleware = session(options)
})
```

**Comment by wesleytodd** [comment]
What @dougwilson shows is the way, but the secret is used to sign the cookie.  So if you change the secret it will invalidate all the session cookies you set.   Just be aware of that.

**Comment by dougwilson** [comment]
Yes, that is a good point @wesleytodd . You can get around that by setting `secret` to an array instead of a string. The first element of the array is what is used to sign new cookies and all the rest are used to validate existing ones. This way you can roll through them without invalidating.
