### ISSUE TITLE
Get the Session from sid in Express

### ISSUE THREAD

**Issue by n0807701j2d2** [expressjs/session#594]
I'm trying to set up multiple websocket servers that handle users with one central http server. The express program sets up a session during login by storing the username in session, and the user is redirected to a page with a websocket client. The websocket server then tries to break down the session and receive the username when the client connects. It became obvious during testing that the user object is only stored on the http server (not within the cookie) and is not actually receivable on the websocket server. Here's the http server code:

    var http = require('http');
    var Express = require('express');

    var bodyParser = require('body-parser');
    var session = require('express-session');
    var sessionParser = session({
        secret: 'lalala',
        cookie: { 
            maxAge: 3 * 60 * 60 * 1000
        },
        resave: true,
        saveUninitialized: true
    });

    var app = Express();

    app.use(sessionParser);
    app.use(bodyParser.json());
    app.use(bodyParser.urlencoded({
        extended: true
    }));

    var server = app.listen(args.port, function() {
        console.log("HTTP server connected!");
    });
Now that I've explained the whole problem, my question is: how can I get the username stored in the session by just the session id?

P.S. To avoid confusion, this question is not about getting the username off of an http GET/POST request. Essentially, I'm asking WHERE the sessions are stored on the http server program so that I can retrieve the username by only providing the session_id.

**Comment by dougwilson** [comment]
Because you never set up a session store and passed it to this module, you are using the memory store that is for basic development and is only in the http server memory. You want to actually use a store that stores sessions by the sid in a database.

The list of stores you can use is in the readme: https://github.com/expressjs/session/blob/master/README.md#compatible-session-stores
