### ISSUE TITLE
req.session.destroy() not working as intended

### ISSUE THREAD

**Issue by Illuminati4Life** [expressjs/session#596]
req.session.destroy() returns a TypeError: req.session.destroy() is not a function.

Full code:
```
const express = require('express');
const router = express.Router();
const request = require('request');
const session = require('express-session');

router.get('/', function(req, res) {
        
    if (req.session) {
        req.session.destroy(function(err) {
            if (err) return console.log(err);
            return res.redirect('/');
        });
    }

});

module.exports = router;
```
I'm unsure if this is an error in my code or an error in express-session.

**Comment by em92** [comment]
Have you included `app.use(session(options))` before importing this module?

**Comment by Illuminati4Life** [comment]
Yes, I used `app.use(session(options))`:

```
let options = {
    name: 'Cookie',
    secret: 'cookiesecret'
    //etc
}
app.use(session(options));

**Comment by Illuminati4Life** [comment]
This is a cookie-based session, and from http://expressjs.com/api.html#cookieSession I found to clear the session, it is:

`req.session = null`

for cookie-based sessions.
