### ISSUE TITLE
Session not persisting between CORS calls

### ISSUE THREAD

**Issue by Niskarsh** [expressjs/session#597]
I have perfectly working backend in which I have implemented sessions for usual reasons, and It supports my frontend which still has ways to go
Prob : Like I said, I implemented sessions, and to get and post cookies I have appropriate routes in backend : **GET /cookies/check** and **POST /cookies/destroy**  : and they working fine when I checked with postman, but when do CORS calls from my frontend(search for file cookiePing.js in frontend project) GET /cookies/check gives me null irrespective of user is logged in or not
FRONTEND package : https://github.com/Niskarsh/journal-react.git
BACKEND package : https://github.com/Niskarsh/Journals.git

For testing only frontend on local machine clone the frontend repo,  then **``npm i``**, **``npm start``**

for checking them both on local machine, clone the repos,  then **``npm i``** for both the repos, then run **``PORT=3001 npm start``** inside backend repo and **``PORT=3000 npm start``** on frontend repo
Furthur you will have to change **uri** inside **options** in **signinPost.js** and **signupPost.js** to
**``http://localhost:3001/signin``** and **``http://localhost:3001/signup``** respectively inside frontend package

**Comment by Niskarsh** [comment]
Its in /journal-react/src/views/JournalPage/cookies/cookiesPing.js
This is file tree which follows location of cookiesPing.js

**Comment by Niskarsh** [comment]
Check now!!!! I forgot to push latest commits

**Comment by em92** [comment]
Include `withCredentials: true` in `option` object and check network activity debugger.

**Comment by Niskarsh** [comment]
CORS calls is not the problem, I'm successfully able to ping my deployed backend server, probem is that I'm receiving no data

**Comment by Niskarsh** [comment]
check **``cookies.controller.js``** in my back end code, its returning false everytime, when I ping from frontend project, but If I try same with postman, it returns user object

**Comment by em92** [comment]
https://github.com/Niskarsh/Journals/blob/master/server/controllers/resSetHeaders.js
I would change this to 
```
  if (req.headers.origin) {
    res.header("Access-Control-Allow-Origin", req.headers.origin);
    res.header("Access-Control-Allow-Credentials", "true")
  } else {
    res.header("Access-Control-Allow-Origin", "*");
  }
  res.header("Access-Control-Allow-Methods", "GET, POST");
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
```
Also make sure that origin header is sent from client and in production mode set hardcoded values of `Access-Control-Allow-Origin` header.

Also read this: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials

**Comment by Niskarsh** [comment]
@em92 thanks, it worked
