### ISSUE TITLE
Session timeout threshold

### ISSUE THREAD

**Issue by JaneJiangHH** [expressjs/session#599]
Hi, 
Recently I set my app session timeout with express-session. It works fine with 60 minutes or 15 days, but when I changed the cookie maxAge to 1 year or longer and then restart server, the session does not work properly(keep timeout state when logging in). Is there an upper threshold for session timeout?

**Comment by mattandrews** [comment]
I've been seeing something like this – sessions timing out within half an hour or so, even when the cookie expiration (in both my database and the client-side cookie) is set to +1 week from now. I can't work out what's causing it but I have a large maxAge (`604800000`).

**Comment by dougwilson** [comment]
What session store module are you using? That is what controls the storage and expiration on the server side.

**Comment by mattandrews** [comment]
`connect-session-sequelize` for me. I've checked and that module isn't removing still-valid sessions. It's possible something is killing my cookies/session in between my reverse proxy server (nginx) and CDN (Cloudfront), so will look there if it's nothing to do this with this module – thank you.

**Comment by dougwilson** [comment]
So the mechanics of this module is that it will look at the cookie in the request and ask your store module to look up the session. It them either gives back the session or not at that point. There is no expiration checks or anything in this module.

The maxage is just used to set the expires on the cookie (which you seem to indicate is correct) and the store gets that value and many will use it to expire on its end.
