### ISSUE TITLE
Session will not persist

### ISSUE THREAD

**Issue by aarondtaveras** [expressjs/session#602]
I'm currently working on a MERN stack application that will utilize a login/sign-up form that is linked to my Mongo database. I have successfully been able to create a user, hash the user's password, and then store this user into the database, as well as log the user in by checking their credentials from the database.

When attempting to employ a solution that's industry standard, I decided to work with Passport and Express-session to implement authentication and sessions for each user when they log in. Once a user is created/logged in, passport correctly stores their information into req.user, and a session is created and logged with req.session. Below is the console log of req.user followed by req.session :

```
user with id xxx serialized 
email: ...
password: ...
isAuthenticated: true
Session {
    path: '/',
    _expires: null,
    originalMaxAge: null,
    httpOnly: true },
    passport: {user: xxx } } 
```

This all displays right after I log-in, and to my knowledge this means that a session has been created and my user has been serialized properly. However, when I go to a new page on the webapp, I lose my session-- req.user becomes undefined, and req.sessionId changes each time the page does -- which leads me to believe that a new session with an empty user is created each time I switch pages (I am running a fetch method in my NavBar in React that triggers each time the Component mounts). Google Chrome also does not accurately log the cookies even when they are created as evidenced by the console logs.

My question is : why won't my session persist when I switch pages? My goal is to keep track of this session data to pass to my React frontend to render specific content. Is there a better way to go about this? Below is my middleware ordering:

```
app.use(session({
  secret: 'test',
  saveUninitialized: false,
  resave: true
}));
app.use(passport.initialize());
app.use(passport.session());
Here are the methods I am calling in my router file:

router.get('/',function(req, res){
 console.log(req.user);
 console.log(req.session);
 res.end();
});

router.post('/login',passport.authenticate('local'), function(req,res)      
{
 console.log(req.user);
 console.log(req.isAuthenticated());
 console.log(req.session);
 res.end();
});

passport.serializeUser(function(user, done) {
  console.log("user with id " + user._id + " serialized");
  done(null, user._id);
});

passport.deserializeUser(function(id, done) {
  console.log("deserializing user with id " + id + " ");
  User.findById(id, function(err, user) {
  done(err, user);
 });
});


Here is my api fetch call from my front end:

componentDidMount(){
    var current_user = "";
    fetch("http://localhost:3001/users/", {
        credentials: 'same-origin',
        method: "get",
        headers: {
            'Accept':'application/json',
            'Content-Type': 'application/json'
        }        
    })
    .then( (response)=> response.json())
    .then( (response)=> {
        if(response.user!==current_user){
            current_user = response.user;
            this.setState({
                user: current_user
            }), ()=> console.log(response);
        }
    })
}
```
I am also aware that currently the fetch method will not properly work: the goal is for that skeleton to work properly and have it return the correct id. What is logging improperly is the session and the req.user before I can even get the chance to pass it to my front end. Any and all help would be appreciated.

**Comment by joewagner** [comment]
Some other people were having an issue using Fetch without specifically adding the `credentials` init options.  i.e. https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch#Parameters

Can you make sure you're sending the cookie containing the session id?

**Comment by aarondtaveras** [comment]
Hi Joe, thanks for the reply. 
I did attempt the solution that others had come across trying `credentials: 'same-origin'`, and `credentials: 'include'. ` Unfortunately they were both to no avail. 

Also, this may seem like a silly question, but how can I "make sure" I'm sending the cookie containing the session id? I'm pretty new to authentication and sessions so I'm learning everything as I go along. Thank you.

**Comment by joewagner** [comment]
@aarondtaveras couple things you could try:
 - open your browser debugger and look in the network tab.  You should see a cookie with the name `connect.sid`.  
 - or log `req.headers.cookie` on the server

Most of the issues here arise from some variation of the client not sending the `connect.sid` cookie

**Comment by aarondtaveras** [comment]
That definitely seems to be the issue. There typically isn't a cookie created on the client side when I check in the "network" tab, and logging `req.headers.cookie` gives me undefined. I also posted an edit stating that things work fine within POSTMAN, so everything is good from the backend perspective. Any suggestions?

**Comment by aarondtaveras** [comment]
@joewagner Oddly enough, when I set credentials to 'include' I no longer get any logs in my console - and my subsequent requests aren't handled after the initial pre-flight OPTIONS request. I do currently have a working version of this app on my github (by working I mean functioning aside from this bug haha). 

The link is here: https://github.com/chuckolate/tournament-bracket.git 

After all the installs, if you sign up via the "Join EGF" link in the footer, then refresh the page or navigate away... then the issue arises. Same goes for if you log in a created user, and then navigate away from the page. Thanks for your help so far Joe!

**Comment by joewagner** [comment]
@aarondtaveras Sorry I'm not familiar enough with React to be able to help, and this doesn't seem to be anything to do with the Session module.  I would ask a question on stackoverflow or the like.
Good luck
