### ISSUE TITLE
Cookie value is longer than necessary

### ISSUE THREAD

**Issue by James2516** [expressjs/session#604]
A cookie with value that looks like 
> s%3A**Jhn2NJfjasdu52df36GaZxf**.YIZs23%534ADS23JKJFd12cxzA 

is set for the client. The bolded part correspond to the `session_id` in the `sessions` table in database. What is the use of the other parts (i.e. `s%3A` and the string (`YIZs23%534ADS23JKJFd12cxzA`) after the dot)?

**Comment by dougwilson** [comment]
The rest of the text is wrapping the set value with a cryptographic signature, which prevents forging session ids.
