### ISSUE TITLE
Session data being overwritten on consecutive writes.

### ISSUE THREAD

**Issue by Renari** [expressjs/session#606]
```
router.post('/', (req, res) => {
    if (req.session.files === undefined) {
        req.session.files= {};
    }
    let files = req.session.files;
    let uuid = uuidv4();
    files[uuid] = {};
    files[uuid]['size'] = file.size;
    files[uuid]['name'] = file.name;
    res.send(JSON.stringify(files[uuid]));
}
```

In the above example I'm having an issue where `req.session.files` is being overwritten when multiple requests happen at the same time. I've tried initializing `req.session.files` elsewhere thinking this was a race condition while initializing the object, however the same issue persisted. When multiple files are uploaded at the same time the session will end up holding a random number of them while others will disappear.

It should be mentioned that I'm using (mysql-express-session)[https://www.npmjs.com/package/express-mysql-session] as the session store, I have not tried using another. If required I can work on try making a live test case.

**Comment by Renari** [comment]
I ended up finding out that since there is no cookie data on the client before a file gets uploaded, what happens is multiple sessions are made and the clients cookie gets overwritten.

**Comment by Renari** [comment]
Upon further testing and fixing the cookie issue by sending the client a cookie ahead of the requests this is still occuring.

**Comment by gireeshpunathil** [comment]
@Renari - now that you have consistently reproduced this issue, can you please pass along a complete test case?

**Comment by Renari** [comment]
Sorry it's been more than a year since I worked on this, I no longer have access to the code in question here.

**Comment by gireeshpunathil** [comment]
ok, we should close this then I guess, given that we cannot progress
