### ISSUE TITLE
Session lost redirecting to PayPal

### ISSUE THREAD

**Issue by danielflippance** [expressjs/session#611]
I've noticed that if I set secure: true, then after redirecting to paypal and coming back, the session is lost:

```
app.use(
	session({
		cookie: { 
			maxAge : 60 * 60 * 1000,	//1 Hour

			//Setting this to true causes session to get lost when redirecting to PayPal for payment
			secure: true, 
			sameSite: true,
		},	
		name: '__Host-connect.sid',		//Prefix limits where cookie is sent
		resave: false,					//Don't save the session to store if it hasn't changed				
		rolling: true,					//Reset the cookie Max-Age on every request
		saveUninitialized: true,		
		secret: EXPRESS_SECRET,
		store: new MongoStore({ 
			mongooseConnection: mongooseConnection,
		}),
		proxy: process.env.ENVIRONMENT === 'development' ? false : true,
	})
);

if (process.env.ENVIRONMENT !== 'development') {
	app.enable('trust proxy'); 
}
```

express-session: "version": "1.15.6",

The entire site is running on https and the redirect to paypal goes to their https URL:

`res.redirect('https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_ap-payment&paykey=AP-31E6asdfghjkl')
`

The session is fine if I just manually change the URL in the browser to another website then come back to my site.

I've tried with and without the session.name, session.resave, cookie.sameSite being changed from the default but with the same results.

It happens on my dev machine and in staging and production on Heroku.

**Comment by danielflippance** [comment]
On closer inspection the problem doesn't seem to be caused by the secure flag. The issue is so far non-deterministic:

- Everything is fine
- I change one field in the session config
- Session stops working on the paypal redirect
- I then reverse the change but the problem persists

**Comment by joewagner** [comment]
@danielflippance There's not enough code to understand what you're trying to do, but the only things in this configuration that look potentially off to me at first glance are `httpOnly: false` and `sameSite: true`.  If changing those doesn't fix your issue, you may have to post more code.  
Also this may be relevant reading...
https://medium.com/@PeterNagyJob/how-did-i-waste-6-hours-finding-out-all-about-same-site-cookies-82d75062ede2

**Comment by danielflippance** [comment]
Thanks for the tip and the link, setting `sameSite` to `'lax'` seems to have solved the problem with PayPal
