### ISSUE TITLE
dev team! we have a very serious issue! please help

### ISSUE THREAD

**Issue by Viral** [expressjs/session#612]
I've implemented express-session in my project. I tell people this. they say I cannot use express-session in production!! they downvote me. they call me names. it gets really ugly. I ask for explanation yet I receive none! they cannot help me they say! so I come here to ask for your help! tell me please what is wrong with using express-session in my code in production?

```
 // App.js
app.use(session({
    secret: config.secret,
    cookie: { maxAge: 31536E6 },
    resave: false,
    saveUninitialized: false,
    store: new mongodb({ uri: config.url, collection: 'sessions'})
}));

// controllers/user.js

exports.auth = (req, res, next) => {
	if (req.session.userid) return next()
	res.sendStatus(401);
};

exports.login = (req, response) => {
	const { email, password } = req.body;
	global.db.collection('users').findOne({ email: email }, (err, result) => {
   		if (result) {
   			bcrypt.compare(password, result.password, function(err, match) {
				if (match) {
					if (result.active) {
						req.session.userid = result._id.toString();
						req.session.save( () => {
							return response.redirect('/');
						});
					} else {
						global.db.collection('invoices').findOne({ user: result._id.toString() }, (err, res3) => {
							if (res3) {
								return response.redirect('/users/invoice/' + res3._id );
							} else {
								return response.json({ error: 'unknown error. what did you do?' });
							}
						});
					}
				} else {
	   				return response.json({ error: 'incorrect email or password' });
				}
	   		});
   		} else {
	   		return response.json({ error: 'incorrect email or password' });
   		}
	});
};
```

**Comment by dougwilson** [comment]
What is the issue you're having with the above code? It's hard to really understand without the code being complete enough we can actually run.

**Comment by Viral** [comment]
no issues! it works perfect. but people are telling me it's insecure and I should not use it? that express-session can somehow be hacked??

**Comment by dougwilson** [comment]
I have no idea. Without more information how can I help?

**Comment by Viral** [comment]
okay let me ask this a different way.... to your knowledge is there anyway for a client to somehow forge or hack my req.session.userid variable? or would you say it's pretty secure? I feel like I'm using this app for its intended purpose...

**Comment by dougwilson** [comment]
I mean there are a couple issues with that question: (1) there is no way to provide any real answer without an actual runnable app to test against and, probably even more (2) I am not a security expert and really any response I would provide in that sense would ultimately be meaningless.
