### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by ZXZs** [expressjs/session#616]
Error:
`TypeError: Cannot read property 'name' of undefined
    at /media/testus/index.js:23:22
    at Layer.handle [as handle_request] (/media/testus/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/media/testus/node_modules/express/lib/router/index.js:317:13)
    at /media/testus/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/media/testus/node_modules/express/lib/router/index.js:335:12)
    at next (/media/testus/node_modules/express/lib/router/index.js:275:10)
    at Immediate.<anonymous> (/media/testus/node_modules/express-session/index.js:489:7)
    at runCallback (timers.js:814:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)`

My code:
```JS
// IMPORTS //

var express = require('express');
var app = express();
var bodyparser = require('body-parser'); app.use(bodyparser.json()); app.use(bodyparser.urlencoded({extended: true,}));
const __mongo__ = require("mongodb").MongoClient; const url = "mongodb://192.168.1.102:27018/";
const __session__ = require('express-session');
```
```JS
app.use(__session__({
	secret: 'govnoed',
	resave: true,
	saveUninitialized: true
}));
```
```JS
app.use(function(req, res){
	if(!req.__session__.name)    { req.__session__.name    = null; }
	if(!req.__session__.surname) { req.__session__.surname = null; }
	if(!req.__session__.email)   { req.__session__.email   = null; }
});
```

***
What's my mistake? Thanks.

**Comment by dougwilson** [comment]
Your stack trace says the error in on line 23 n the file /media/testus/index.js Can you point out which line that is?

**Comment by ZXZs** [comment]
> Your stack trace says the error in on line 23 n the file /media/testus/index.js Can you point out which line that is?
```JS
22 app.use(function(req, res){
23	if(!req.__session__.name)    { req.__session__.name    = null; }
24	if(!req.__session__.surname) { req.__session__.surname = null; }
25	if(!req.__session__.email)   { req.__session__.email   = null; }
26 });
```

**Comment by dougwilson** [comment]
Thanks. So that would indicate that `req.__session__` is undefined and so in javascript you get an error trying to access a property on something undefined.

I hope that helps!

**Comment by ZXZs** [comment]
Thanks for the quick response, but 
`__session__` is defined here -> `const __session__ = require('express-session');`

I solved my problem:
`__session__` must be a `session`
```JS
const session = require('express-session');
```

**Comment by dougwilson** [comment]
Well, not sure what to tell ya.

**Comment by mrp100461** [comment]
Your request is undefined so the name is undefined.
