### ISSUE TITLE
Cookies are being rejected after 5 min

### ISSUE THREAD

**Issue by marcioaffonso** [expressjs/session#618]
My sessions cookies are being rejected after 5 min. The cookie expiration date is larger, though. Looking at the browser console, I noticed that the cookie is being sent back in the response, even though the expiration date is larger. See my screenshot.

<img width="501" alt="screen shot 2018-10-09 at 13 18 29" src="https://user-images.githubusercontent.com/10703025/46666065-f7220d80-cbc5-11e8-9045-1132d01b23c4.png">

**Comment by dougwilson** [comment]
Very strange. Not sure what is happening. Is it possible to provide code and instructions so we can reproduce the issue?

**Comment by kinovlee** [comment]
same problem waiting resolving

**Comment by dougwilson** [comment]
With no instructions provided on how to reproduce or any other follow up and now a me too, I'm going to close this issue. If someone can provide what I asked for above I will reopen.
