### ISSUE TITLE
req.session data is not persistent in multiple controller files

### ISSUE THREAD

**Issue by Dimple-Kanwar** [expressjs/session#619]
Hi,
I am using ES6. I have used classes for the rest-api definition.

I am facing following issue:

When I call login api which is there in loginController.js. User's data is getting stored in req.session which is as below:
Session {
  cookie:
   { path: '/',
     _expires: 2018-10-16T20:42:24.732Z,
     originalMaxAge: 1800000,
     httpOnly: true },
  username: 'abcs',
  accountAddress: '12343',
}
When I call another api after login, req.session is not storing any user's data which I stored in login api as showing below:
Session {
  cookie:
   { path: '/',
     _expires: 2018-10-16T20:42:24.732Z,
     originalMaxAge: 1800000,
     httpOnly: true },
}

Directory structure:
server.js(server file)
routes.js ( all apis routing)
models(mongo db models)
    --- User.js
   --- Account.js
controllers(class functions of which will be linked with api)
       ---- loginController.js
       ---- userController.js
       ---- accountController.js 

How can I persist the session in multiple files?

**Comment by Dimple-Kanwar** [comment]
When I test these APIs in POSTMAN , it's working fine.
But when I use curl command to test the APIs, Session is not persistent in multiple files

**Comment by dougwilson** [comment]
You have to send the session cookie in your curl command. Use `curl --help` and use the cookie jar options.

**Comment by Dimple-Kanwar** [comment]
If we dont want to store in cookies then?

**Comment by dougwilson** [comment]
Then use a different session management module.

**Comment by Dimple-Kanwar** [comment]
can other storage options help in this?

**Comment by dougwilson** [comment]
Like what, for example?

**Comment by Dimple-Kanwar** [comment]
mongodb storage

**Comment by dougwilson** [comment]
Changing the server side storage will make no difference if you're not storing the cookies on the client side. Cookies are needed because HTTP requests are stateless, as in when you make curl for url A and then make curl for url B somehow the server has to know the same client is making those two requests. This module links the requests with cookies.
