### ISSUE TITLE
Session token from cookies can be taken over and transferred

### ISSUE THREAD

**Issue by expertup** [expressjs/session#620]
> var express = require('express');
> var session = require('express-session');
> var app = express();
> app.use(session({
> 	secret: 'xxxxxxxxx',
> 	name: 'sessionID',
> 	resave: false,
>     saveUninitialized: true,
> 	cookie: {
> 		maxAge: 24 * 60 * 60 * 1000,
> 		httpOnly: true
> 	}
> }));

I for test copy session ID from cookie, from browser where I'm logged and paste to another browser, where I'm not logged. After refresh page, I see that I'm logged without password. This mean, that session is moved.

How to secure before this issue? In PHP I remember, that after change ID session in browser, it will renew and change to other. Also after paste session ID from other browser.

**Comment by dougwilson** [comment]
This is just how cookies work... the request with the cookie value _is_ the person.
