### ISSUE TITLE
Does not work in Angular with Server side rendering enabled.

### ISSUE THREAD

**Issue by sunojvijayan** [expressjs/session#631]
Hi,
    I was using express-session and my site works fine before enabling SSR. But after I enabled SSR via universal, I dont get the session object. The browser does not register the cookie. Anyone else facing this problem. Can anyone help please?

**Comment by dougwilson** [comment]
Hi @sunojvijayan sorry you're having trouble. I'm not familiar with that SSR is, or universal. I didn't answer right away, as I was hoping someone would be able to chime in, but it's been 14 days. Are you still having this issue? Is it possible you can walk me through a reproduction if so?

**Comment by byokap97** [comment]
hi i am interested in this problem, cause i will use sessions on my project with SSR. Can you let some notes if u already have fixed it or more detail from which is the problem

**Comment by bijupmana** [comment]
We are using express-session with Angular SSR. We do not have the problem. 
Perhaps your cookie context path is ending with a slash at the end. If you have a slash at the end of cookie path then you must invoke the app url also with slash at the end.

**Comment by gireeshpunathil** [comment]
@sunojvijayan - is this still an outstanding issue? if so, please provide more specific information as requested by @dougwilson - what is your code looking like, what is your expected behavior, and what is the actual. thanks!

**Comment by dougwilson** [comment]
Closing due to no response.
