### ISSUE TITLE
Race condition between logout request and long running request

### ISSUE THREAD

**Issue by danielegli** [expressjs/session#632]
In my application, I have noticed that if a user tries to logout while they have a running API request (loading data from database), the sessions is not terminated in our store.  Reading through the documentation, I can see that this occurs because the module replaces the response end function and does an additional save to the store; this is verified by monitoring the redis store and observing a SET after the response ends for the database query.  Flow would look like this:

1. Client makes request to database
2. Client hits log out
3. Destroy() is called and session removed from store
4. Initial request finishes, SET is called and session is saved in store again

Logout route:
![image](https://user-images.githubusercontent.com/25332627/52666321-d561cb80-2ec2-11e9-866b-946a8790ba55.png)

How is this scenario supposed to be handled?  I assume I'm not the only one that has sessions cluttering the store from this and I obviously don't want a client that has logged out to be able to still access my app.

**Comment by dougwilson** [comment]
So what you have explain is the expected default behavior, though you can likely configure this not to occur, depending on your setup. The first question I would have is are you altering the session data during the log running API request? If not, then perhaps `resave: false` in your session options will resolve the issue if you don't already have that set.

If so, then unless the store saves the session ID as "destroyed" in itself, then the sore does not have a way to know not to resurrect that session, as it would look like a brand new session to itself. If this is the case, it would need to be brought up as an issue to the store module.

**Comment by danielegli** [comment]
I'm not altering the session data during the long running API request but have already tried `resave:false` without any luck.  From viewing the session in the REDIS store, I can see that the renewed attribute is the only one that has changed.  

connect-redis does not save a session ID as "destroyed", it merely flushes that key and hence the problem.

**Comment by dougwilson** [comment]
Gotcha. So it sounds like it is an issue with that store module. There is no method in which express-session can track state; all state has to be tracked by the store layer, as it has a storage mechanism to track such state.

**Comment by danielegli** [comment]
But the `resave` idea is so close to what I need.  If I have `resave:false` but the module updates the renewed attribute and then resaves anyways, how is anyone able to use `resave:false` successfully?

**Comment by dougwilson** [comment]
So when resave is false, this module does not send a save event to the store. Why is the store resurrecting the session?

**Comment by danielegli** [comment]
Okay, I realize now that our session has a `state.renewed` attribute that is actual a custom attribute that we've created (I missed this fact).  That is getting updated and therefore the module is sending the save event when the response ends.  I had just assumed this was part of the module, but in fact that is obviously not the case. 

My apologies for missing that and thanks for such quick responses.
