### ISSUE TITLE
expire event

### ISSUE THREAD

**Issue by Grayson95** [expressjs/session#636]
Hi there!
Can I set a event triggered by cookie meet maxAge and expire?

**Comment by dougwilson** [comment]
Hi @Grayson95 ! There isn't a way to do this currently, as the expiration of cookies occurs in the user's browser and not on the server. Now, the underlying session data that is stored should also expire, and an event for that action would depend on the session store module you're using to store the sessions server-side.

**Comment by Grayson95** [comment]
> Hi @Grayson95 ! There isn't a way to do this currently, as the expiration of cookies occurs in the user's browser and not on the server. Now, the underlying session data that is stored should also expire, and an event for that action would depend on the session store module you're using to store the sessions server-side.

Thanks a lot!
