### ISSUE TITLE
User is "stealing" session from other user

### ISSUE THREAD

**Issue by VitorReginatto** [expressjs/session#637]
Normally, **USER 1** authenticates and if everything happens, the session stores things like name, id and permission. When **USER 2** goes through the authentication and stores the information in the session, in some cases **USER 2** "steals" the session of **USER 1** and gets all information from **USER 1**, but when **USER 2** refresh the page, everything returns to normal. I tried to use connect-mongo to see if it corrected the error, but continued the same thing.

app.js
```
var express = require('express');
var consign = require('consign');
var bodyParser = require('body-parser');
var expressValidator = require('express-validator');
var expressSession = require('express-session');
var MongoStore = require('connect-mongo')(expressSession);

var app = express();
var server = require('http').Server(app);
var io = require('socket.io')(server);

app.set('view engine', 'ejs');
app.set('views', './app/views');

app.use(bodyParser.urlencoded({ extended: true }));
app.use(expressValidator());
app.use(expressSession({
	secret: 'secret',
	store: new MongoStore({url: 'mongodb://localhost:27017'}),
	resave: false,
	saveUninitialized: false
}));

app.use(express.static('./app/public'));

consign()
	.include('config/dbConnection.js')
	.then('app/helpers')
	.into(app);
var usuarioHelper = app.app.helpers.usuarioHelper
var dateHelper = app.app.helpers.dateHelper
var errorHelper = app.app.helpers.errorHelper
app.use(usuarioHelper.usuarioHelper)
app.use(dateHelper.dateHelper)
app.use(errorHelper.errorHelper)

consign()
	.include('app/models')
	.then('app/controllers')
	.then('app/routes')
	.into(app);


server.listen(3000, function () {
	console.log('Servidor Iniciado');
});

var visitas = 0;
io.sockets.on('connection', function (socket) {
	visitas++;
	socket.emit('visits', visitas);
	socket.broadcast.emit('visits', visitas);
	socket.on('disconnect', function () {
		visitas--;
		socket.broadcast.emit('message', visitas);
	});
});
```
auth.js
```
this.autenticacao = async function (req, res) {
		var body = req.body
		var bcrypt = require('bcrypt');
		let jsonDB = await autenticaoModel.autenticar(body.email)
		if (jsonDB[0]) {
			let senhaDB = jsonDB[0].senha
			var result = await bcrypt.compare(body.senha, senhaDB)

			if (result) {
				req.session.autorizado = true
				req.session.idUsuario = jsonDB[0].id
				req.session.nome = jsonDB[0].nome
				req.session.email = jsonDB[0].email
				req.session.grupo = jsonDB[0].grupo
			}
			else {
				res.redirect('/');
			}
			if (req.session.autorizado) {
				res.redirect('/dashboard');
			}
		}
		else {
			res.redirect('/');
		}
	}
```
helper.js
```
this.usuarioHelper = function(req, res, next){
		application.locals.getUsuarioLogado = () => {
			return req.session.nome
		}

		application.locals.getEmailUsuarioLogado = () => {
			return req.session.email
		}

		application.locals.getGrupoUsuarioLogado = () => {
			return req.session.grupo
		}

		application.locals.getIDUsuarioLogado = () => {
			return req.session.idUsuario
		}
		next()
	}
```

**Comment by dougwilson** [comment]
Thanks for the report! There is a lot going on in that code, and it seems likely other things happening that may not be displayed. Is there a way I can get it running and reproduce the described issue? I could then use a debugger to determine what is happening in this case.

**Comment by VitorReginatto** [comment]
Is there a way to send the site to you privately? Contains sensitive information as a database.

**Comment by dougwilson** [comment]
I can set up a database. But the best method I have seen is to add my user to a private repo on github to share the code and instructions.

**Comment by VitorReginatto** [comment]
I invited you to private repository

**Comment by dougwilson** [comment]
Thanks! I got it and cloned it. I'm just setting up a MongoDB to use, but after that, can you provide the instructions on how I can reproduce the issue you described?

**Comment by dougwilson** [comment]
Ok, I got a MongoDB setup, and can load the login screen, but not sure how to auth at that point to try running through the flow you described above. I typed some simple emails, but they are not valid.

**Comment by VitorReginatto** [comment]
Instructions for the bug are on repository.

**Comment by dougwilson** [comment]
Thanks!

**Comment by dougwilson** [comment]
I investigated the code provided and provided a summary in the private repo. For anyone coming across this issue, there was no issue with express-session, instead the app was setting user data in the Express.js `app.locals`, which is global to the process, and then using that to render the pages. This meant parallel requests would overwrite the globals during processing and the rendered page would have another user's information.
