### ISSUE TITLE
Session is not getting set

### ISSUE THREAD

**Issue by yathindrakodithuwakku** [expressjs/session#644]
When i set up  express-session in nodejs back end it didn't set the session cookie in my browser even though setCookie response header is present. Then i had to add `credentials: true` flag in my cors setup. as follows.
```
app.use(cors({
    origin: "http://myhost:8080",
    credentials: true,
}));
```
Also set `withCredentials: true` in react axios request call. 

Then only browser cookie is created and `Access-Control-Allow-Credentials: true` header had been set.

But the other problem is still console.log(req.session) is not showing the my session variables, i set. 

Below mentioned my express-session config. Also secure flag is false since i am using  http, not https.

`app.use(session(
    {
        name: "testsession",
        saveUninitialized: true,
        resave: true,
        secret: 'asdaasd',
        cookie: {
            maxAge: 1000 * 60 * 60 * 24 * 7,
            sameSite: false,
            secure: false,
            httpOnly: false
        }
    }) );`

version: "express-session": "^1.15.6"
browsers checked with: firefox, chrome

**Comment by dougwilson** [comment]
Everything you said seems right, so not sure what is going on. In order to troubleshoot, I would need your complete app with instructions on how I can run your app and reproduce the issue.

**Comment by yathindrakodithuwakku** [comment]
Hi @dougwilson, 

Unfortunately, I have removed express-session library and used cookie-session, since it's not working.

**Comment by dougwilson** [comment]
Alright, thanks for following up. Without a repo so we can try and fix, this module will never get fixed, unfortunately.
