### ISSUE TITLE
conflict in session

### ISSUE THREAD

**Issue by hainguyents13** [expressjs/session#647]
I found an issue that opened by a user but it's closed because there was no way to fix it. https://github.com/expressjs/session/issues/478

> I logged it to an account, then I refresh the page and see another account displayed. and there is no relation between them. refresh the page and my account come back.

But I'm facing it now and can't help myself finding a way to fix it and I need your help, please.
Here is my server.js code
``` javascript
const csrf = require('csurf')
const session = require('express-session')
const MongoStore = require('connect-mongo')(session)
const cookieParser = require('cookie-parser')
// Sessions
app.set('trust proxy', 1)
app.use(session({
    name: 'myapp.v2',
    secret: config.app.secret,
    resave: true,
    saveUninitialized: true,
    cookie: { httpOnly: true },
    store: new MongoStore({ mongooseConnection: mongoose.connection, collection: 'Sessions' }),
}))
// body parser 
const bodyParser = require('body-parser')
app.use(bodyParser.json({ limit: '100mb' }))
app.use(bodyParser.urlencoded({ limit: '100mb', extended: true }))
app.use(cookieParser())
app.use(csrf({ cookie: true }))
```
I mentioned cookieParser because I thought it is related to the issues.

signin.js
``` javascript
// information corrected, log user in
req.session.regenerate(err => {
    if (err) {
        console.log(err);
    }
})
req.session.user = _.omit(User, ['pwd_hash', 'salt'])
if (remember) {
    req.session.cookie.maxAge = 60 * 60 * 24 * 30 * 1000
}
```

Please help!

**Comment by dougwilson** [comment]
Hi! We've had this report several times and every time it has turned out to be an issue somewhere else in the app and not this module, sometimes even the store itself was the issue.

Regardless, please provide us with the complete code to reproduce and the steps so we have something to debug, or if you cannot share code and cannot shrink the code into something reproducible, you can always debug the code and provide the technical details of where the issue is happening and we can use that to guess the issue (you could even suggest a fix).

**Comment by hainguyents13** [comment]
I created this repo for full code
https://github.com/hainguyents13/myapp
Please take a look, thanks!

**Comment by dougwilson** [comment]
Thanks @hainguyents13 I can see the repo! Can you provide instructions for how to run the server and the instructions for how to reproduce the issue once I have it running? There was no readme or anything in the repo regarding those, so just asking here. You can post in that repo as a response if you don't want these things to be here.

**Comment by hainguyents13** [comment]
I think I found the problem, it happens because I have assigned context properties to the `app.locals`, and therefore it affects the whole app. 
the way to fix it is just assign the context to `res.locals` instead
