### ISSUE TITLE
CloudFront

### ISSUE THREAD

**Issue by renehauck** [expressjs/session#652]
Hi, I'm just trying to get my app ready for production. 
The app is hosted by Aws and is built like this: 
Route53 -> CloudFront -> ELB (no cluster, only SingleApp) 
CloudFront is used to make the app accessible via SSL. The Nodejs app listens on an HTTP port.
Unfortunately the SessionCookie is not set.
Here is my config:
```
session({
            genid: (req) => {
                return uuid() // use UUIDs for session IDs
            },
            secret: process.env.SESSION_SECRET,
            resave: false,
            saveUninitialized: false,        
            proxy:!dev,    
            store: new MongoStore({ mongooseConnection: mongoose.connection }),
            rolling: true,
            cookie:{
                secure:!dev,
                httpOnly:true,
                domain:hostName,
                expires: expiryDate
            }
        })
```
What am I doing wrong? 

Thanks for your work :smiley: .

**Comment by dougwilson** [comment]
What are the values of all those variables when it is in the non working condition?

**Comment by renehauck** [comment]
hi, I have written the values to the variables:
```
const dev = process.env.NODE_ENV !== 'production';
const expiryDate = new Date( Date.now() + 60 * 60 * 1000 ); // 1 hour
session({
            genid: (req) => {
                return uuid() // use UUIDs for session IDs
            },
            secret: process.env.SESSION_SECRET, // fdsa83nfs83...........232dasdas
            resave: false,
            saveUninitialized: false,        
            proxy:!dev,    // false
            store: new MongoStore({ mongooseConnection: mongoose.connection }),
            rolling: true,
            cookie:{
                secure:!dev, // false
                httpOnly:true,
                domain:hostName, // https://app.***.de
                expires: expiryDate
            }
        })
```

**Comment by dougwilson** [comment]
Thank you. The only thing that jumps out at me from that is the cookie domain cannot have the https:// part on it.

**Comment by renehauck** [comment]
No, I'm afraid not. :disappointed: 
I have just tried 2 variants:
this works:
```
                secure:false,
                httpOnly:true,
              //  domain:hostName,
                expires: expiryDate
```
this not:
```
                secure:true,
                httpOnly:true,
              //  domain:hostName,
                expires: expiryDate
```

**Comment by dougwilson** [comment]
Did you set up trust proxy? https://github.com/expressjs/session/blob/master/README.md#cookiesecure

**Comment by renehauck** [comment]
yes:

```
  server.enable('trust proxy');
  server.set("trust proxy", (ip)=>{
    return true;
  });
```
still the same :disappointed:

**Comment by dougwilson** [comment]
Is your server getting a x-forwarded-proto header with the vale "https"?

**Comment by renehauck** [comment]
No, but a x-forwarded-for, maybe this helps. The full list:

`{
"host":"mysite.eu-central-1.elasticbeanstalk.com",

"x-amz-cf-id":"abddasdas22321-3223131dads==",

"connection":"Keep-Alive",

"cookie":"_csrf=Ph1kmGT6uzslEabZ31qfuzGV; csrfToken=UxH3eyVi-EoPgnq6z4xEukc8odQhaGaKMEl4",

"user-agent":"Amazon CloudFront",

"via":"2.0 123456789abcde.cloudfront.net (CloudFront)",

"x-forwarded-for":"178.4.*.*",

"accept-encoding":"gzip"
}`

**Comment by dougwilson** [comment]
Ah. That would prevent s secure cookie from getting set, which is the setting you have.

**Comment by renehauck** [comment]
These are my settings :smiley: :
![aws1](https://user-images.githubusercontent.com/3898144/56470487-f7d60f00-6446-11e9-97ca-dcdf00326283.png)
![aws2](https://user-images.githubusercontent.com/3898144/56470488-fc022c80-6446-11e9-8c44-1898d2516ae2.png)
![aws3](https://user-images.githubusercontent.com/3898144/56470489-fc9ac300-6446-11e9-8f38-17296732ed8d.png)
![aws4](https://user-images.githubusercontent.com/3898144/56470500-37046000-6447-11e9-9173-9d22b9788e8b.png)

**Comment by dougwilson** [comment]
I'm not familiar with those settings panels, so no idea what it means.

**Comment by renehauck** [comment]
Sorry, a misunderstanding, I thought I should send the settings. These are the cloutfront settings, maybe someone sees an error in these settings.

**Comment by dougwilson** [comment]
It's no problem. Yea, there could be one. Ultimately to set a secure cookie the connection either needs to be secure to express or reverse proxies indicate that the connection is secure with x-forwarded-proto header.

**Comment by renehauck** [comment]
Okay, that helps a lot, thanks for your time. If I find a solution, I will post you here directly.

**Comment by renehauck** [comment]
Finally it works! :tada: 
The solution is to select "whitelist" instead of "all" under "Cache Based on Selected Request Headers". No idea why "all" is not "all".

Under "WhiteList-Headers" the header "cloudfront-forwarded-proto" must be in the whitelist. 
![Bildschirmfoto vom 2019-04-22 09-04-32](https://user-images.githubusercontent.com/3898144/56488451-abd6a900-64de-11e9-9df2-32ac5314e1cc.png)

Now the following middleware must be created in the Express App before the session and cookie middleware:
```
server.use([(req, res, next) => {
    if (req.headers['cloudfront-forwarded-proto']) {
      req.headers['x-forwarded-proto'] = req.headers['cloudfront-forwarded-proto'];
    }
    next();
  },
```
Many thanks for the great help @dougwilson

**Comment by samteb** [comment]
I have the same problem and I am struggling to make it works.
I have an AWS S3 bucket to serve the front end and my server running in an EC2 instance.
I have also have an Elasticache Redis to store user sessions.

In local everyhting wors fine and a session cookie is set in the browser. In production, a session is created when a user logged in but no cookie is set in the browser.

I tried your configuration but it didn't work.

Help please !!

**Comment by samteb** [comment]
Here my express-session options : 

`       name: 'session-id',
        secret: 'mySecret',
        store: new redisStore({ client: redisClient }),
        saveUninitialized: false,
        resave: false,
        cookie: {
            path: '/',
            proxy: true,
            secure: true,
            httpOnly: true,
            maxAge: 1000 * 60 * 60 * 10
        },
        unset: 'destroy'
`

**Comment by dougwilson** [comment]
Please open a new issue with your information. If you believe this is a similar issue you can link to it.
