### ISSUE TITLE
npm install express-session --save   404 Error.

### ISSUE THREAD

**Issue by scottie-uk** [expressjs/session#655]
All, I am trying to install express-session via the NPM as mentioned in Ethan Brown's Web Development With Node and Express.

However, it seems when I type the following I get a 404 error:
```
hidden@secret:~/CS253SP19/P4/app$ npm install epress-session --save
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/epress-session - Not found
npm ERR! 404 
npm ERR! 404  'epress-session@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hidden/.npm/_logs/2019-04-23T19_59_06_080Z-debug.log
```

When going to the URL the repository uses (below), there is nothing there I just get a standard express 404 page.
 https://registry.npmjs.org/epress-session 

So what has happened to this project reference in the repository?

**Comment by dougwilson** [comment]
The issue is that the command you're running is `npm install epress-session --save`, in which the module name is spelled "epress-session". It's just a typo missing the `x` as the second character.

It should work if you do `npm install express-session --save`

**Comment by scottie-uk** [comment]
My goodness silly me. I was copying and pasting from some notes. My dyslexic brain did not see that the x was missing. Thank you very much and feel free to hide this post down a very dark hole. :)

**Comment by dougwilson** [comment]
It's no problem at all :)
