### ISSUE TITLE
Session not saving when redirect

### ISSUE THREAD

**Issue by alex55132** [expressjs/session#660]
When an user logs in the data is saved in `req.session`, then I redirect the user to the homepage using `res.redirect(url);`. The problem appears when that redirect execute, the data from the session get lost but if instead of redirecting I go to the homepage manually (with the browser), the session data is available.

Here are some snippets of my code:

main.js:
```
var session = require('express-session');
var mySQLStore = require('express-mysql-session')(session);

let sessionConfiguration = session({ /*Session configuration */});

function checkSession(req, res, next) {
  if(req.session.user) {
    console.log("Exists");
    console.log(req.session.test);
    next();
  } else {
    console.log("No exist :( ");
    next();
  }
}

app.use('/', sessionConfiguration, checkSession, router);

```

redirect.js:

```
router.get('/route', function (req, res) {  

     req.session.test = "hey"
     console.log(req.session.test);

      //Data get lost here
      res.redirect("/");

  });
```

Also, the data of the session that remains when the redirect is done is this:

`{"cookie":{"originalMaxAge":3600000,
"expires":"2019-05-07T21:15:06.727Z",
"httpOnly":false,
"path":"/",
"sameSite":true}}`

**Comment by dougwilson** [comment]
Due to how most web browser handle redirects, you need to save before the direct (https://github.com/expressjs/session#sessionsavecallback).

**Comment by alex55132** [comment]
@dougwilson Also tried that, still not working

**Comment by dougwilson** [comment]
What does your code look like when trying it?

**Comment by alex55132** [comment]
@dougwilson In redirect.js:

```
router.get('/route', function (req, res) {  

     req.session.test = "hey"
     console.log(req.session.test);

      req.session.save(function(err) {
         if(!err) {
             //Data get lost here
             res.redirect("/");
         }
      });

  });
```

**Comment by dougwilson** [comment]
Hm, that should work. I'll reopen so we can investigate. Can you provide a full app and reproduction steps?

**Comment by alex55132** [comment]
@dougwilson Well the full app is the code provided earlier with the express module and the line which listens for connections, its only that

**Comment by dougwilson** [comment]
Right but it doesn't run as is. I modified it enough to actually run and then I had no issue and session didn't loose data after I made the session save modification as well.

**Comment by alex55132** [comment]
@dougwilson Can you show the code please? Which version are you using? This is really really weird :/

**Comment by dougwilson** [comment]
I am using latest. I already left work and you'll have to wait until I get back on Thursday to get the code I had.

**Comment by alex55132** [comment]
@dougwilson What's the code?

**Comment by dougwilson** [comment]
I had to stay home today, but plan to be in tomorrow.

**Comment by alex55132** [comment]
@dougwilson any update? :S

**Comment by frnk94** [comment]
I Have the same issue. It look like the session is save in the store but the redirect does not pass the new cookie `sessionId` in the response thus the server saying:
`express-session no SID sent, generating session`

Here my complete logs I also added a middleware that logs my `req.session.id`

<img width="1436" alt="Screen Shot 2019-07-23 at 4 48 42 PM" src="https://user-images.githubusercontent.com/11723501/61746631-23c89f80-ad6a-11e9-93d0-6c6383faad3c.png">

Weird enough If I refresh the page and do the browser redirection to localhost:/ then it work as expected.

**Comment by frnk94** [comment]
I had this issue and I resolve it by removing the `sameSite` options which was set to strict and I totally forgot about it. Maybe a log in the console could help developper when the cookie is not set due to same site policy being violated

**Comment by gireeshpunathil** [comment]
ping @alex55132 - did @frnk94 's suggestion help you?

**Comment by alex55132** [comment]
@gireeshpunathil Nope :(

**Comment by deveshMantra** [comment]
@alex55132 Can you share your code and steps to reproduce it?

**Comment by HarshithaKP** [comment]
@alex55132  Please find the session persistence with redirection example here : 
https://gist.github.com/HarshithaKP/3d9ad81138245aa7527bf385d37daba7
Let me know if it helps resolving your issue.

**Comment by yeahga** [comment]
Same issue
@HarshithaKP, It did not help

**Comment by ghinks** [comment]
hello @alex55132 has this issue be resolved to your satisfaction? Are there additional questions associated with this issue. If there are not any current issues I would like to close this.

**Comment by alex55132** [comment]
I don't have the code I was working with anymore, I'll reopen if the problem appears again in the future. Closing

**Comment by umakanth-pendyala** [comment]
@dougwilson Hey, I have a similar issue. Could you please help me out here? https://github.com/expressjs/session/issues/790

**Comment by imjohnbo** [comment]
This did the trick for me inside an `async` function. I am using `express-session` with the `@google-cloud/connect-firestore`.

```js
const myFunc = async (request, response) => {
    //...
    // save session before redirecting
    return new Promise((resolve, reject) => {
      request.session.save((err) => {      
        // redirect home
        if (err) {
          reject(err);
        }
        resolve(response.redirect('/'));
      })
    });
};
```
