### ISSUE TITLE
Make SameSite: Lax the default cookie setting

### ISSUE THREAD

**Issue by ethanresnick** [expressjs/session#662]
Having secure defaults is a pretty fundamental idea, since most people aren't going to change the out-of-the-box settings. `SameSite: Lax` is offers protection from many kinds of cross-origin information leaks and CSRF attacks, without breaking site functionality in most cases. There's [a proposal](https://tools.ietf.org/html/draft-west-cookie-incrementalism-00#section-3.1) from a Chrome engineer to have the browser treat `SameSite: Lax` as the default, which would secure the whole web. But, until that can happen, making it the default in this library would be a good step for Node users.

**Comment by dougwilson** [comment]
When this module came out, SameSite did not even exist. Adding it as a default would be a breaking change, and there is nothing fundamental about a session that makes Lax the clear and obvious way it should function. It would depend on what someone is using the session for.

If your session are used only for information in which Lax makes sense, this module does support setting your session cookies to the lax value: https://github.com/expressjs/session/blob/master/README.md#cookiesamesite

**Comment by dougwilson** [comment]
There is a plan to create a 2.0 branch soon to clean up various things. You're welcome to make a pull request to implement this as a default if you are interested in pursuing a change of default in the next major version, which is planned for very soon.

The cookie-session module is one that is going to come out even sooner (master is already 2.0 beta) and this module is ideally supposed to align so a change of default in it's 2.0 would make these match.

**Comment by dougwilson** [comment]
I think a downside to this change without any commitment from more people to triage issues is that the number one issue in the repo is users confused a out why their sessions do not load, and this setting would increase the cases for that, very likely increasing the amount of support requests in the process :(

**Comment by ethanresnick** [comment]
> Adding it as a default would be a breaking change, and there is nothing fundamental about a session that makes Lax the clear and obvious way it should function. It would depend on what someone is using the session for.

Yup, I understand this would be a breaking change, and I was imagining it for the next major release. 

You're right that not _every_ session can be Lax, but I'd guess that Lax would improve security without causing any breakage in the _vast_ majority of cases (95%+?), compared to the current default of `SameSite: None`, which is applied implicitly by browsers. If that weren't true, there'd be no way for browsers to even consider making Lax the browser-default value. 

I'm happy to make the PR for the next major version, if it would be accepted, but I can't in good faith make a commitment to help with ongoing support. If Lax really is appropriate for such a high percentage of cases, though, I'd hope the increase in support requests would be small.

**Comment by dougwilson** [comment]
So almost all the cases are because they are trying to use the session cross site and need to get the cors setup right. Why using them cross site is so popular seems to be due to the standard setup of tutorials of running a UI one one domain and the server on a different domain. I would assume that this change would break that use case, right?

**Comment by ethanresnick** [comment]
> I would assume that this change would break that use case, right?

Yeah, it [seems like it would, at least for now](https://github.com/whatwg/fetch/issues/769) :(
