### ISSUE TITLE
req.session.token is undefined

### ISSUE THREAD

**Issue by 931168348** [expressjs/session#675]
![image](https://user-images.githubusercontent.com/28802223/61686887-8498ad80-ad53-11e9-8169-7409e604eddb.png)
![image](https://user-images.githubusercontent.com/28802223/61686943-a7c35d00-ad53-11e9-87db-8e6c7365d3e8.png)
![image](https://user-images.githubusercontent.com/28802223/61686991-c88bb280-ad53-11e9-843e-d19db71b1ce6.png)

**Comment by 931168348** [comment]
Why sessions can be saved and not fetched？

**Comment by stigmat4j** [comment]
Some problem.

**Comment by strugee** [comment]
@931168348 it's bad form to post screenshots of code. Instead please edit your issue so your code is pasted in and surrounded with three ` characters (you can click the `<>` icon in the GitHub comment box toolbar to do this). It's also unclear what you're asking. Please describe fully what you expect to happen and what you actually observe.

**Comment by stigmat4j** [comment]
`session({
	name: "ex-qid",
	secret: `some-random-secret-here`,
	resave: true,
	saveUninitialized: true,
	store: new redisStore({ host: 'localhost', port: 6379, client: client, ttl: 360000 }),
	cookie : { httpOnly: true, maxAge: 2*60*60 }
})`
This code work for me. @931168348 Maybe use session store?

**Comment by gireeshpunathil** [comment]
ping @931168348 - does the suggestion from @stigmat4j help your issue? if not, can you describe the issue in a bit more detail: what is expected, and what is the actual. thanks!

**Comment by deveshMantra** [comment]
@931168348 can you please share -
What are you doing after saving token in the session?
what is the response sent by API as in screenshot it is not clear whether we are sending the response or not?

**Comment by dougwilson** [comment]
Closing due to no response.
