### ISSUE TITLE
Infinite sessions?

### ISSUE THREAD

**Issue by BorntraegerMarc** [expressjs/session#678]
Hi 👋 
I took a bit of a closer look in this library and wasn't sure whether it's at all possible to configure "infinite" sessions? So a session that really never expires. Even when the user is inactive forever.

I know about the [rolling option](https://github.com/expressjs/session#rolling) but if I understand it correctly this is only applied to "refresh" an existing session before it expires. So the user needs to make a HTTP request for the session to refresh.

So what I mean is having a session that doesn't expire without any user interaction.

**Comment by dougwilson** [comment]
The default behavior is sessions that never expire as long as the user does not close their web browser. This module specifically only controls the cookie; your store module may have a separate expiration policy you would need to look into.

**Comment by BorntraegerMarc** [comment]
Right. Makes sense.

Now that I think about it it's probably more a cookie restriction than this library. Source: https://stackoverflow.com/questions/3290424/set-a-cookie-to-never-expire

Anyways, thanks for the answer. Awesome job with maintaining the library @dougwilson !
