### ISSUE TITLE
Why sign the cookie?

### ISSUE THREAD

**Issue by ethanresnick** [expressjs/session#68]
I'm probably missing something simple, but what it the security benefit of sending a signed session-id in the cookie rather than an unsigned one? What are you preventing being tampered with? If the thought is that it makes it harder to guess valid session ids, don't you get this same benefit by simply making the ids longer?

**Comment by cdown** [comment]
There is some discussion of this here: http://security.stackexchange.com/questions/92122/why-is-it-insecure-to-store-the-session-id-in-a-cookie-directly
