### ISSUE TITLE
secure cookies not saved over https connection

### ISSUE THREAD

**Issue by Elliot128** [expressjs/session#680]
When using my app on Heroku, I use an https connection. Yet secure cookies do not get stored. Switching off secure cookies works. 

I thought secure cookies should work over https connections. Am I misunderstanding something about this?

**Comment by dougwilson** [comment]
Did you set up the trust proxy etc. according to the directions at https://github.com/expressjs/session/blob/master/README.md#cookiesecure ?

**Comment by Elliot128** [comment]
Wow I feel like a fool for missing that. I am not currently setting the trusted proxy, only the secure cookie Boolean.

I will try that in a few hours and close this issue asap if it works. 

Thank you for the quick response!

**Comment by dougwilson** [comment]
Cool. Your description makes me think that the Heroku is using a proxy, where your node.js server is actually just running http and they have a proxy doing https to http on the backend.

**Comment by Elliot128** [comment]
This was the issue. Seems like Heroku terminates the ssl on the load balancer they set up. Following the link from Doug solved my issues.

Thanks again!
