### ISSUE TITLE
Cookie not setting in production

### ISSUE THREAD

**Issue by malimccalla** [expressjs/session#681]
I'm having issues with the cookie not setting in a production environment. These are the debug logs I am getting 

```
// Login
Tue, 20 Aug 2019 13:54:00 GMT express-session saving dH8epNKKGGIhkjuzHNTvdtHyUAKCfzOX
Tue, 20 Aug 2019 13:54:00 GMT express-session split response
Tue, 20 Aug 2019 13:54:00 GMT express-session set-cookie tbsid=s%3AdH8epNKKGGIhkjuzHNTvdtHyUAKCfzOX.5U5m0OzHZsNWae6ZRURxR5tPL%2FYkTdYp9bvo0dELjvU; Path=/; HttpOnly

// Attempt to access logged in user
Tue, 20 Aug 2019 13:54:00 GMT express-session no SID sent, generating session
```

I can see in my browser that the cookie has not been set so is not actually getting sent back on requests. Here is exactly the same flow with the same set up that works in development

```
Tue, 20 Aug 2019 14:39:37 GMT express-session touching
Tue, 20 Aug 2019 14:39:37 GMT express-session split response
Tue, 20 Aug 2019 14:39:37 GMT express-session touched
Tue, 20 Aug 2019 14:39:37 GMT express-session fetching 9Vzkxzknn0h1iGPIhH5rO8qc6ZCJtah1
Tue, 20 Aug 2019 14:39:37 GMT express-session session found
```

This is my set up

```ts
  app.set('trust proxy', 1);

  app.use(
    session({
      store: new RedisStore({
        client: redis,
        prefix: redisSessionPrefix,
        host: process.env.REDIS_URL,
      }),
      resave: false,
      name: 'tbsid',
      proxy: true,
      secret: 'secret',
      saveUninitialized: false,
      cookie: {
        path: '/',
        maxAge: 1000 * 60 * 60 * 24 * 7,
        httpOnly: true,
        secure: false
      },
    })
  );
```

I have attempted various solutions from other issues (such as removing `cookie` block from configuration to use defaults) but still no luck. Everything works fine in test and development environments, its only when my server is hosted on either heroku or digital ocean that this happens

**Comment by mattandrews** [comment]
Have you tried setting the following?

`app.set('trust proxy', 1);` (or a different number depending on your config)?

**Comment by malimccalla** [comment]
hey @mattandrews - i do indeed have `app.set('trust proxy', 1);` set but will try increasing it thanks

**Comment by malimccalla** [comment]
@mattandrews unfortunately that didn't do it

**Comment by mattandrews** [comment]
Hmm – and this is over HTTP, right? Are you using a CDN (which might drop cookies) and can you confirm Redis is connecting properly?

**Comment by malimccalla** [comment]
I am accessing over HTTPS (I have tried both HTTPS and HTTP with `secure` set appropriately depending on if its HTTP or HTTPS) and not using a CDN. I can confirm that redis is connecting properly as I just managed to list all the session ids i've been saving. This has my stumped 😕

**Comment by malimccalla** [comment]
It may be worth mentioning that my api running express is on a different domain to the app consuming it maybe this has something to do with why the cookie does not set because If I run them on the same domain the cookie sets correctly

**Comment by mattandrews** [comment]
Yeah that sounds like it'll be the issue, especially if you can see the `set-cookie` call in the logs but never see it in your browser. You can use the `cookie.domain` setting when configuring your session, but this might be tricky as you won't be able to share them across different domains (only subdomains).

**Comment by malimccalla** [comment]
Thanks @mattandrews  you've been a big help I think that is my issue. Do you know if there is a way to get the generated cookie so that I can send it back to the client in the response body so that it can set it manually. I don't actually know if this is even a best practice... maybe I should just host my api and app on the same domain 😅

**Comment by mattandrews** [comment]
There's probably some way you could hack that together like you suggest, but yeah – not best practice! If you can architect things so your apps share a domain, that's probably going to save you further headaches down the road (eg. cross-site origin requests, SSL certificates mismatching etc).

**Comment by malimccalla** [comment]
Yeah definitely pretty hacky, I felt guilty even writing it out haha. Thanks for your help, will close this issue as I am going to move to a same domain architecture
