### ISSUE TITLE
res.setHeader with multiple cookies

### ISSUE THREAD

**Issue by saveman71** [expressjs/session#692]
I have a question about the way `express-session` is supposed to handle existing cookies.

It seems that it merges existing cookies with the new one, and then calls Node's `setHeader` that says

>Use an array of strings here to send multiple headers with the same name

So that is supposed to work.

But then, on the wire, I can witness that there is only *one* `Set-Cookie` header:

```
Set-Cookie: dismissBanner=; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT,connect.sid=s%3AjlPTOW-Vo4JIecSiHod_l-4_MZCNCqdp.rC%2BzQT0JRWihDI666AFoHEdAm%2FxIAAHY%2FTjP0DibaMM; Path=/; Expires=Fri, 27 Sep 2019 13:48:46 GMT; HttpOnly
```

However, many user agents, such as `superagent` (using [cookiejar](https://www.npmjs.com/package/cookiejar)), do not support such string and usually only care about the first cookie (which is not the session cookie).

See also https://github.com/visionmedia/superagent/issues/1508

This [answer on StackOverflow](https://stackoverflow.com/a/2880070/2367848) explains how it's generally a bad idea to have multiple cookies in the same `Set-Cookie` header.

Is this a Node bug? It seems express had [fixed this](https://github.com/expressjs/express/commit/08497683bf7421210efce8a7361b869c1eac76ae) an other way.

**Comment by dougwilson** [comment]
Unless you think this module is using the Node.js API in the wrong way, or it should be doing something different, it sounds like you are describing a Node.js bug somewhere if this module is calling the API in the expected way to set multiple `Set-Cookie` headers.

**Comment by dougwilson** [comment]
> It seems express had fixed this an other way.

That is a commit from 2010, almost 10 years ago, and many, many Node.js versions ago. Current Node.js versions will actually reject any header that contains the `\n` character in the value.

**Comment by saveman71** [comment]
Thanks for the quick answer. I drafted a quick repro to check if it was a Node.js bug, *it's not*.

```
const http  = require('http');

const httpServer = http.createServer(requestResponseHandler);
httpServer.listen(3000, () => {
  console.log('Node is listening on port 3000')
})
function requestResponseHandler(req, res){
  res.setHeader('Set-Cookies', ['a', 'b'])
  res.writeHead(200, {'Content-Type': 'text/plain'});
  res.write('test header');
  res.end();
}
```

![Screenshot from 2019-09-20 16-52-49](https://user-images.githubusercontent.com/1615426/65336717-29563080-dbc7-11e9-88f7-f3a4579a3d33.png)

I'm investigating.

**Comment by saveman71** [comment]
So actually my full set-up seems to set both headers separately. It seems to be a bug with `super-agent`. Sorry for the spam.

**Comment by saveman71** [comment]
For what it's worth, it was caused by https://github.com/facebook/jest/issues/2549

**Comment by dougwilson** [comment]
Thanks for the follow up link.
