### ISSUE TITLE
Update session for other users

### ISSUE THREAD

**Issue by neerajhiretual** [expressjs/session#693]
I have a use-case where in an Admin can change roles for other users in his team. In that case, the role change must be reflected in the other users' sessions.

I know, we can do something like `req.login and similar fns` to manipulate the currently logged-in user's session. But i am not sure how to achieve the same for other users.
I am not sure as to what might be a correct way to do it. I use `express-mysql-session` as a store.

This is a question rather than an issue. If you can reflect some light on this, that'd be great. 
Right now, only solution that comes to my mind is to show some floating notification on UI whenever user's role is changed in DB (either do polling or some socket related things, to verify if roles has changed). As soon as user clicks the notification, a request is triggered to express app which can then update that user's session. But this does not seem like a good solution, hence this question.

**Comment by dougwilson** [comment]
Hi @neerajhiretual thanks for the question. You'll need to ask this particular one on your store's issue tracker, as any kind of management of sessions as a general operation is all done at the store level. This module is the glue that populates `req.session` with just the specific session that corresponds to that request.

**Comment by neerajhiretual** [comment]
That was fast, thanks!
