### ISSUE TITLE
express interface api to get sessionid has different when i unified session multiple submissions

### ISSUE THREAD

**Issue by xulayen** [expressjs/session#695]
![image](https://user-images.githubusercontent.com/15044564/65473622-17b4a780-deab-11e9-8a00-052a4ebb4d13.png)

**Comment by knoxcard** [comment]
What are using for your session store? Redis?

**Comment by gireeshpunathil** [comment]
ping @xulayen

**Comment by gireeshpunathil** [comment]
no response in almost a month; a close candidate. [ it could be a plain case of session expiry? without further info hard to tell]

**Comment by dougwilson** [comment]
I'll close it out and if OP responds we can re-open the issue.
