### ISSUE TITLE
[Cookie]: Cannot set the `SameSite: None` cookie

### ISSUE THREAD

**Issue by legomushroom** [expressjs/session#696]
Hi,

In anticipation of the breaking change in Chromium regarding the [SameSite cookie defaults](https://www.chromestatus.com/feature/5088147346030592) we try to set the cookie to `None` to explicitly enforce the prior browser behaviour.
When we do that, we the latest version `1.16.2` the server blows up since the `express-session` module does not support the `nonce` value to be set.

Looks like the fix was [already merged in](https://github.com/expressjs/session/pull/674), but npm still have the [old version of the cookie module](https://unpkg.com/express-session@1.16.2/package.json).

Do you mind to publish the latest to `npm`?

Thanks!

**Comment by dougwilson** [comment]
Yes, the change was merged in and I did forget about publishing it. I saw the comment on the PR but am just out of the country and will publish as soon as I am back.

**Comment by RoiTal88** [comment]
+1
wating for the npm publish
thank you!

**Comment by Moniarchy** [comment]
Thanks, @dougwilson! Do you know when you're coming back/plan to publish?

**Comment by dougwilson** [comment]
I was just merging some outstanding easy PRs (like docs) into master yesterday, but then ran into a personal issue and was not able to come back to github the rest of the night. I am almost off work now today and plan to complete it when I get home tonight.
