### ISSUE TITLE
Not persisting session cookie on subdomain

### ISSUE THREAD

**Issue by cph2117** [expressjs/session#705]
When I deploy to production my frontend (`frontend.example.com`) does not persist the cookie being returned from my API (`api.example.com`). I make the frontend request with withCredentials:true (axios). Here is my code on the backend (edited for brevity):
```
const cors = require('cors');
var session = require('express-session');
var SequelizeStore = require('connect-session-sequelize')(session.Store);

const sessionStore = new SequelizeStore({
    db: db.sequelize,
    checkExpirationInterval: 15 * 60 * 1000,
    expiration: sessionExpiration,
});
sessionStore.sync();

const app = express();

// corsOrigin is a function that returns a matching domain
app.use(cors({ origin: corsOrigin, credentials: true }));

app.use(
    session({
        name: 'sid',
        secret: process.env.SESSION_SECRET,
        store: sessionStore,
        saveUninitialized: true,
        resave: false,
        proxy: false,
        cookie: {
            maxAge: sessionExpiration,
            httpOnly: false,
            domain: '.example.com',
            secure: false,
        },
    })
);
```
I think it's a sub/cross-domain issue, but I expected domain: '.example.com' to solve the issue. Any thoughts?

Stack:
node: v10
express: v4.16
express-session: v1.17
connect-session-sequelize: v6.0.0

**Comment by gireeshpunathil** [comment]
what front-end code you are using? do you have any evidence of the `cookie` being arrived at the front-end?  is it possible to put some debug statement to validate that? If it is coming, it might have to do with the client inhibiting cookie in some manner, not an issue in the back end.

**Comment by dougwilson** [comment]
Closing due to no response.
