### ISSUE TITLE
Unable to pass express-session from one route to another route

### ISSUE THREAD

**Issue by ajaybirbal** [expressjs/session#706]
I am trying to log in user using express-session variable. I am not able to pass sessions on other routes. 

MY app initialization file (index.js) file: -

```
    const session = require('express-session');
    app.use(session({
        secret: config.get('secretKey.key'),
        resave: false,
        saveUninitialized: true,
        cookie: {
            maxAge: 6000
        }
      }))

```
When someone clicks on submit after filling in username and passowrd, node redirects to this login controller page: - 

```
    router.post('/', (req, res) => {
    
        let user_session = req.session;
        if(!user_session._id){
                
            Users.findOne({username: req.body.username}, (err, user) => {
    
                if (err) console.log("Database error: " + err);
        
                let passwordMatch = checkUser(req.body.password, user.password);
                if (passwordMatch) {
        
                    user_session.userId = user._id;
        
                    console.log("Successfully logged in: " + user_session.userId);
                } else {
                    console.log("Login failed");
                }
                
            })
    
        } else {
            res.redirect('/admin');
        }
    })
```

Once the login is successful, they will be redirected to this route. However, I am not getting logged in and instead, I am getting you need to log in the message as I have set below. This is my admin page code 

```
    router.get('/', function (req,res) {
    
        let user_session = req.session;
        if (user_session.userId){
            console.log(session.userId)
            res.render('./../views/admin/admin.pug');
        } else {
            res.send("You need to login first!");
        }
    })
```

**Comment by gireeshpunathil** [comment]
shouldn't 

```js
router.get('/', function (req,res) {
```

be

```js
router.get('/admin', function (req,res) {
```
?

**Comment by PyroSA** [comment]
> shouldn't
> 
> ```js
> router.get('/', function (req,res) {
> ```
> 
> be
> 
> ```js
> router.get('/admin', function (req,res) {
> ```
> 
> ?

It's likely that router is linked into the app under 'admin' - so the /admin is added automatically

**Comment by gireeshpunathil** [comment]
> - so the /admin is added automatically

I am not sure I follow that. In either way, the logic that checks the validity of the session is present in `/` route, not in the (automatically added or otherwise) `/admin` route - is my point. Unless we put the logic in that route, this is not going to work as expected.

Makes sense to you?
