### ISSUE TITLE
Session Does Not Persist After Redirect

### ISSUE THREAD

**Issue by austencollins** [expressjs/session#71]
For the life of me, I can't seem to get the session to consistently save data after redirecting.  It works maybe 1 out of every 6 tries in my production app.  It works every time in my development app.  Could anyone tell me what I'm doing wrong?  Here is my stackoverflow post with my source:  http://stackoverflow.com/questions/24981181/express-session-does-not-save-after-redirect

Austen

**Comment by anied** [comment]
Five years later, and the advice from @dougwilson that setting `resave: true` "has a high likelyhood of requests stomping out the changes you're making to your session" just saved me.  Thanks!
