### ISSUE TITLE
You have `resave` set to true if you look at the readme:

### ISSUE THREAD

**Issue by OsborneDS** [expressjs/session#717]
You have `resave` set to true if you look at the readme:

> Forces the session to be saved back to the session store, even if the session was never modified during the request.

essentially saving the session automatically no matter what you do. In addition the `saveUninitialized: true` means that if the user has no session they will be given a blank session which you are free to change while the request is still being handled on the server. If either of these sounds like something you do not want to be doing I would suggest you change them to `false`.

_Originally posted by @gabeio in https://github.com/expressjs/session/issues/186#issuecomment-124135570_

**Comment by OsborneDS** [comment]
Hello @gabeio, My name is Osborne D'Silva. I am working on a Angular 7 project with Node JS as my api server. I have been working on express-session in node js for a while now and am facing the same issue that is, the node server creates new session on different api's. I have tried all the configurations possible but am not able find a solution to this issue.

I tried the above suggestion and have set 
resave: false,
saveUninitialized: true

Any suggestions would be of great help. Thanks in advance.

**Comment by HarshithaKP** [comment]
@OsborneDS  Setting `saveUninitialized: false` doesn't save the session if the session object given to user is unaltered. Can you try and let me know if this resolves your problem ?

**Comment by OsborneDS** [comment]
@HarshithaKP thanks for the suggestion, I'll try that out. Just one more query, Should I keep resave as False or should that be changed to true?

**Comment by OsborneDS** [comment]
Hello @HarshithaKP, the issue still persists. Thanks for the suggestion though. Any other pointers on the same?

**Comment by HarshithaKP** [comment]
@OsborneDS Can you provide minimal reproducible code ?

**Comment by OsborneDS** [comment]
![session2](https://user-images.githubusercontent.com/58810638/70773155-a515e280-1d9c-11ea-9059-1ebe4634af99.png)

**Comment by HarshithaKP** [comment]
@OsborneDS What you provided is the session constructor code, can you provide the usage of session object , to see what makes unaltered session to be saved.

**Comment by OsborneDS** [comment]
![session3](https://user-images.githubusercontent.com/58810638/70774322-e0fe7700-1d9f-11ea-80bc-19040790605b.png)

**Comment by HarshithaKP** [comment]
@OsborneDS The code which you have pasted is working fine for me with memory store and session is not saved with `saveUninitialized: false`, can you cross check the same by putting it in debug mode as follows :

`export DEBUG = express-session`

Let me know the output of debug.

**Comment by gireeshpunathil** [comment]
@OsborneDS - also, when you provide code, please paste as text, as opposed to image:
 - easy for others to copy-paste and try out,
 - reduces the overall data pressure in the internet. :)
 - you could use github markdown (enclose the code in triple backtick followed by js and triple backtick) to show the code in style.

thanks!

**Comment by OsborneDS** [comment]
thanks @gireeshpunathil

**Comment by OsborneDS** [comment]
Thanks @HarshithaKP for the suggestions. I'll be omitting the full thing.
