### ISSUE TITLE
Frequent test failure

### ISSUE THREAD

**Issue by BridgeAR** [expressjs/session#719]
Node.js runs this modules test suite on the newest Node.js versions as smoke test using [citgm](https://github.com/nodejs/citgm). Doing that frequently returns this error:

```
           1) should equal original maxAge for all requests
   119 passing (4s)
   1 failing
   1) session()
        req.session
          .cookie
            .originalMaxAge
              should equal original maxAge for all requests:
      Error: expected '2000' response body, got '1999'
       at error (node_modules/supertest/lib/test.js:301:13)
       at Test._assertBody (node_modules/supertest/lib/test.js:218:14)
       at Test._assertFunction (node_modules/supertest/lib/test.js:283:11)
       at Test.assert (node_modules/supertest/lib/test.js:173:18)
       at Server.localAssert (node_modules/supertest/lib/test.js:131:12)
       at emitCloseNT (net.js:1652:8)
       at processTicksAndRejections (internal/process/task_queues.js:83:21)
 npm ERR! Test failed.  See above for more details.
```

It is likely that this is a rounding issue and the test could be fixed by accepting 1999 as passed as well. The specific test name is also not unique and that should probably also be changed.

See https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2141/nodes=fedora-last-latest-x64/testReport/junit/(root)/citgm/express_session_v1_17_0/ (available ~7 days)

**Comment by dougwilson** [comment]
Clicking on that link is trying to authorize access to private data in the organizations I'm a member of. Is there another link i can use?

**Comment by BridgeAR** [comment]
@dougwilson not that I am aware off. I just expanded the test failure result above. There's not much more interesting to see.

**Comment by dougwilson** [comment]
Thanks! I will try to get a change to make your testing not flaky and will ping you here when ready on master branch in case you can test in your infra.
