### ISSUE TITLE
Session doesn't work with mac but it works with windows

### ISSUE THREAD

**Issue by BrenM94** [expressjs/session#720]
Everytime I try to save the session on Mac, it doesn't but when i try to do it with windows it works perfectly. It's the same with react native app, the cookies do not save on ios but it does with android.

**Comment by gireeshpunathil** [comment]
can you try this link to enable cookies for ios and retry?
https://help.overdrive.com/en-us/0606.html

**Comment by BrenM94** [comment]
Thanks! It helped me a lot
