### ISSUE TITLE
Saved session data not found in other network(IP).

### ISSUE THREAD

**Issue by pradeep-raj** [expressjs/session#726]
I'm working with

    1. "nodejs": "12.15.0"
    2. "express": "^4.17.1"
    3. "express-session": "^1.17.0"
    4. "cookie-parser": "^1.4.4"

When i use session variables across pages or routes is working fine on network(localhost). but session variables doesn't exist(req.session), while checking with different network like IP, system.

Expected Output: I want to access session variables (declared in my network-localhost) to remote network(IP).

**Comment by jonchurch** [comment]
What session store are you using? By default MemoryStorage is used, which won't be available across different machines and is not recommended for production.

**Comment by pradeep-raj** [comment]
> What session store are you using? By default MemoryStorage is used, which won't be available across different machines and is not recommended for production.

Thanks for reply @jonchurch
 	
This is session initialization on my code.

     app.use(session({
           secret: 'loginCredential',
           name: 'Username',
           proxy: true,
           cookie: { secure: process.env.NODE_ENV == 'production' ? true : false, httpOnly: false,  maxAge: 60000  },
           resave: true,
           saveUninitialized: true
    }));

I don't use _**store**_ property in initialization and any of store modules in [express-session](https://github.com/expressjs/session) **"Compatible Session Stores"**, that's why it takes default MemoryStorage.

Yes i understood, the default MemoryStorage not be available across different machines, Whether it's mandatory to use any one of store module for across different machines?

**Comment by jonchurch** [comment]
The store implementation is up to you. Once its set up, any machine that is running this code with proper access to the store DB should be able to access the sessions.

**Comment by pradeep-raj** [comment]
Yep, i used [connect-mongo](https://www.npmjs.com/package/connect-mongo) module  for access the session working fine.
thanks a lot @jonchurch for the suggestions and quick reply, now i clearly known about session used in nodejs .
so I would like to closing this issue as answered.

**Comment by jonchurch** [comment]
@pradeep-raj happy to help
