### ISSUE TITLE
Add an option to specify a "touch interval" when using rolling sessions

### ISSUE THREAD

**Issue by simlawr** [expressjs/session#727]
When the "rolling" option is used the session expiration is reset on every response, resulting in a write to the session store. For short-term sessions e.g. 10 minutes this is perfectly acceptable but for longer durations e.g. 30 days, it's not necessary to update quite so frequently.

In situations where writes to the session store are expensive, this behaviour is undesirable. 

Excessive writes pose a particular problem to users of on demand databases such as DynamoDB, which charge for every write (or the capacity to write at a certain rate).

I propose introducing a "touch interval" option that would specify a minimum time period  between calls to `touch()` when using "rolling" sessions. Here are some examples:

- 10 minute session updated every 0 seconds (every request)
- 2 hour session updated every 10 minutes
- 24 hour session updated every hour
- 30 day session updated every 48 hours

[dynamodb-store](https://github.com/agstover/dynamodb-store) has this functionality but it applies globally, regardless of `maxAge`. 

Whereas specifying a "touch interval" in _express-session_ would provide the kind of per session customisation as shown in the above examples, to every session store.

**Comment by ghinks** [comment]
@simlawr your proposal has been noted. We are in the process of adding more resources to this repo. Have you considered raising a PR?

**Comment by dougwilson** [comment]
Hi @simlawr this is an issue with your store implementation, under the hood. The `touch` is called on a store on every end of a session, regardless of anything happening. The purpose of this is to allow your store to do with it what it wants to do. If your store wants to keep bumping the session expiration, that is perfectly OK to do.

This is something you should propose to your store implementation -- to only write session accesses every n amount of time. Your post even indicates that this is an issue with some particular store types, which is another reason this type of option should be delegated to the specific store implementation that has that type of limitation.

> Whereas specifying a "touch interval" in express-session would provide the kind of per session customisation as shown in the above examples, to every session store.

I would say, if that is your goal, it still does not need to be done in this module. You can publish a module that uses the decorator pattern to decorate any store you like with this option without adding further complexity to this module and without keeping this specific to the store. If there are more decorator-style modules out there, we could even add a section to the README with them.

**Comment by jotaen** [comment]
Would it be viable to offer some sort of pre-touch hook, along the lines of `shouldTouch :: Session => bool`? That would default to `() => true` but can be overriden to account for specific use cases, like the one above (which I personally think is not that uncommon in regards to session management).

That way it would be easy to customise, while keeping additional complexity away from this library.

**Comment by dougwilson** [comment]
Hi @jotaen you can make a module that uses the decorator pattern to decorate any store you like with this option without adding further complexity to this module and without keeping this specific to the store.
