### ISSUE TITLE
Unpredictable undefined cookie after redirect

### ISSUE THREAD

**Issue by Gehbrial** [expressjs/session#730]
**Node**: Version 13.9.0
**Store**: MongoDB v.4.3.2 using the _connect-mongodb-session_ package

```js
import session from "express-session";
import connectMongoDbSession from "connect-mongodb-session";

const MongoDbStore = connectMongoDbSession(session);

app.use(session({
  secret: "someSecret",
  name: "someName",
  resave: true,
  saveUninitialized: true,
  cookie: {
    maxAge: 60000,
    path: "/",
    httpOnly: true,
    secure: false
  },
  store: new MongoDbStore({
    uri: "mongodb://localhost/auth",
    collection: "sessions"
  })
}))
```

Here is our current authentication flow:

1. User hits our login route at **/login**
2. We save the session then redirect to our OAuth provider authentication page: `req.session.save(err => { if (!err) { res.redirect(someUrl); } })`
3. On login success, our oAuth provider sends a POST request on our redirect URI at **/login/callback**
4. The **login/callback** handler redirects the user to our home page: `res.redirect("/home")`

**The problem is the following**: the cookie isn't always populated on our redirect URI route.

**After being redirected to the home page**
If I wait about 30 seconds then hit the login route, my **login/callback** handler will see the `req.headers.cookie` value as being `undefined` and the `req.session.id` value will be different, meaning a new session has been created. Here is an exemple of the behavior:
```js
// @GET /login
console.log(req.session.id); // Outputs "sessionA"
console.log(req.headers.cookie); // Outputs "cookieA"

// @POST /login/callback (oAuth provider)
console.log(req.session.id); // Outputs "sessionA"
console.log(req.headers.cookie); // Outputs "cookieA"

// At this point, there is only one session in our session store
// Wait around 30 seconds...

// @GET /login
console.log(req.session.id); // Outputs "sessionA"
console.log(req.headers.cookie); // Outputs "cookieA"

// @POST /login/callback (oAuth provider)
console.log(req.session.id); // Outputs "sessionB"
console.log(req.headers.cookie); // Outputs undefined

// At this point, our session store contains two sessions
```

Waiting 30 seconds doesn't always trigger the creation of a new session. It seems like a timing or race condition issue. We have tried multiple options configurations and nothing changes. We are somewhat clueless as to what could be the problem. Any help would be appreciated.

Thank you!

**Comment by Gehbrial** [comment]
I managed to resolve my issue: it was caused by the new Chrome 80's SameSite cookie policy. Our oAuth flow was using the _form_post_ response mode which made the call to our callback route a POST request. It was therefore considered a cross-site request and the cookie wasn't attached. We resolved it by using the _query_ response mode and by using the following configuration:
```
if (process.env.NODE_ENV === "production") {
  app.set("trust proxy", 1);
}

app.use(session({
  secret: process.env.SESSION_SECRET,
  name: "someName",
  resave: false,
  saveUninitialized: true,
  cookie: {
    maxAge: 14 * 24 * 60 * 60 * 1000, // 2 weeks
    path: "/",
    httpOnly: true,
    secure: process.env.NODE_ENV === "production",
    sameSite: "lax"
  },
  store: new MongoStore({
    uri: process.env.DB_URI
    collection: "sessions"
  })
}))
```

To my understanding, the _query_ response mode is considered a redirect, which is supported by SameSite: Lax (the new Chrome default value). To this day, I'm still not sure why the first redirect used to work for a while but stopped after about 30 seconds.

**Comment by ryhinchey** [comment]
Thanks for following up with the fix for your issue @Gehbrial!  I'm going to go ahead and close this issue.

If anyone else finds this issue when dealing with `SameSite` attributes in their cookies, here's a great read about them:

https://web.dev/samesite-cookies-explained/
