### ISSUE TITLE
Cookie expire getting changed with rolling=false

### ISSUE THREAD

**Issue by stormbard** [expressjs/session#732]
I'm setting the session up as follows:
```javascript
let sess = session({
    store: sessionStore,
    secret: config.cookie.secret,
    cookie: { maxAge: Number(config.cookie.maxAge), httpOnly: false },
    saveUninitialized: false,
    name: config.cookie.name,
    unset: 'keep',
    resave: false,
    target: null,
    rolling: false
})
```
The session store is connect-redis.

The behavior I am seeing is that the cookie maxAge and expires are getting reset when I update any data I am adding to the session. Am I misunderstanding what rolling is supposed to do? If so how do I create the session in such a way that it expires maxAge from creation?

**Comment by dougwilson** [comment]
The values in the `cookie` option are just what parameters the cookie will have whenever it is set. That means every time the cookie is set, the `max-age` (i.e. `expires`) will be set to the value provided, along with your `httpOnly` value.

The `rolling` controls how often the cookie is set. See the rolling documentation: https://github.com/expressjs/session#rolling

> With this enabled, the session identifier cookie will expire in maxAge since the last response was sent instead of in maxAge since the session was last modified by the server.

**Comment by stormbard** [comment]
Is there a way to create a session where he expires is immutable and max-age only counts down?

**Comment by ghinks** [comment]
I am sorry @stormbard  please open another issue as this has been closed.

**Comment by dougwilson** [comment]
Hi @stormbard , no, there is currently no option to do this in this module, mainly because such a restriction needs to occur on the server-side (in the store mechanism) vs in the client side (the cookie expiration). This is because a client can alter the cookie expiration and the server would not know that is happening.
