### ISSUE TITLE
Question: Setting custom express-session session cookie data

### ISSUE THREAD

**Issue by sgpinkus** [expressjs/session#736]
I have two servers. One that generates the sessions, and another that has access to the cookie encryption key and will receive the session cookie. I want to parse extra payload data to the 2nd server that is tied to the session life time. I could just create another cookie, but I want to the express-session cookie because it's 1 to 1 with the express session and managed by express-session, as opposed to me keeping two different cookies life times in sync. Is this possible? Thanks!

**Comment by ghinks** [comment]
From what you have written above I think you want to share data via the session cookie on multiple servers. 

- one server generates sessions
- second server is sent the cookies but does not generate sessions

From your description I am assuming server #2 would not have express-session middleware running.
But would be able to validate the cookie via its secret. 

if you have the session Id you could access the store directly to access the information, that information could expire or change at any time as a result of server #1.  But you could **read** it. It sounds very much that even thought the 2nd server is your server it would behave much like a third party server that gets cookies. This is not explicitly supported but if can access store and you understand it you can see the same data.

**Comment by sgpinkus** [comment]
Thanks for the help @ghinks. 

> but if can access store and you understand it you can see the same data.

That's exactly the way it's setup now - server two has access to the Redis store with read access. It only needs a small amount of info from that store, that is static from the point of session initialization to session destruction. Given this, I was wanting to remove the 2nd servers dependency on Redis and just use a cookie. Reasoning: 1. Well, generally removing the Redis dep reduces complexity 2. easier to setup test environments, 3. Limit access to Redis where not necessary.

I'm just creating a second encrypted cookie along side the session cookie and passing that server 2. It's working.
