### ISSUE TITLE
Option to save session before sending response

### ISSUE THREAD

**Issue by skoranga** [expressjs/session#74]
Looks like fix for https://github.com/expressjs/session/issues/61 (https://github.com/expressjs/session/commit/901c8e062c8789d3963ebe175a75d25d3c229245) is causing some wired race condition. 
In my usecase `req.session.save` is calling also encrypting the data before storing. And usually it takes more little longer than non-encrypted version. Because of the async nature of session save the next request is starting most of the time before the save is complete. And this next request is fetching the old version of session. 
Is there any possibility to add some flag to control the async/sync session save or any other solution?

**Comment by mjquito** [comment]
I still have the same issue as @skoranga was having it. The res.session.save() is saving twice. I'm using "express": "4.16.2", "express-session": "1.15.6". I really need help!
