### ISSUE TITLE
Cannot set property user of undefined

### ISSUE THREAD

**Issue by LandenStephenss** [expressjs/session#743]
So i have this in my main `index.js` file
```js
app.set('trust proxy', 1)
app.use(session({
    secret: "xCubedBakesCookies",
    resave: false,
    saveUninitialized: true,
    cookie: {
        secure: true
    }
}))
app.use("/oauth", Routers.OAuth)
```
and then i have this in my OAuth router
```js
    req.session.user = {
        ...user,
        isAdmin: config.admins.includes(user.id),
    }
```
I keep getting that same error no matter what i do, any help?

**Comment by ghinks** [comment]
Please could provide a **little more detail**. This does not look like an issue but rather a **question** about usage. It would help both us( the front line triage team) and yourself if you could create a **small repo** which demonstrates you problem.  I believe you are using middleware that sets a user on the session but are getting an error.

**Comment by LandenStephenss** [comment]
https://github.com/LandenStephenss/xCubed.xyz Everything session related is inside of ./src/server

**Comment by ghinks** [comment]
I could not run the repo provided as it had several bugs associated with your config file. I did however examine the code. Now that I have context I can assure you that the issue you have is that the routers are higher up the middleware than the session middleware is.  For this to work the router calls would need to be made after the session middleware is **used**. I am going to **close this issue** as I am sure it is an application use error. You may however ask for it to be re-opened if you believe this is a real issue with the **session** software and not your application.

**Comment by LandenStephenss** [comment]
Even if it is above all of my routers i still get the error.
https://i.imgur.com/eagyL4r.png
https://i.imgur.com/wAUgH6S.png
https://i.imgur.com/6RLvkct.png

**Comment by ghinks** [comment]
@LandenStephenss we are not here to debug your applications the issue remains closed. Provide a working example of the failure with instructions.

**Comment by DavidAlejandro18** [comment]
@ghinks For example, how can I get the value of req.session.views so far to a different page (/ base / bar2)?
