### ISSUE TITLE
Two session cookies with different maxAge! Is it possible

### ISSUE THREAD

**Issue by teknolojia** [expressjs/session#745]
My server requires email and password to log in user but after inactivity or when browser is closed, user will be asked to enter pin (just 4 digits) to unlock the account and new session would be generated. Why I am trying to do is to have session with `maxAge of 30 minutes` and `rolling = true`.

I was thinking of setting longer session (1 year) which would only be used to identify the user and shorter session which would allow access to the rest of system if user supplied correct pin. I wonder what would be the right approach to this.

I honestly don't know if this lib alone could provide the feature I want for my app, But any idea that would get me to the right direction will be much appreciated.

**Comment by ghinks** [comment]
You can certainly have more than one session cookie and the scenario you describe is not uncommon, essentially a user session cookie and a logged in cookie each with different behaviors. 
The session middleware is designed for a single session cookie and handles most of the complexity for a single session cookie for you. For your scenario you are going to have to get involved directly with setting your own cookies.
