### ISSUE TITLE
User agent based `sameSite` cookie value

### ISSUE THREAD

**Issue by stephtr** [expressjs/session#756]
Starting with July, Chrome in specific cases requires the `sameSite` property of cookies to be set to `None`. However some browsers like specific versions of Safari don't support that value and automatically switch to `Strict` when `None` is sent. [User agent sniffing](https://www.chromium.org/updates/same-site/incompatible-clients) is therefore necessary for deciding which value to send, which however isn't possible with the current implementation of express-session.

Since I wouldn't include the UA sniffing part into this library [(neither did Microsoft with ASP.NET Core)](https://devblogs.microsoft.com/aspnet/upcoming-samesite-cookie-changes-in-asp-net-and-asp-net-core/), would it be OK to add the functionality for `sameSite` to also accept a function `(req) => string | boolean` to set the value based on the incoming request?

**Comment by dougwilson** [comment]
The issue with this proposal,  of course, is that you will need to go though all the modules on npm getting them to do this. I would suggest (if not already on npm) to create a module that will alter any existing set-cookie headers on the response just before they are sent, as a hook. When it sniffs the user agent is Safari, it would remove sameSite=None from the header. This solution would not require every npm module to add sameSite as a function or similar and require users to then add this sniffing logic there for everything that needs it :+1:

**Comment by dougwilson** [comment]
A quick search on npm turned up https://www.npmjs.com/package/should-send-same-site-none which has a middleware that does exactly what you are looking for, I believe. Just use that middleware above this module and it will take care of the Safari issue for you.

**Comment by stephtr** [comment]
Thank you, that's obviously the best solution!
Would it make sense to add a sentence about that to the README file?

**Comment by dougwilson** [comment]
I mean, there are many of these types of situations and issues, the samesite is not the first and unlikely to be the last. Having every module (like this one) list evert issue out there and try to keep a list of modules we don't maintain is just not really tenable. All I searched on npm was samsite and it was right there, so it would seem for many issues, like this one, npm is a good source for finding the right solution for a given need.

**Comment by stephtr** [comment]
I just thought because basically everyone using `sameSite: 'none'` will run into that issue and I didn't think about changing the set-cookie header by using a middleware.
Anyway, thank you again for your help!
