### ISSUE TITLE
Deferred Errors causing Duplicate header sent errors

### ISSUE THREAD

**Issue by scirelli-c1** [expressjs/session#758]
I'm using express-session with connect-sesssion-sequalize as the store. 

When there is no session cookie set code here [line 470](https://github.com/expressjs/session/blob/master/index.js#L475) calls next and allows the next middleware to run. In my case it's a simple GET request handler and immediately sends a response with some data. It looks like some database connection/communication continues on. When the database is not present or errors out, the `next` from the already handled request is called with this database error.

Since I have an express error handler to look at the errors and determine what to send to the client, I get a: 
> Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client  

To fix this I have to check if the response is finished before sending a response.

I have express-session as one of the first middlewares executed.

**Comment by dougwilson** [comment]
Hi @scirelli-c1 can you provide a very simple app that replicates this issue for us?

**Comment by scirelli-c1** [comment]
Quick and dirty. You should just be able to run this after an `npm install`. I tested it I get the same error logged. To run it more than once you have to clear the cookie that gets set.

The "fix" is the first commented out line in the error handler.

<details>
<summary>Code</summary>

```
#!/usr/bin/env node
const expressSession = require('express-session');
const Sequelize = require('sequelize');
const SequelizeStore = require('connect-session-sequelize')(expressSession.Store);
const debug = require('debug');
const LOG_TAG = 'DEMO',
    logger = {
        debug:   debug(`${LOG_TAG}:debug`),
        info:    debug(`${LOG_TAG}:info`),
        log:     debug(`${LOG_TAG}:log`),
        warn:    debug(`${LOG_TAG}:warn`),
        error:   debug(`${LOG_TAG}:error`),
        request: debug(`${LOG_TAG}:request`)
    };
const FIFTEEN_MINUTES = 15 * 60 * 1000;
const TWENTY_FOUR_HOURS = 24 * 60 * 60 * 1000;
const port = 8080;

const app = require('express')();

const sequelize = new Sequelize('dbname', 'username', 'password', {
    host:    'localhost',
    dialect: 'postgres'
});

const sessionStore = new SequelizeStore({
    db:                      sequelize,
    checkExpirationInterval: FIFTEEN_MINUTES,
    expiration:              TWENTY_FOUR_HOURS,
    disableTouch:            true
});

const session = expressSession({
    secret:            'sd',
    store:             sessionStore,
    saveUninitialized: true,
    resave:            false,
    proxy:             true
});

sessionStore.sync().then(()=>{
    return sequelize.sync({force: false});
}).catch((e)=>{
    logger.error(e);
});

app.use(session);

app.get( '/health-check', async (request, response) => {
    response.send('up');
});

app.use(function genericErrorHandler(err, req, res, next) {
    // if(res.finished) return next(err);
    logger.error(err);
    if(err instanceof Sequelize.Error) {
        res.status(575).send({
            statusCode: 575,
            id:         575,
            message:    'Database Error'
        });
    }else {
        next(err);
    }
});

app.listen(port, () => logger.log(`Listening on port ${port}`));
```

</details>

<details>
<summary>package.json</summary>

```
{
  "name": "demo",
  "version": "0.1.0",
  "dependencies": {
    "connect-session-sequelize": "^6.1.1",
    "debug": "^4.1.1",
    "express": "^4.17.1",
    "express-session": "^1.17.0",
    "pg": "^7.18.2",
    "pg-hstore": "^2.3.3",
    "sequelize": "^5.21.5"
  },
  "scripts": {
    "start": "node server.js",
    "debug:dev": "env DEBUG=* node --inspect-brk server.js",
    "server": "node server.js"
  }
}
```

</details>

**Comment by dougwilson** [comment]
Thank you, but I'm not seeing an issue here. I think the bug is just in your custom error handler. You can read more about how to write one at http://expressjs.com/en/guide/error-handling.html , notably:

> So when you add a custom error handler, you must delegate to the default Express error handler, when the headers have already been sent to the client:

**Comment by scirelli-c1** [comment]
The key in that quote is "when headers have already been sent". How would I know this when it's express-session calling `next`? This is forcing anyone using express-session to add this to their code
```
if (res.headersSent) {
    return next(err)
}
```

You can see out of all the examples they give, only one has that check.

**Comment by dougwilson** [comment]
So what do you expect this module to do with the error? It is passing it to the Express error handling system for the user to perhaps do something with. If you remove your customer error handler, there is no issue, as the issue is just that the custom error handler is not checking if the error occurred after the header were sent before sending a response. Errors can happen after headers have already been sent, as operations are still occurring.

**Comment by scirelli-c1** [comment]
Yeah you are right. Rushed to an issue without thinking it through.
