### ISSUE TITLE
Notifications and video

### ISSUE THREAD

**Issue by EricBZH22** [expressjs/session#759]
Hello, it's the first time I post something in Github. I didn't received some notifications for new messenger on android 9. Version 1.2.3 of Session.

I can send videos, but I can't read videos

**Comment by jonchurch** [comment]
Hey there, I think youre looking for https://github.com/loki-project/session-android

**Comment by EricBZH22** [comment]
Exact ;-)

Thanks

**Comment by ghinks** [comment]
closing this question as I believe it has been answered.
