### ISSUE TITLE
Can the cookie signing be set "off"?

### ISSUE THREAD

**Issue by pulli23** [expressjs/session#761]
Well I am currently sharing a "session" database between several servers, where a singular (python/flask) database acts as login server which should provide a session with the correct key (randomly generated using nanoid) inside it.

The problem is, express-session tries to "decrypt" this session given a certain key and apparently *some* hidden scheme. I obviously cannot encrypt it the same way, the server generating the session isn't even using javascript so it cannot (unbearably difficult) use the code in express-session.

So can I tell express-session to not use encryption? And just tell it to use "cookie xyz"?

**Comment by ghinks** [comment]
Yes, the cookie is signed. For server side cookies the server needs to verify that the cookie originated upon that server.

The underlying algorithm for signing and unsigning is located in [cookie-signature](https://www.npmjs.com/package/cookie-signature). This uses the node crypto library to sign with hmac sha256. It is possible to use this in other languages on other servers as long as you share the secret key between the servers. 

The simple answer is no and currently the secret must be set.

**Comment by pulli23** [comment]
But it is silly to sign the cookie - it's not more secure as the *signed* cookie now acts as token. And you sent the signed cookie anyways.

This means that the underlying database token has no relevance and only the signed cookie is relevant. It's actually less secure because now not a standard hash -which can be made secure by the API programmer-. is determining that it is secure but rather a third party library, there is a bug in the security of cookie.signature it will mean this is also insecure.

If one could provide their own signature/hashing/id-generation the security is based on what the user wants and hence it is more secure?

it's explained in depth here: https://security.stackexchange.com/questions/92122/why-is-it-insecure-to-store-the-session-id-in-a-cookie-directly/93448

I notice that this is due to allowing us to enable a session-id-generator. But this is even less valuable than allowing us to provide a custom signing library. And if you allow such a thing, why do we care about security in the first place? Or rather, why not allow removing the signing but do allow not using secure or html-only cookies.

**Comment by dougwilson** [comment]
> It's actually less secure because now not a standard hash

Public github is not the place to be reporting security issues. Please put together your report on the specific insecurity here and how to reproduce it so we can take a look. Instructions for security reports are at https://github.com/expressjs/express/blob/master/Security.md

Please note I'm going to edit out the security issues you noted here so we can first have it brought up in the appropriate forum in order to evaluate the impact, device a security fix, and address the issue. I hope you understand.
