### ISSUE TITLE
Session data not saving

### ISSUE THREAD

**Issue by adammo94** [expressjs/session#763]
In my main node.js file I have:
```app.use(session({
  key: 'sess_key',
  secret: 'secret',
  saveUninitialized: true,
  resave: true,
  rolling: true,
  store: new MemoryStore(),
  cookie: {
      expires: 3600000,
      secure: false
  }
}));
```
then in login part I have this and req.session.Osoba is being displayed correctly in console.log:

```users.post('/login', (req, res) => {
  User.findOne({
    where: {
      email: req.body.email
    }
  })
    .then(user => {
      if (user) {
        if (bcrypt.compareSync(req.body.password, user.password)) {
          let token = jwt.sign(user.dataValues, process.env.SECRET_KEY, {
            expiresIn: 1440
          })
          req.session.Osoba=user.Osoba
          console.log(req.session.Osoba)
          res.send(token)
        }
      } else {
        res.status(400).json({ error: 'Taki użytkownik nie istnieje' })
      }
    })
    .catch(err => {
      res.status(400).json({ error: err })
    })
})
```

then I have just a simple:

```  app.get('/wypozyczanie', async (req, res) => {
    console.log(req.session.Osoba)
})
```

value of console.log(req.session.Osoba)? Undefined. Could someone tell me why? I'm clueless at this point

**Comment by ghinks** [comment]
Hello @adammo94, I see you have a question. I will do my best to help you answer your question. Your question is **why is the session data not saving** yes?

You have provided a little bit of context but not much.

I believe you are using mongoDB or something similar for data?

For the session store you are using the **MemoryStore** which is not mongoDB or similar.


So we will do what is appropriate.

Did you **use the session middleware correctly**

Is the req.session.Osoba **actually set anywhere?**

Please try to create a **minimal but complete working example that demonstrates your applications issue**. We need something that runs and we can see all the code context that demonstrates the issue.  **Context** is very helpful :)

Often we find this exercise of reducing to a minimal program with just session setup and one route demonstrates the issue.

Without the context of you program we are equally at a loss to what your application issue could be.

(In general this repo should be used for things that you think are an issue with the **express-session** module. However it looks like you are new to express, so please be patient )

**Comment by adammo94** [comment]
> Hello @adammo94, I see you have a question. I will do my best to help you answer your question. Your question is **why is the session data not saving** yes?
> 
> You have provided a little bit of context but not much.
> 
> I believe you are using mongoDB or something similar for data?
> 
> For the session store you are using the **MemoryStore** which is not mongoDB or similar.
> 
> So we will do what is appropriate.
> 
> Did you **use the session middleware correctly**
> 
> Is the req.session.Osoba **actually set anywhere?**
> 
> Please try to create a **minimal but complete working example that demonstrates your application's issue**. We need something that runs and we can see all the code context that demonstrates the issue. **Context** is very helpful :)
> 
> Often we find this exercise of reducing to a minimal program with just session setup and one route demonstrates the issue.
> 
> Without the context of you program we are equally at a loss to what your application issue could be.
> 
> We want you to have the best possible experience with the Express eco-system, so lets work together on this.
> 
> (In general this repo should be used for things that you think are an issue with the **express-session** module. However it looks like you are new to express, so please be patient )

That's my session middleware, I assumed memorystore is a way to store session data so I used it:
```
app.use(session({
  key: 'sess_key',
  secret: 'secret',
  saveUninitialized: true,
  resave: false,
  rolling: true,
  store: new MemoryStore(),
  cookie: {
      expires: 3600000,
      secure: false
  }
}));
```
req.session.Osoba is being set when user is logging in and I can correctly `console.log(req.session)` just before sending token. I'm using fetch requests in my components if it does matter, but they `all contain credentials: 'include'`

**Comment by ghinks** [comment]
Thank you @adammo94 this is still a bit **light** for the team to be able to offer any advice to you. This is the advice I can give.

- Is the cookie header being set-cookie header being sent back in the response?
- if the cookie is being sent back does it get set on the client browser?
- is the cookie being sent in following responses back to the server

If you do not provide a minimal working example of your issue I am essentially guessing.

Please provide a minimal working example showing the issue. Our intent is to help you, but you have to meet me half way by doing as I have requested.

Start a small repo, with just express and session something very simple to prove that session in stored and then start adding your code back in.

**Comment by ghinks** [comment]
I will offer further advice here, but I believe closing this issue is the best course of action as I see no real evidence there is an issue with the session module.

**Comment by ghinks** [comment]
I have not seen any response and will close this issue, I can however re-open it with a click of a button. The express team wish you every success with your application.
