### ISSUE TITLE
SameSite none and secure flag true

### ISSUE THREAD

**Issue by saijayaprakash** [expressjs/session#774]
Hai, I used the below config for express session
```
app.use(session({ 
    secret: '****',
    store: new MongoStore(***)
    resave : false,
    saveUninitialized : false,
    cookie : { sameSite: 'none' , secure: true }
}));
```
And it is sent over a secured [https]. But still, the cookie is not getting set.

**Comment by akroushan** [comment]
+1

**Comment by DotOp3rator011** [comment]
+1

**Comment by saijayaprakash** [comment]
In my case i have deployed my app in heroku and when i used 
`app.set('trust proxy', 1)` along with above config it worked like a charm..!

**Comment by DotOp3rator011** [comment]
This worked for me too. Thank you!

**Comment by dougwilson** [comment]
Thanks for the update. I'm going to close this, as it sounds like the solution is covered in the docs already at https://github.com/expressjs/session#cookiesecure
