### ISSUE TITLE
Cookie not setting on .onion site

### ISSUE THREAD

**Issue by testaccount00000** [expressjs/session#776]
"Note be careful when setting this to true, as compliant clients will not send the cookie back to the server in the future if the browser does not have an HTTPS connection."

I believe this may be my problem, as I had set secure to true and accessed the .onion site before, but as I understand it, Tor should not remember that upon creating a new identity, no?  If that's not how that works, is there some way to reset this?

I've tried all different combinations of setting resave and saveUninitialized to true/false, app.set(trust proxy 1/true);, proxy: true, rolling: true, setting the cookie's domain to the .onion site, using two separate stores for the normal website and the .onion site, not using an external store, renaming the cookie, using a different genid, secure: true/false/'auto', and using default settings, and I can't get the cookie to show up on the .onion site, but it works fine on the normal web.

I am not sure why it doesn't work on the .onion site with secure set to false, as it works on the normal web with HTTPS with secure set to true.  The app is on Heroku and the .onion site is non-SSL.  I can actually apply secure cookies to the .onion site and Tor will just ignore the secure: true value and keep the cookie, but this session cookie just will not appear regardless.  Any help would be appreciated.

Edit: it seems most likely that this is just how .onion sites work and it is not due to express-session in particular.  I cannot get any req.session object to persist across multiple requests and I believe that is due to the 3 relays per .onion request.  Any info set onto req.session seems to get left behind on relay 1.

**Comment by ghinks** [comment]
I think you may have answered your own question @testaccount00000 .

You have provided a great deal of information but I think we will have trouble addressing this issue when it is so specific. 

Going forwards you would best be served giving context around the issue starting with what you are doing and maybe some code examples.
