### ISSUE TITLE
Question: Is there any way to set secure cookie when x-forward-proto header is http

### ISSUE THREAD

**Issue by Yamini07** [expressjs/session#786]
I see expressjs checking https to set secure cookie but is there any way where we can explicitly set secure cookie when x-forward-proto return `http` instead of`https`. 
What exactly is the reason behind checking x-forward-proto before setting this attribute. Please provide more insights on this?

**Comment by dougwilson** [comment]
The cookie RFC says servers should not set a secure cookie on an insecure channel, so we implement that.

If you want to indicate that you express app is always over a secure channel (assuming you acknowledge any security implications this has), you can redefine req.protocol to always return https.
