### ISSUE TITLE
Hiding  req: {"headers": {"set-cookie": [xxx]  }}} and req: {"cookie": "connect.sid="xxx"} from express logs generated

### ISSUE THREAD

**Issue by PankajRoy1983** [expressjs/session#787]
Is there a way to hide the cookie information for the header.
const app = express()
    .use(pinoLogger)
    .use(session({
        secret: xxx
        resave: false,
        saveUninitialized: true})
    .use('/*', cookieParser())
    .use('/', express.static())
app.get('/', (req: any, res: any, next: any) => {}

**Comment by dougwilson** [comment]
From your code above, it looks like you are using the Pino logger. You will want to use the `redact` option (https://github.com/pinojs/pino/blob/master/docs/api.md#redact-array--object). If you need assistance for how to use that Pino feature, please file a help request in the Pino forum.
