### ISSUE TITLE
Is there a method to save just one session property as opposed to the entire session?  That would come in handy.

### ISSUE THREAD

**Issue by 333one** [expressjs/session#791]
Session.save(callback) is called at the end of every http response.

However it can also be called at any time like this.

`req.session.save();`

This saves the entire session.  95% of the time that's fine however in some cases it would be nice to save just 1 property on the session.  Is that possible?

`req.session.justOneProperty.save();`

**Comment by dougwilson** [comment]
Unfortunately this is not possible currently. The interface to the store modules doesn't allow for such granularity, either. So to add this feature, it would require some kind of change/new API in this module, then between this module and the store modules, and then the store modules would need to implement that API.

**Comment by 333one** [comment]
Thanks dougwilson!  At least I know to start looking for another way to solve my challenge.
