### ISSUE TITLE
Existing sessions not updating after middleware config change

### ISSUE THREAD

**Issue by uiii** [expressjs/session#793]
Hi, I've updated the express session config (e.g. httpOnly from true to false) and after server restart, the existing session keep the old values and are not udpated. For new session it is fine. How to update the existing sessions, is there some option or I have to do it manually, if yes, tell me please how.

**Comment by uiii** [comment]
I'm storing the session in postgres using connect-pg-simple.

**Comment by dougwilson** [comment]
Yes, this is intentional as many browsers will reject updating the cookie value if the options do not match what they were originally, so the store saves the original attributes that the cookie was set with so it can keep setting the value without the web browser discarding it.

**Comment by uiii** [comment]
So it is not possible to update cookies attributes, because of browsers. So I have to destroy the sessions and recreate them?

**Comment by dougwilson** [comment]
That's correct.

**Comment by uiii** [comment]
But with `rolling` the expiration of cookie is updated, so only expiration is allowed to change? If so, it still not work for the change from the maxAge default value to some specific.

**Comment by dougwilson** [comment]
Right, only the maxage and expires attributes can be changed, as well as the value of the cookie, as far as I am aware.

**Comment by uiii** [comment]
So it could be possible to update maxAge according the config for existing sessions. However I understand that it is not so important functionality, because the server config shouldn't change often. Thanks for help.
