### ISSUE TITLE
A better error message for an undefined secret

### ISSUE THREAD

**Issue by CalebDelbridge** [expressjs/session#796]
It's been almost 5 years, and we still have the same error message suggesting that the method we are using is deprecated but, in actuality, is just undefined.

_Originally posted by @CalebDelbridge in https://github.com/expressjs/session/issues/116#issuecomment-731382639_

**Comment by dougwilson** [comment]
Hi @CalebDelbridge thank you for your issue! We can always improve things, and different messages are better for some people and worse for others. I can tell you feel like some message from this module needs to be better, but you do not provide any sessions of a better message or criteria for what would make a better message for us to act on.

As this is an open source project, anyone can actually directly propose changes through a pull request. I would encourage you to help push forward what you think it an issue by opening a pull request with the changes you would propose so we can better understand and even land it quicker!

**Comment by CalebDelbridge** [comment]
Okay, this will be my first time actually contributing to open source, so here goes nothing 😄
