### ISSUE TITLE
Extend Express Session with own property in TypeScript

### ISSUE THREAD

**Issue by mpgr04** [expressjs/session#797]
I would like to give the Express Session an own property. But I encounter problems.
I have defined my own folder @types and added it to the TypeRoots in the .tsconfig file, the @types folder contains an index.d.ts file.
I saw that it should be possible to extend the Session object like this

```typescript
declare module 'express-session' {
    interface SessionData {
        counter: number;

    }
}
```

This works fine, but in my code the type Session changes to any because of this: Module '"express-session"' has no exported member 'Session'.

Now I found out that in newer versions you can probably extend the object as follows:

```typescript
declare module 'express-session' {
    interface Session {
        counter: number;

    }
}
```

This also works, the session type does not change to any and the property is present, but this triggers this error:
Property 'counter' is missing in type 'Session & Partial<SessionData>' but required in type 'Session'

Therefore it is now unclear to me how exactly I can extend the Session object

**Comment by dougwilson** [comment]
Hi @mpgr04  thank you for the report! We do not actually maintain the TypeScript definitions directly, like many npm modules. The definitions are part of the following project, which you can file an issue or open a PR: https://github.com/DefinitelyTyped/DefinitelyTyped
