### ISSUE TITLE
Session Cookie not set

### ISSUE THREAD

**Issue by TroyDota** [expressjs/session#801]
Hi, I dont know what I am doing wrong.
On my frontend I am redirecting to the backend page to set a cookie (csfr-token) and then the backend is redirecting to another site (oauth-provider) which is being sent back to a callback. On the initial request to lets say the `/login` endpoint the cookie is being set and then on the `/callback` its being fetched. If I access the backend page directly (no referrer) the cookie is set and the token validates on the callback. If I have a js redirect on the client side the cookie is not set and the token fails to validate. 
Frontend to redirect:
`window.location = "newlocation";`
and i also tried
`window.location.replace("newlocation");`
both have the same effect
backend, the cookie is being set on the domain `localhost` which happens to be the dev env host where the frontend runs on port `4000` and the backend port `4001`. 
```
app.use(
  session({
    store: new RedisStore({ client: redisClient }),
    secret: config.session_key,
    resave: false,
    saveUninitialized: false,
    cookie: {
      path: '/',
      domain: "localhost",
      httpOnly: false,
      sameSite: "lax",
    }
  })
);
```
is the express middleware.
```
req.session.csrf_token = state;
req.session.save(() => {
  res.redirect(`oauthprovider`);
})
```
is the code used to set the cookie.
Am I missing something?

edit i also tried to set a normal cookie
```
res.cookie("xd", '123');
```
which is also not set when navigating from a referrer, although the `Set-Cookie` response header exists on this cookie it does not set the cookie in storage but that might be cause I am returning an non `2xx` response I am not sure. Also the referrer header has no influence afaik as I disabled it it Firefox to see if that was the issue and it yielded the same result.

**Comment by rattkin** [comment]
I don't know if this is your case, but Chrome will not accept cookies coming from localhost, if it is running on localhost or using non-standard ports.
we had to roll self-signed fake domains for our app as well as as the api.

**Comment by rattkin** [comment]
> Chrome will not accept cookies coming from localhost, if it is running on localhost or using non-standard ports.
I mean it will silently drop the cookie like it did not exist

**Comment by TroyDota** [comment]
Ic thanks <3
