### ISSUE TITLE
Informix data store

### ISSUE THREAD

**Issue by lyonmerc** [expressjs/session#803]
Please add Informix data store based on node-informixdb, thank you.

**Comment by dougwilson** [comment]
Hi @lyonmerc just send us a PR with a module that implements this and we can add to the readme :)

**Comment by lyonmerc** [comment]
Hi Douglas, I do not have a module, sorry I’m new to nodejs. There is  an informixdb package for accessing Informix database, not for Informix datastore on express-session.
