### ISSUE TITLE
Export sign function

### ISSUE THREAD

**Issue by daveisfera** [expressjs/session#805]
This is a request that the sign function be exported so it can be used by services that want to generate a cookie (like creating and driving a headless browser session for screenshot/PDF generation). Currently, we're doing this by having our own function that matches the behavior, but this is fragile and it would be nice to be able to use the actual function.

**Comment by dougwilson** [comment]
Hello! This module uses the https://www.npmjs.com/package/cookie-signature module for the cookie signing. The function exported from that module would be the signing you want to use 👍
