### ISSUE TITLE
Why session not persisted anymore after expire time?

### ISSUE THREAD

**Issue by bettafish15** [expressjs/session#806]
Hi, i I apologize in advance if this is a not good place to ask questions but i am cant wrap my mind around this one. I am trying to use express-session with expires time and store session with mongo, like this.

```js

const config = require('./config/config')();
const session = require('express-session');
const MongoStore = require('connect-mongo')(session);
const express = require('express');
const app = express();



var expiryDate = new Date(Date.now() + 5 * 1000) // 10 second
app.use(session({
    secret: config.secret,
    store: new MongoStore({ url: config.mongo_url }),
    resave: false,
    saveUninitialized: false,
    cookie: {
        secure: process.env.NODE_ENV == 'production' ? true : false,
        expires: expiryDate,
    }
}));


app.use('/', function(req, res){
    req.session.views = req.session.views ? req.session.views + 1 : 1;
    console.log(req.session.views);
    res.sendStatus(200);
});

app.listen('8080');
```

This code works perfectly first time. But the problem came in when the session expired. next session would not persists at all. It would be new session every time i make request. Like this:
```
1
2
3
4
5
6
1
1
1
```
Can you guys help me out?

**Comment by gabeio** [comment]
I believe expireDate is an absolute, try maxAge instead. What I mean by absolute is that after your 10 second window is up as you see there it will always expired because it is passed the absolute time. Where maxAge of 10s creates a cookie that will last for 10s.

**Comment by bettafish15** [comment]
> I believe expireDate is an absolute, try maxAge instead. What I mean by absolute is that after your 10 second window is up as you see there it will always expired because it is passed the absolute time. Where maxAge of 10s creates a cookie that will last for 10s.

I dont believe that is the case because i am using Date.now() . When i tested in postman, if i make the request first time, set-cookie was sent and postman got it fine. But after the cookie expired and postman requested it again, set-cookie was sent but postman ignored it, same with chrome. Cookie no longer worked and every request the server return 1. It is very confusing

**Comment by gabeio** [comment]
On boot the `var expiryDate = new Date(Date.now() + 5 * 1000) // 10 second` is evaluated to 10s in the future. After which it is never updated, so when 10s passes all cookies _should_ expire immediately, since the global expiryDate is in the past it will expire every time, if you'd like to test my theory you can try:

```
const config = require('./config/config')();
const session = require('express-session');
const MongoStore = require('connect-mongo')(session);
const express = require('express');
const app = express();



var expiryDate = new Date(Date.now() + 5 * 1000) // 10 second
app.use(session({
    secret: config.secret,
    store: new MongoStore({ url: config.mongo_url }),
    resave: false,
    saveUninitialized: false,
    cookie: {
        secure: process.env.NODE_ENV == 'production' ? true : false,
        expires: expiryDate,
    }
}));


app.use('/', function(req, res){
    req.session.views = req.session.views ? req.session.views + 1 : 1;
    console.log(req.session.views);
    console.log(expiryDate); // <- printing the date
    console.log(req.cookie.expires); // <- print the cookie expires (this might not worry, I'm not in-front of my computer to test this)
    res.sendStatus(200);
});

app.listen('8080');
```

**Comment by dougwilson** [comment]
Hi @bettafish15 what @gabeio is saying is correct; the behavior you want is accomplished by using `maxAge` and not `expires`. Since `expires` sets an absolute expiration date on the boot of your app. This is why you are seeing the postman/chrome ignore the cookie later, as they will ignore cookies that expire in the past.

**Comment by bettafish15** [comment]
> Hi @bettafish15 what @gabeio is saying is correct; the behavior you want is accomplished by using `maxAge` and not `expires`. Since `expires` sets an absolute expiration date on the boot of your app. This is why you are seeing the postman/chrome ignore the cookie later, as they will ignore cookies that expire in the past.

Oh yes omg i am such an idiot. The cookie set is global and is not a middleware. How can i missed it? Thanks u guys so much for helping me and sorry for wasting your times haha
