### ISSUE TITLE
Extending session object

### ISSUE THREAD

**Issue by Avcajaraville** [expressjs/session#807]
Hi there, I know this is not an actual issue, but a help wanted.

I'm struggling with typescript and express session and I have been playing around and trying to fiugure out this one for quite a bit.

I'm trying to extend my session object, for that, I'm trying to do a merge of typings as per in the documentation:

I have a `types/session.d.ts` with the following interface to be merged:
```
declare module 'express-session' {
  interface SessionData {
    userId: string;
  }
}
```

But this is not working, as an example, in `other-folder/some.ts`
```
req.session.userId = user.id;
// Property 'userId' does not exist on type 'Session & Partial<SessionData>'.
```

However, if I import `Session` from `express-session`, it does work:
```
import { Session } from 'express-session'

declare module 'express-session' {
  interface SessionData {
    userId: string;
  }
}
```

I'm not very proficient with TypeScript and I'm unsure about importing a module in a type defintion, event TypeScript complains about this (warning):

'Session' is declared but its value is never read.

I'm wondering, is this the right way of tackling the problem?

What can I do different?

Kind regards!

PS: my tsconfig should be fine as I have available through my code other type definitions and they are working with no issues at all.

**Comment by dougwilson** [comment]
I think this is a duplicate of #799 . If not, let me know and I can re-open this one.

**Comment by Avcajaraville** [comment]
Seems quite similar, but even on the linked issue, the last comment author is afraid of regression on this.

Seems that the import/export pattern on a d.ts file is like a hack?

I'm not super sure about this and that is kind of the point of this issue.

I have never encountered a pattern like the one on that issue, where we either do an import or export to make this work.

As far as I know, merging should be working out of the box.

What do you think or what's your take on this?

The main goal would be to extend SessionData interface from an external d.ts file.

Thanks a lot for your quick and kind response!

**Comment by dougwilson** [comment]
I can certainly reopen the issue, but I have no idea about anything Typescript related so cannot provide any answers myself on the topic. The typescript stuff is not even managed in this repository so there is nothing to merge into here to affect change around it, if that is needed.

**Comment by Avcajaraville** [comment]
I understand, I will oversee this issue and if in a week or so nothing pops, I will close it my self.

Thanks a lot for being kind and compressive 👍

**Comment by Avcajaraville** [comment]
Closing because of lack of input. Thanks @dougwilson  :)
