### ISSUE TITLE
Unable to access document.cookie

### ISSUE THREAD

**Issue by krislee** [expressjs/session#810]
I have in the server side the following code:

```
app.use(session({

    secret: process.env.SESSION_SECRET,
    resave: false,
    saveUninitialized: false,
    store: sessionStore,
    cookie: {
      maxAge: 1000*60*60*24*30, 
      secure: true, 
      httpOnly:false,
      sameSite: 'none'
    }
  }))
```
  
```
  app.use(function(req, res, next) {
    res.setHeader('Access-Control-Allow-Credentials', true);
    res.setHeader('Access-Control-Allow-Methods', 'GET, PUT, POST, DELETE');
    res.setHeader("Access-Control-Allow-Origin", "https://some-app-name.netlify.app");
    // res.setHeader("Access-Control-Allow-Origin", "http://localhost:3000");
    res.setHeader("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept, Authorization, Set-Cookie, Cookie, X-Forwarded-Proto");
    next();
  });
```

The server code is deployed to heroku, so the front-end `fetch` to https://some-app-name.herokuapp.com

When I run the front-end locally and `console.log(document.cookie)` and on netlify (https://some-app-name.netlify.app) and `console.log(document.cookie)`, it is an empty string. Please advise.

**Comment by Zikoel** [comment]
You use the option `saveUninitialized: false` so, if you don't touch the session processing the request on your server no session will be created and no cookie will be set. Try to check this.

**Comment by krislee** [comment]
> You use the option `saveUninitialized: false` so, if you don't touch the session processing the request on your server no session will be created and no cookie will be set. Try to check this.

I tried setting `saveUnitialized: true` and `document.cookie` on the client side is still empty.

**Comment by Zikoel** [comment]
There is nothing wrong in my opinion in the the code you have posted! Another problematic thing under developing is `secure: true` that require for the cookie a correct and valid `https` connection! Check this last things or try to provide a minimal not working example project on gitub!

**Comment by joewagner** [comment]
@krislee Can you confirm that the cookie is being sent to the client in the response headers?  Also, double check that the client is sending the cookie back to the server?  Also the Chrome debugger will show you the page's cookies and if they are `httpOnly`.  Can you check to see what that shows?
Lastly, before you do any of the above, make sure you clear all cookies for the domain in question

**Comment by ttcy** [comment]
Had a similar scenario as what you have mentioned, no warning/error message was shown in Chrome DevTools. 
I solved it by adding withCredentials in my Axios's header options and Chrome DevTools start to print out related errors.

You can intercept the request from your expressJS before it is sent back to the client and ensure Set-Cookie header is included before sending it back to the client.

For the client-side, do check the request which is supposed to receive the Set-Cookie header. It should show the exact error message once you include the credentials header.

Check the link for sending a request with credentials included:
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#sending_a_request_with_credentials_included

**Comment by dougwilson** [comment]
I'm going to close this, as the conversation seems to have ended, with some good questions, but no further response from the OP.
