### ISSUE TITLE
Manage login activity

### ISSUE THREAD

**Issue by TheKnown44** [expressjs/session#811]
Hi, 

I'm developing a website with node.js, passport.js, express and express-sessions. 

I want to make a feature that allows signed-in users to remove previous sessions from e.g. other devices they signed into before and forgot to logout from, basically so they could choose to logout from all devices or specific devices. I also want to store user-agent and IP address in the database along with the user sessions.

Express-sessions are stored in a database table using the [connect-pg-simple][2] store.

The session table has 3 columns and looks like this:

|  sid | sess | expire |
|:---- |:------:| -----:|
| AH_oe3YCEahqcKA2VxxHp_Xf  | {"cookie":{"originalMaxAge":7200000,"expires":"2021-01-15T11:11:02.164Z","secure":false,"httpOnly":true,"path":"/"},"flash":{},"passport":{"user":"106"}}| 2021-01-15 12:11:03 |
     

Currently the userid is stored inside a JSON string `{"user":"106"}` on the session, so I don't know how to query all sessions that belong to a specific user. I would make a new column `userId` along with the 3 existing columns and store userId, but I don't know if that's possible at all and I don't know how I would be able to save user-agent and IP address at the same time.

I will gladly provide more code that I have or information about the packages that I have used. I have searched everywhere, but I couldn't find any helpful information.

Any help would be appreciated. Thanks.

  [2]: https://www.npmjs.com/package/connect-pg-simple

**Comment by dougwilson** [comment]
Hi! This would be a question for your store module; this module provides all the data to your store as a plain, non serialized object and the store module you are using is what serializes the data and places it into the database.
