### ISSUE TITLE
secure cookies doesn't work

### ISSUE THREAD

**Issue by flyhigh-hifi** [expressjs/session#812]
Due to browsers restrictions – it is now required to set Secure in pair with SameSite: None
But here is the thing: https://github.com/expressjs/session/blob/a8641429502fcc076c4b2dcbd6b2320891c1650c/index.js#L635
This condition doesn't work in conjunction with the above one https://github.com/expressjs/session/blob/a8641429502fcc076c4b2dcbd6b2320891c1650c/index.js#L630

I guess author meant that trustProxy can be either of undefined or of Boolean type, however instead of type-checking, strict comparison was used which led to bug.

**Comment by dougwilson** [comment]
It works just fine. We can reopen if you can provide a reproduction of said bug so we can see. We have a few tests in our test suite that demo the functionality which are passing.
