### ISSUE TITLE
Session does not survive refresh

### ISSUE THREAD

**Issue by Bexy-Lyn** [expressjs/session#815]
Hi everyone.
I am new to cookies... I hope that anyone here might help me.

I want to use a session to keep my users logged in on refresh. But unfortunately req.session seems to be undefined if I call it after refreshing the site. 

This is my "app.js":
```
//...
const express = require('express');
const session = require('express-session');
const app = express();
const login = require('./routes/user');
require('dotenv').config();

app.use(session({
  secret: process.env.SECRET,
  resave: false,
  saveUninitialized: true,
  cookie: { secure: 'auto', maxAge: 60*60, sameSite: 'strict', path: '/user' }
}))
app.use('/login', login);
//...
```

This is my route "user.js", which handles the login and the update on page refresh:
```
const express = require('express');
const router = express.Router();
const Sequelize = require('sequelize');
//...

router.post('/login', (req, res) => {
   //check login data, if correct
    req.session.key=key;
    console.log("session-key: "+req.session.key) //logges the key correctly
   //else return mistakes
)}

router.post('/update', (req,res) => {
    console.log("session-key2: "+req.session.key) //session-key2: undefined
    if(req.session.key !== "" && req.session.key !== undefined){
        //code does not enter condition
    } else res.json({error: "missing", loggedIn: false});
})
```

Has anyone an idea where I went wrong? 
Thanks in advance!

**Comment by jipd** [comment]
Check you are passing credentials with the request from the client, otherwise you will never receive the cookie resulting in a new session on every request. This could be a different setting depending on the library, e.g. with Axios the option is withCredentials: true

**Comment by dougwilson** [comment]
Closing due to no further response from the OP.
