### ISSUE TITLE
Set two cookies

### ISSUE THREAD

**Issue by MrYbo** [expressjs/session#816]
Due to business requirements, I need to set two cookies. What I do now is as follows: add a new parameter `samesiteWithoutSecure`  to the parameter set by cookie. When it is true, I will add the following code to the `onHeaders()` function when setting cookie
```javascript
var setCookieData = req.session.cookie.data;
setcookie(res, name, req.sessionID, secrets[0], setCookieData);
if (samesiteWithoutSecure) {
  setCookieData.sameSite = 'None';
  setCookieData.secure = 'Secure';
  setcookie(res, _name, req.sessionID, secrets[0], setCookieData);
}
```

The problem I encountered is that when I first use HTTPS request, the browser sets two cookies, and then use HTTP request, there is only one cookie, and then I clear the cookie, restart the service, and then use HTTP request, and then use HTTPS request, but I find that the two cookies have different values. How can I keep these two values always the same？

 I am a little rookie, can not find a solution, please help me。thanks

**Comment by dougwilson** [comment]
Unfortunately this is an issue with the web browser: you cannot control cookies with the Secure flag over a HTTP connection, you need to use HTTPS connect to update the HTTPS cookie.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie

> Note: Insecure sites (http:) can't set cookies with the Secure attribute (since Chrome 52 and Firefox 52). For Firefox, the https: requirements are ignored when the Secure attribute is set by localhost (since Firefox 75).

**Comment by MrYbo** [comment]
@dougwilson Thank you very much for your answer. It means a lot to me
