### ISSUE TITLE
excessive MySQL SELECT/UPDATE session calls

### ISSUE THREAD

**Issue by redbotHQ** [expressjs/session#818]
I'm using express-session with sequelize and connect-session-sequelize. Express-session is set to log all SQL calls, which highlights the issue I am encountering. A res.render('index') from the app to a pug template initiates both a SELECT and UPDATE call as expected. However, adding linked header elements (style/script tags) and body elements such as  img tags to the template results in an additional call to both the SELECT and UPDATE query for every linked element. Adding additional elements results in an exponential number of database calls.

DEBUG=express-session npm run dev, outputs the following in the console for the template and every linked element:
express-session fetching
express-session session found
express-session touching

How do you prevent style, script and img calls from initiating the session fetch/touch call?

app.js

```
const config    = require('./config');      
const http      = require('http');
const express   = require('express');
const session   = require('express-session');
const Sequelize = require('sequelize');

const sequelize = new Sequelize(
    config.dbDatabase,
    config.dbUser,
    config.dbPassword,
    {
        host    : config.dbHost,
        dialect : config.dbDialect,
        define  : {
            timestamps  : false,
            underscored : true
        }
    }
);

const app = express();

const sequelizeStore = require('connect-session-sequelize')(session.Store);
const sessionStore = new sequelizeStore({
    db: database.sequelize,
    modelKey: 'session'
});

app.set('view engine', 'pug');
app.set('views', './views');

app.use(express.static('./public'));

app.get('/', function(req, res){
    res.render('index'); // pug 
}

const server = http.createServer(app);

server.listen(config.port, () => {
    console.log(`App listening on port: ${config.port}`);
});
```

index.pug

```
doctype html
html
    head
        meta(charset='utf8')
        title example
        link(rel='stylesheet' href='/css/example.css')
        script(src='/js/lib/angular/angular.min.js')
        script(src='/js/lib/angular/angular-resource.min.js')
        script(src='/js/example.min.js')
    body
        H1 Example Template
        img(src= "/img/sample.jpg" alt="Sample image") 
```

**Comment by joewagner** [comment]
@redbotHQ I'm not familiar with `connect-session-sequelize`, but I don't see any call to `app.use(session({...))` in your example. Is there more to your example? The database calls will happen once for every request that makes it to the session middleware, which would normally be between `app.use(express.static('./public'));` and `app.get('/',...`

**Comment by redbotHQ** [comment]
@joewagner Thanks for the response, you are corect that the code example was cut down. While we had `app.use(session({...));`, it was used before `app.use(express.static('./public'));`. Relocating it, as per your suggestion, has removed the duplication issue. Really appreciate the heads up!
