### ISSUE TITLE
Clear unneeded sessions

### ISSUE THREAD

**Issue by mayeaux** [expressjs/session#821]
I have a database with 17,000,000 session documents in it now stored in MongoDB, however I really only want sessions that are for logged in users so they won't have to login again, is there a smart way to do this and is this a problem that many people face? Basically my database is getting clogged up with too many sessions and it's becoming more difficult to backup my data, so I would like to clear a lot of these out. Maybe a good design would be to conditionally set a maxAge depending on whether a user is logged in or not? Has anyone faced a similar problem and had a good solution? Sorry if I don't have a ton of work to show I am just trying to wrap my head around this at the moment, thanks!

**Comment by dougwilson** [comment]
Hi @mayeaux this module is a session module. A session can mean many things, and does not always correspond to a "logged in user", as that is an abstraction on top of a session. This module does provide your store with an expiration for every session, and you could always implement something in your store to be aware of logged in or not as well, that is certainly up to you :)

Ultimately the abstraction this module provides is that it provides a link between a cookie in a web browser and a session that comes from the store you provide to this module, exposing it as `req.session`. Pruning sessions is let up entirely to the store module you are using, as this module doesn't know if your store is distributed or not, if it is using a database with auto pruning, needs active pruning, or how your pruning schedule would work.

I would suggest posting this in the store module you are using, as that is there the pruning responsibility lives.

**Comment by mayeaux** [comment]
Okay sounds good, it sounds like pruning sessions is something that is done as part of regular work so I'll look into that, thank you!

**Comment by dougwilson** [comment]
No problem. If it helps, What I do is have a store module that stores into MySQL. Since MySQL does not really provide any type of pruning, I have a separate process outside of the Node.js site that deletes all the records that are over n age and have the user not logged in. There is second logic to also prune when just over z age even if the user is logged in as well.
