### ISSUE TITLE
Type definition error when setting cookie sameSite to none

### ISSUE THREAD

**Issue by Diego-Romero** [expressjs/session#825]
I'm currently getting a typescript error when trying to define my express session config to sameSite: 'none'. I'm currently using @types/express-session: 1.17.3 and have tried unsuccessfully with an older version too.

The documentation indicates that what I'm doing is right, but the Type definitions are somewhat wrong. https://expressjs.com/en/resources/middleware/session.html

In the index.d.ts of express-sessions it indicates that I can use it that way, but I'm getting a  compiler error.

index.d.ts for express-session
```
 class Cookie implements CookieOptions {
        originalMaxAge: number;
        maxAge?: number;
        signed?: boolean;
        expires?: Date;
        httpOnly?: boolean;
        path?: string;
        domain?: string;
        secure?: boolean | 'auto';
        sameSite?: boolean | 'lax' | 'strict' | 'none';
    }
```

My session config:
```

  const sessionConfig = {
    secret: config.sessionSecret || '',
    resave: false,
    saveUninitialized: true,
    cookie: {
      secure: false, // if set to true tests won't work
      maxAge: 10 * 60 * 1000 * 100000,
      sameSite: 'none',
    },
  };

  if (app.get('env') === 'production') {
    app.set('trust proxy', 1); // trust first proxy
    sessionConfig.cookie.secure = true; // serve secure cookies
  }

  app.use(cookieParser());
  app.use(
    cors({
      origin: config.clientUrl,
      methods: ['POST', 'PUT', 'GET', 'OPTIONS', 'HEAD'],
      credentials: true,
    }),
  );
  app.use(session(sessionConfig));
```

The Typescript error:
```
src/loaders/middleware.ts:35:19 - error TS2345: Argument of type '{ secret: string; resave: boolean; saveUninitialized: boolean; cookie: { secure: boolean; maxAge: number; sameSite: string; }; }' is not assignable to parameter of type 'SessionOptions'.
  The types of 'cookie.sameSite' are incompatible between these types.
    Type 'string' is not assignable to type 'boolean | "none" | "lax" | "strict" | undefined'.
```

**Comment by dougwilson** [comment]
Unfortunately I am not familiar with using typescript and the definitions are not maintained in this repo. I can confirm that you are using it correctly, so it would seem to me to be some issue with the definitions.

**Comment by Diego-Romero** [comment]
Could you please point to the repo that has the type definitions, I don't mind submitting the Typescript fix for this :)

**Comment by Diego-Romero** [comment]
I've fixed by prepending the line // @ts-ignore to the sessionConfig, which is certainly not ideal.

Like this:
// @ts-ignore
  app.use(session(sessionConfig)); // sessions has to go before passport sessions

**Comment by dougwilson** [comment]
The npm page for the type package should have the link to the right repo https://www.npmjs.com/package/@types/express-session

**Comment by raarts** [comment]
For whoever ends up here after experiencing the same problem. This is the solution:

    cookie: {
      sameSite: 'none' as const,  // <--------
    },
