### ISSUE TITLE
Is it possible to enforce single session per user?

### ISSUE THREAD

**Issue by tony-sunny** [expressjs/session#832]
Basically I want to remove the session  on previous device if user signs in from another device.
Is it possible to do this using express-session?

**Comment by dougwilson** [comment]
Probably not though this module directly, as there is no concept of a user here, as this is more low level. This just creates the session that is more of a "device session" and you would add on top of this the concept of a user session.

**Comment by tony-sunny** [comment]
@dougwilson  Ok, Thanks for the answer. Let me close the issue.
