### ISSUE TITLE
Session cookie not updating consistently

### ISSUE THREAD

**Issue by mklimkin0190** [expressjs/session#834]
I'm using express-session in nestjs with svg captcha: svg is generated in the server and sent to the client, while the captcha solution is saved on session, as recommended in https://github.com/produck/svg-captcha:

```Javascript
const { text, data } = generateCaptcha()
session.captcha = text // solution
session.save(() => {
  console.log(session.captcha) // always correct
})
return data // svg is returned to the client
```

The session store I'm using is `connect-pg-simple`. The session is created with a correct cookie object, but from time to time the `captcha` property of the cookie is not updated in the store, even though the correct captcha is printed out in the `session.save` callback.

I tried to make the captcha call async like this:

```Javascript
// inside the async call
const { text, data } = generateCaptcha()
session.captcha = text // solution
await new Promise((resolve) => {
  session.save(() => {
    console.log(session.captcha) // always correct
    resolve(null)
  })
})
return data // svg is returned to the client
```

This caused the cookie in the store to be updated consistently every second time (which is even worse than the original issue).

My setup:
```Javascript
app.use(
  session({
    store: new (pgStore(session))(),
    secret: process.env.SECRET_KEY_BASE,
    resave: true,
    saveUninitialized: false,
    cookie: {
      secure: process.env.NODE_ENV && process.env.NODE_ENV !== Environment.Local,
      maxAge: 24 * 60 * 60 * 1000, // 24 hours
    },
  })
)
```

Any idea on what am I doing wrong here? Thanks!

**Comment by dougwilson** [comment]
It sounds like you may be having parallel updates to your session conflicting. Are you sure you need `resave` to be `true`?

**Comment by mklimkin0190** [comment]
> It sounds like you may be having parallel updates to your session conflicting. Are you sure you need `resave` to be `true`?

You are right! Explicitly setting `resave: false` solved the problem.
Thank you, closing.
