### ISSUE TITLE
DIY store, MongoDB, and SQL schema

### ISSUE THREAD

**Issue by NamedArray** [expressjs/session#836]
1. If I wanted to write my own JS class/module (Data Model) for interacting with a database, how can I use _that_ as my session store?

2. Why is Mongo utilized so often for session storage?  (We already have MSSQL, and I may not be able to utilize Mongo).

3. Is there a common or unwritten rule about the Table schema and indexes for session storage?  Should any of the columns be clustered/non-clustered?

4. What **_shouldn't_** you record in the Sessions table?

**Comment by dougwilson** [comment]
Hi @NamedArray !

> If I wanted to write my own JS class/module (Data Model) for interacting with a database, how can I use that as my session store?

You just need to create a class that provides an instance of the https://github.com/expressjs/session#session-store-implementation and then you want to pass an instance of your store to https://github.com/expressjs/session#store

> Why is Mongo utilized so often for session storage? (We already have MSSQL, and I may not be able to utilize Mongo).

This module does not make you use any particular type of store. I have not personally used Mongo for my store ever, so really I have no idea why. You probably would have to poll those who use it to determine why the decided to use that particular store.

> Is there a common or unwritten rule about the Table schema and indexes for session storage? Should any of the columns be clustered/non-clustered?

This module has no rules for how the stores store the session data into their underlying storage system. It just provides an object of key-value pairs and a string identifier and then just wants that object back again later when given the same string identifier.

> What shouldn't you record in the Sessions table?

You can record anything you like. This module has no opinions for how you should store the data it provides.

I hope that helps!
