### ISSUE TITLE
Firefox ignores sameSite while Chrome does properly use it

### ISSUE THREAD

**Issue by 205g0** [expressjs/session#842]
My config:
```
session({
  resave: false,
  secret: 'xxx',
  saveUninitialized: false,
  rolling: true,
  cookie: {
    maxAge: 1000 * 60 * 60 * 24 * 7
    secure: process.env.NODE_ENV != "development",
    sameSite: "strict",
  },
  ...
});
```
**leads in Chrome to:**
![image](https://user-images.githubusercontent.com/74575852/130315090-8693b888-d8a2-4f59-b330-3491b598b2b7.png)

**and in Firefox to:**
![image](https://user-images.githubusercontent.com/74575852/130315118-d12bde2d-a469-4a95-a360-db8421fbe872.png)
and
![image](https://user-images.githubusercontent.com/74575852/130315182-0dc20d32-f212-498e-9baa-021bf3f9c68f.png)

**Comment by dougwilson** [comment]
As the message from Firefox states, it seems that Firefox requires you to set `secure: true` if you want to set `sameSite: 'strict'`. It would surmise that in your example `process.env.NODE_ENV` is set to `development`.
