### ISSUE TITLE
Sharing a session between Browsers for the same user

### ISSUE THREAD

**Issue by kaiyer-de** [expressjs/session#843]
Our backend uses nodejs with expressjs and express-session and redis as SessionStore. Imagine the following usecase:

You want to log into a webapplication from multiple devices and if you logout on one device or your session expires, every device should be notified about this event and be logged out. If i could share a session between multiple devices i wouldn't need to sync the TTL of all the sessions if a request gets send to the backend. Because redis only sends the expired key to a event listener, this key needs to be a channelname for a websocket to notify the frontend about the expiry / deletion of the session.

I already tried to change the sessionID before sending a response.
```
req.sessionID = user.uuid;
```
I also tried updating the set-cookie Header before sending a response. This results in a set-cookie Header with two cookies with the same id.
```
const session = await getSession(user);
if (session && session['set-cookie']) {
  res.setHeader('set-cookie', session['set-cookie']);
}
res.sendStatus(200);
```
Lastly i tried to regenerate the session if there is none or reload the session if there is already a session for this user.
```
req.body.identifier = identifier;
req.sessionID = identifier;
const otherSessions = await getSessions(user);
if (otherSessions.length > 0) {
  req.session.reload(respond);
} else {
  req.session.regenerate(respond);
}
```
But this also doesn't work, because express-session uses `req.session.id` instead of `req.sessionID` when reloading the session.

My `options` Object looks like this: 
```
const sessionOptions = {
  store,
  name: 'session-id',
  secret,
  saveUninitialized: false,
  resave: false,
  rolling: true,
  cookie: {
    maxAge: 3600,
    secure: true',
    sameSite: 'lax',
  },
  genid = req => req.body.identifier || uuid() || '-'
};
```

Does anyone know how to implement this usecase?

**Comment by dougwilson** [comment]
To achieve your goal, you would need to use a secondary session that is linked from your express-session sessions. The sessions from this module are for the web browser and a key part of them is the expiration value in the cookie set in a specific web browser. It would not work to share the same ID from this session with two different web browsers, as the stored cookie data in the session would be out of sync.

The solution is to leverage your store's API and then create sessions there directly and store an identifier in the session of this module and do the cross-reference that way.
