### ISSUE TITLE
Express-session with Passport-Oauth2 doesn't send the access token to frontend after setting the cookie settings.

### ISSUE THREAD

**Issue by josephyhu** [expressjs/session#853]
This is my cookie (and other session) settings:
```
app.use(
  session({
    secret: "secretcode",
    resave: true,
    saveUninitialized: true,
    // cookie: {
    //   sameSite: "none",
    //   secure: true,
    //   maxAge: 1000 * 60 * 60 * 24 * 7
    // }
  })
);
```

This is the route to send access token to frontend:
```
app.get('/gettoken', (req, res) => {
  res.send(req.user);
});
```

And this is the code to retrieve the token and log it to the console (for now):
```
  useEffect(() => {
    axios.get("http://localhost:4000/gettoken", {withCredentials: true}).then((res) => {
      if (res.data) {
        console.log(res.data)
    }
  }
})
```

I first thought somehow deploying to Heroku and changing server URLs was what was causing the problem, but after removing my app from Heroku and changing the URLs back to localhost:4000 the problem was still there. The problem gets fixed if I comment out (like I did in the above code snippet) or remove the cookie settings; however, I need those settings for my app to not get an error (like the error in this video: https://youtu.be/cD17CYA1dck?t=7512) when deploying to Heroku and trying to authenticate (i.e. click the log in button).

Although it doesn't send the token, if you go to the `/gettoken` route, you will see the token posted to the screen instead. Oh and since I haven't deployed the frontend yet, its link is localhost:3000.

**Comment by dougwilson** [comment]
Hi @josephyhu thank you for the detailed explanation. I have read through and it re-read through it, but I'm not exactly sure what is going on to really understand where you are encountering the issue and what the technical details of the issue are. Is it possible you can can provide full code that I can run locally which demonstrates the issue? The reason I ask is because I'm not really sure where to start with the debugging besides break out Wireshark and Node inspector and start poking around, but I'm not able to do that based on the information provided above. Another alternative is that we always accept pull requests for fixes that you diagnose as well.

**Comment by josephyhu** [comment]
Here's my repository: https://github.com/josephyhu/JYs-AniApp-v1, but you'd need an AniList account to test the bug. Let me post two videos demonstrating the problem instead:

Working (notice the login link changes to logout after logging in; also notice the commented out cookie settings):
https://youtu.be/Q34yZHGxu5s

Not working (notice the login link does **not** change to logout after logging in; also notice I've uncommented out the cookie settings):
https://youtu.be/wb0qNL522n0

**Comment by dougwilson** [comment]
Thank you for that. So you cannot have `secure: true` set when you are not using https otherwise the browser discards the cookie. Can you test it again without `secure: true` ?

**Comment by josephyhu** [comment]
I originally meant to deploy the app to Heroku though, and (according to video guide I've been watching) I need the URLs to use https.

Also, just tested it, and removing the secure: true didn't work. Only removing the entire cookie settings (or commenting them out) seems to work.

**Comment by dougwilson** [comment]
Very strange. Can you post a new video showing it not working on localhost with secure not there? Please also have the cookie console open as well so I can see what chrome is doing with the cookies. It may also help to show the response headers as well for each response in the video so we can check that the cookie is there or not and what the settings are.

**Comment by josephyhu** [comment]
https://www.youtube.com/watch?v=Wb88HICmA5s
(showing the (what I think) are relevant headers first, cookies shown later)

**Comment by dougwilson** [comment]
Thank you. Can you show what the warning triangle is about next to the `set-cookie` field in the web browser? It would seem that the browser is indicating some kind of issue with the cookie, so I wonder what it says, please.

**Comment by dougwilson** [comment]
Another thing I noted is that your web browser has an existing cookie set with no sameSite setting, but your options have that as "none". I believe web browsers will thus discard the new cookie based on that mis-match. Can you clear your cookies and perform the test again with your cookie settings (excluding secure: true)? I wonder if that is what the warning triangle is indicating.

**Comment by josephyhu** [comment]
I for some reason can't capture it with OBS, but the warning says that attempt to set cookie using a Set-Cookie header was blocked because I have the SameSite=None attribute but don't have the Secure attribute.

**Comment by dougwilson** [comment]
Ah, well, that I guess is the answer: this module is dulely sending the cookie with the arributes you have provided, but it is the web browser that is refusing to set it. It seems like you have two options that browser gives you: use a different setting for samesite or set up your site on https and use secure: true.

I hope that helps. I'm going to close this for now as this is related to the web browser you are using and not with this module.
