### ISSUE TITLE
Session lost between localhost and domain regardless of protocol and configuration

### ISSUE THREAD

**Issue by DallasP9124** [expressjs/session#854]
We are working on an express application and we use this session library for sessions, what a surprise. As we are learning how sessions work, we find that we are having issues with our development environment and allowing localhost frontend app development connections to our server persist the sessions.

The deployed environment with a given domain (eg https://front.example.com) and server (eg https://back.example.com) are able to communicate with persistent sessions. When running and backend express server and the frontend code on localhost (different ports) the sessions are also persistent. 

The issues come up when the we attempt to have our local development frontend communicate with the deployed backend server and have the sessions persist. This occurs with both http and https communication.

Architecturally, the diagram attached shows a more details understanding of the traffic:
![Diagram](https://i.ibb.co/dDpnh8g/Session-Diagram.jpg)

Here is the current configuration of the session:
session.js
```js
export const initializeSession = () => {
  appSessionHandler = createSessionMiddleware();
  return appSessionHandler;
};
...
const createSessionMiddleware = () => {
  const isRedisSession = sessionManager === 'shared';
  const store = isRedisSession ? createRedisSessionStore() : createMemorySessionStore();
  return {
    session: session({
      name: "example session",
      store,
      secret: sessionSecret,
      proxy: true,
      rolling: true,
      saveUninitialized: false,
      resave: false,
      cookie: {
        sameSite: 'none',
        _expires: conf.get('app:session_timeout'),
        secure: true
      },
    }),
    store,
  };
};
```

httpPlatform.js
```js 
app.use(appSessionHandler.session);
app.set('trust proxy', 2) // Not sure of total proxy vs redirect count
...
  // -- Passport login
  app.get(`${basePath}/auth/:provider`, (req, res, next) => {
    try {
      req.session.referer = req.headers.referer;
      const { provider } = req.params;
      console.log(`[Passport] [SID: ${req.session.id}] Login auth/${provider}/ -> [referer:${req.headers.referer}]`)
      passport.authenticate(provider, {}, (err) => {
        setCookieError(res, err?.message);
        logApp.error(`[Passport] Auth error callback]`)
        next(err);
      })(req, res, next);
    } catch (e) {
      setCookieError(res, e?.message);
      next(e);
    }
  });
...
  // -- Passport callback
  const urlencodedParser = bodyParser.urlencoded({ extended: true });
  app.all(`${basePath}/auth/:provider/callback`, urlencodedParser, passport.initialize({}), (req, res, next) => {
    const {referer} = req.session;
    console.log(`[Passport] [SID: ${req.session.id}] Passport callback -> [referer:${referer}]`)
    const { provider } = req.params;
    console.log(`[Passport] Provider ${provider}`)
    passport.authenticate(provider, {}, async (err, user) => {
      if (err || !user) {
        console.log(`[Passport] [SID: ${req.session.id}] Authentication failed: [referer: ${referer}] ${err?.message}`)
        setCookieError(res, err?.message);
        return res.redirect(referer);
      }
      console.log(`[Passport] [SID: ${req.session.id}] User authenticated: [referer: ${referer}`)
      ...
      req.session.referer = null;
      return res.redirect(referer);
    })(req, res, next);
  });
```

We essentially need to figure out how to allow localhost frontend development code to connect and maintain sessions with the deployed backend. We have tried setting `cookie.sameSite` to `none`, and `cookie.secure` to both `true` and `false`. We included the console logs to show the session ID differences

Below is an example of logs with deployed front and backend
```
[Passport] [SID: nJMECwqVHdBJo7bzdLqTdKI-L7IxS0Hk] Login auth/oic/ -> [referer:<redact>]
[Passport] [SID: nJMECwqVHdBJo7bzdLqTdKI-L7IxS0Hk] Passport callback -> [referer:<redact>]
[Passport] Provider oic
[Passport] [SID: nJMECwqVHdBJo7bzdLqTdKI-L7IxS0Hk] User authenticated: [referer: <redact>
```
Below is an example log of localhost run front and deployed backend
```
| [Passport] [SID: 8AIJogMc00X3bFjdh43gTo35-D-Kakih] Login auth/oic/ -> [referer:<redact>]
// SESSION CHANGE
| [Passport] [SID: nJMECwqVHdBJo7bzdLqTdKI-L7IxS0Hk] Passport callback -> [referer:null]
| [Passport] Provider oic
| [Passport] [SID: nJMECwqVHdBJo7bzdLqTdKI-L7IxS0Hk] Authentication failed: [referer: null] did not find expected authorization request details in session...
```

**Comment by dougwilson** [comment]
Hi @DallasP9124 thank you for the detailed explanation. I have read through and it re-read through it, but I'm not exactly sure what is going on to really understand where you are encountering the issue and what the technical details of the issue are. Is it possible you can can provide full code that I can run locally which demonstrates the issue? The reason I ask is because I'm not really sure where to start with the debugging besides break out Wireshark and Node inspector and start poking around, but I'm not able to do that based on the information provided above. Another alternative is that we always accept pull requests for fixes that you diagnose as well.

**Comment by DallasP9124** [comment]
I understand @dougwilson, unfortunately I can't share the runnable code is proprietary and not sharable. To shorten and simplify our desired scenario:

we set some information in the session before it redirects to our auth provider. Based on the architecture, we need this in order to properly redirect from the original request back to the referer. What we see in same domain setups (deployed with domain or on localhost) is that the session persists (based on the logged session ID's) when redirected back from the auth provider to the frontend that proxies the callback to the backend. When we have cross domain setup/communication, that session is lost (again, based on the logged ID's) and the referer information we stored in the cookie is gone, causing redirect issues back to the frontend.

We thought is was a cross domain issue bit when we set the cookie `sameSite` property to `none`  we thought that would solve the issue and the cookie would be passed along, but it doesnt appear to be based on the lost information and different session ID.

Perhaps ignoring our current configuration and just thinking plainly, is it possible to keep a session across domains where one of those is simply running the frontend from localhost?
If this is possible, what is the recommended configuration to accomplish this?

**Comment by dougwilson** [comment]
Hi @DallasP9124 I'm mainly just having trouble wrapping my head about what the exact HTTP requests are being made and from where. To help clarify: this module simply uses HTTP cookies, and how HTTP cookies work is not determined by this module at all, rather it is determined by the web platform of the software that originates the HTTP requests. Perhaps, if you cannot share the exact code or even make a simplified code set that you can share, can you share what exactly all the HTTP requests are, their complete headers along with their responses and what software is originating each one?

**Comment by dougwilson** [comment]
Closing due to no further response.
