### ISSUE TITLE
Query | Is there a way to control concurrent logins

### ISSUE THREAD

**Issue by Praveen9999** [expressjs/session#856]
My requirement is to control concurrent logins for a particular user. E.g. I would like to have control over how many devices a user can log into.
I've checked on the internet and the proposed way is to create some token when the user logs in and save it in some persistent store. Pass the token with subsequent requests and compare it with the saved one.

Is there any OOTB feature provided by the library to achieve this requirement?

**Comment by dougwilson** [comment]
No, there is no OOFB way in thia library, as thia library provides no user tracking or log in functionality OOTB at all. It just provides a spot to store any generic data that is tied to a web browser session. You may want to check in to something like Passport JS.
