### ISSUE TITLE
Confused about req.session.cookie.maxAge ...

### ISSUE THREAD

**Issue by sameerjalnapurkar** [expressjs/session#863]
As per the [documentation on maxAge](https://github.com/expressjs/session#cookiemaxage-1), req.session.cookie.maxAge tells us how much time the session cookie has left. But the life of the cookie is measured at the client end, and what is sent with a request is only the cookie name-value pair, and not any other property of the cookie. At the server, we have not kept any record of when the cookie was set at the client end, nor do we know about the network latency. So where does req.session.cookie.maxAge come from?? Thanks for any hints / pointers! 🙂 🙏

**Comment by dougwilson** [comment]
Yes, you are correct the client can drift from what the server knows. The value is indeed stored on the server and every response from this module sets it again (depending on your settings). Since this module always sets with expires, it is an absolute date and network latency does not change that. I hope that helps!

**Comment by sameerjalnapurkar** [comment]
Thanks, that helped a lot. This is my mental model, as of now. Hopefully mostly correct! -

- The server stores, in a cookie table, all non-expired session cookies that have been sent out.

- Default cookie properties are specified in sessionOptions.cookie. Note that only one of expires and maxAge is considered. Either all cookies can expire at some set time, or all cookies can live for some set time interval.

- When a fresh request is received, without any session cookie, the settings in sessionOptions.cookie are used to craft a fresh cookie. Properties of the cookie are made available in req.session.cookie, and they can be changed during processing of the request.

- For a fresh request, at the end of the request processing, the session cookie is always sent with the response, in a Set-Cookie header, using the values in req.session.cookie. (Probably the res.cookie() method is used for setting the Set-Cookie header in the response.) At the same time, the server stores the cookie details in the cookie table.

- Consider a request that is in an ongoing session, and comes in with a session cookie. The only information that comes with the request is the cookie name-value pair, and not any other property of the cookie. However, other properties are retrieved from the cookie table and made available in req.session.cookie.

- In req.session.cookie, maxAge is an accessor (computed) property which is used to set expires, and is computed from expires. maxAge = expires - currentTime, and expires = maxAge + currentTime. Thus maxAge acts as like countdown timer at the server end.

- While the request is being served, properties of req.session.cookie can be changed.

- req.session.touch() will reset req.session.cookie.maxAge to its original value.

- If sessionOptions.rolling = true, then, for a continuing session, at the time of retrieval of information from the cookie table, req.session.cookie.maxAge is reset to its original value. At the end of request processing, current values in req.session.cookie are used to set the Set-Cookie header in the response. (Probably the res.cookie() method is used for setting the Set-Cookie header in the response.) At the same time, the server stores the cookie details in the cookie table.

- In the Set-Cookie header sent with the response, only the expires property is used. maxAge is not used.
