### ISSUE TITLE
Destroy old session store after regenerate

### ISSUE THREAD

**Issue by axmad386** [expressjs/session#866]
I think I miss something here. When i call `req.session.regenerate`, it successfully regenerate session. But old session still exist on store. For additional info, I use `session-file-store`.
Is this correct behavior?
I just need same behavior like Laravel SessionManager `migrate` method 
```php
function migrate(bool destroy): bool
```
How can I delete old session data from store after regenerate?
For now this is my work around, 
```js
 const oldID = req.session.id
 req.session.regenerate((err)=>{
   if(!err){
      setTimeout(()=>{
        //This will make sure old session is unlinked befor we destroy it
        // this.store is instance of session-file-store
        this.store.destory(oldID)
      },1000)
   }
})
```
Please tell me if there is better way. Thank you

**Comment by dougwilson** [comment]
Hello, unfortunately this is a bug in the store you are using. The regenerate method will call destroy and then create, so if it is not being destroyed, you should open an issue with the store implementation you are using.

**Comment by axmad386** [comment]
Hey, thanks for clarification

**Comment by dougwilson** [comment]
No problem. I will add that this module will, specifically, call destroy on the session and wait for the store to callback saying destroy is finished before creating the new one and returning to your code. It is possible that the store is returning from the destroy too early, especially if you manually calling destroy seems to work.
