### ISSUE TITLE
Readme not showing on npmjs

### ISSUE THREAD

**Issue by noahliechti** [expressjs/session#868]
On https://www.npmjs.com/package/express-session the readme is not displayed.
I can't imagine what the error is,  but it would be helpful in my opinion if the readme appears.

![npm screenshot](https://user-images.githubusercontent.com/38284563/149541571-7dd539b6-c199-428c-a876-6c0ab648bf0f.png)
.

**Comment by dougwilson** [comment]
At least as of now, and for me, it is working. If you are still having trouble, you will need to contact npm.

**Comment by noahliechti** [comment]
Okay, weird! Thanks for answering.
