### ISSUE TITLE
Support autoCommit=false for Next.js v12 compatibility

### ISSUE THREAD

**Issue by yomed** [expressjs/session#870]
As of Next.js v12, there are console warnings when accessing `res` after `getServerSideProps` finishes. The warning looks like this: 
> warn  - You should not access 'res' after getServerSideProps resolves.
Read more: https://nextjs.org/docs/messages/gssp-no-mutating-res

This appears to be due to the automatic committing of session changes within `express-session` here: 
https://github.com/expressjs/session/blob/66634e9f77132a444dfda7e279a399054e3b28df/index.js#L246-L250

The library `next-session` uses a similar mechanism, but allows disabling it via option `{autoCommit: false}`:
https://github.com/hoangvvo/next-session/blob/b87f2cae77b321fb8960358cb3e85cfda9ecd701/src/session.ts#L119-L124

In the Next.js PR related to this change, they noted that this warning shouldn't break anything, but would prevent future adoption of streaming features. They suggested that libraries like `express-session` could support manual committing of session changes in order to avoid this issue:
https://github.com/vercel/next.js/pull/29010#issuecomment-944484016

Would you be open to this additional option?

**Comment by dougwilson** [comment]
This is already supported -- call `req.session.save()` when you want and then this library will not do it automatically at the end.

**Comment by yomed** [comment]
Hi @dougwilson, thanks for taking a look. I'm not too knowledgable about this, but from my own debugging it looks like even if the session doesn't need to be saved at the end, it will still get `touched` automatically at the end (which would lead to the same issue). I'm looking at this code:

https://github.com/expressjs/session/blob/66634e9f77132a444dfda7e279a399054e3b28df/index.js#L344-L354

https://github.com/expressjs/session/blob/66634e9f77132a444dfda7e279a399054e3b28df/index.js#L453-L461

**Comment by dougwilson** [comment]
Thanks. Perhaps you can provide a reproducable example of your issue? If your session is fully saved at the end of the request, nothing should be happening unless there is a bug. Providing reproduction steps with code and how to run would be a big help.
