### ISSUE TITLE
MemoryStore is not designed for production env 

### ISSUE THREAD

**Issue by sajcics** [expressjs/session#871]
Hi.

I can not figure out why I am getting this error:
_connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process._

using:
express: v4
connect-mongo: 4.6.0
express-session: 1.17.2

```
const session = require('express-session');
const MongoStore = require('connect-mongo');

  app.use(session({
    resave: true,
    saveUninitialized: true,
    secret: process.env.SECRET,
    store: MongoStore.create({
      mongoUrl: process.env.MONGO_URL
    })
  }));
  
```
  Any ideas why this is happening ?

**Comment by dougwilson** [comment]
I'm not able to reproduce that with the code you provided. Are you able to reproduce that message when given a file that contains only the code provided? I assume no, since I could not run it without defining the `app` variable. Please provide all the code necessary to reproduce so we can help.

**Comment by dougwilson** [comment]
Closing due to no response.
