### ISSUE TITLE
Feature request: configurable header name for x-forwarded-proto

### ISSUE THREAD

**Issue by rickknowles-cognitant** [expressjs/session#872]
Hi,

Would it be possible to make the exact header-name checked for in line 640 of index.js to be a config option instead of hard coded to "x-forwarded-proto" please ?

![image](https://user-images.githubusercontent.com/37247203/152174193-de7c0fe1-3337-435a-a9fd-f164fcb8f156.png)

The reason I ask is that we have a deployment situation where there are 2 AWS load balancers sequentially reverse proxying before the express code is requested, and the 2nd one unfortunately overwrites the x-forwarded-proto set by the 1st (which has the value we want). 

In other applications we've been able to write the 1st LB's x-forwarded-proto into another header so it's visible downstream, and then look at the other header. Unfortunately without forking and modifying express-session's source, we can't find a way to trick express-session's issecure() method into looking at that other named header, so all secure cookies are dropped.

I'm happy to fork and maintain a clone if its the only way, but I just thought I'd ask: if it's possible to take the header name to use instead of x-forwarded-proto as an option in the session constructor that could be overridden or a custom ```getXForwardedProtoHeaderValue()``` function be supplied it would make that unnecessary.

Happy to write a patch if it would help and submit, just wanting to sound out whether it's an option or not. Thank you,

Rick Knowles

**Comment by dougwilson** [comment]
Using that header in this lib is an old fallback. You should instead use whatever logic you like to set `req.secure`, which rhis module will honor.

**Comment by rickknowles-cognitant** [comment]
Isn't req.secure not settable though ?

**Comment by rickknowles-cognitant** [comment]
And isn't closing this a little premature ?

**Comment by dougwilson** [comment]
Hi, yes you can co figure it though express to use any logic you like. When an issue has a straight forward answer, we typically close it until new information comes to light, and many people don't respond back. Closing the issue does not stop comments, nor our replies, as you can see :)

**Comment by rickknowles-cognitant** [comment]
OK sure - I'll I can see is this though:

![image](https://user-images.githubusercontent.com/37247203/152177018-f9f23244-20a0-4d77-876e-e8f8adb8cdfb.png)

and when we tried doing ```req.secure = true``` it doesn't allow it. How exactly would one go about configuring it with any logic we like ? Obviously I prefer this approach too, I've only asked for this feature because the approach wasn't allowed

**Comment by dougwilson** [comment]
http://expressjs.com/en/guide/overriding-express-api.html

```js
Object.defineProperty(app.request, 'ip', {
  configurable: true,
  enumerable: true,
  get: function () { return getXForwardedProtoHeaderValue() === 'https' }
})
```

**Comment by rickknowles-cognitant** [comment]
thank you - v helpful
