### ISSUE TITLE
redis v4 library incompatible with express-session

### ISSUE THREAD

**Issue by davidalvarez305** [expressjs/session#876]
Hey,

Migrated one of my apps to redis v4 (npm-redis) and my express-session started to faulter. Figured out it's because redis v4 introduced a lot of breaking changes. Solved by switching to "io-redis", however, what's the correct way to use redis v4 with express-session?

**Comment by dougwilson** [comment]
This module, express-session, does not interact with redis directly. What store module are you using?

**Comment by davidalvarez305** [comment]
store module "connect-redis" and using "redis (v4)" to connect to the client, I realize now what you just said

**Comment by dougwilson** [comment]
It looks like version 6.1.0 of that store added support for redis v4 (https://github.com/tj/connect-redis/releases/tag/v6.1.0). I would make sure you are running the latest of that module. If you are having additional trouble with the store, they are very responsible, I would recommend opening an issue there 👍
