### ISSUE TITLE
Handle session timeout

### ISSUE THREAD

**Issue by jeff-pal** [expressjs/session#882]
Is there a way to handle a request which its cookie session expired?

**Comment by dougwilson** [comment]
Hi @jeff-pal , when a cookie expires, the web browser no longer sends it. From the server side where this module is, there is no difference between a request that never had a session or a request where the session expired, as the browser does not provide any difference.

I hope that helps!

**Comment by jeff-pal** [comment]
Thanks @dougwilson !

**Comment by dougwilson** [comment]
You can do it on the server side. This would need to be a function of the store module you are using, as they all store and expire sessions differently.
