### ISSUE TITLE
Feature Request: priority cookies

### ISSUE THREAD

**Issue by mlucool** [expressjs/session#884]
Hi,

cookie has recently been released to allow for users to set the priority cookie (https://github.com/jshttp/cookie/issues/138). This is important to set for session cookies due to the corresponding issued log in https://bugs.chromium.org/p/chromium/issues/detail?id=1309656 where users session cookies may be deleted.

Can we support passing through this attribute similar to other cookie properties?

**Comment by mlucool** [comment]
Hi,

I see this is now labeled as an enhancement and not just "discuss". Would you be open to PR for this feature or is someone already planning to do this?

**Comment by dougwilson** [comment]
Hi @mlucool sorry, I did start on this, but then forgot about it. I'll get that added here 👍

**Comment by mlucool** [comment]
Hi. Just checking in again @dougwilson. Happy to make a PR here.

**Comment by mohsinulhaq** [comment]
@dougwilson would it be possible to get this one going? The PR has been pending for so long with no comments. Let me know if I should direct my queries to someone else instead. :)
