### ISSUE TITLE
Cookie Session Destroying on Redeploy

### ISSUE THREAD

**Issue by RiseValco** [expressjs/session#885]
Every time my web app gets redeployed on localhost and server you have to re login. Is there any way to make it where you dont got to re login?

Ive tried many and many times and research to find but still cant so idk.

**Comment by dougwilson** [comment]
Hi, sorry you are having issues. I would say that shouldn't happen, but this module doesn't by itself do anything with logging in, so really cannot say what is casuing your issue.

If you believe it is a bug in this module specifically, please provide a full app that reproduces the issue so we can track down the case or you can contribute a fix for the issue via a pull request.

**Comment by RiseValco** [comment]
I dont think its a bug but I just wanted to see if there was a feature to stop it because its annoying having to re login after every redeploy/restart.

**Comment by dougwilson** [comment]
There is no log in feature in this module, so the general question of why you have to log back in every deploy doesn't make sense in the context here, so there is no answer to give just based on that description.

**Comment by RiseValco** [comment]
I know there is no login feature but a feature where it somehow saves the cookies so when it redeploys you dont gotta re login{I dont think saving cookies like that is possible but yeah)

**Comment by dougwilson** [comment]
Cookies are saved in the web browser, not in this module. They should be saved and sent back to the server, but if that is not happening, you would need to determine what is wrong in the web browser if it is not saving them.

**Comment by RiseValco** [comment]
I know cookies are saved in the browser and they are saving them. I just wish there was a way to save the cookies so u didnt have to re login every time. Other websites do it and I dont know how.

**Comment by dougwilson** [comment]
You may need to take a look though the log in logic or such. There isn't enough information provided in thia issue to provide any help yet. If you believe it is a bug in this module specifically, please provide a full app that reproduces the issue so we can track down the case or you can contribute a fix for the issue via a pull request.
