### ISSUE TITLE
Can session be tampered by the client?

### ISSUE THREAD

**Issue by Tenpi** [expressjs/session#889]
Hi, I cannot find a straight answer for this but basically I want to know if it's safe to do something like this: 

```ts
app.delete("/api/user/delete", async (req: Request, res: Response, next: NextFunction) => {
        try {
            if (!req.session.username) return res.status(400).send("Bad request")
            const user = await sql.user(req.session.username)
            if (!user) return res.status(400).send("Bad request")
            await sql.deleteUser(req.session.username)
            req.session.destroy((err) => {
                if (err) throw err
                res.status(200).send("Success")
            })
        } catch (e) {
            console.log(e)
            return res.status(400).send("Bad request")
        }
    })
```

And it's impossible for the client to modify the `req.session.username` so they can't delete someone other than themselves? I am setting the `req.session.username` in my login endpoint only if the password matches.

**Comment by dougwilson** [comment]
Hello! So typically none of the session data is sent to the client, but the exact storage location and details for the session data will depend on the store module you are using. You'll need to confirm that with the store to get a clear answer for that particular question 👍

**Comment by Tenpi** [comment]
I am using `pg-connect-simple` as my store, and all of the sessions are stored on the back-end database. 

Honestly the github repo of that project seems to be dead, but if you won't give me a straight answer, I guess I'll ask there instead.

**Comment by dougwilson** [comment]
I cam say that nothing in this module sends or reads data from the client, only to and from the store. Unfortunately there is too much unknown to give you a direct answer without risking liability, as your question sounds like it is asking me to confirm something that would pin liability on me for a wrong answer. I'm not familiar with thay particular store and cannot speak to it. If you feel like that store is not active, you can always use a different store or make your own that meets your needs.

**Comment by Tenpi** [comment]
OK, that library doesn't seem to read anything from client-side so I will consider this safe. Thanks for the quick replies.
