### ISSUE TITLE
Session not saving

### ISSUE THREAD

**Issue by richiepreece** [expressjs/session#89]
I have a very simple application set up to test my session storage, and nothing is saving. Here's the basic setup:

``` js
var sessionOptions = {
  key: 'session.sid',
  secret: 'Some secret key',
  resave: true,
  saveUninitialized: true,
  cookie: {
    secure: true,
    maxAge: 600000
  }
};

app.use(session(sessionOptions));

app.get('/user', function getUser(req, res, next) {
  console.log(req.session, req.session.user);

  if(!req.session.user) {
    req.session.user = { test: 'test' };
    res.status(403);
    return res.send('Not logged in');
  }

  res.send(req.session.user);
});
```

This should return a 403 status on the FIRST request only, but it's returning a 403 every time I reload the page. Am I totally missing something?

**Comment by pmiri** [comment]
Very glad this issue exists, it saved us on our project!

**Comment by Jafer46** [comment]
Thanks very much this actually saved me a lot of trouble
