### ISSUE TITLE
Session Not Storing

### ISSUE THREAD

**Issue by omerfdmrl** [expressjs/session#901]
in my app.js file;
```
var cookieParser = require("cookie-parser");
var session = require('express-session');
....
app.use(cookieParser());
app.use(session({
    name : "session",
    secret: "asdasdasd864sd5",
    saveUninitialized:true,
    cookie: { maxAge: 1000 * 60 * 60 * 24 , secure : false },
    resave: true
}));
```
in my test router;
```
app.get('/',(req,res) => {
  req.session.user = 1;
  res.json(req.session)
})
```
My response is;
```
{
  cookie: {
    originalMaxAge: 86400000,
    expires: "2022-07-01T19:04:21.481Z",
    secure: false,
    httpOnly: true,
    path: "/"
  },
  user: 1
}
```
It seems ok. But after that code I'm removing `req.session.user = 1` line. After that session not showing;
```
app.get('/',(req,res) => {
  res.json(req.session)
})
```
Response;
```
{
  cookie: {
    originalMaxAge: 86400000,
    expires: "2022-07-01T19:06:14.853Z",
    secure: false,
    httpOnly: true,
    path: "/"
  }
}
```
Now, user session not showing.To give an real world example, I'm using `req.session.user = 1` in my login controller. İt should be store. But when I refresh page it's destroying. I think it's not storing. How can I fix that?

**Comment by alps991** [comment]
My guess is that when you made the code change to remove the line `req.session.user = 1`, you are restarting your express web server to make that code change take effect. Doing this will clear all your session data. If you want your data to persist between web server restarts you'll need to store that in some sort of cache or database. However in this case, it sounds like your code will work as expected as long as you don't restart your webserver.

**Comment by dougwilson** [comment]
Closing due to no reponse from OP, assuming answered above.
