### ISSUE TITLE
Probably, an error with "rolling".

### ISSUE THREAD

**Issue by Alex0881** [expressjs/session#902]
I have method of use below
```js
app.use(session({
  secret: 'keyboard cat',
  cookie: { 
    maxAge: 60000
  },
  rolling: false,
  resave: false,
  saveUninitialized: false,
  store: MongoStore.create({ mongoUrl: 'mongodb://localhost/test-app' })
}))
```
Session will continue maxAge  althouth rolling: false.  In index.js after line with 'var touched = false;' i wrote 'touched = !rollingSessions;' After that i have predictable work process.

**Comment by dougwilson** [comment]
Hello and thank you for the report. It is unfortunately difficult to determine what is happening baded on the information ptovided.

Please provide a full server that reproduces the behavior you are seeing. Please list module and node.js versions and include instructions to run the code and see the behavior, thank you.

**Comment by Alex0881** [comment]
Good day. You may delete "  store: MongoStore.create({ mongoUrl: 'mongodb://localhost/test-app' }) " from code below - problem is the same. After every request expire time of cookie increase, i watch in chrome devtools.

`var express = require('express')
var parseurl = require('parseurl')
var session = require('express-session')
var MongoStore = require('connect-mongo')

var app = express()

app.use(session({
  secret: 'keyboard cat',
  cookie: { 
    maxAge: 60000
  },
  rolling: false,
  resave: false,
  saveUninitialized: false,
  store: MongoStore.create({ mongoUrl: 'mongodb://localhost/test-app' })
}))


app.use(function (req, res, next) {
  if (!req.session.views) {
    req.session.views = {}
  }

  // get the url pathname
  var pathname = parseurl(req).pathname

  // count the views
  req.session.views[pathname] = (req.session.views[pathname] || 0) + 1

  next()
})

app.get('/foo', function (req, res, next) {
  res.send('you viewed this page ' + req.session.views['/foo'] + ' times')
})

app.get('/bar', function (req, res, next) {
  res.send('you viewed this page ' + req.session.views['/bar'] + ' times')
})


app.listen(4000)`

**Comment by dougwilson** [comment]
Hi @Alex0881 thank you for that. This is working exactly as documented. See https://github.com/expressjs/session#rolling

> With this enabled, the session identifier cookie will expire in [maxAge](https://github.com/expressjs/session#cookiemaxage) since the last response was sent instead of in [maxAge](https://github.com/expressjs/session#cookiemaxage) since the session was last modified by the server.

Since you have `rolling` disabled, it will only update the maxAge when the session was last modified by the server, and in your example you modify the session for every request, thus why you are seeing the maxAge update with every request.

**Comment by Alex0881** [comment]
I understand, thank you.
