### ISSUE TITLE
add user-agent detection to prevent session creation for bots

### ISSUE THREAD

**Issue by haxxxton** [expressjs/session#94]
I was encountering issue with both crawler bots (that i would still like to be able to crawl my site for data), and AWS's HealthChecker bots getting session keys created for them, as this added unnecessary keys to my storage (redis).

I found piggy backing off the ua-parser2 library gave me most of what i needed, except for HeathChecker bots (https://github.com/commenthol/ua-parser2/issues/1). I added the following code to the `function session(req, res, next)` function just below the self-aware check:

```
   var UA = require('ua-parser2')(); /*included at top of document*/


   // dont generate for bots
    var isBot = false;
    var browserDetails = UA.parse(req.headers['user-agent']);
    if(browserDetails.ua.hasOwnProperty('type')){
        if(browserDetails.ua.type == 'bot'){
            isBot = true;
        }
    }
    if(browserDetails.string.indexOf('HealthChecker') >= 0){
        isBot = true;
    }
    if (isBot) return next();
```

Apologies if theres a super simple alternative to stopping bots from generating session's, but my googling turned up nothing :(

Happy to submit a pull request, but figured you guys might prefer to look into an alternative user-agent parser/detector

**Comment by dmarcelino** [comment]
I just came across this thread and I want to thank you both for the insightful information!
