### ISSUE TITLE
[Feature Request] Support of phasing out third-party cookies

### ISSUE THREAD

**Issue by nicob-29** [expressjs/session#961]
Hi 
Google plan soon to activate  phasing out third-party cookies
See Third-Party Cookies doc: https://privacysandbox.com/open-web/#the-privacy-sandbox-timeline

Doc about phasing out third-party cookies: https://developer.chrome.com/en/docs/privacy-sandbox/third-party-cookie-phase-out/#partitioned-cookies

This feature request requires the possibility to add "Partitioned" to the cookie like Secure.

**Comment by sergioRozenszajn** [comment]
Hi,
We have the same urgent requirement, do you have any plans/timelines to support Partitioned cookie property?
We tried to workaround but it looks like not there is none.

**Comment by dougwilson** [comment]
The implementation is being discussed currently but should be integrated soon.

**Comment by sblecon** [comment]
Hi @dougwilson ,
Any idea when the fix will be available?
Best regards,
Stéphane

**Comment by stefanbeigel** [comment]
Hi,
we also need such support to test partitioned cookies for our sessions.

**Comment by nicob-29** [comment]
Hi
Any update ?

**Comment by stefanbeigel** [comment]
@nicob-29 
I think it first needs to be added to `cookie` library, which was done but not released
https://github.com/jshttp/cookie/pull/153
Because it's used here:
https://github.com/expressjs/session/blob/master/session/cookie.js#L14

**Comment by nicob-29** [comment]
@sergioRozenszajn 
jshttp/cookie about partitioned was released (See version 0.6.0)
https://github.com/jshttp/cookie/releases is not good but 

![image](https://github.com/expressjs/session/assets/56296287/ee9ddc0c-c205-4c34-8ed8-45128d5d678d)

**Comment by dougwilson** [comment]
Thank you, I missed added it to the github releases. There is a long holiday where I am currently, sorry for the delayed reply. I will get out a new release of this with partitioned support asap for you all.

**Comment by nicob-29** [comment]
@sergioRozenszajn
The version of cookie was released yesterday ;-) 
Thank you @dougwilson

**Comment by sergioRozenszajn** [comment]
Hi @dougwilson , @nicob-29 

In the meantime I forked into https://github.com/sergioRozenszajn/approuter-session.git, using cookie 0.6.0 and adding partitioned to data: 
      , sameSite: this.sameSite
      , partitioned: this.partitioned
Using this fork the JSESSIONID cookie is now partitioned:
![image](https://github.com/expressjs/session/assets/9656073/588027bc-f2a1-44c4-9afe-92c7b1fadd6d)

**Comment by dougwilson** [comment]
Hi @nicob-29 I just got home yesterday and working through the backlog. Please if you can give me a little breather from the holiday to get it done, that would be great.

**Comment by cattermo** [comment]
Please start work on this 🙏 
Since Chrome will start blocking from beginning of next year it's starting to become very urgent.

**Comment by nicob-29** [comment]
Happy New Year
Friendly reminder.

**Comment by rgsthethird** [comment]
Another request for this to be added soon. Thanks!
