### ISSUE TITLE
 req.sessionStore.all with typescript bug?

### ISSUE THREAD

**Issue by pablojsx** [expressjs/session#962]
I'm using express-session with tRPC and in my context:

```
declare module 'express-session' {
  interface SessionData {
    user: User;
  }
}
```

I wanted to get all user sessions from the database, I tried " req.sessionStore.all" and also " store.client.db().collection('sessions');"  but with both I'm getting the same issue. I get the information but it's not of the type that it should be and it is nested inside another array!. 

When I get the information from the callback req.sessionStore.all receives I get this: 

![Captura de pantalla 2023-11-16 002406](https://github.com/expressjs/session/assets/40902487/9abeae36-3bd8-4b76-8c75-2e4214d2578b)

All good but this array isn't a "sessionData[]" array. What I mean is that when you use  req.sessionStore.all it will return from the callback a sessions array and that's a "sessionData[]" array that doesn't match the info from the pic above. 

I get the information but it is nested!! in the pic below, the session

![Captura de pantalla 2023-11-16 003020](https://github.com/expressjs/session/assets/40902487/efbbf91f-76e4-4a81-b689-b0a6a79fb8d6)

You can see here what I mean, the info is nested:

![Sin títul2o](https://github.com/expressjs/session/assets/40902487/564492a8-4625-4afe-8af3-e5b856c488f4)

If I destructure the session object:

![Captura de pantalla 2023-11-16 013807](https://github.com/expressjs/session/assets/40902487/f8d356cc-c9d7-4522-b41b-ecd3d7355b2b)

If I cast the information everything works!

![Captura de pantalla 2023-11-16 013917](https://github.com/expressjs/session/assets/40902487/598b2b80-70f1-4638-8f77-ae7879b20262)

![Captura de pantalla 2023-11-16 014529](https://github.com/expressjs/session/assets/40902487/4983584a-2b86-481f-8048-200808995adf)

**Comment by dougwilson** [comment]
Hello, this method is implemented by the store module you are using, which may need to fiz their implementation. What store are you using?

**Comment by pablojsx** [comment]
> Hello, this method is implemented by the store module you are using, which may need to fiz their implementation. What store are you using?

Hello Doug!. I'm using the MongoDBStore

**Comment by dougwilson** [comment]
Thanks! It looks like we have a couple of MongoDB ones listed. Do you happen to know the name of the npm module?

**Comment by pablojsx** [comment]
> Thanks! It looks like we have a couple of MongoDB ones listed. Do you happen to know the name of the npm module?

Yep this is all I have for the server:

![Captura de pantalla 2023-11-16 015645](https://github.com/expressjs/session/assets/40902487/8bc7bae5-c732-4f21-b597-a10c8c10157f)

**Comment by dougwilson** [comment]
Ok, cool. It is connect-mongodb-session. Here is where that module implements the .all method that is return what you are not expecting: https://github.com/mongodb-js/connect-mongodb-session/blob/50c80519f54983c3d0a2f6ee6828bacffa5c58dd/index.js#L152

And here is their bug tracker to report the issue: https://github.com/mongodb-js/connect-mongodb-session/issues

**Comment by pablojsx** [comment]
In Javascript it works fine, but the problem start when you use Typescript since the types won't match the info!

**Comment by pablojsx** [comment]
> Ok, cool. It is connect-mongodb-session. Here is where that module implements the .all method that is return what you are not expecting: https://github.com/mongodb-js/connect-mongodb-session/blob/50c80519f54983c3d0a2f6ee6828bacffa5c58dd/index.js#L152
> 
> And here is their bug tracker to report the issue: https://github.com/mongodb-js/connect-mongodb-session/issues

Thanks for your help Doug, I'll report the bug now
